Repository segmentio/segment-docs, pull requests merged in 2021-12, with the labels that each got.

#2211 Removed public beta flag
  src/connections/storage/data-lakes/sync-history.md
Labels: fixed-content

#2228 Merging master back into develop to send changes downstream after one-off release
  src/connections/storage/data-lakes/sync-history.md
Labels: release

#2226 Update Databrain destination for rebranding.
  src/connections/destinations/catalog/databrain/index.md
Labels: enhancement

#2220 Update tracking plan timestamp format requirements.
  src/protocols/tracking-plan/create.md
Labels: enhancement

#2219 render handlebar samples as raw
  src/connections/destinations/catalog/slack/index.md
Labels: back-end

#2233 Edits to "Getting Started with Segment" and "What is Segment?" [DOC-378]
  src/_data/sidenav/main.yml
  src/getting-started/01-what-is-segment.md
  src/getting-started/index.md
Labels: fixed-content

#2236 Add support for connection mode overrides in dossier
  src/_data/catalog/overrides.yml
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/intercom/index.md
Labels: back-end

#2240 Segment Spec Page updates
  src/connections/spec/page.md
Labels: fixed-content

#2243 Appcues Events updates [DOC-389]
  src/connections/destinations/catalog/appcues/index.md
Labels: fixed-content

#2239 Export Schema
  src/connections/destination-data-control.md
  src/connections/images/export-source-schema.png
  src/protocols/enforce/schema-configuration.md
Labels: enhancement

#2249 Landing page updates
  src/_data/landing.yml
Labels: fixed-content

#2250 Update index.md
  src/connections/destinations/catalog/appcues/index.md
Labels: fixed-content

#2237 Updates to Databrain destination.
  src/connections/destinations/catalog/databrain/index.md
Labels: enhancement

#2244 Added edit buttons to the footer for smaller window
  src/_includes/components/feedback.html
  src/_sass/components/_button.scss
Labels: back-end

#2257 Release 21.49.1
  src/_data/landing.yml
  src/_includes/components/feedback.html
  src/_sass/components/_button.scss
  src/connections/destination-data-control.md
  src/connections/destinations/catalog/appcues/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/databrain/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/index-all.md
  src/connections/destinations/destination-filters.md
  src/connections/images/export-source-schema.png
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/spec/page.md
  src/privacy/faq.md
  src/protocols/enforce/schema-configuration.md
Labels: release

#2260 Update braze maintenance mode link
  src/connections/destinations/catalog/braze/index.md
Labels: fixed-content

#2262 Regal Voice source table updates
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
Labels: fixed-content

#2259 Add clarity to Events in Sendgrid source and fixe a typo
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: fixed-content

#2253 Update to clarifying the format required for Filtering Array Properties
  src/connections/destinations/destination-filters.md
  src/connections/destinations/images/destination-filters/filter-array-properties.png
Labels: fixed-content

#2248 BigQuery content edits
  src/_includes/content/warehouse-sync-sched.md
  src/connections/storage/catalog/bigquery/index.md
Labels: fixed-content

#2263 Release 21.49.2
  src/_includes/components/actions-fields.html
  src/_includes/content/ajs-upgrade.md
  src/_includes/content/warehouse-sync-sched.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/destination-filters.md
  src/connections/destinations/images/destination-filters/filter-array-properties.png
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/storage/catalog/bigquery/index.md
Labels: release

#2266 sprig action destination documentation
  src/connections/destinations/catalog/actions-sprig-web/index.md
Labels: new-integration

#2280 repo sync
  src/_data/sidenav/main.yml
  src/getting-started/implementation-guide.md
  src/getting-started/index.md
Labels: autoupdate, automated-reposync-pr

#2282 Fix Braze maintenance mode links
  src/connections/destinations/catalog/braze/index.md
Labels: fixed-content

#2281 Add clarity to Singular destination doc
  src/connections/destinations/catalog/singular/index.md
Labels: fixed-content

#2285 Update the context table in the common spec
  src/connections/spec/common.md
Labels: enhancement

#2271 Sprig actions
  src/connections/destinations/catalog/actions-sprig-web/index.md
Labels: new-integration

#2286 Add note to hubspot docs about event tester
  src/connections/destinations/catalog/hubspot/index.md
Labels: enhancement

#2287 Update Google Universal Analytics with information about Consent Mode
  netlify.toml
  src/_data/sidenav/strat.yml
  src/_layouts/default.html
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: enhancement

#2265 Added Amazon S3 destination limited access information
  src/connections/storage/catalog/amazon-s3/images/AWS-S3.png
  src/connections/storage/catalog/amazon-s3/index.md
  src/connections/storage/catalog/aws-s3/index.md
Labels: fixed-content

#2288 Release 21.50.2
  src/connections/destinations/catalog/actions-friendbuy-web/index.md
  src/connections/destinations/catalog/actions-sprig-web/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/vitally/index.md
  src/connections/sources/catalog/cloud-apps/desk-com/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/spec/common.md
  src/connections/storage/catalog/amazon-s3/images/AWS-S3.png
  src/connections/storage/catalog/amazon-s3/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/guides/how-to-guides/segment-and-attribution.md
Labels: release

#2297 Fixed the image that appears in the Amazon S3 documentation
  src/connections/storage/catalog/amazon-s3/images/AWS-S3.png
  src/connections/storage/catalog/amazon-s3/images/aws-s3-tile.png
  src/connections/storage/catalog/amazon-s3/index.md
Labels: fixed-content
