Repository segmentio/segment-docs, pull requests merged in 2021-11, with the labels that each got.

#2079 Update Personas Default Limits [DOC-349]
  src/personas/product-limits.md
Labels: fixed-content

#2077 Clarify nonInteraction flag behavior Google Universal Analytics
  lychee-out.txt
  src/connections/destinations/catalog/google-analytics/index.md
Labels: enhancement

#2086 Clarify language around what Segment supports when connecting mobile and project sources to multiple instances of destinations
  src/connections/destinations/add-destination.md
Labels: enhancement

#2085 Personas Limits SQL Traits Rows Fix [DOC-343]
  src/personas/product-limits.md
Labels: fixed-content

#2090 Release 21.44.1
  .github/release.yml
  lychee-out.txt
  src/_data/catalog/overrides.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/add-destination.md
  src/connections/destinations/catalog/chameleon/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/iterable/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/personas/product-limits.md
Labels: release

#2094 repo sync
  src/_data/products.yml
  src/_data/sidenav/main.yml
  src/connections/regional-segment-eu.md
  src/connections/regional-segment.md
  src/connections/storage/warehouses/faq.md
Labels: autoupdate, automated-reposync-pr

#2093 RF: Add agent attribute edited event properties
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
Labels: enhancement, fixed-content

#2099 Fixed a copy paster error with the destination name
  src/connections/destinations/catalog/actions-customer-io/index.md
Labels: fixed-content

#2100 Add settings detail to Salesforce source [DOC-362]
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: fixed-content

#2101 minor typo fix on warehouse schema doc
  src/connections/storage/warehouses/schema.md
Labels: fixed-content

#2102 Release 21.44.2
  src/connections/destinations/catalog/actions-customer-io/index.md
  src/connections/regional-segment-eu.md
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/storage/warehouses/schema.md
Labels: release

#2104 repo sync
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
Labels: autoupdate, automated-reposync-pr

#2082 Update Data Lakes manual installation set up instructions for EMR v5.33.0 [DOC-356]
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  vale-styles/Vocab/Docs/accept.txt
Labels: enhancement

#2092 Update Iterable Destination Personas section for clarity
  src/connections/destinations/catalog/iterable/index.md
Labels: enhancement

#2122 Fixed React Native doc in Braze destination #2072
  src/connections/destinations/catalog/braze/index.md
Labels: fixed-content

#2121 Add note about MFA in Salesforce [DOC-366]
  src/connections/destinations/catalog/salesforce/index.md
Labels: enhancement

#2124 Update link in Braze documentation
  src/connections/destinations/catalog/braze/index.md
Labels: fixed-content

#2127 Updated Bing Ads Destination docs to include additional parameters
  src/connections/destinations/catalog/bing-ads/index.md
Labels: enhancement

#2108 Add information about migrating to Destination Actions
  src/connections/destinations/actions.md
Labels: enhancement

#2132 repo sync
  src/_data/sidenav/main.yml
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/selective-sync.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/guides/filtering-data.md
Labels: autoupdate, automated-reposync-pr

#2137 Update broken links to Customer.io API Docs
  src/connections/destinations/catalog/customer-io/index.md
Labels: fixed-content

#2136 Data Lakes Reports Documentation [DOC-359]
  src/_data/sidenav/main.yml
  src/connections/storage/data-lakes/sync-history.md
Labels: enhancement

#2138 Houseware destination documentation
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/warehouse_papi.yml
  src/connections/destinations/catalog/houseware/index.md
Labels: new-integration

#2139 Fixed a typo in a heading
  src/guides/how-to-guides/create-push-notification.md
Labels: fixed-content

#2146 Update sql traits frequency settings
  src/personas/sql-traits.md
Labels: enhancement

#2148 repo sync
  src/_data/regional.yml
  src/_includes/content/regional-integrations-table.md
  src/connections/regional-segment-eu.md
  src/utils/regional-table.md
Labels: autoupdate, automated-reposync-pr

#2143 Hiding the release notes, they are out of date
  _config.yml
  src/_includes/menu/menu-mobile.html
  src/_includes/menu/menu.html
Labels: back-end

#2156 Update Google Enhanced Conversion docs
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: enhancement

#2158 update the catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#2153 Added warning to GCS [DOC-359]
  src/connections/storage/catalog/google-cloud-storage/index.md
Labels: enhancement

#2160 Release 21.46.3
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/connections/storage/catalog/google-cloud-storage/index.md
  src/connections/storage/data-lakes/sync-history.md
  src/getting-started/02-simple-install.md
Labels: release

#2162 Added object/array table to Warehouse Schema doc
  src/connections/storage/warehouses/index.md
  src/connections/storage/warehouses/schema.md
Labels: enhancement

#2179 repo sync
  src/_includes/menu/menu-strat.html
Labels: autoupdate, automated-reposync-pr

#2182 Missing double quotes
  src/connections/sources/catalog/libraries/ott/roku/index.md
Labels: fixed-content

#2190 Fix typo in DestinationPlugin section
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: fixed-content

#2187 Small edits to GEC docs
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: fixed-content

#2195 fix(formatting): indent industry spec items
  src/connections/spec/index.md
Labels: fixed-content

#2197 Niall/update catalog autopilotapp
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: fixed-content

#2196 Salesforce Integration: Update doc to include sandbox name at the end of account email
  src/connections/destinations/catalog/salesforce/index.md
Labels: enhancement

#2199 Update troubleshooting.md
  src/connections/sources/catalog/libraries/mobile/android/troubleshooting.md
Labels: fixed-content

#2208 Typewriter image and note updates
  src/protocols/apis-and-extensions/images/typewriter-token.png
  src/protocols/apis-and-extensions/typewriter.md
Labels: fixed-content

#2178 Updated procedure for creating an IAM role in the AWS console [DOC-375]
  src/connections/storage/catalog/aws-s3/index.md
Labels: fixed-content

#2207 Remove beta flag from AWS S3 destination in warehouse catalog
  src/_data/catalog/warehouse.yml
Labels: fixed-content

#2206 Fix sentence fragment
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: bug, fixed-content

#2204 Fixed grammatical errors - Issue 2201
  src/connections/spec/best-practices-identify.md
Labels: fixed-content

#2214 Add banner to point to Public API Beta docs
  src/config-api/index.md
Labels: back-end

#2210 Build a Journey edits [DOC-383]
  src/personas/journeys/build-journey.md
Labels: fixed-content

#2217 Release 21.48.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/warehouse.yml
  src/config-api/index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/autopilotapp/index.md
  src/connections/destinations/catalog/salesforce/index.md
  src/connections/sources/catalog/libraries/mobile/android/troubleshooting.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/sources/catalog/libraries/ott/roku/index.md
  src/connections/spec/best-practices-identify.md
  src/connections/spec/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/personas/journeys/build-journey.md
  src/privacy/user-deletion-and-suppression.md
  src/protocols/apis-and-extensions/images/typewriter-token.png
  src/protocols/apis-and-extensions/typewriter.md
Labels: release
