Repository segmentio/segment-docs, pull requests merged in 2021-10, with the labels that each got.

#1969 DOC-332 added overrides for Friendbuy
  src/_data/catalog/overrides-list.yml
  src/_data/catalog/overrides.yml
  src/_includes/content/destination-dossier.html
  src/_includes/content/destination-footer.md
  src/connections/destinations/catalog/friendbuy/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: fixed-content

#1974 Update CNAME description too
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: enhancement

#1994 Added info about how to prevent duplication in the Klaviyo source
  src/connections/sources/catalog/cloud-apps/klaviyo/index.md
Labels: enhancement

#2010 Documentation for the new Statsig destination
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/warehouse_papi.yml
  src/connections/destinations/catalog/statsig/index.md
Labels: new-integration

#2021 DOC-341 Fix HubSpot integration object reference
  src/_data/catalog/overrides.yml
Labels: fixed-content

#2047 Update instructions to enable Enhanced Conversions in Google Ads.
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: enhancement

#2043 Adobe Target destination is removed [DOC-346]
  src/connections/destinations/catalog/adobe-target/index.md
Labels: back-end

#2044 Customer.io (Actions) doc updates
  src/_data/actions/customer-io.yml
  src/connections/destinations/catalog/actions-customer-io/index.md
Labels: enhancement

#2054 Fix functions cache example
  src/_includes/content/functions/runtime.md
Labels: fixed-content

#2055 remove liquid-c
  Gemfile
  Gemfile.lock
Labels: back-end
