Repository segmentio/segment-docs, pull requests merged in 2022-12, with the labels that each got.

#3895 Add docs for proxy config option in React Native library
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#3896 December 1 Catalog Update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3893 Clean up script for adding private beta destination details
  scripts/private-destination.js
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-logrocket/index.md
Labels: back-end

#3898 Release 22.48.3
  scripts/private-destination.js
  src/_data/catalog/destinations_private.yml
  src/_data/sidenav/main.yml
  src/_includes/icons/reverse-etl.svg
  src/connections/destinations/catalog/actions-logrocket/index.md
  src/reverse-etl/bigquery-setup.md
  src/reverse-etl/images/RETL_Doc_Illustration.png
  src/reverse-etl/index.md
  src/reverse-etl/snowflake-setup.md
  src/segment-app/iam/roles.md
Labels: release

#3907 Add Events at Limits Updates
  src/engage/faqs.md
  src/profiles/faqs.md
  src/profiles/profile-api-limits.md
Labels: new-feature

#3906 Profiles Sync Public Beta
  src/_data/sidenav/main.yml
  src/_sass/components/_markdown.scss
  src/profiles/profiles-sync/index.md
  src/profiles/profiles-sync/sample-queries.md
  src/profiles/profiles-sync/tables.md
Labels: new-feature

#3904 Add section for supported Alias call to CleverTap
  src/connections/destinations/catalog/clevertap/index.md
Labels: content-update

#3903 Unhide Google Sheets documentation
  src/connections/destinations/catalog/actions-google-sheets/index.md
Labels: new-integration

#3899 CleverTap anonymous ID behaviour with AJS connection modes
  src/connections/destinations/catalog/clevertap/index.md
Labels: content-update

#3909 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/google-sheets/index.md
Labels: back-end

#3908 Clarify that all A.js Classic sources will upgrade to 2.0 after EOL
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#3913 removed the A.js 2.0 automatic migration table [DOC-625]
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#3915 Remove Transformations beta references
  src/protocols/transform/index.md
Labels: content-update

#3912 Update folder name for Webhooks (Actions)
  src/connections/destinations/catalog/actions-webhook/index.md
Labels: back-end

#3916 Profiles Sync Updates
  src/profiles/profiles-sync/index.md
  src/profiles/profiles-sync/sample-queries.md
  src/profiles/profiles-sync/tables.md
Labels: content-update

#3927 Add Profiles Sync dbt repo link
  src/profiles/profiles-sync/tables.md
Labels: content-update

#3917 Add updates to FullStory cloud mode destination docs
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
Labels: content-update

#3928 Release 22.49.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/pendo/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/engage/index.md
  src/profiles/profiles-sync/index.md
  src/profiles/profiles-sync/sample-queries.md
  src/profiles/profiles-sync/tables.md
  src/protocols/faq.md
Labels: release

#3938 Fix broken links for RETL docs
  src/reverse-etl/bigquery-setup.md
  src/reverse-etl/index.md
  src/reverse-etl/snowflake-setup.md
Labels: broken links

#3936 update to A.js Classic EOL warning note
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#3940 Update Linked User Endpoint Wording
  src/profiles/profile-api.md
Labels: content-update

#3941 EOS note for Analytics React Native Classic
  src/connections/sources/catalog/libraries/mobile/react-native/classic.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#3939 Adding info about increment traits, removing duplicate sections
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: content-update

#3945 Catalog updates
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/salesforce-marketing-cloud-actions/index.md
  src/connections/destinations/catalog/segment/index.md
  src/connections/destinations/catalog/webhooks-actions/index.md
Labels: back-end

#3933 Clarified how to add destination functions to the integrations object
  src/connections/functions/destination-functions.md
Labels: content-update

#3947 Release 22.50.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-adobe-target-cloud/index.md
  src/connections/destinations/catalog/actions-adobe-target-web/index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-hubspot-web/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/actions-segment/index.md
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/delighted/index.md
  src/connections/destinations/catalog/facebook-offline-conversions/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/mailchimp/index.md
  src/connections/destinations/catalog/pardot/index.md
  src/connections/destinations/catalog/salesforce-marketing-cloud-actions/index.md
  src/connections/destinations/catalog/segment/index.md
  src/connections/destinations/catalog/webhooks-actions/index.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/libraries/mobile/react-native/classic.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/profiles/profile-api.md
  src/reverse-etl/bigquery-setup.md
  src/reverse-etl/index.md
  src/reverse-etl/snowflake-setup.md
Labels: release

#3948 Add override for actions slug
  src/_includes/content/destination-maintenance.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/pardot/index.md
Labels: back-end

#3954 Engage Events Source GA
  src/_data/sidenav/main.yml
  src/engage/user-subscriptions/engage-source.md
Labels: content-update

#3956 Journey Archive GA [DOC-618]
  src/engage/journeys/build-journey.md
Labels: new-feature

#3943 Clarified on GA4 sessions tracking implementation
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update

#3959 Add FAQ to Salesforce (Actions)
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: content-update

#3951 Add docs for Commandbar destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-commandbar/index.md
Labels: new-integration

#3946 Update S3 Source to be EU compatible
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
Labels: content-update

#3962 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/google-ads-conversions/index.md
Labels: back-end

#3952 Ripe destination docs
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-ripe/index.md
Labels: new-integration

#3953 Update import statement to explicitly call segment.analytics
  src/connections/sources/catalog/libraries/server/python/quickstart.md
Labels: content-update

#3963 Release 22.50.2
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/ab-smartly/index.md
  src/connections/destinations/catalog/actions-commandbar/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-ripe/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/google-ads-conversions/index.md
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
  src/connections/sources/catalog/libraries/server/python/quickstart.md
Labels: release

#3966 Add Destination Actions Mappings Step #3960
  src/connections/destinations/actions.md
Labels: fixed-content
