Repository segmentio/segment-docs, pull requests merged in 2022-01, with the labels that each got.

#2298 [LiveIntent Audiences] new destination documentation
  src/connections/destinations/catalog/liveintent-audiences/index.md
Labels: new-integration

#2301 Delete src/connections/destinations/catalog/tableau directory
  src/connections/destinations/catalog/tableau/images/tableausetup1.png
  src/connections/destinations/catalog/tableau/images/tableausetup2.png
  src/connections/destinations/catalog/tableau/images/tableausetup3.png
  src/connections/destinations/catalog/tableau/index.md
Labels: enhancement

#2254 Kameleoon updated their HackMD doc - updated docs accordingly
  src/connections/destinations/catalog/kameleoon/index.md
Labels: fixed-content

#2300 update incorrect description of a few fields
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
Labels: content

#2304 Update ClientSuccess Destination doc
  src/connections/destinations/catalog/clientsuccess/index.md
Labels: content

#2305 Display links for partner owned components
  src/_includes/content/destination-dossier.html
Labels: enhancement

#2306 Add the NPM option to A.js quickstart
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
Labels: content

#2294 Update index.md
  src/connections/sources/catalog/cloud-apps/radar/index.md
Labels: enhancement

#2325 Pause/Resume Journeys [DOC-402]
  src/personas/journeys/build-journey.md
Labels: fixed-content

#2331 Release 22.2.1
  .github/workflows/check-links-external.yml
  .github/workflows/check-links-internal.yml
  Makefile
  package.json
  scripts/catalog_papi.js
  scripts/checklinks-external.js
  scripts/checklinks-internal.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/contributors.yml
  src/_data/img.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/current-version.html
  src/connections/destinations/catalog/adjust/index.md
  src/connections/destinations/catalog/adobe-analytics/index.md
  src/connections/destinations/catalog/amazon-lambda/index.md
  src/connections/destinations/catalog/cruncher/index.md
  src/connections/destinations/catalog/gtag/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/liveintent-audiences/index.md
  src/connections/destinations/catalog/natero/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/twilio-event-streams-beta/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/migration.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/catalog/libraries/website/javascript/spa.md
  src/connections/sources/cross-domain.md
  src/connections/spec/mobile.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/getting-started/05-data-to-destinations.md
  src/guides/how-to-guides/cross-channel-tracking.md
  src/guides/how-to-guides/dynamic-coupon-program.md
  src/guides/how-to-guides/set-up-notifications-alerts.md
  src/guides/ignore-bots.md
  src/help/index.md
  src/partners/co-marketing.md
  src/partners/index.md
  src/personas/index.md
  src/privacy/faq.md
  src/utils/formatguide.md
  src/utils/images.md
  yarn.lock
Labels: release

#2334 Realtime Audience and Trait Editability [DOC-390]
  src/personas/audiences/index.md
Labels: fixed-content

#2348 Journeys Historical Data updates
  src/personas/journeys/faq-best-practices.md
Labels: fixed-content

#2351 Release 22.2.2
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-sprig-web/index.md
  src/connections/destinations/catalog/appcues/index.md
  src/connections/destinations/catalog/customer-io-actions/index.md
  src/connections/destinations/catalog/sailthru-v2/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/personas/journeys/faq-best-practices.md
Labels: release

#2360 Remove usage of 'backfill'
  src/personas/journeys/faq-best-practices.md
Labels: fixed-content

#1966 BytePlus destination
  src/connections/destinations/catalog/datarangers/index.md
Labels: new-integration

#2364 Personas and GDPR updates [DOC-428]
  src/personas/personas-gdpr.md
Labels: fixed-content

#2367 Personas Numbers Fix
  src/personas/using-personas-data.md
Labels: fixed-content

#2376 Journeys Recurrence [DOC-432]
  src/personas/journeys/build-journey.md
Labels: content

#2353 Identify-call-NodeJS-2327
  src/_includes/content/syntax-note.md
  src/connections/spec/alias.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/track.md
Labels: enhancement

#2380 Release 22.3.2
  src/_data/catalog/overrides.yml
  src/_includes/content/connection-modes.md
  src/_includes/content/syntax-note.md
  src/connections/destinations/catalog/datarangers/index.md
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
  src/connections/spec/alias.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/track.md
Labels: release

#2386 DOC-433 Removing the 'last updated' dates
  src/connections/destinations/catalog/adobe-target/index.md
  src/connections/destinations/catalog/alexa/index.md
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
  src/connections/destinations/catalog/ambassador/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/apptimize/index.md
  src/connections/destinations/catalog/autopilothq/index.md
  src/connections/destinations/catalog/bing-ads/index.md
  src/connections/destinations/catalog/branch-metrics/index.md
  src/connections/destinations/catalog/bugherd/index.md
  src/connections/destinations/catalog/bugsnag/index.md
  src/connections/destinations/catalog/clearbit-enrichment/index.md
  src/connections/destinations/catalog/clicky/index.md
  src/connections/destinations/catalog/crazy-egg/index.md
  src/connections/destinations/catalog/criteo-offline-conversions/index.md
  src/connections/destinations/catalog/elevio/index.md
  src/connections/destinations/catalog/evergage/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/destinations/catalog/facebook-offline-conversions/index.md
  src/connections/destinations/catalog/flurry/index.md
  src/connections/destinations/catalog/foxmetrics/index.md
  src/connections/destinations/catalog/gainsight-px/index.md
  src/connections/destinations/catalog/gainsight/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/heap/index.md
  src/connections/destinations/catalog/hotjar/index.md
  src/connections/destinations/catalog/indicative/index.md
  src/connections/destinations/catalog/inspectlet/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/kissmetrics/index.md
  src/connections/destinations/catalog/leanplum/index.md
  src/connections/destinations/catalog/lucky-orange/index.md
  src/connections/destinations/catalog/mailchimp/index.md
  src/connections/destinations/catalog/matomo/index.md
  src/connections/destinations/catalog/mouseflow/index.md
  src/connections/destinations/catalog/new-relic/index.md
  src/connections/destinations/catalog/parsely/index.md
  src/connections/destinations/catalog/qualaroo/index.md
  src/connections/destinations/catalog/quanticmind/index.md
  src/connections/destinations/catalog/quora-conversion-pixel/index.md
  src/connections/destinations/catalog/salesforce-dmp/index.md
  src/connections/destinations/catalog/simplereach/index.md
  src/connections/destinations/catalog/slack/index.md
  src/connections/destinations/catalog/snapengage/index.md
  src/connections/destinations/catalog/track-js/index.md
  src/connections/destinations/catalog/tv-squared/index.md
  src/connections/destinations/catalog/userlike/index.md
  src/connections/destinations/catalog/uservoice/index.md
  src/connections/destinations/catalog/wootric-by-inmoment/index.md
  src/connections/destinations/catalog/yandex-metrica/index.md
  src/connections/destinations/catalog/zendesk/index.md
  src/connections/destinations/catalog/zopim/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/twilio/index.md
  src/connections/storage/catalog/snowflake/index.md
Labels: fixed-content

#2392 docs: update Algolia products
  src/connections/destinations/catalog/algolia-insights/index.md
Labels: fixed-content

#2389 Track link functionality documentation update
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: enhancement

#2379 Add stackadapt browser destination docs
  src/connections/destinations/catalog/stackadapt/index.md
Labels: new-integration

#2391 Added mention of Swift Package Manager to Quickstart:iOS
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
Labels: fixed-content

#2384 DOC-403 Adding admonition to Google Universal Analytics docs
  src/connections/destinations/catalog/google-analytics/index.md
Labels: fixed-content

#2402 Destination Filter updates [DOC-434]
  src/connections/destinations/destination-filters.md
Labels: fixed-content

#2388 Journeys Recurrence Update [DOC-432]
  src/personas/journeys/build-journey.md
Labels: fixed-content

#2409 Add new RegalVoice events and associated fields.
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
Labels: enhancement, fixed-content

#2410 Remove incorrect support info
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: fixed-content

#2407 Add mixpanel-actions docs
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-mixpanel/images/set-group-key.gif
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: hidden

#2415 Update Computed Traits
  src/personas/computed-traits.md
Labels: fixed-content

#2418 New Vale styles
  vale-styles/segment/exclamation.yml
  vale-styles/segment/links.yml
  vale-styles/segment/numbers.yml
Labels: enhancement

#2419 Release 22.4.2
  .github/release.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-mixpanel/images/set-group-key.gif
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
  src/personas/computed-traits.md
  vale-styles/segment/exclamation.yml
  vale-styles/segment/links.yml
  vale-styles/segment/numbers.yml
Labels: release

#2424 repo sync
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/warehouse_papi.yml
  src/_data/regional.yml
  src/_data/regionl_support.yml
  src/_data/sidenav/main.yml
  src/_includes/components/ajs-cookie.html
  src/_includes/components/button-hollow.html
  src/_includes/content/regional-integrations-table.md
  src/_sass/components/_markdown.scss
  src/connections/destinations/catalog/byteplus/index.md
  src/connections/regional-segment-eu.md
  src/connections/regional-segment.md
  src/guides/regional-segment.md
Labels: autoupdate, automated-reposync-pr

#2425 Release 22.4.3
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/warehouse_papi.yml
  src/_data/regional.yml
  src/_data/regionl_support.yml
  src/_data/sidenav/main.yml
  src/_includes/components/ajs-cookie.html
  src/_includes/components/button-hollow.html
  src/_includes/content/regional-integrations-table.md
  src/_sass/components/_markdown.scss
  src/connections/destinations/catalog/byteplus/index.md
  src/connections/regional-segment-eu.md
  src/connections/regional-segment.md
  src/guides/regional-segment.md
Labels: release

#2408 Analytics.js EOL note
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: enhancement

#2431 Release 22.5.1
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/guides/regional-segment.md
Labels: release

#2433 small update to ga4
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: fixed-content
