Repository segmentio/segment-docs, pull requests merged in 2022-09, with the labels that each got.

#3438 Update how zlib must be referenced in functions docs
  src/_includes/content/functions/runtime.md
Labels: content-update

#3440 Add note to GEC about order ID requirements
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update

#3441 Release 22.35.2
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: release

#3447 Add Compute Times Note #3428
  src/engage/audiences/index.md
  src/engage/profiles/computed-traits.md
  src/personas/audiences/index.md
  src/personas/computed-traits.md
Labels: content-update

#3449 Add Personas Sync ETA Content [DOC-576]
  src/personas/audiences/index.md
  src/personas/faqs.md
  src/personas/product-limits.md
Labels: new-feature

#3453 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3436 Iterate actions documentation
  src/connections/destinations/catalog/actions-iterate/index.md
Labels: new-integration

#3454 Release 22.36.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-iterate/index.md
  src/connections/destinations/catalog/actions-qualtrics/index.md
  src/engage/audiences/index.md
  src/engage/profiles/computed-traits.md
  src/personas/audiences/index.md
  src/personas/computed-traits.md
  src/personas/faqs.md
  src/personas/product-limits.md
Labels: release

#3457 Profiles at Limits Fix [DOC-575]
  src/personas/audiences/index.md
  src/personas/faqs.md
  src/personas/product-limits.md
Labels: content-update

#3462 Remove line from GA4 docs
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update

#3456 Custom externalIDs section updates
  src/personas/identity-resolution/externalids.md
Labels: content-update

#3467 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3469 Release 22.36.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/connection-modes-intro.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/destination-filters.md
  src/connections/destinations/index.md
  src/connections/sources/index.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/personas/identity-resolution/externalids.md
  src/protocols/apis-and-extensions/typewriter.md
Labels: release

#3478 Remove region unsupported message for Sendgrid and Mandrill
  src/connections/sources/catalog/cloud-apps/mandrill/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: content-update

#3486 Update number of unique events to 4,000 from 2,000
  src/connections/schema-unique-limits.md
Labels: content-update

#3487 Release 22.37.1
  .github/styles/Vocab/Docs/accept.txt
  src/_includes/components/available-actions.html
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/category-compare.md
  src/connections/schema-unique-limits.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/migration.md
Labels: release

#3489 Update index.md
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: content-update

#3493 Update Public API GA Includes Link
  src/_includes/content/papi-ga.html
Labels: fixed-content

#3500 Fix an anchor link
  src/connections/destinations/actions.md
Labels: content-update

#3504 Release 22.37.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destinations_private.yml
  src/_data/landing.yml
  src/_includes/content/papi-ga.html
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-sendgrid/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: release

#3510 Update index.md
  src/connections/destinations/catalog/intercom/index.md
Labels: content-update

#3513 Add docs for new Bento destination
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/bento/index.md
Labels: new-integration

#3509 Add redirect to Config API
  src/api/config-api/index.md
Labels: back-end

#3518 Fix Broken Gainsight Link [DOC-581]
  src/_includes/content/sync-frequency-note.md
  src/connections/destinations/catalog/gainsight/index.md
Labels: fixed-content

#3519 Update Adjust SDK SKAdNetwork Guidance [DOC-584]
  src/connections/destinations/catalog/adjust/index.md
Labels: fixed-content

#3514 Fixed some broken links
  src/_data/nav.yml
  src/connections/destinations/catalog/selligent-marketing-cloud/index.md
  src/connections/destinations/repeater-migration.md
  src/connections/spec/mobile.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/partners/enable-with-segment.md
Labels: back-end

#3443 Analytics for AMP edits
  src/connections/sources/catalog/libraries/mobile/amp/index.md
Labels: content-update

#3525 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3523 Cross link FullStory destinations
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-fullstory/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/fullstory/index.md
Labels: content-update

#3527 Release 22.38.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/nav.yml
  src/_includes/content/sync-frequency-note.md
  src/api/config-api/index.md
  src/connections/destinations/catalog/actions-cordial/index.md
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-fullstory/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/actions-moengage/index.md
  src/connections/destinations/catalog/adjust/index.md
  src/connections/destinations/catalog/bento/index.md
  src/connections/destinations/catalog/fullstory/index.md
  src/connections/destinations/catalog/gainsight/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/selligent-marketing-cloud/index.md
  src/connections/destinations/repeater-migration.md
  src/connections/sources/catalog/cloud-apps/mandrill/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/sources/catalog/libraries/mobile/amp/index.md
  src/connections/spec/mobile.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/partners/enable-with-segment.md
Labels: release

#3533 Add ability to hide individual actions
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-intercom-web/index.md
Labels: back-end

#3536 fixes minor typo
  src/personas/audiences/index.md
Labels: content-update

#3540 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/available-actions.html
Labels: back-end

#3531 small changes to intercom cloud actions docs
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
Labels: content-update

#3545 Release 22.38.2
  Gemfile.lock
  package-lock.json
  package.json
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/_includes/components/available-actions.html
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/guides/how-to-guides/cross-channel-tracking.md
  src/guides/regional-segment.md
  src/personas/audiences/index.md
  yarn.lock
Labels: release

#3549 adds FAQ to Source Function docs about GET requests
  src/connections/functions/source-functions.md
Labels: content-update

#3555 Add Channels Billing Info [DOC-580]
  src/guides/usage-and-billing/mtus-and-throughput.md
Labels: content-update

#3552 Fix TikTok Conversions Link #3550
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/tiktok-conversions/index.md
Labels: fixed-content

#3560 Fix Server Debugger Typo #3558
  src/_includes/content/troubleshooting-server-debugger.md
Labels: fixed-content

#3543 Update Shopify Littledata - Deploy
  Gemfile.lock
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
Labels: content-update

#3565 Hidden sources should be hidden
  src/_includes/content/cloud-source-type-list.md
Labels: back-end

#3567 Update destination filters screenshot
  src/connections/destinations/images/destination-filters/clean_example.png
Labels: content-update

#3562 Azure doc updates
  .github/styles/Vocab/Docs/accept.txt
  src/connections/storage/catalog/data-lakes/images/storageaccount.png
  src/connections/storage/catalog/data-lakes/images/storagecontainer.png
  src/connections/storage/catalog/data-lakes/index.md
Labels: content-update

#3573 Update Azure Data Lakes to Segment Data Lakes (Azure) [DOC-585]
  src/_data/catalog/destinations.yml
  src/_data/catalog/slugs.yml
  src/connections/storage/catalog/data-lakes/index.md
  src/connections/storage/data-lakes/comparison.md
  src/connections/storage/data-lakes/index.md
  src/connections/storage/data-lakes/lake-formation.md
  src/connections/storage/data-lakes/sync-history.md
  src/connections/storage/data-lakes/sync-reports.md
  src/guides/regional-segment.md
Labels: content-update

#3574 Docs for new Statsig source
  .github/styles/Vocab/Docs/accept.txt
  src/connections/sources/catalog/cloud-apps/statsig/index.md
Labels: new-integration

#3580 Add Journeys Level Analytics Datepicker Info
  src/engage/journeys/images/journeys_analytics_tiles.png
  src/engage/journeys/journeys-analytics.md
Labels: content-update

#3581 Add Analytics.js Cookie Subdomain Info [DOC-582]
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/website/javascript/persistence.md
Labels: content-update

#3576 Update order of birthday traits
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: content-update

#3583 Release 22.39.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destinations.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-moengage/index.md
  src/connections/destinations/catalog/moengage/images/moengage_segment_identify.png
  src/connections/destinations/catalog/moengage/images/moengage_segment_track.png
  src/connections/destinations/catalog/moengage/images/segment_audience_1.png
  src/connections/destinations/catalog/moengage/images/segment_audience_2.png
  src/connections/destinations/catalog/moengage/images/segment_audience_4.png
  src/connections/destinations/catalog/moengage/images/segment_audience_5.png
  src/connections/destinations/catalog/moengage/images/segment_audience_destination.png
  src/connections/destinations/catalog/moengage/images/segment_new_trait.png
  src/connections/destinations/catalog/moengage/images/segment_new_trait_backfill.png
  src/connections/destinations/catalog/moengage/images/segment_new_trait_button.png
  src/connections/destinations/catalog/moengage/images/segment_select_moengage_destination.png
  src/connections/destinations/catalog/moengage/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/connections/sources/catalog/cloud-apps/statsig/index.md
  src/connections/sources/catalog/libraries/website/javascript/persistence.md
  src/engage/journeys/images/journeys_analytics_tiles.png
  src/engage/journeys/journeys-analytics.md
Labels: release

#3591 Remove Segment Data Lakes (Azure) Beta Flag
  src/connections/storage/data-lakes/sync-history.md
Labels: fixed-content
