Repository segmentio/segment-docs, pull requests merged in 2022-03, with the labels that each got.

#2547 Release 22.9.1
  src/_data/catalog/destinations.yml
  src/connections/destinations/add-destination.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/graphjson/index.md
Labels: release

#2554 Add required server fields to Facebook CAPI (Actions)
  .github/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: enhancement

#2553 Add 'name' to traits list for Group call
  src/connections/destinations/catalog/hubspot/index.md
Labels: enhancement

#2552 Add a note about super properties in Mixpanel
  src/connections/destinations/catalog/mixpanel/index.md
Labels: enhancement

#2558 Release 22.9.2
  .github/Vocab/Docs/accept.txt
  Makefile
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#2559 Add required indicator to actions fields
  src/_includes/components/actions-fields.html
  src/_sass/components/_markdown.scss
Labels: enhancement

#2563 Docs Update - Integration: Kustomer
  src/connections/destinations/catalog/kustomer/index.md
Labels: fixed-content

#2569 repo sync
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/migration.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/index.md
Labels: autoupdate, automated-reposync-pr

#2571 Release 22.10.1
  Gemfile.lock
  src/_includes/components/actions-fields.html
  src/_sass/components/_markdown.scss
  src/connections/destinations/catalog/kustomer/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/migration.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/index.md
  src/getting-started/06-testing-debugging.md
Labels: release

#2572 Removing date associated with shared service account section of BigQuery docs
  src/connections/storage/catalog/bigquery/index.md
Labels: enhancement

#2574 Added clarity around what each icon means
  Gemfile.lock
  src/_includes/content/regional-integrations-table.md
  src/_sass/components/_markdown.scss
  src/guides/regional-segment.md
Labels: enhancement

#2582 Update page to remove appsflyer from the swift supported destinations list
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: fixed-content

#2581 Update index.md for Kotlin page to remove appsflyer from destination list
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: fixed-content

#2584 Release 22.10.3
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: release

#2591 Release 22.10.4
  src/_includes/content/destination-dossier.html
  src/_sass/components/_quickinfo.scss
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: release

#2593 Add deduplication FAQ
  src/connections/destinations/catalog/tiktok-conversions/index.md
Labels: enhancement

#2598 Braze External ID Update [DOC-473]
  src/personas/identity-resolution/externalids.md
Labels: fixed-content

#2599 HTTP API/Spec Field ID Updates [DOC-470]
  src/_includes/content/spec-field-anonymous-id.md
  src/_includes/content/spec-field-user-id.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/spec/identify.md
Labels: fixed-content

#2603 Release 22.11.1
  src/_data/catalog/overrides.yml
  src/_includes/content/destination-dossier.html
  src/_includes/content/spec-field-anonymous-id.md
  src/_includes/content/spec-field-user-id.md
  src/connections/destinations/catalog/amplitude/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/spec/identify.md
  src/personas/identity-resolution/externalids.md
Labels: release

#2533 Warehouse doc updates
  src/_data/sidenav/main.yml
  src/_includes/content/how-a-sync-works.md
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/images/sql-redshift-table-1.jpg
  src/connections/storage/warehouses/index.md
  src/connections/storage/warehouses/redshift-useful-sql.md
  src/connections/storage/warehouses/schema.md
  src/connections/storage/warehouses/warehouse-syncs.md
Labels: enhancement

#2611 SendGrid Source Updates
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: fixed-content

#2609 Removed the hyperlink new tab icon [DOC-483]
  src/_sass/components/_markdown.scss
Labels: back-end

#2610 Common Spec cleanup
  src/_includes/content/spec-table-header.md
  src/connections/spec/common.md
  src/protocols/tracking-plan/create.md
Labels: fixed-content

#2613 Release 22.11.2
  src/_data/sidenav/main.yml
  src/_includes/content/how-a-sync-works.md
  src/_includes/content/spec-table-header.md
  src/_sass/components/_markdown.scss
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/java/quickstart.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/spec/common.md
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/images/sql-redshift-table-1.jpg
  src/connections/storage/warehouses/index.md
  src/connections/storage/warehouses/redshift-useful-sql.md
  src/connections/storage/warehouses/schema.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/partners/streams.md
  src/protocols/tracking-plan/create.md
Labels: release

#2617 fix(content): replace period with colon in object
  src/connections/storage/warehouses/schema.md
Labels: fixed-content

#2620 Correct Nested Properties Objects to Flattened
  src/connections/storage/warehouses/schema.md
Labels: fixed-content

#2622 repo sync
  _redirects
  src/utils/env.md
Labels: autoupdate, automated-reposync-pr

#2623 repo sync
  _config.yml
  src/_redirects
Labels: autoupdate, automated-reposync-pr

#2628 Journeys Connect to Existing Steps content [DOC-475]
  src/personas/journeys/build-journey.md
  src/personas/journeys/images/journey_step-types.png
Labels: enhancement

#2629 repo sync
  src/_redirects
Labels: autoupdate, automated-reposync-pr

#2630 Fixed a broken link for RN Migration Guide
  src/connections/sources/catalog/libraries/mobile/react-native/migration.md
Labels: broken links

#2627 Crossingminds
  src/connections/destinations/catalog/crossing-minds/index.md
Labels: new-integration

#2637 repo sync
  src/_redirects
Labels: autoupdate, automated-reposync-pr

#2638 Protocols/Google Sheets Tracking Plan Fix [DOC-484]
  src/protocols/apis-and-extensions/index.md
Labels: fixed-content

#2640 Niall/kinesis base64 remove
  src/connections/destinations/catalog/amazon-kinesis/index.md
Labels: fixed-content

#2643 Updating migration guide
  src/_redirects
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/migration.md
  src/connections/storage/warehouses/redshift-useful-sql.md
  src/protocols/apis-and-extensions/index.md
Labels: fixed-content

#2648 REST vs. SOAP endpoint
  src/connections/destinations/catalog/marketo-static-lists/index.md
Labels: fixed-content

#2647 Remove partner owned sections for integrations we own
  src/connections/destinations/catalog/attribution/index.md
  src/connections/destinations/catalog/clearbit-reveal/index.md
  src/connections/destinations/catalog/natero/index.md
Labels: fixed-content

#2649 Swift/Kotlin no longer in beta
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: enhancement

#2646 Prevent mistakes when setting up Marketo
  src/connections/destinations/catalog/marketo-static-lists/index.md
Labels: enhancement

#2644 Add Groundswell Destination to Segment Doc
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/groundswell/index.md
Labels: new-integration

#2652 Release 22.12.2
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/amazon-kinesis/index.md
  src/connections/destinations/catalog/attribution/index.md
  src/connections/destinations/catalog/clearbit-reveal/index.md
  src/connections/destinations/catalog/crossing-minds/index.md
  src/connections/destinations/catalog/groundswell/index.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/natero/index.md
  src/connections/destinations/catalog/retentive/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: release

#2656 Script to add id to integration frontmatter
  .yarn/cache/ansi-colors-npm-4.1.1-97ad42f223-138d04a510.zip
  .yarn/cache/enquirer-npm-2.3.6-7899175762-1c0911e14a.zip
  .yarn/install-state.gz
  Makefile
  package.json
  scripts/add_id.js
  scripts/update.js
  yarn.lock
Labels: back-end

#2665 Add required imports for kotlin
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: fixed-content

#2655 add info about device id could be empty
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: fixed-content

#2668 Fix broken external links
  ignore-links.txt
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
  src/connections/destinations/catalog/fullstory/index.md
  src/connections/destinations/catalog/madkudu/index.md
  src/connections/destinations/catalog/moengage/index.md
  src/connections/destinations/catalog/vero/index.md
  src/connections/destinations/catalog/vespucci/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: fixed-content

#2657 Documentation update for Android and iOS
  src/connections/destinations/catalog/moengage/index.md
Labels: fixed-content

#2676 Correcting Page methods name
  src/connections/destinations/methods-compare.md
Labels: fixed-content

#2632 Add five new Zendesk collections [DOC-452]
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
Labels: enhancement

#2570 Adding BCR Compliance page to the Privacy docs [DOC-460]
  src/_data/sidenav/main.yml
  src/privacy/account-deletion.md
  src/privacy/user-deletion-and-suppression.md
Labels: enhancement

#2681 Update Ambassador destination docs
  src/connections/destinations/catalog/ambassador/index.md
Labels: fixed-content

#2683 Unlimited Journeys Updates [DOC-454]
  src/personas/product-limits.md
Labels: enhancement

#2684 Release 22.13.2
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/ambassador/index.md
  src/connections/destinations/catalog/moengage/index.md
  src/connections/destinations/catalog/salesforce-marketing-cloud/index.md
  src/connections/destinations/methods-compare.md
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
  src/personas/product-limits.md
  src/privacy/account-deletion.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#2686 DOC 206 part 2
  .gitignore
  .yarn/cache/find-up-npm-6.3.0-e5056fc655-9a21b7f924.zip
  .yarn/cache/locate-path-npm-7.1.0-d19ada3feb-17d5eb6c04.zip
  .yarn/cache/p-limit-npm-3.1.0-05d2ede37f-7c3690c4db.zip
  .yarn/cache/p-limit-npm-4.0.0-5dccf29b67-01d9d70695.zip
  .yarn/cache/p-locate-npm-5.0.0-92cc7c7a3e-1623088f36.zip
  .yarn/cache/p-locate-npm-6.0.0-b6cfb720dc-2bfe5234ef.zip
  .yarn/cache/path-exists-npm-5.0.0-0bf403c56c-8ca842868c.zip
  .yarn/cache/pkg-dir-npm-6.0.1-ccd2d573ff-ba14970537.zip
  .yarn/cache/yocto-queue-npm-0.1.0-c6c9a7db29-f77b3d8d00.zip
  .yarn/cache/yocto-queue-npm-1.0.0-7b502f1987-2cac84540f.zip
  .yarn/install-state.gz
  package.json
  src/_includes/content/destination-dossier.html
  yarn.lock
Labels: enhancement
