Repository segmentio/segment-docs, pull requests merged in 2022-02, with the labels that each got.

#2423 redirect sprig actions
  src/connections/destinations/catalog/actions-sprig-web/index.md
Labels: fixed-site

#2414 [byteplus] adding new destination folder in order to show new name in…
  src/connections/destinations/catalog/byteplus/index.md
Labels: fixed-site

#2422 Add region unsupported message for all cloud sources
  src/_includes/content/source-region-unsupported.md
  src/connections/sources/catalog/cloud-apps/activecampaign/index.md
  src/connections/sources/catalog/cloud-apps/aircall/index.md
  src/connections/sources/catalog/cloud-apps/airship/index.md
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
  src/connections/sources/catalog/cloud-apps/amplitude-cohorts/index.md
  src/connections/sources/catalog/cloud-apps/autopilothq/index.md
  src/connections/sources/catalog/cloud-apps/beamer/index.md
  src/connections/sources/catalog/cloud-apps/blueshift/index.md
  src/connections/sources/catalog/cloud-apps/braze/index.md
  src/connections/sources/catalog/cloud-apps/candu/index.md
  src/connections/sources/catalog/cloud-apps/chatlio/index.md
  src/connections/sources/catalog/cloud-apps/customer-io/index.md
  src/connections/sources/catalog/cloud-apps/delighted/index.md
  src/connections/sources/catalog/cloud-apps/desk-com/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/cloud-apps/factual-engine/index.md
  src/connections/sources/catalog/cloud-apps/foursquare-pilgrim/index.md
  src/connections/sources/catalog/cloud-apps/friendbuy/index.md
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
  src/connections/sources/catalog/cloud-apps/herow/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/intercom/index.md
  src/connections/sources/catalog/cloud-apps/iterable/index.md
  src/connections/sources/catalog/cloud-apps/klaviyo/index.md
  src/connections/sources/catalog/cloud-apps/klenty/index.md
  src/connections/sources/catalog/cloud-apps/launchdarkly/index.md
  src/connections/sources/catalog/cloud-apps/leanplum/index.md
  src/connections/sources/catalog/cloud-apps/looker/index.md
  src/connections/sources/catalog/cloud-apps/mailchimp/index.md
  src/connections/sources/catalog/cloud-apps/mailjet/index.md
  src/connections/sources/catalog/cloud-apps/mandrill/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
  src/connections/sources/catalog/cloud-apps/moesif-api-analytics/index.md
  src/connections/sources/catalog/cloud-apps/nudgespot/index.md
  src/connections/sources/catalog/cloud-apps/pendo/index.md
  src/connections/sources/catalog/cloud-apps/provesource/index.md
  src/connections/sources/catalog/cloud-apps/radar/index.md
  src/connections/sources/catalog/cloud-apps/refiner/index.md
  src/connections/sources/catalog/cloud-apps/regal-voice/index.md
  src/connections/sources/catalog/cloud-apps/salesforce-marketing-cloud/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/selligent-marketing-cloud/index.md
  src/connections/sources/catalog/cloud-apps/selligent/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/sources/catalog/cloud-apps/shopify-littledata/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/sources/catalog/cloud-apps/twilio-event-streams-beta/index.md
  src/connections/sources/catalog/cloud-apps/twilio/index.md
  src/connections/sources/catalog/cloud-apps/vero/index.md
  src/connections/sources/catalog/cloud-apps/wootric/index.md
  src/connections/sources/catalog/cloud-apps/youbora/index.md
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
Labels: fixed-site

#2416 Friendbuy cloud destination
  src/connections/destinations/catalog/actions-friendbuy-cloud/index.md
  src/connections/destinations/catalog/actions-friendbuy/index.md
Labels: new-integration

#2446 Removed a property that does not exist in the Intercom source
  src/connections/sources/catalog/cloud-apps/intercom/index.md
Labels: fixed-content

#2449 chore: updating troubleshooting docs with flush use case
  src/_includes/content/troubleshooting-server-debugger.md
Labels: enhancement

#2444 Wenxi/update kotlin migration guide
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
Labels: enhancement

#2413 Updating Amazon S3 limited access banner
  src/connections/storage/catalog/amazon-s3/index.md
Labels: fixed-content

#2462 Fix URLs in Regional Segment support table
  src/_data/sidenav/strat.yml
  src/_includes/content/regional-integrations-table.md
  src/connections/destinations/catalog/salesforce-dmp/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/connections/storage/catalog/amazon-s3/index.md
Labels: fixed-site

#2467 table code inline css into class
  src/_sass/components/_markdown.scss
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
Labels: back-end

#2469 Journeys FAQ update
  src/personas/journeys/faq-best-practices.md
Labels: fixed-content

#2463 Reformat og:title
  src/_layouts/default.html
Labels: fixed-site

#2460 Add more to GA4 docs
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: enhancement

#2458 Added a note about property hashing
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
Labels: enhancement

#2471 Updated the 'Relying on Analytics.js Classic's ajs_anonymous_id cookie format' section [DOC-393]
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: fixed-content

#2479 Release 22.6.2
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
Labels: release

#2480 Update sample code in IDFA tracking section
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: fixed-content

#2474 Fix some links
  src/connections/destinations/catalog/actions-friendbuy-cloud/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: fixed-site

#2485 Release 22.6.3
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-friendbuy-cloud/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: release

#2491 Built tooling to spit out a CSV of beta sources and destinations
  .gitignore
  Makefile
  package-lock.json
  package.json
  scripts/beta.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/aircall/index.md
  src/connections/sources/catalog/cloud-apps/airship/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/cloud-apps/klenty/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/provesource/index.md
Labels: back-end

#2489 Added clarity to Facebook App Events context.device.type accepted values
  src/connections/destinations/catalog/facebook-app-events/index.md
Labels: enhancement

#2498 Added Google Analytics destination metadata
  .yarn/cache/@fast-csv-format-npm-4.3.5-e0dba6439e-36d5fb76c2.zip
  .yarn/cache/@fast-csv-parse-npm-4.3.6-38021b86fe-15434d2bc7.zip
  .yarn/cache/@types-node-npm-14.18.11-a9cca941fe-58f75d0540.zip
  .yarn/cache/fast-csv-npm-4.3.6-f41c31419c-77ae68c08b.zip
  .yarn/cache/lodash.escaperegexp-npm-4.1.2-c5b90e0e9c-6d99452b1c.zip
  .yarn/cache/lodash.groupby-npm-4.6.0-b885eee622-e2d4d13d12.zip
  .yarn/cache/lodash.isboolean-npm-3.0.3-b575b41488-b70068b4a8.zip
  .yarn/cache/lodash.isfunction-npm-3.0.9-72aaa7f66c-99e54c34b1.zip
  .yarn/cache/lodash.isnil-npm-4.0.0-8c8ee34fe6-ebf8df6987.zip
  .yarn/cache/lodash.isundefined-npm-3.0.1-2d32487d33-52b4d99a47.zip
  .yarn/cache/lodash.uniq-npm-4.5.0-7c270dca85-a4779b57a8.zip
  .yarn/install-state.gz
  package.json
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/graphjson/index.md
  yarn.lock
Labels: enhancement

#2484 Add another FAQ to GEC docs
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: enhancement

#2500 Release 22.7.1
  .gitignore
  .yarn/cache/@fast-csv-format-npm-4.3.5-e0dba6439e-36d5fb76c2.zip
  .yarn/cache/@fast-csv-parse-npm-4.3.6-38021b86fe-15434d2bc7.zip
  .yarn/cache/@types-node-npm-14.18.11-a9cca941fe-58f75d0540.zip
  .yarn/cache/fast-csv-npm-4.3.6-f41c31419c-77ae68c08b.zip
  .yarn/cache/lodash.escaperegexp-npm-4.1.2-c5b90e0e9c-6d99452b1c.zip
  .yarn/cache/lodash.groupby-npm-4.6.0-b885eee622-e2d4d13d12.zip
  .yarn/cache/lodash.isboolean-npm-3.0.3-b575b41488-b70068b4a8.zip
  .yarn/cache/lodash.isfunction-npm-3.0.9-72aaa7f66c-99e54c34b1.zip
  .yarn/cache/lodash.isnil-npm-4.0.0-8c8ee34fe6-ebf8df6987.zip
  .yarn/cache/lodash.isundefined-npm-3.0.1-2d32487d33-52b4d99a47.zip
  .yarn/cache/lodash.uniq-npm-4.5.0-7c270dca85-a4779b57a8.zip
  .yarn/install-state.gz
  Makefile
  package-lock.json
  package.json
  scripts/beta.js
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/graphjson/index.md
  src/connections/sources/catalog/cloud-apps/aircall/index.md
  src/connections/sources/catalog/cloud-apps/airship/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/cloud-apps/klenty/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/provesource/index.md
  yarn.lock
Labels: release

#2503 Doc-457-Batch-Destinations-Sync-Frequency
  src/_includes/content/destination-footer.md
  src/_includes/content/sync-frequency-note.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/connections/destinations/catalog/responsys/index.md
  src/personas/product-limits.md
Labels: fixed-content

#2502 Added yaml file for integration slug overrides
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#2501 Enabled destination metadata block for Actions destinations
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/catalog/actions-customer-io/index.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-friendbuy-cloud/index.md
  src/connections/destinations/catalog/actions-friendbuy/index.md
  src/connections/destinations/catalog/actions-fullstory/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/actions-slack/index.md
  src/connections/destinations/catalog/actions-sprig-web/index.md
  src/connections/destinations/catalog/actions-voyage/index.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/braze-web-device-mode-actions/index.md
Labels: enhancement

#2517 Update Journeys Re-entry Sections
  src/personas/journeys/build-journey.md
  src/personas/journeys/journeys-logic.md
Labels: fixed-content

#2520 OneSignal update DOC-464
  src/connections/destinations/catalog/onesignal-new/index.md
Labels: enhancement

#2516 Add Schema Controls to main nav
  src/_data/sidenav/main.yml
Labels: fixed-site

#2527 Release 22.8.1
  .github/workflows/grammar-lint.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/onesignal-new/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/personas/journeys/build-journey.md
  src/personas/journeys/journeys-logic.md
  src/segment-app/iam/scim.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#2530 feat(content): minor improvements
  .github/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/marketo-static-lists/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: fixed-content

#2532 url fixes
  ignore-links.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/databrain/index.md
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
  src/connections/destinations/catalog/funnelfox/index.md
  src/connections/destinations/catalog/ibm-ubx/index.md
  src/connections/destinations/catalog/kochava/index.md
  src/connections/destinations/catalog/lytics/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/msg91/index.md
  src/connections/destinations/catalog/nielsen-dcr/index.md
  src/connections/destinations/catalog/scuba-analytics/index.md
  src/connections/destinations/catalog/slack/index.md
  src/connections/destinations/catalog/uservoice/index.md
  src/connections/destinations/catalog/vitally/index.md
  src/connections/destinations/catalog/woopra/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: fixed-site

#2534 Batch-audience-compute-clarification
  src/personas/audiences/account-audiences.md
Labels: fixed-content

#2537 Release 22.8.2
  .github/Vocab/Docs/accept.txt
  .github/workflows/grammar-lint.yml
  ignore-links.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/databrain/index.md
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
  src/connections/destinations/catalog/funnelfox/index.md
  src/connections/destinations/catalog/ibm-ubx/index.md
  src/connections/destinations/catalog/kochava/index.md
  src/connections/destinations/catalog/lytics/index.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/msg91/index.md
  src/connections/destinations/catalog/nielsen-dcr/index.md
  src/connections/destinations/catalog/scuba-analytics/index.md
  src/connections/destinations/catalog/slack/index.md
  src/connections/destinations/catalog/uservoice/index.md
  src/connections/destinations/catalog/vitally/index.md
  src/connections/destinations/catalog/woopra/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/personas/audiences/account-audiences.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#2542 Fix regional-supporting connections table
  Gemfile.lock
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/sync-frequency-note.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
Labels: fixed-site
