Repository segmentio/segment-docs, pull requests merged in 2022-04, with the labels that each got.

#2687 table fix
  src/getting-started/04-full-install.md
Labels: fixed-content

#2690 Updated Retry Policy FAQ
  src/connections/functions/source-functions.md
Labels: fixed-content

#2696 A.js 2.0 minor doc updates [DOC-490]
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: fixed-content

#2697 Updated on request
  src/privacy/complying-with-the-gdpr.md
Labels: enhancement

#2693 Conn mode override and cleanup
  src/_data/catalog/overrides.yml
  src/connections/destinations/catalog/clevertap/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: fixed-content

#2702 Journeys Step Limits
  src/personas/product-limits.md
Labels: fixed-content

#2705 Zendesk source updates [DOC-452]
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
Labels: fixed-content

#2704 Add UA to GA4 section
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: enhancement

#2714 Add extra config for setting IDFA in RN classic
  src/connections/sources/catalog/libraries/mobile/react-native/classic.md
Labels: fixed-content

#2711 Pull actions data by ID, with slug fallback
  src/_includes/components/actions-fields.html
Labels: back-end

#2722 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/launchdarkly-events/index.md
Labels: back-end

#2725 Release 22.14.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/launchdarkly-events/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/classic.md
Labels: release

#2700 Lake Formation overview & setup [DOC-467]
  src/_data/sidenav/main.yml
  src/connections/storage/catalog/data-lakes/index.md
  src/connections/storage/data-lakes/lake-formation.md
Labels: new-integration

#2633 Add: Talon.One (Action) Destination
  src/connections/destinations/catalog/actions-talon-one/index.md
  src/connections/destinations/catalog/talonone/index.md
Labels: new-integration

#2726 Release 22.14.3
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/actions-talon-one/index.md
  src/connections/destinations/catalog/talonone/index.md
  src/connections/storage/catalog/data-lakes/index.md
  src/connections/storage/data-lakes/lake-formation.md
Labels: release

#2742 Release 22.15.1
  Gemfile.lock
  src/connections/destinations/catalog/talonone/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/connections/storage/catalog/data-lakes/index.md
Labels: release

#2739 catalog update
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/willow/index.md
Labels: back-end

#2748 Update RN docs to specify version
  src/_includes/content/react-dest.md
  src/connections/destinations/catalog/branch-metrics/index.md
  src/connections/destinations/catalog/braze/index.md
Labels: fixed-content

#2760 Fix typo in implementation-guide.md
  src/getting-started/implementation-guide.md
Labels: fixed-content

#2763 publish Talon.One action destination
  src/connections/destinations/catalog/actions-talon-one/index.md
  src/connections/destinations/catalog/talonone/index.md
Labels: fixed-content

#2728 Updated Google Ads docs after API upgrade [DOC-458]
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
Labels: enhancement

#2776 Update to install image, AJS 2.0 and help email
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/Nd5L0C6.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
Labels: fixed-content

#2779 Release 22.16.1
  .github/Vocab/Docs/accept.txt
  Gemfile.lock
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/content/react-dest.md
  src/connections/destinations/catalog/actions-adobe-target-cloud/index.md
  src/connections/destinations/catalog/actions-adobe-target-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-salesforce/images/image1.png
  src/connections/destinations/catalog/actions-salesforce/images/image2.png
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/actions-talon-one/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/branch-metrics/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/mailmodo/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/perimeterx/index.md
  src/connections/destinations/catalog/salesforce/index.md
  src/connections/destinations/catalog/talonone/index.md
  src/connections/destinations/catalog/vidora/index.md
  src/connections/destinations/catalog/willow/index.md
  src/connections/destinations/catalog/zendesk/index.md
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/Nd5L0C6.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/getting-started/implementation-guide.md
  src/privacy/user-deletion-and-suppression.md
  src/protocols/tracking-plan/create.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#2784 Add note about Lucky Orange supported versions
  src/connections/destinations/catalog/lucky-orange/index.md
Labels: enhancement, content-update

#2795 Engage Onboarding Page Updates
  src/engage/overview/images/apifields.png
  src/engage/overview/images/apikeys.png
  src/engage/overview/images/engageapifields.png
  src/engage/overview/images/engagewebhook.png
  src/engage/overview/images/requesturl.png
  src/engage/overview/images/subuser.png
  src/engage/overview/images/webhook.png
  src/engage/overview/onboarding.md
Labels: enhancement

#2796 Engage Subscription States Content
  src/engage/profiles/user-subscriptions/subscription-states.md
Labels: enhancement

#2798 Engage Campaigns Overview
  src/engage/campaigns/index.md
Labels: enhancement

#2807 codeowners update
  CODEOWNERS
Labels: back-end

#2809 Engage Onboarding Steps Fix
  src/engage/overview/onboarding.md
Labels: fixed-content

#2806 Added Personas edit task note [DOC-506]
  src/personas/audiences/index.md
Labels: content-update

#2814 Fix broken URl
  src/guides/usage-and-billing/billing.md
Labels: fixed-site

#2813 Override the Drip destination connection modes
  src/_data/catalog/overrides.yml
  src/connections/destinations/catalog/drip/index.md
Labels: content-update

#2817 Update csv-upload.md
  src/engage/profiles/csv-upload.md
Labels: content-update

#2815 Flag that cloud mode destinations are still supported
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#2820 small update to gtag docs
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: content-update
