Repository segmentio/segment-docs, pull requests merged in 2022-08, with the labels that each got.

#3305 update outdated kotlin template info
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: content-update

#3300 Remove action source table
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: fixed-content

#3307 Update Spec Docs Formatting
  src/connections/spec/common.md
  src/connections/spec/ecommerce/v2.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/mobile.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/semantic.md
  src/connections/spec/track.md
Labels: content-update

#3298 Fix Consent Manager URL
  src/_layouts/default.html
Labels: back-end

#3312 Add Journeys Compute Credit Information [DOC-554]
  src/personas/journeys/faq-best-practices.md
  src/personas/product-limits.md
Labels: content-update

#3315 Release 22.31.1
  CODEOWNERS
  src/_layouts/default.html
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/sources/catalog/cloud-apps/snowflake/index.md
  src/connections/sources/catalog/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/spec/common.md
  src/connections/spec/ecommerce/v2.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/mobile.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/semantic.md
  src/connections/spec/track.md
  src/engage/overview/onboarding.md
  src/personas/journeys/faq-best-practices.md
  src/personas/product-limits.md
  src/personas/using-personas-data.md
Labels: release

#3317 Update Python regional host URLs
  .github/styles/Vocab/Docs/accept.txt
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: content-update

#3319 Clarify retry policies
  src/connections/destinations/catalog/webhooks/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/source-functions.md
  src/partners/faqs.md
Labels: content-update

#3320 Add Analytics-Kotlin plugin examples link
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: content-update

#3325 Destination Filters Clarification [DOC-562]
  src/connections/destinations/destination-filters.md
Labels: content-update

#3329 Add information for migration of two Amplitude destination settings
  src/_data/actions/amplitude.yml
Labels: content-update

#3324 Add alias for Swift docs
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#3332 Release 22.31.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/actions/amplitude.yml
  src/connections/destinations/catalog/webhooks/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/destination-functions.md
  src/connections/functions/source-functions.md
  src/connections/sources/catalog/cloud-apps/braze/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/partners/faqs.md
Labels: release

#3334 Specified that A.js messages over 32kb result in a 500 error
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: content-update

#3253 Typewriter 2.0 [DOC-557]
  src/protocols/apis-and-extensions/typewriter-v7.md
  src/protocols/apis-and-extensions/typewriter.md
Labels: content-update

#3341 updating code sample per partners request
  src/connections/destinations/catalog/appsflyer/index.md
Labels: fixed-content

#3340 Add query parameter info to Computed Traits
  src/engage/profiles/computed-traits.md
  src/personas/computed-traits.md
Labels: content-update

#3346 Add info for device identifiers
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#3349 Update Braze Destination maintenance mode information
  src/connections/destinations/catalog/braze/index.md
Labels: content-update

#3302 Fixes from docs dashboard set 1
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/sources/catalog/cloud-apps/project/index.md
  src/connections/sources/catalog/cloud-apps/twilio-event-streams-beta/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/quickstart.md
  src/connections/spec/identify.md
  src/getting-started/02-simple-install.md
  src/getting-started/05-data-to-destinations.md
Labels: fixed-content

#3350 Catalog update for August 9
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/fullstory-cloud-mode-actions/index.md
Labels: back-end

#3344 Remove Tracking Plan Google Sheet Reference
  src/getting-started/03-planning-full-install.md
Labels: fixed-content

#3357 Add Journeys Level Analytics Content [DOC-563]
  src/personas/journeys/images/jla_tiles.png
  src/personas/journeys/journeys-analytics.md
Labels: new-feature

#3355 Update HubSpot docs for new privateAppToken auth
  src/connections/destinations/catalog/hubspot/index.md
Labels: content-update

#3359 Fix campaign fields supported for GUA
  src/connections/destinations/catalog/google-analytics/index.md
Labels: content-update

#3364 Release 22.32.2
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-pardot/images/image1.png
  src/connections/destinations/catalog/actions-pardot/images/image2.png
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/hubspot/index.md
Labels: release

#3345 add docs for new attentive mobile destination
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/attentive-mobile/index.md
Labels: new-integration

#3369 Add docs for new Jimo destination
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/jimo/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: new-integration

#3375 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/cordial-actions/index.md
  src/connections/destinations/catalog/jimo/index.md
  src/connections/sources/catalog/cloud-apps/bigquery/index.md
Labels: back-end

#3246 Add image that describes MTU and throughput [netlify-build]
  src/guides/usage-and-billing/images/billing-overview.png
  src/guides/usage-and-billing/mtus-and-throughput.md
Labels: content-update

#3379 Release 22.33.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/attentive-mobile/index.md
  src/connections/destinations/catalog/cordial-actions/index.md
  src/connections/destinations/catalog/jimo/index.md
  src/connections/sources/catalog/cloud-apps/bigquery/index.md
  src/connections/storage/catalog/google-cloud-storage/index.md
  src/guides/usage-and-billing/images/billing-overview.png
  src/guides/usage-and-billing/mtus-and-throughput.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#3389 Update index.md
  src/guides/index.md
Labels: fixed-content

#3385 Add `collection` lowercase specification [DOC-569]
  src/connections/functions/destination-functions.md
  src/connections/functions/environment.md
  src/connections/functions/index.md
  src/connections/functions/source-functions.md
  src/connections/functions/usage.md
Labels: content-update

#3380 Remove region not supported box
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/intercom/index.md
  src/connections/sources/catalog/cloud-apps/mailchimp/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/salesforce-marketing-cloud/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/sources/catalog/cloud-apps/twilio/index.md
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
Labels: content-update

#3381 Clarify login page interruption
  src/segment-app/iam/sso.md
Labels: content-update

#3394 Subscription Status Casing Specification [DOC-571]
  src/engage/profiles/csv-upload.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
Labels: content-update

#3397 Moengage (Actions) Deploy
  Gemfile.lock
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-moengage/images/EventTester.png
  src/connections/destinations/catalog/actions-moengage/images/segment_settings.png
  src/connections/destinations/catalog/actions-moengage/index.md
Labels: new-integration

#3400 Release 22.34.1
  Gemfile.lock
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-moengage/images/EventTester.png
  src/connections/destinations/catalog/actions-moengage/images/segment_settings.png
  src/connections/destinations/catalog/actions-moengage/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/environment.md
  src/connections/functions/index.md
  src/connections/functions/source-functions.md
  src/connections/functions/usage.md
  src/connections/sources/catalog/cloud-apps/desk-com/images/desk_com_image_1.png
  src/connections/sources/catalog/cloud-apps/desk-com/images/desk_com_image_2.png
  src/connections/sources/catalog/cloud-apps/desk-com/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/intercom/index.md
  src/connections/sources/catalog/cloud-apps/mailchimp/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/salesforce-marketing-cloud/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/sources/catalog/cloud-apps/twilio/index.md
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/engage/profiles/csv-upload.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
  src/guides/index.md
  src/personas/profile-api.md
  src/segment-app/iam/sso.md
  templates/sources.example.yml
Labels: release

#3383 Clarification to the Ajs 2.0 migration doc [DOC-570]
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/jimo/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: fixed-content

#3407 DC Floodlight clean up
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
Labels: content-update

#3406 MoEngage Actions Updated Deploy
  src/connections/destinations/catalog/actions-moengage/index.md
Labels: content-update

#3331 Update copy in Google Tag Manager article
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: content-update

#3403 Make cordial actions searchable in catalog
  src/connections/destinations/catalog/actions-cordial/index.md
Labels: back-end

#3402 Remove beta status for mixpanel actions
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: content-update

#3409 Add autogenerated tables and dossier back to Pardot (Actions)
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-pardot/index.md
Labels: content-update

#3411 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
Labels: back-end

#3413 Release 22.34.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-cordial/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/actions-moengage/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/jimo/index.md
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/react-faqs.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: release

#3421 Fix minor typo
  src/getting-started/04-full-install.md
Labels: fixed-content

#3415 More Pardot (Actions) updates for 8/30 deploy
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/actions-pardot/index.md
Labels: back-end

#3418 Add pagination and increase results
  src/_layouts/search.html
  src/_sass/components/_search.scss
  src/utils/search.md
Labels: back-end

#3417 Make moengage actions searchable in docs
  src/connections/destinations/catalog/actions-moengage/index.md
Labels: back-end

#3416 Update Snapchat Conversions API docs prior to GA
  src/connections/destinations/catalog/actions-snap-conversions/index.md
Labels: new-integration

#2730 Introducing the new Log Purchases Action
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: content-update

#3424 Updated A.js Classic end of service note
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#3430 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/moengage-actions/index.md
Labels: back-end

#3431 Release 22.35.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/_layouts/search.html
  src/_sass/components/_search.scss
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-moengage/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/moengage-actions/index.md
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/getting-started/04-full-install.md
  src/utils/search.md
Labels: release
