Repository segmentio/segment-docs, pull requests merged in 2022-06, with the labels that each got.

#2965 BigQuery docs review
  src/connections/storage/catalog/bigquery/index.md
Labels: content-update

#2971 Public API Subscription Confirmation
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
Labels: content-update

#2973 Engage Onboarding SMS Setup Update
  src/engage/overview/images/engageapifields.png
  src/engage/overview/onboarding.md
Labels: content-update

#2974 Release 22.22.2
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/engage/overview/images/apikeys.png
  src/engage/overview/images/engageapifields.png
  src/engage/overview/onboarding.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
Labels: release

#2982 Segment Help Page fixes
  src/help/index.md
Labels: fixed-content

#2986 Mixpanel People Update [DOC-523]
  src/connections/destinations/catalog/mixpanel/index.md
Labels: content-update

#2992 Remove Cloud-web from CleverTap's connection modes
  src/_data/catalog/overrides.yml
Labels: content-update

#2991 Added verbiage to describe the maximum number of mappings
  src/_includes/components/actions-fields.html
  src/connections/destinations/actions.md
Labels: content-update

#2985 [index.md] add docs for new partner destination
  src/connections/destinations/catalog/saasquatch-v2/index.md
Labels: new-integration

#2981 Account Management and Workspace Admin Updates [DOC-496]
  src/guides/intro-admin.md
  src/guides/usage-and-billing/account-management.md
Labels: fixed-content, content-update

#2996 Release 22.23.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/ab-tasty-client-side/index.md
  src/connections/destinations/catalog/lumen/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/saasquatch-v2/index.md
  src/connections/destinations/lumen/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/guides/intro-admin.md
  src/guides/usage-and-billing/account-management.md
  src/help/index.md
Labels: release

#3004 Resolving issue #2949: Create AWS Glue ETL job
  src/connections/destinations/catalog/amazon-personalize/index.md
Labels: content-update

#3003 Added the default trigger to Available Actions
  src/_includes/components/actions-fields.html
  src/connections/destinations/actions.md
Labels: content-update

#2999 Add information about GA4 custom event naming
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update

#2998 Updated Python package name
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/python/quickstart.md
Labels: content-update

#2997 Fixed broken links
  scripts/catalog_papi.js
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/byteplus/index.md
  src/connections/destinations/catalog/datarangers/index.md
  src/connections/destinations/catalog/simplereach/index.md
  src/connections/destinations/catalog/trafficguard/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: broken links, content-update

#3000 add new freshsales suite docs, and remove beta status from vitally
  .github/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/freshsales-suite---crm/index.md
  src/connections/destinations/catalog/freshsales-suite-crm/images/custom-traits.png
  src/connections/destinations/catalog/freshsales-suite-crm/images/freshsales-screenshot.png
  src/connections/destinations/catalog/freshsales-suite-crm/index.md
  src/connections/destinations/catalog/vitally/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: new-integration

#3014 Fixed misspelling in strat.yml
  src/_data/sidenav/strat.yml
Labels: fixed-site

#3015 Updated example page call to include category
  src/connections/destinations/catalog/google-analytics/index.md
Labels: content-update

#3016 Update CleverTap connection modes
  src/_data/catalog/overrides.yml
Labels: content-update

#3028 Clarify Expo compatibility
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#3034 Add vale rule to check for empty image alt tags
  .github/styles/segment/alt-tag.yml
  src/utils/vale-test.md
  vale-styles/segment/alt-tag.yml
Labels: back-end

#3036 fix kotlin outdated info
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
Labels: content-update

#3035 Analytics for Android Doc updates [DOC-529]
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/connections/sources/catalog/libraries/mobile/android/index.md
Labels: content-update

#3024 Braze Source Improvements [DOC-492]
  src/connections/sources/catalog/cloud-apps/braze/index.md
Labels: fixed-content, content-update

#3040 Release 22.24.1
  .github/Vocab/Docs/accept.txt
  .github/styles/segment/alt-tag.yml
  src/_data/catalog/overrides.yml
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/dev-center-note.md
  src/connections/destinations/catalog/actions-metronome/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/inflection/index.md
  src/connections/destinations/catalog/moengage/index.md
  src/connections/destinations/catalog/salesforce/index.md
  src/connections/destinations/catalog/split/index.md
  src/connections/sources/catalog/cloud-apps/braze/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/spec/group.md
  src/connections/storage/catalog/db2/index.md
  src/connections/storage/warehouses/faq.md
  src/partners/index.md
  src/partners/plugins.md
  src/partners/streams.md
  src/partners/subscriptions/build-functions.md
  src/partners/subscriptions/build-webhook.md
  src/partners/subscriptions/index.md
  src/utils/vale-test.md
  vale-styles/Vocab/Docs/accept.txt
  vale-styles/segment/alt-tag.yml
Labels: release

#3044 Remove Databrains destination
  src/connections/destinations/catalog/databrain/index.md
Labels: content-update

#3049 Update index.md
  src/connections/destinations/catalog/clevertap/index.md
Labels: content-update

#3047 Multiple Only Send Destination Filters [DOC-528]
  src/connections/destinations/destination-filters.md
Labels: content-update

#3052 Python source supports EU endpoints
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
Labels: content-update

#3061 CSV Uploader Update
  src/engage/profiles/csv-upload.md
Labels: content-update

#3045 Update `HTTP` to `HTTPS` in Source Functions
  src/connections/functions/source-functions.md
Labels: fixed-content

#3058 Updated content to reflect impact of Tracking Plans
  src/protocols/schema.md
Labels: content-update

#3063 Update FB Custom Audiences to appear in FB nav
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: back-end

#3064 update steps to match the UI
  src/connections/destinations/catalog/amplitude/index.md
Labels: content-update

#3060 Update Callback Timeout Info
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#3078 Personas Event Timestamp Limit
  src/personas/product-limits.md
Labels: content-update

#3074 Updating formatting/Vale edits in Data Lakes docs
  src/connections/storage/data-lakes/comparison.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/connections/storage/data-lakes/index.md
  src/connections/storage/data-lakes/sync-history.md
  src/connections/storage/data-lakes/sync-reports.md
Labels: content-update

#3083 Remove user agent for ios
  src/connections/spec/common.md
Labels: fixed-content

#3081 Clarify Engage API Subscription Status Update Process [DOC-532]
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
Labels: content-update

#3088 Release 22.25.1
  scripts/add_id.js
  src/connections/spec/common.md
  src/connections/storage/data-lakes/comparison.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/connections/storage/data-lakes/index.md
  src/connections/storage/data-lakes/sync-history.md
  src/connections/storage/data-lakes/sync-reports.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
  src/personas/computed-traits.md
  src/personas/product-limits.md
  src/protocols/faq.md
Labels: release

#3096 Clarify HTTP API Rate Limits [DOC-534]
  src/_includes/content/troubleshooting-intro.md
  src/_includes/menu/menu.html
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: fixed-content

#3095 Add Klaviyo Personas Guidance #2755
  src/connections/destinations/catalog/klaviyo/index.md
Labels: content-update

#3099 Profile API Updates #3073
  src/personas/profile-api.md
Labels: content-update

#3097 Add instructions for host param to server-side sources
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
Labels: content-update

#3104 private beta docs support
  scripts/private-destination.js
  src/_data/catalog/destinations_private.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-metronome/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
Labels: back-end

#3094 Catalog updates for June 23
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/criteo-audiences/index.md
  src/connections/sources/catalog/cloud-apps/workramp/index.md
Labels: back-end

#3105 metronome fixes
  src/connections/destinations/catalog/actions-metronome/index.md
Labels: content-update

#3107 Deploy Metronome (Actions)
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-metronome/index.md
  src/connections/destinations/catalog/metronome-actions/index.md
Labels: new-integration

#3110 add matcha destination documentation
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/matcha/index.md
Labels: new-integration

#3118 Add Randomized Split Content [DOC-537]
  src/personas/journeys/build-journey.md
Labels: content-update

#3076 updates to braze [Issue 2934]
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/braze-web-device-mode-actions/index.md
Labels: content-update

#3113 Added some clarity to the initial setup section
  src/connections/destinations/catalog/actions-metronome/index.md
Labels: content-update

#3112 Update list of events that Segment receives from the Iterable Source.
  .github/styles/Vocab/Docs/accept.txt
  src/connections/sources/catalog/cloud-apps/iterable/index.md
Labels: content-update

#3124 Engage Docs Update
  src/engage/audiences/index.md
  src/engage/profiles/computed-traits.md
  src/personas/computed-traits.md
Labels: fixed-content

#3121 Add link to desktop-csv-uploader
  src/guides/how-to-guides/import-historical-data.md
Labels: content-update

#3126 update SMC destination documentation
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/selligent-marketing-cloud/images/1.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/2.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/3.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/4.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/5.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/6.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/adminconfig.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/adminurl.jpg
  src/connections/destinations/catalog/selligent-marketing-cloud/images/apps.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/keysecret.jpeg
  src/connections/destinations/catalog/selligent-marketing-cloud/images/organization.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/secretplus.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/smc2.jpeg
  src/connections/destinations/catalog/selligent-marketing-cloud/images/wheelicon.jpg
  src/connections/destinations/catalog/selligent-marketing-cloud/index.md
Labels: content-update

#3119 add Orb destination documentation
  src/connections/destinations/catalog/orb/index.md
Labels: new-integration

#3130 Release 22.26.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-metronome/index.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/braze-web-device-mode-actions/index.md
  src/connections/destinations/catalog/matcha/index.md
  src/connections/destinations/catalog/orb/index.md
  src/connections/destinations/catalog/selligent-marketing-cloud/images/1.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/2.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/3.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/4.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/5.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/6.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/adminconfig.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/adminurl.jpg
  src/connections/destinations/catalog/selligent-marketing-cloud/images/apps.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/keysecret.jpeg
  src/connections/destinations/catalog/selligent-marketing-cloud/images/organization.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/secretplus.png
  src/connections/destinations/catalog/selligent-marketing-cloud/images/smc2.jpeg
  src/connections/destinations/catalog/selligent-marketing-cloud/images/wheelicon.jpg
  src/connections/destinations/catalog/selligent-marketing-cloud/index.md
  src/connections/sources/catalog/cloud-apps/iterable/index.md
  src/connections/sources/catalog/cloud-apps/jebbit/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/engage/audiences/index.md
  src/engage/journeys/build-journey.md
  src/engage/profiles/computed-traits.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
  src/guides/how-to-guides/import-historical-data.md
  src/personas/computed-traits.md
Labels: release

#3135 Small punctuation correction
  src/connections/destinations/catalog/intercom/index.md
Labels: content-update

#3133 Add Region Unsupported box
  src/connections/destinations/catalog/actions-metronome/index.md
  src/connections/destinations/catalog/metronome-actions/index.md
  src/connections/sources/catalog/cloud-apps/drip/index.md
  src/personas/journeys/build-journey.md
Labels: content-update

#3134 Add heading sentence case exceptions
  .github/styles/segment/headings.yml
  scripts/catalog_papi.js
  src/connections/destinations/catalog/drip/index.md
  src/undefined/index.md
Labels: back-end

#3140 Update User Subscription Content [DOC-539]
  src/engage/profiles/user-subscriptions/index.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
  src/engage/profiles/user-subscriptions/subscription-states.md
Labels: fixed-content, content-update

#3115 Destination function batching updates [DOC-527]
  src/_includes/content/functions/settings.md
  src/connections/functions/destination-functions.md
Labels: content-update

#3143 fix catalog script
  scripts/catalog_papi.js
Labels: back-end

#3144 Add required variable to Swift documentation
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#3147 Release 22.26.2
  .github/styles/segment/headings.yml
  src/_includes/content/functions/settings.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/drip/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/metronome-actions/index.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/cloud-apps/customer-io/index.md
  src/connections/sources/catalog/cloud-apps/drip/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/engage/profiles/user-subscriptions/index.md
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
  src/engage/profiles/user-subscriptions/subscription-states.md
  src/undefined/index.md
Labels: release

#3151 Update Engage CSV Content [DOC-541]
  src/engage/overview/index.md
  src/engage/profiles/csv-upload.md
Labels: content-update
