Repository segmentio/segment-docs, pull requests merged in 2022-11, with the labels that each got.

#3749 Release 22.44.1
  src/_data/actions/mixpanel.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/guides/ignore-bots.md
  src/protocols/tracking-plan/best-practices.md
  vale-styles/segment/subs.yml
Labels: release

#3752 Added a note about using in Zendesk.
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/zendesk/index.md
Labels: content-update

#3757 Release 22.44.2
  .github/styles/Vocab/Docs/accept.txt
  CONTRIBUTING.md
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-linkedin-audiences/images/image1.png
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
  src/connections/destinations/catalog/zendesk/index.md
  styleguide.md
Labels: release

#3771 Littledata docs update
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/segment.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
Labels: content-update

#3766 Unhide HubSpot Cloud Actions for 11/8 Public Beta
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: new-integration

#3765 Unhide LinkedIn Audiences doc on 11/8 Public Beta
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
Labels: new-integration

#3776 Update nodejs version and remove out-of-date images
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
Labels: content-update

#3775 Revert "update http api index file"
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: back-end

#3778 add logrocket documentation
  .github/styles/Vocab/Docs/accept.txt
  .yarn/cache/minimist-npm-1.2.7-51d33b1371-7346574a10.zip
  CONTRIBUTING.md
  package-lock.json
  src/_data/actions/mixpanel.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/components/actions-fields.html
  src/api/config-api/fql.md
  src/api/public-api.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-hubspot-web/index.md
  src/connections/destinations/catalog/actions-linkedin-audiences/images/image1.png
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
  src/connections/destinations/catalog/actions-logrocket/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/atatus/index.md
  src/connections/destinations/catalog/zendesk/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/segment.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/engage/faqs.md
  src/profiles/faqs.md
  src/protocols/tracking-plan/best-practices.md
  src/segment-app/iam/roles.md
  styleguide.md
  yarn.lock
Labels: new-integration

#3785 Revert "add logrocket documentation (#3778)"
  .github/styles/Vocab/Docs/accept.txt
  .yarn/cache/minimist-npm-1.2.7-51d33b1371-7346574a10.zip
  CONTRIBUTING.md
  package-lock.json
  src/_data/actions/mixpanel.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/sidenav/main.yml
  src/_includes/components/actions-fields.html
  src/api/public-api/fql.md
  src/api/public-api/index.md
  src/connections/destinations/catalog/actions-hubspot-web/index.md
  src/connections/destinations/catalog/actions-linkedin-audiences/images/image1.png
  src/connections/destinations/catalog/actions-logrocket/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/zendesk/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/segment.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/engage/faqs.md
  src/profiles/faqs.md
  src/protocols/tracking-plan/best-practices.md
  src/segment-app/iam/roles.md
  styleguide.md
  yarn.lock
Labels: back-end

#3790 Clarify that Object and Event sources are Cloud sources
  .yarn/cache/minimist-npm-1.2.5-ced0e1f617-86706ce5b3.zip
  src/_includes/content/cloud-app-note.md
  src/connections/sources/index.md
Labels: content-update

#3793 Atatus destination documentation
  src/connections/destinations/catalog/atatus/index.md
  src/connections/sources/catalog/cloud-apps/braze/index.md
Labels: new-integration

#3796 Airship Source supports EU region delivery
  src/connections/sources/catalog/cloud-apps/airship/index.md
Labels: content-update

#3788 Destination Slug Overrides
  src/_data/catalog/slugs.yml
Labels: back-end

#3798 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3800 Release 22.45.2
  .yarn/cache/minimist-npm-1.2.5-ced0e1f617-86706ce5b3.zip
  package-lock.json
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/cloud-app-note.md
  src/connections/destinations/catalog/atatus/index.md
  src/connections/sources/catalog/cloud-apps/airship/index.md
  src/connections/sources/catalog/cloud-apps/braze/index.md
  src/connections/sources/index.md
  src/connections/storage/data-lakes/index.md
  yarn.lock
Labels: release

#3803 Add docs for new Aampe destination
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/aampe/index.md
Labels: new-integration

#3816 Add note that Tracking Plans do not transfer to a new workspace
  src/guides/usage-and-billing/account-management.md
Labels: content-update

#3817 Update Engage Onboarding IP Warmup Instructions
  src/engage/onboarding.md
Labels: content-update

#3821 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/akita-user-tracking/index.md
  src/connections/destinations/catalog/logrocket/index.md
  src/connections/sources/catalog/cloud-apps/testing-party-yay/index.md
Labels: back-end

#3823 Release 22.46.1
  .github/styles/Vocab/Docs/accept.txt
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/akita-user-tracking/index.md
  src/connections/destinations/catalog/logrocket/index.md
  src/connections/sources/catalog/cloud-apps/testing-party-yay/index.md
  src/engage/onboarding.md
  src/guides/usage-and-billing/account-management.md
Labels: release

#3828 Update index.md file for the HTTP API section
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#3819 Add docs for new akita user tracking destination
  src/connections/destinations/catalog/akita-user-tracking/index.md
Labels: new-integration

#3825 Update source schema export page
  src/connections/destination-data-control.md
  src/connections/images/export-source-schema-including-props.png
Labels: content-update

#3830 Add docs for new 1Flow Analytics destination
  src/connections/destinations/catalog/1flow-analytics/index.md
Labels: new-integration

#3839 correct role definition
  src/segment-app/iam/roles.md
Labels: content-update

#3836 Salesforce Selective Sync is available to all users
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: content-update

#3841 Airship and Moengage (Actions) support EU endpoints
  src/_data/regional-support.yml
Labels: content-update

#3842 catalog update for 11/17
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/modern-pricing/index.md
Labels: back-end

#3844 Release 22.46.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/connections/destinations/catalog/1flow-analytics/index.md
  src/connections/destinations/catalog/actions-clevertap/index.md
  src/connections/destinations/catalog/actions-sabil/index.md
  src/connections/destinations/catalog/akita-user-tracking/index.md
  src/connections/destinations/catalog/modern-pricing/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/segment-app/iam/roles.md
Labels: release

#3847 Update index.md
  src/connections/sources/catalog/libraries/server/go/index.md
Labels: content-update

#3858 Update CSV Uploader
  src/engage/profiles/csv-upload.md
Labels: content-update

#3865 Release 22.47.1
  src/connections/destination-data-control.md
  src/connections/images/export-source-schema-including-props.png
  src/connections/sources/catalog/libraries/server/go/index.md
  src/engage/profiles/csv-upload.md
Labels: release

#3859 Wisepops Destination
  .github/styles/Vocab/Docs/accept.txt
  scripts/private-destination.js
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-custom-event.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-id.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-setup-code.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-user-first-name.png
  src/connections/destinations/catalog/actions-wisepops/index.md
Labels: new-integration

#3870 Add docs for new Insider source
  src/connections/sources/catalog/cloud-apps/insider/index.md
Labels: new-integration

#3875 Update link for helpscout destination
  src/connections/destinations/catalog/help-scout/index.md
Labels: back-end

#3878 Update android-faqs.md
  src/connections/sources/catalog/libraries/mobile/android/android-faqs.md
Labels: content-update

#3872 Functions batch errors edit
  src/connections/functions/destination-functions.md
Labels: content-update

#3879 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/akita-customer-success/index.md
  src/connections/sources/catalog/cloud-apps/commandbar/index.md
Labels: back-end

#3874 Advanced Transformations beta updates
  src/protocols/transform/index.md
Labels: content-update, new-feature

#3892 Minor fixes on Wisepops destination documentation
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-id.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-plan.png
  src/connections/destinations/catalog/actions-wisepops/index.md
Labels: content-update

#3890 Added image to better illustrate the configuration of a Person Account
  src/connections/destinations/catalog/actions-salesforce/images/custom-object_person-account.png
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: content-update

#3889 Add required event field in example Track payload
  src/connections/spec/common.md
Labels: content-update

#3888 Remove link to private repository
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#3887 Remove images from doc, vale edits
  src/connections/storage/catalog/snowflake/index.md
Labels: back-end

#3886 Add traits section for insider source
  src/connections/sources/catalog/cloud-apps/insider/index.md
Labels: content-update

#3884 Remove extra word
  src/connections/data-export-options.md
Labels: content-update

#3882 Remove image from LinkedIn Audience docs
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
Labels: fixed-content, content-update

#3891 Audiences clarification
  src/engage/audiences/index.md
Labels: content-update
