Repository segmentio/segment-docs, pull requests merged in 2022-07, with the labels that each got.

#3152 Update Application Uninstall Content
  src/connections/spec/mobile.md
Labels: content-update

#3158 Add Engage Analytics Content [DOC-543]
  src/_data/sidenav/engage.yml
  src/engage/analytics/index.md
  src/engage/analytics/message-events.md
Labels: content-update

#3157 Recommend alternatives to Google Ads (Classic)
  src/connections/destinations/catalog/google-ads-classic/index.md
Labels: content-update

#3168 Release 22.27.1
  .github/styles/Vocab/Docs/accept.txt
  .github/styles/segment/headings.yml
  src/_includes/content/destination-dossier.html
  src/_includes/content/destination-footer.md
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/algolia-insights/index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/hotjar/index.md
  src/connections/destinations/catalog/variance/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/ecommerce-tracking-plan.md
  src/connections/spec/mobile.md
  src/engage/overview/index.md
  src/engage/profiles/csv-upload.md
  src/getting-started/03-planning-full-install.md
  src/getting-started/implementation-guide.md
  src/protocols/faq.md
  src/protocols/tracking-plan/best-practices.md
Labels: release

#3170 Mixpanel (Actions) to public Beta
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/mixpanel-actions/index.md
  src/connections/destinations/catalog/spideo/index.md
  src/connections/sources/catalog/cloud-apps/ibm-watson-assistant/index.md
Labels: new-integration

#3173 add ninetailed destination docs
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/ninetailed/index.md
Labels: new-integration

#3179 DOC-549 Add clarity around device modes to Mixpanel destination
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/mixpanel/index.md
  src/guides/regional-segment.md
Labels: content-update

#3178 Link to Integration Error Codes
  src/connections/event-delivery.md
  src/connections/functions/destination-functions.md
  src/connections/integration_error_codes.md
  src/getting-started/06-testing-debugging.md
Labels: content-update

#3181 Provide alternatives for attribution tracking in GA4
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update

#3185 Publish Criteo Audiences destination docs
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-criteo-audiences/index.md
  src/connections/destinations/catalog/criteo-audiences/index.md
Labels: new-integration

#3186 Release 22.27.3
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-criteo-audiences/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/criteo-audiences/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/ninetailed/index.md
  src/connections/destinations/catalog/spideo/index.md
  src/connections/destinations/catalog/windsor/index.md
  src/connections/event-delivery.md
  src/connections/functions/destination-functions.md
  src/connections/functions/source-functions.md
  src/connections/integration_error_codes.md
  src/getting-started/06-testing-debugging.md
  src/guides/regional-segment.md
Labels: release

#3189 Updated description of the way Segment calculates timestamps
  src/connections/spec/common.md
Labels: content-update

#3190 Updated the way that the integrations object handles All: false
  src/connections/destination-data-control.md
  src/guides/filtering-data.md
Labels: content-update

#3199 Document support for Hubspot destination with EU endpoints
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/connections/destinations/catalog/appcues-mobile/index.md
  src/connections/destinations/catalog/rokt-integration/index.md
Labels: content-update

#3202 Add Personas Connections Clarification #2948
  src/personas/audiences/index.md
Labels: fixed-content

#3205 Disabling Data Collection Code Update
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: content-update

#3204 FAQ section for upgrading to A.js 2.0 [DOC-551]
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#3082 Device mode improvements for RN 2.0
  src/connections/destinations/catalog/firebase/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#3187 Heap (Actions) destination docs
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-heap/index.md
Labels: new-integration

#3210 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3203 Add Source Function Alphabetization FAQ [DOC-536]
  src/connections/functions/source-functions.md
Labels: content-update

#3211 Release 22.28.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/connections/destination-data-control.md
  src/connections/destinations/catalog/actions-heap/index.md
  src/connections/destinations/catalog/appcues-mobile/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/rokt-integration/index.md
  src/connections/functions/source-functions.md
  src/connections/sources/catalog/cloud-apps/workramp/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/connections/spec/common.md
  src/connections/storage/catalog/google-cloud-storage/index.md
  src/guides/duplicate-data.md
  src/guides/filtering-data.md
  src/partners/checklist.md
  src/personas/audiences/index.md
Labels: release

#3213 Fix Personas Audiences Typo
  src/personas/audiences/index.md
Labels: fixed-content

#3198 rokt destination docs
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/rokt-integration/index.md
Labels: new-integration

#3218 Personas Edits
  src/personas/sql-traits.md
  src/personas/using-personas-data.md
  src/personas/warehouses.md
Labels: content-update

#3220 name updated in partner portal, reflecting change in docs
  src/connections/destinations/catalog/rokt-integration/index.md
Labels: content-update

#3222 7 14 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/rokt/index.md
Labels: back-end

#3223 Release 22.28.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/rokt-integration/index.md
  src/connections/destinations/catalog/rokt/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/migration.md
  src/personas/audiences/index.md
  src/personas/sql-traits.md
  src/personas/using-personas-data.md
  src/personas/warehouses.md
Labels: release

#3229 Release 22.28.3
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/ibm-watson-assistant/index.md
  src/connections/storage/catalog/data-lakes/index.md
  src/connections/storage/data-lakes/comparison.md
  src/connections/storage/data-lakes/images/Azure_DL_setup.png
  src/connections/storage/data-lakes/images/data_lakes_overview_graphic.png
  src/connections/storage/data-lakes/index.md
  src/connections/storage/data-lakes/lake-formation.md
  src/connections/storage/data-lakes/sync-history.md
  src/connections/storage/data-lakes/sync-reports.md
Labels: release

#3231 Small update to Snap CAPI docs
  src/connections/destinations/catalog/actions-snap-conversions/index.md
Labels: content-update

#3217 Disclaimer - track calls only with Marketing Hub
  src/connections/destinations/catalog/hubspot/index.md
Labels: content-update

#3227 Add note about MoEngage anonymous id support
  src/connections/destinations/catalog/moengage/index.md
Labels: content-update

#3241 add docs for new Jebbit source
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/jebbit/index.md
Labels: new-integration

#3252 Personas Identity Resolution Edits
  src/personas/identity-resolution/ecommerce-example.md
  src/personas/identity-resolution/externalids.md
  src/personas/identity-resolution/identity-resolution-onboarding.md
  src/personas/identity-resolution/identity-resolution-settings.md
  src/personas/identity-resolution/index.md
  src/personas/identity-resolution/personas-space-set-up.md
  src/personas/identity-resolution/use-cases.md
Labels: content-update

#3254 Add Engage Computed Traits Image Files
  src/engage/profiles/images/1525835194991.png
  src/engage/profiles/images/1525835663131.png
  src/engage/profiles/images/1525836239527.png
  src/engage/profiles/images/1525836568474.png
  src/engage/profiles/images/1525836818177.png
  src/engage/profiles/images/1525837083070.png
  src/engage/profiles/images/1525837374378.png
  src/engage/profiles/images/1525837601768.png
  src/engage/profiles/images/1542073415630.png
  src/engage/profiles/images/1542073887657.png
  src/engage/profiles/images/1542074153487.png
  src/engage/profiles/images/large_trait_csv.png
  src/engage/profiles/images/trait_overview.png
Labels: content-update

#3257 Catalog update for July 21
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3259 Release 22.29.2
  .github/styles/Vocab/Docs/accept.txt
  .github/styles/segment/headings.yml
  package-lock.json
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/pendo/index.md
  src/connections/sources/catalog/cloud-apps/bluedot/index.md
  src/connections/sources/catalog/cloud-apps/jebbit/index.md
  src/engage/profiles/images/1525835194991.png
  src/engage/profiles/images/1525835663131.png
  src/engage/profiles/images/1525836239527.png
  src/engage/profiles/images/1525836568474.png
  src/engage/profiles/images/1525836818177.png
  src/engage/profiles/images/1525837083070.png
  src/engage/profiles/images/1525837374378.png
  src/engage/profiles/images/1525837601768.png
  src/engage/profiles/images/1542073415630.png
  src/engage/profiles/images/1542073887657.png
  src/engage/profiles/images/1542074153487.png
  src/engage/profiles/images/large_trait_csv.png
  src/engage/profiles/images/trait_overview.png
  src/personas/identity-resolution/ecommerce-example.md
  src/personas/identity-resolution/externalids.md
  src/personas/identity-resolution/identity-resolution-onboarding.md
  src/personas/identity-resolution/identity-resolution-settings.md
  src/personas/identity-resolution/index.md
  src/personas/identity-resolution/personas-space-set-up.md
  src/personas/identity-resolution/use-cases.md
Labels: release

#3264 Add docs for new Gladly source
  src/connections/sources/catalog/cloud-apps/gladly/index.md
Labels: new-integration

#3269 fix(typo): minor misspelling
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: content-update

#3278 Update index.md
  src/connections/destinations/catalog/braze/index.md
Labels: content-update

#3271 Update Video Spec Formatting [DOC-558]
  src/connections/spec/video.md
Labels: content-update

#3280 Catalog update
  Gemfile.lock
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3283 Release 22.30.1
  Gemfile.lock
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/overrides-list.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-fullstory/index.md
  src/connections/destinations/catalog/factorsai/index.md
  src/connections/sources/catalog/cloud-apps/gladly/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/migration.md
  src/connections/spec/video.md
Labels: release

#3285 Fixed broken table
  src/connections/sources/catalog/cloud-apps/gladly/index.md
Labels: fixed-site

#3276 Update FB Offline Conversions with API upgrade note
  src/connections/destinations/catalog/facebook-offline-conversions/index.md
Labels: content-update

#3275 Update FB Conversions API Actions with API upgrade
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: content-update

#3274 Update FB Conversions API with API upgrade note
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
Labels: content-update

#3290 [Content]: Update tab label on function example
  src/getting-started/04-full-install.md
Labels: fixed-content

#3111 Update Node docs configuration to include new `errorhandler` property
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: content-update

#3295 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end
