Repository segmentio/segment-docs, pull requests merged in 2022-05, with the labels that each got.

#2729 Criteo forks/develop
  .github/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/actions-criteo-audiences/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: new-integration

#2832 Update proxy process
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: fixed-content

#2829 Fixed some broken URLs
  src/_data/sidenav/engage.yml
  src/connections/destinations/catalog/ambassador/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/nudgespot/index.md
Labels: broken links

#2805 Bundle Obfuscation [DOC-508]
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: new-feature

#2843 Added warning note to not create Custom Events for standard events that already exist in GA4 Actions Destinations [DOC-502]
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update

#2822 Updating the Postgres RDS docs [DOC-504]
  src/connections/storage/catalog/postgres/index.md
Labels: content-update

#2842 DOC-324 Add Cloud Source type to metadata
  .github/Vocab/Docs/accept.txt
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/cloud-app-note.md
  src/_includes/content/cloud-source-type-list.md
  src/connections/sources/index.md
  src/connections/sources/sources-compare.md
  vale-styles/Vocab/Docs/accept.txt
Labels: content-update

#2846 Release 22.18.2
  .github/Vocab/Docs/accept.txt
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/cloud-app-note.md
  src/_includes/content/cloud-source-type-list.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/adobe-analytics/index.md
  src/connections/destinations/catalog/close/index.md
  src/connections/sources/index.md
  src/connections/sources/sources-compare.md
  src/connections/storage/catalog/postgres/index.md
  src/getting-started/implementation-guide.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#2860 Specific instructions for MFA recovery [SECFEAT-819]
  src/segment-app/iam/mfa.md
Labels: content-update

#2863 Revert "Merge pull request #2853 from segmentio/document-functions-aws-sdk"
  src/_data/sidenav/main.yml
  src/_includes/content/functions/runtime.md
  src/connections/functions/aws-apis.md
Labels: content-update

#2864 Subscription States Formatting Updates [DOC-517]
  src/engage/profiles/csv-upload.md
Labels: content-update

#2857 Engage Setting User Subscription Updates
  src/engage/profiles/user-subscriptions/set-user-subscriptions.md
Labels: content

#2858 Personas Audience Key Caution [DOC-491]
  src/personas/audiences/index.md
  src/personas/faqs.md
Labels: fixed-content

#2867 Added Action Source table
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: content-update

#2866 Engage IA Updates [DOC-515]
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/sms-campaigns.md
Labels: content-update

#2861 [index.md] destination docs for new Flagshipio destination
  src/connections/destinations/catalog/flagshipio/index.md
Labels: new-integration

#2848 added heading about creating separate dev and prod sources
  src/getting-started/02-simple-install.md
Labels: content-update

#2875 Engage Onboarding SendGrid Updates [DOC-516]
  src/engage/overview/onboarding.md
Labels: fixed-content

#2877 Release 22.19.1
  Makefile
  scripts/catalog_capi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/content/functions/runtime.md
  src/config-api/fql.md
  src/connections/destinations/catalog/actions-close/index.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/Untitled-2.js
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-launchdarkly/index.md
  src/connections/destinations/catalog/actions-talon-one/index.md
  src/connections/destinations/catalog/close/index.md
  src/connections/destinations/catalog/flagshipio/index.md
  src/connections/destinations/catalog/talon-one-actions/index.md
  src/connections/functions/aws-apis.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/overview/onboarding.md
  src/engage/profiles/csv-upload.md
  src/getting-started/02-simple-install.md
  src/guides/filtering-data.md
  src/personas/audiences/index.md
  src/personas/faqs.md
  src/segment-app/iam/mfa.md
Labels: release

#2890 Fixed typo
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: fixed-content

#2887 Updated Tracking Plan link
  src/connections/spec/ecommerce-tracking-plan.md
  src/protocols/tracking-plan/best-practices.md
Labels: content-update

#2886 Update Schema Controls Page [DOC-518]
  src/protocols/schema.md
Labels: fixed-content

#2891 Update Analytics.js trackForm Table #2856
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: fixed-content

#2893 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/flagship-io/index.md
  src/connections/destinations/catalog/koala/index.md
Labels: back-end

#2895 Release 22.19.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/spec-identities.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-launchdarkly/index.md
  src/connections/destinations/catalog/flagship-io/index.md
  src/connections/destinations/catalog/koala/index.md
  src/connections/functions/aws-apis.md
  src/connections/sources/catalog/cloud-apps/snowflake/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/ecommerce-tracking-plan.md
  src/connections/storage/catalog/postgres/index.md
  src/protocols/schema.md
  src/protocols/tracking-plan/best-practices.md
Labels: release

#2898 Engage IA Navigation Update
  src/engage/overview/onboarding.md
Labels: content-update

#2889 Fixed sentence and format errors
  src/partners/streams.md
Labels: content-update

#2911 Fix Firebase link
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#2908 broken link fixes
  ignore-links.txt
  src/connections/destinations/catalog/flagshipio/index.md
  src/personas/using-personas-data.md
Labels: broken links

#2910 Schema Integration Filters Fix [DOC-518]
  src/protocols/schema.md
Labels: fixed-content

#2905 [index.md] blitzllama destination docs
  .github/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/blitzllama/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: new-integration

#2917 Update documentation about testing
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: content-update

#2925 Update GA4 Docs Session ID and Session Number
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update

#2930 Add actions info to LaunchDarkly (Actions)
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-launchdarkly/index.md
Labels: back-end

#2938 fixes typo on ID res page
  src/personas/identity-resolution/index.md
Labels: fixed-content

#2945 Release 22.21.1
  src/connections/destinations/catalog/mouseflow/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/connections/storage/catalog/azuresqldw/index.md
  src/personas/identity-resolution/index.md
Labels: release

#2947 Restore category headings to destinations catalog
  Gemfile.lock
  src/connections/destinations/catalog/index.md
Labels: content-update

#2954 Update Twilio Credentials Onboarding Section
  src/engage/overview/images/twilioaccountsid.png
  src/engage/overview/onboarding.md
Labels: fixed-content

#2957 Release 22.21.2
  .github/Vocab/Docs/accept.txt
  Gemfile.lock
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/index.md
  src/connections/destinations/catalog/skalin/index.md
  src/engage/overview/images/twilioaccountsid.png
  src/engage/overview/onboarding.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#2919 CSV Uploader Updates [DOC-517]
  src/engage/profiles/csv-upload.md
Labels: content-update

#2964 Release 22.22.1
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/engage/profiles/csv-upload.md
Labels: release
