Repository segmentio/segment-docs, pull requests merged in 2022-10, with the labels that each got.

#3548 DOC 579 TP library updates
  src/protocols/tracking-plan/create.md
  src/protocols/tracking-plan/libraries.md
Labels: new-feature

#3588 Hide qualtrics until integration is launched next year
  src/connections/destinations/catalog/actions-qualtrics/index.md
Labels: back-end

#3596 Add missing comma to code example
  src/connections/sources/catalog/libraries/mobile/amp/index.md
Labels: content-update

#3586 Update footer to inlcude Engage link
  src/_data/nav.yml
Labels: back-end

#3592 Add specification to the Onboarding Steps
  src/_data/sidenav/main.yml
  src/engage/onboarding.md
  src/engage/quickstart.md
  src/profiles/index.md
  src/profiles/quickstart.md
Labels: content-update

#3601 Update Journeys Analytics Screenshot
  src/engage/journeys/images/journeys_analytics_tiles.png
Labels: content-update

#3589 Update index.md new sprig content
  src/connections/destinations/catalog/sprig-cloud/index.md
Labels: content-update

#3590 Update index.md new sprig content
  src/connections/destinations/catalog/sprig-web/index.md
Labels: content-update

#3606 Release 22.40.1
  src/_data/nav.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/actions-moengage/index.md
  src/connections/destinations/catalog/actions-qualtrics/index.md
  src/connections/destinations/catalog/moengage/index.md
  src/connections/destinations/catalog/sprig-cloud/index.md
  src/connections/destinations/catalog/sprig-web/index.md
  src/connections/sources/catalog/libraries/mobile/amp/index.md
  src/engage/index.md
  src/engage/journeys/images/journeys_analytics_tiles.png
  src/engage/onboarding.md
  src/engage/quickstart.md
  src/profiles/index.md
  src/profiles/quickstart.md
  src/protocols/tracking-plan/create.md
  src/protocols/tracking-plan/libraries.md
Labels: release

#3611 Hide new actions for Google Enhanced Conversions
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: back-end

#3609 Update Stream Merge Highlight [DOC-593]
  src/profiles/identity-resolution/index.md
Labels: content-update

#3610 Update Castle destination docs
  src/connections/destinations/catalog/castle/index.md
Labels: content-update

#3616 Release 22.40.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/castle/index.md
  src/engage/onboarding.md
  src/profiles/identity-resolution/index.md
Labels: release

#3622 Fixed link to correct page (led to a 404 page before)
  src/api/config-api/index.md
Labels: fixed-content

#3629 Add Profiles Space Setup page to nav
  src/_data/sidenav/main.yml
Labels: back-end

#3619 Remove link to closed repository
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#3620 CSV Upload nav updates
  src/engage/profiles/csv-upload.md
Labels: content-update

#3635 Update Journey Analytics Datepicker Descriptions
  src/engage/journeys/journeys-analytics.md
Labels: content-update

#3634 Add Engage Source Content [DOC-597]
  src/engage/user-subscriptions/engage-sources.md
Labels: new-feature

#3637 Release 22.41.1
  scripts/checklinks-internal.js
  src/_data/catalog/destinations_private.yml
  src/_data/sidenav/main.yml
  src/api/config-api/fql.md
  src/api/config-api/index.md
  src/connections/destinations/catalog/actions-google-sheets/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/engage/journeys/journeys-analytics.md
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/engage-sources.md
  src/segment-app/iam/labels.md
Labels: release

#3643 Update Lambda command to resolve error
  .github/styles/Vocab/Docs/accept.txt
  .github/styles/segment/headings.yml
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
Labels: content-update

#3642 Add additional version to Braze Cloud (Actions)
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
Labels: back-end

#3645 Functions updates
  src/_includes/content/functions/perms.md
  src/_includes/content/functions/runtime.md
  src/connections/destinations/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/environment.md
  src/connections/functions/index.md
  src/connections/functions/source-functions.md
Labels: content-update

#3649 Template Editor upload limit
  src/engage/content/email/editor.md
Labels: content-update

#3647 Specify display name and not DB name
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/eloqua/index.md
Labels: content-update

#3644 Remove 'SLA' from title and nav to remove confusion
  src/_data/sidenav/main.yml
  src/connections/rate-limits.md
Labels: back-end

#3651 Update the EU endpoint for server-side sources
  src/guides/regional-segment.md
Labels: content-update

#3652 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
Labels: back-end

#3656 Release 22.41.2
  .github/styles/Vocab/Docs/accept.txt
  .github/styles/segment/headings.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/_data/sidenav/main.yml
  src/_includes/content/functions/perms.md
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/eloqua/index.md
  src/connections/destinations/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/environment.md
  src/connections/functions/index.md
  src/connections/functions/source-functions.md
  src/connections/rate-limits.md
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
  src/engage/content/email/editor.md
  src/guides/regional-segment.md
Labels: release

#3658 Clarify Swift Destinations
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: content-update

#3668 Add Journeys Ad Destination Step [DOC-601]
  src/engage/journeys/step-types.md
Labels: new-feature

#3670 Add template cloning feature
  src/engage/content/email/template.md
  src/engage/content/sms/template.md
Labels: new-feature

#3598 Mobile Device Mode Destination Filters Beta (Swift, Kotlin, React Native 2.0) [DOC-589]
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/guides/filtering-data.md
Labels: new-feature

#3659 Mention integrations object in Warehouse FAQ
  src/connections/storage/warehouses/faq.md
Labels: content-update

#3657 Update Intercom destination docs
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/intercom/index.md
Labels: content-update

#3673 Update the catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#3675 Cloud Object sources are available in the EU
  src/guides/regional-segment.md
Labels: content-update

#3676 Release 22.42.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-fullstory/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/schema.md
  src/guides/regional-segment.md
Labels: release

#3682 Add a note that explains why Segment does not map Identify to LaunchDarkly (Actions)
  src/connections/destinations/catalog/actions-launchdarkly/index.md
Labels: content-update

#3681 Add information about events Mutiny sends to Segment
  src/connections/destinations/catalog/mutiny/index.md
Labels: content-update

#3680 Update Analytics import statement to avoid error
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: content-update

#3683 Fix integrations object typo
  src/connections/spec/common.md
Labels: content-update

#3671 Mailchimp Destination updates
  src/connections/destinations/catalog/mailchimp/images/identify-call.png
  src/connections/destinations/catalog/mailchimp/index.md
Labels: content-update

#3688 Update name for Regal Voice
  src/connections/destinations/catalog/regal-voice/index.md
Labels: content-update

#3689 Make regional config URLs a snippet
  src/_includes/content/regional-config.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
Labels: back-end

#3690 Catalog update 10-20
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/regal-io/index.md
Labels: back-end

#3691 Release 22.42.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/regional-config.md
  src/connections/destinations/catalog/actions-launchdarkly/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/mailchimp/images/identify-call.png
  src/connections/destinations/catalog/mailchimp/index.md
  src/connections/destinations/catalog/mutiny/index.md
  src/connections/destinations/catalog/regal-io/index.md
  src/connections/destinations/catalog/regal-voice/index.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
  src/connections/spec/common.md
  src/guides/regional-segment.md
Labels: release

#3694 Updated docs for azure setup
  src/connections/storage/catalog/data-lakes/index.md
Labels: content-update

#3699 Update HubSpot warning box
  src/connections/destinations/catalog/hubspot/index.md
Labels: content-update

#3700 Update Functions dependencies
  Gemfile.lock
  src/_includes/content/functions/runtime.md
Labels: dependencies

#3704 Add Engage Event Tester Section [DOC-606]
  src/engage/journeys/send-data.md
Labels: new-feature

#3706 Update Engage Sources
  src/engage/user-subscriptions/engage-sources.md
Labels: content-update

#3722 update mixpanel destination name
  src/connections/destinations/catalog/mixpanel/index.md
Labels: content-update

#3716 Update Woopra Connection modes
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destinations.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/woopra/index.md
Labels: content-update

#3724 Unhide Pardot Actions docs
  src/connections/destinations/catalog/actions-pardot/index.md
Labels: back-end

#3728 Updated Actions template for actions that don't have a default trigger
  src/_includes/components/actions-fields.html
Labels: back-end

#3736 update http api index file
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#3735 Vale Substitution List Updates
  vale-styles/segment/subs.yml
Labels: back-end

#3742 Update demo data in Tracking Plan best practices
  src/protocols/tracking-plan/best-practices.md
Labels: content-update

#3738 Fixed Destination Function code sample
  src/connections/functions/destination-functions.md
Labels: content
