Repository segmentio/segment-docs, pull requests merged in 2023-05, with the labels that each got.

#4664 update typewriter docs
  src/protocols/apis-and-extensions/typewriter.md
Labels: content-update

#4648 Tracking UTMs on SPAs
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
Labels: content-update, KCS

#4670 csharp redirect
  src/connections/sources/catalog/libraries/server/csharp/index.md
Labels: back-end

#4668 Remove Versioning beta note
  src/connections/functions/environment.md
Labels: content-update

#4631 Remove beta note on TikTok Audiences docs
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: content-update

#4667 update kotlin desugaring info
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
Labels: content-update

#4672 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/libraries/mobile/csharp/index.md
Labels: back-end

#4673 Release 23.18.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/blackbaud-raisers-edge-nxt/index.md
  src/connections/destinations/catalog/inkit/index.md
  src/connections/sources/catalog/libraries/mobile/csharp/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/go/quickstart.md
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
  src/protocols/apis-and-extensions/typewriter.md
Labels: release

#4652 Add info about $value mapping for Klaviyo's Track events
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#4680 Clarify SendGrid Subuser Onboarding Step #4649
  src/engage/onboarding.md
Labels: content-update

#4681 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#4682 Release 23.18.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/klaviyo/index.md
  src/engage/onboarding.md
Labels: release

#4686 Fixed Typo
  src/connections/destinations/catalog/intercom/index.md
Labels: KCS

#4685 Added information that the Engage generated source should not be disabled
  src/unify/debugger.md
Labels: KCS

#4689 update name per partner request
  src/connections/destinations/catalog/userpilot/index.md
Labels: content-update

#4661 Note to add destinations in Engage
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: KCS

#4694 Remove grammatical error
  src/protocols/validate/connect-sources.md
Labels: KCS

#4699 Update email and sms subscription field.md
  src/engage/user-subscriptions/subscription-sql.md
Labels: fixed-content, KCS

#4687 Add Selective Sync content
  src/unify/profiles-sync/index.md
Labels: new-feature

#4698 Fix Build a Stream Typos
  src/partners/streams.md
Labels: content-update

#4671 Add info about properties with the "\" character
  src/protocols/transform/index.md
Labels: KCS

#4702 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/userpilot-web-plugin/index.md
  src/connections/sources/catalog/libraries/server/object-api/index.md
Labels: back-end

#4688 Add info about Event Names
  src/protocols/transform/index.md
Labels: KCS

#4705 Release 23.19.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/connections/destinations/catalog/usermaven/index.md
  src/connections/destinations/catalog/userpilot-web-plugin/index.md
  src/connections/destinations/catalog/userpilot/index.md
  src/connections/sources/catalog/cloud-apps/mailchimp/index.md
  src/connections/sources/catalog/libraries/server/object-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
  src/engage/user-subscriptions/subscription-sql.md
  src/partners/streams.md
  src/protocols/transform/index.md
  src/protocols/validate/connect-sources.md
  src/unify/debugger.md
  src/unify/profiles-sync/index.md
Labels: release

#4693 Navattic source
  src/connections/sources/catalog/cloud-apps/navattic/index.md
Labels: new-integration

#4598 Tracking Plan implemented
  src/protocols/faq.md
Labels: KCS

#4706 Updating Mixpanel Public Doc Link
  src/connections/destinations/catalog/mixpanel/index.md
Labels: KCS

#4710 Adding CleverTap to the list of supported plugin
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#4714 Change code to stop reference array being cleared
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#4712 Add fetch-retry dependency
  src/_includes/content/functions/runtime.md
Labels: content-update

#4684 Mixpanel Cohorts update
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
Labels: content-update

#4719 Update AWS S3 Language
  src/connections/storage/catalog/aws-s3/index.md
Labels: content-update

#4711 Add Link Shortening content
  src/engage/content/sms/template.md
Labels: new-feature

#4218 Update Environment string format example to match field description in UI
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#4075 GA4 handling null/object/array types event parameters
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#4720 Release 23.19.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/sources/catalog/cloud-apps/attacker_source/index.md
  src/connections/sources/catalog/cloud-apps/clevertapx/index.md
  src/connections/sources/catalog/cloud-apps/hubspot-x/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
  src/connections/sources/catalog/cloud-apps/navattic/index.md
  src/connections/sources/catalog/cloud-apps/source_b2/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/engage/content/sms/template.md
  src/protocols/faq.md
Labels: release

#4721 change name to remove IO
  src/connections/destinations/catalog/dreamdata-io/index.md
Labels: content-update

#4697 Update cookie validity.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: KCS

#4725 Remove section
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/amplitude-react-native.md
Labels: KCS

#4731 Add callout for ROW UI update
  src/engage/audiences/computed-traits.md
  src/engage/audiences/index.md
Labels: content-update

#4730 Add note about Marketo's Lead Activity Type IDs field
  src/connections/sources/catalog/cloud-apps/marketo/index.md
Labels: content-update

#4729 Add note about Talon.One rate limit
  src/connections/destinations/catalog/talon-one-actions/index.md
Labels: content-update

#4728 Add note that Help Scout OAuth supports one destination per user
  src/connections/destinations/catalog/help-scout/index.md
Labels: content-update

#4727 add new events for braze
  src/connections/sources/catalog/cloud-apps/braze/index.md
Labels: content-update

#4679 minor tweaks from inkit
  src/connections/destinations/catalog/inkit/index.md
Labels: content-update

#4726 Update Engage test message content
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/content/email/template.md
  src/engage/content/sms/template.md
Labels: content-update

#4722 Add details for blocked fields
  src/privacy/portal.md
Labels: KCS

#4742 Update firebase for React Native updates
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/firebase-react-native.md
Labels: KCS

#4754 one-off release
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
  src/privacy/portal.md
  src/protocols/tracking-plan/create.md
Labels: release

#4745 Add FAQ about auto-disabled sources
  src/connections/index.md
Labels: content-update

#4759 Copy of GWEN source #4748
  src/connections/sources/catalog/cloud-apps/gwen/index.md
Labels: new-integration

#4760 Release 23.20.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_layouts/default.html
  src/connections/destinations/catalog/salesforce/index.md
  src/connections/index.md
  src/connections/sources/catalog/cloud-apps/gwen/index.md
  src/connections/sources/catalog/cloud-apps/listrak-dev/index.md
  src/connections/sources/catalog/cloud-apps/mailmodo/index.md
Labels: release

#4761 Updating Link to Google's Docs (Event Naming Rules)
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update

#4764 Mixpanel RN Redesign
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/mixpanel-react-native.md
Labels: KCS

#4768 new section on event naming conventions
  src/partners/sources.md
Labels: content-update

#4611 Update Transfer To Workspace section w/ limitation
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#4594 Delivery Overview Public Beta [DOC-655]
  src/_data/sidenav/main.yml
  src/connections/delivery-overview.md
  src/connections/sources/debugger.md
  src/connections/test-connections.md
Labels: new-feature

#4757 IPv6 not supported
  src/connections/spec/common.md
Labels: KCS

#4737 TikTok Audience and Advertiser ID clarification.
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: content-update, KCS

#4788 Remove delivery overview rollout note
  src/connections/delivery-overview.md
Labels: fixed-content

#4789 add links specific to integration doc instructions
  src/partners/index.md
Labels: content-update

#4791 Release 23.21.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/_includes/content/syntax-note.md
  src/connections/destinations/catalog/actions-pinterest-conversions-api/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/castle/index.md
  src/connections/destinations/catalog/customfit-ai/index.md
  src/connections/sources/catalog/cloud-apps/http-server/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/spec/common.md
  src/partners/index.md
Labels: release

#4769 Update Plugin Architecture link AJS
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4792 [FB Conversions API (Actions)] - Updates docs to describe 'App Events' usage
  src/connections/destinations/catalog/actions-facebook-conversions-api/images/app_data.png
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: content-update

#4804 Add warning to CSV and SQL docs
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/subscription-sql.md
Labels: content-update

#4815 add id and remove hidden frontmatter
  src/connections/sources/catalog/cloud-apps/gwen/index.md
Labels: new-integration

#4799 Remove content on specific tax areas
  src/guides/usage-and-billing/billing.md
Labels: content-update

#4798 Clarify email and SMS template docs
  src/engage/content/email/editor.md
  src/engage/content/email/template.md
  src/engage/content/sms/template.md
Labels: content-update

#4797 Update roles.md
  src/segment-app/iam/roles.md
Labels: KCS

#4812 Add FAQ's on notifications to backgrounded Android apps
  src/connections/spec/native-mobile-spec.md
Labels: content-update, KCS

#4823 Deploy version of Encharge docs
  src/connections/destinations/catalog/actions-encharge/index.md
Labels: new-integration

#4820 Fixed typo
  src/connections/sources/catalog/libraries/server/object-bulk-api/index.md
Labels: KCS

#4785 Provided links to destination filters and edge functions - Swift
  src/connections/sources/catalog/libraries/mobile/apple/index.md
Labels: KCS

#4131 Fixed spelling/grammar errors
  src/connections/destinations/catalog/adobe-analytics/settings.md
Labels: KCS

#4225 Update Troubleshooting Google Ads Conversions section
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: KCS

#4828 fix: fix broken braze middleware links
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-middleware-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/index.md
Labels: broken links

#4291 Adding FAQ of filtering unsupported events.
  src/connections/destinations/destination-filters.md
Labels: KCS

#4292 Add steps to remove invalid or expired invite
  src/segment-app/iam/membership.md
Labels: KCS

#4373 Change name in integrations object in payload
  src/connections/destinations/catalog/marketo-v2/index.md
Labels: KCS

#4395 Identifier should be available in ID resolution settings to update the trait value on profile.
  src/engage/audiences/sql-traits.md
Labels: KCS

#4399 what field is supposed to map to Salesforce’s required field "Bulk Update Record ID" and "Bulk Upsert External ID"
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: KCS

#4493 Info about settings variable.
  src/connections/functions/destination-functions.md
Labels: KCS

#4531 Add to FAQ on SQL traits returning arrays
  src/engage/audiences/sql-traits.md
Labels: KCS

#4533 Mixpanel requirement on sending anonymousID in UUID V4 format.
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: KCS

#4540 Update section about Custom Events Facebook Pixel
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#4574 Adding section for new feature - useQueryString
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
Labels: KCS

#4588 Added faq regarding modifying Audience Key
  src/engage/faqs.md
Labels: KCS

#4606 Update custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4630 Add FAQ & Troubleshooting
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: KCS

#4651 GAclientId may cause user merge
  src/unify/identity-resolution/externalids.md
Labels: KCS

#4715 Update HubSpot Source to add custom property instructions
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: KCS

#4732 Update docs for when GA4 will replace UA
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update, KCS

#4751 clarification on timestamp values - Intercom classic
  src/connections/destinations/catalog/intercom/index.md
Labels: KCS
