Repository segmentio/segment-docs, pull requests merged in 2023-03, with the labels that each got.

#4331 Add onetrust source docs
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
Labels: new-integration

#4243 Update custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4335 Update integrations object info on Filtering Your Segment Data page
  src/guides/filtering-data.md
Labels: KCS

#4342 Add Engage Emoji Availability Note
  src/engage/campaigns/index.md
Labels: content-update

#4341 Remove line about data sent when 'Segment.io: false'
  src/guides/filtering-data.md
Labels: KCS

#4339 Changes for VWO Cloud and Web (Actions) Destinations'
  src/connections/destinations/catalog/actions-vwo-cloud/index.md
  src/connections/destinations/catalog/actions-vwo-web/index.md
Labels: content-update

#4171 Move paragraph on Event Delivery page
  src/connections/event-delivery.md
Labels: KCS

#4308 removing self service customer part from Custom object
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: KCS

#4343 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/libraries/mobile/flutter/index.md
Labels: back-end

#4337 Update verbiage, address vale concerns
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/google-ads-classic/index.md
Labels: content-update

#4311 Add link to SFMC Actions
  src/connections/destinations/catalog/salesforce-marketing-cloud/index.md
Labels: back-end

#4290 add support for a deprecated: true flag
  src/_includes/content/deprecated.md
  src/_layouts/destination.html
  src/connections/destinations/catalog/hull/index.md
  src/connections/destinations/catalog/promoter-io/index.md
Labels: back-end

#4278 Update trait and audience conditions
  src/engage/audiences/computed-traits.md
Labels: content-update

#4347 remove engage section
  src/connections/destinations/catalog/voucherify/index.md
Labels: back-end

#4325 Google Analytics 4 Docs
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: new-integration

#4354 CUSTINT-19134: Emarsys (Actions) documentation
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-emarsys/index.md
Labels: new-integration

#4357 Update GA4 Cloud name on strat nav
  src/_data/sidenav/strat.yml
Labels: back-end

#4329 Segment Profiles public documentation
  src/connections/destinations/catalog/actions-segment-profiles/index.md
Labels: new-integration

#4356 Add hubspot dependency
  src/_includes/content/functions/runtime.md
Labels: content-update

#4360 updating incorrect information
  src/engage/warehouses.md
Labels: KCS

#4365 Add the API proxy address for EU workspaces
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4279 Add UTM Tracking information for AJS
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4201 Added note on SLA for deletion requests
  src/privacy/user-deletion-and-suppression.md
Labels: KCS

#4372 Add link to http API source
  src/connections/destinations/catalog/actions-segment/index.md
Labels: content-update

#4350 Update Klaviyo docs link for Identify
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#4371 Update user-deletion-and-suppression.md
  src/privacy/user-deletion-and-suppression.md
Labels: KCS

#4369 Add link to growing list of supported partners
  src/privacy/user-deletion-and-suppression.md
Labels: KCS

#4338 Adding note for automatically track deep links
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: KCS

#4349 Update links to Optimizely Web JS and Web X
  src/connections/destinations/catalog/optimizely-full-stack/index.md
Labels: KCS

#4334 First party cookies
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#4273 Upollo Actions Destination
  src/connections/destinations/catalog/upollo/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: new-integration

#4386 Update destination-data-control.md
  src/connections/destination-data-control.md
Labels: fixed-content

#4387 Toplyne Actions Destination
  src/connections/destinations/catalog/toplyne/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: new-integration

#4380 Add source type suggestion for event forwarding
  src/protocols/enforce/forward-blocked-events.md
Labels: KCS

#4389 20230309 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/ripe-cloud-mode-actions/index.md
  src/connections/destinations/catalog/toplyne/index.md
  src/connections/destinations/catalog/upollo/index.md
  src/connections/sources/catalog/cloud-apps/redshift/index.md
Labels: back-end

#4391 fix links to upollo and toplyne
  src/connections/destinations/catalog/actions-toplyne-cloud/index.md
  src/connections/destinations/catalog/actions-upollo/index.md
Labels: back-end

#4392 Master back into develop after one-off
  src/connections/destinations/catalog/actions-toplyne-cloud/index.md
  src/connections/destinations/catalog/actions-upollo/index.md
Labels: back-end

#4174 add info about using base64 encoding
  src/profiles/profile-api.md
Labels: content-update, KCS

#4394 Fix Broken Link in Webhooks (Classic) Destination
  src/connections/destinations/catalog/webhooks/index.md
Labels: fixed-site

#4408 Fix broken link to Destination filters
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: KCS

#4381 Add Intro & Getting Started sections to Eloqua docs
  src/connections/destinations/catalog/eloqua/index.md
Labels: KCS

#4398 Hiding mobile destination filters
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/guides/filtering-data.md
Labels: back-end

#4262 Added information on recording userId for mailchimp - not to use trait.id
  src/connections/destinations/catalog/mailchimp/index.md
Labels: KCS

#4411 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/upollo-web-actions/index.md
  src/connections/sources/catalog/cloud-apps/livelike-test/index.md
  src/connections/sources/catalog/cloud-apps/testsource/index.md
Labels: back-end

#4412 Release 23.11.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/api/public-api/fql.md
  src/connections/destinations/catalog/actions-upollo/index.md
  src/connections/destinations/catalog/eloqua/index.md
  src/connections/destinations/catalog/mailchimp/index.md
  src/connections/destinations/catalog/upollo-web-actions/index.md
  src/connections/destinations/catalog/webhooks/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/livelike-test/index.md
  src/connections/sources/catalog/cloud-apps/testsource/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/spec/best-practices-identify.md
  src/guides/filtering-data.md
  src/profiles/profile-api.md
  src/protocols/transform/index.md
  src/reverse-etl/bigquery-setup.md
  src/reverse-etl/index.md
  src/reverse-etl/redshift-setup.md
  src/reverse-etl/snowflake-setup.md
  src/segment-app/iam/sso.md
Labels: release

#4418 Fixed typo
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#4419 make docs unsearchable until integration is public
  src/connections/destinations/catalog/actions-emarsys/index.md
Labels: back-end

#4422 Clarify the timeframe on the import events option
  src/protocols/tracking-plan/create.md
Labels: KCS

#4424 batch example
  src/connections/functions/destination-functions.md
Labels: KCS

#4426 Small punctuation edit
  src/connections/destinations/catalog/pendo/index.md
Labels: KCS

#4423 Regional support information pulled from the Public API
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regionl_support.yml
  src/_includes/content/regional-integrations-table.md
  src/connections/sources/catalog/cloud-apps/bento/index.md
  src/connections/sources/catalog/cloud-apps/testsource2/index.md
  src/utils/region-compare.md
Labels: back-end

#4429 update length() description
  src/api/public-api/fql.md
Labels: KCS

#4421 Added some points to the "FAQ & Troubleshooting" section
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#4430 Outfunnel deploy PR
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-outfunnel/index.md
Labels: new-integration

#4431 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#4432 Release 23.11.2
  .github/styles/Vocab/Docs/accept.txt
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regionl_support.yml
  src/_includes/content/regional-integrations-table.md
  src/api/public-api/fql.md
  src/connections/destinations/catalog/actions-emarsys/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-outfunnel/index.md
  src/connections/destinations/catalog/pendo/index.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/cloud-apps/bento/index.md
  src/connections/sources/catalog/cloud-apps/testsource2/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/storage/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/guides/usage-and-billing/account-management.md
  src/privacy/user-deletion-and-suppression.md
  src/protocols/tracking-plan/create.md
  src/utils/region-compare.md
Labels: release

#4416 Add sample code to pass custom field in context
  src/connections/spec/common.md
Labels: KCS

#4397 Add info about source options for subdomains
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4435 Schema Controls best practices
  src/protocols/enforce/forward-blocked-events.md
  src/protocols/enforce/schema-configuration.md
  src/protocols/faq.md
Labels: content-update

#4438 update Enforce Email as Primary Identifier
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#4439 Engage unsubscribe link content
  src/engage/content/email/editor.md
Labels: content-update

#4232 Add info for cookies that set by Analytics.js
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4409 Renamed space name can't be reflected in URL.
  src/profiles/quickstart.md
Labels: KCS

#4450 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/innovid/index.md
  src/connections/sources/catalog/cloud-apps/name/index.md
Labels: back-end

#4451 Release 23.12.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/innovid/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/tv-squared/index.md
  src/connections/sources/catalog/cloud-apps/name/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/index.md
  src/connections/spec/common.md
  src/engage/content/email/editor.md
  src/profiles/quickstart.md
  src/protocols/enforce/forward-blocked-events.md
  src/protocols/enforce/schema-configuration.md
  src/protocols/faq.md
Labels: release

#4355 CSV Uploader and other subscription updates [DOC-668]
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/engage-source.md
  src/profiles/images/profile_api_anonymous_id.png
  src/profiles/profile-api.md
Labels: content-update

#4459 WhatsApp in Engage Public Beta
  src/_data/sidenav/main.yml
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/whatsapp.md
  src/engage/images/merge_tag.png
  src/engage/index.md
  src/engage/journeys/build-journey.md
  src/engage/journeys/step-types.md
  src/engage/onboarding.md
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/engage-source.md
  src/profiles/images/profile_api_anonymous_id.png
  src/profiles/profile-api.md
Labels: new-feature

#4375 Adding a note on Iterable destination page
  src/connections/destinations/catalog/iterable/index.md
Labels: KCS

#4406 Add info for support of multi-instances in hybrid Actions destinations
  src/connections/destinations/add-destination.md
Labels: KCS

#4461 netlify redirects
  src/_redirects
Labels: back-end

#4456 Add additional info regarding timestamp fields
  src/connections/destinations/catalog/iterable/index.md
Labels: KCS

#4441 Tracking Plan FAQ update
  src/protocols/faq.md
Labels: KCS

#4455 Make it clearer that the Common JSON Schema is not supported
  src/protocols/apis-and-extensions/typewriter.md
Labels: KCS

#4479 Replay Events don't show in Event delivery tab
  src/guides/what-is-replay.md
Labels: KCS

#4458 Update mapping info with unsupported characters
  src/connections/destinations/actions.md
Labels: KCS

#4463 Destination filters not supported for Mobile
  src/connections/destinations/destination-filters.md
Labels: KCS

#4483 Update catalog and slug overrides
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
Labels: back-end

#4480 Add flush policy docs
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#4467 Reverse ETL GA
  src/_data/sidenav/main.yml
  src/_redirects
  src/connections/destinations/index.md
  src/connections/index.md
  src/connections/reverse-etl/images/RETL_Doc_Illustration.png
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/reverse-etl-catalog.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/connections/sources/index.md
  src/guides/usage-and-billing/mtus-and-throughput.md
  src/reverse-etl/index.md
Labels: new-feature

#4484 20230328 fixes
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_redirects
  src/connections/sources/catalog/cloud-apps/actions-qualtrics/index.md
Labels: back-end

#4420 Update index.md
  src/connections/storage/index.md
Labels: KCS

#4491 hot fix
  src/engage/user-subscriptions/subscription-sql.md
  src/unify/profiles-sync/index.md
  src/unify/profiles-sync/tables.md
Labels: content-update

#4482 Add integration object info for RN
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update, KCS

#4446 Add link for CleverTap server-side support
  src/connections/destinations/catalog/clevertap/index.md
Labels: KCS

#4454 update info on creating eu-workspaces
  src/guides/regional-segment.md
Labels: KCS

#4427 Update index.md
  src/connections/destinations/catalog/heap/index.md
Labels: KCS

#4497 Revert "Journeys Analytics GA [DOC-661]"
  src/engage/journeys/build-journey.md
  src/engage/journeys/images/journeys_analytics_tiles.png
  src/engage/journeys/journeys-analytics.md
  src/engage/journeys/key-terms.md
Labels: fixed-content

#4501 Clarify Mobile Device Mode behavior
  src/connections/destinations/destination-filters.md
Labels: KCS

#4436 Add info about loading plugin for Amplitude (Actions) destination
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#4263 Updated Identifier breakdown information
  src/engage/audiences/index.md
Labels: KCS

#4376 Update Transformation doc
  src/protocols/transform/index.md
Labels: KCS

#4502 add C# tags to metadata
  src/connections/sources/catalog/libraries/server/net/index.md
Labels: back-end

#4492 Predictive Traits Public Beta [DOC-657]
  src/_data/sidenav/main.yml
  src/engage/audiences/predictive-traits/index.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
  src/engage/images/explore_prediction.png
  src/engage/images/trait_builder.png
  src/engage/images/understand_prediction.png
  src/engage/index.md
Labels: new-feature

#4445 Select new fields on selective sync page for SFDC
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: KCS

#4508 Add section on ISO date conversion
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS
