Repository segmentio/segment-docs, pull requests merged in 2023-02, with the labels that each got.

#4172 Remove Streams reference.
  src/connections/sources/catalog/cloud-apps/moengage-source/index.md
Labels: content-update

#4168 Updating docs for Facebook Lead ads
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: content-update

#4121 add support clarification for simple_segment
  src/connections/sources/catalog/libraries/server/ruby/index.md
Labels: KCS

#4107 Update how to navigate to custom field names
  src/connections/destinations/catalog/hubspot/index.md
Labels: KCS

#4073 Add information about the Coalesce function
  src/connections/destinations/actions.md
Labels: KCS

#4096 Add link to schema limits FAQ
  src/connections/destination-data-control.md
Labels: KCS

#4175 Add uuidv5 dependency update [DOC-616]
  src/_includes/content/functions/runtime.md
Labels: content-update

#4177 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/formsort/index.md
  src/connections/sources/catalog/cloud-apps/partner-source-example-500/index.md
Labels: back-end

#4178 Release 23.5.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/functions/runtime.md
  src/connections/destination-data-control.md
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/cloud-apps/formsort/index.md
  src/connections/sources/catalog/cloud-apps/moengage-source/index.md
  src/connections/sources/catalog/cloud-apps/partner-source-example-500/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
  src/engage/audiences/sql-traits.md
Labels: release

#4182 update to reflect source ID > secret ID change
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
Labels: KCS

#4170 Update contact link to point to Impact contact page
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
Labels: KCS

#4186 Fixed broken link
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
Labels: KCS

#4183 Fixed minor typo
  src/guides/how-to-guides/segment-and-attribution.md
Labels: KCS

#4169 Partner documentation instructions
  src/partners/destinations/index.md
  src/partners/sources.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/source.md
Labels: content-update

#4184 Add dependency updates [DOC-651]
  src/_includes/content/functions/runtime.md
Labels: content-update

#4189 add new events and event properties
  src/connections/sources/catalog/cloud-apps/braze/index.md
Labels: content-update

#4190 Object Cloud Source regional support update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/connections/sources/catalog/cloud-apps/journy-io/index.md
Labels: content-update

#4004 ROW 3.0 updates
  src/engage/audiences/account-audiences.md
  src/engage/audiences/computed-traits.md
  src/engage/audiences/index.md
  src/engage/images/1525835194991.png
  src/engage/images/1525835663131.png
  src/engage/images/1525836239527.png
  src/engage/images/1525836568474.png
  src/engage/images/1525836818177.png
  src/engage/images/1525837083070.png
  src/engage/images/1525837374378.png
  src/engage/images/audience_builder.png
  src/engage/images/audience_condition_list.png
  src/engage/images/dynamic_property_audiences1.png
  src/engage/images/funnel_audiences1.png
  src/engage/images/new-audience-type.png
Labels: content-update, new-feature

#4192 Release 23.6.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
  src/connections/sources/catalog/cloud-apps/braze/index.md
  src/connections/sources/catalog/cloud-apps/journy-io/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/audiences/account-audiences.md
  src/engage/audiences/computed-traits.md
  src/engage/audiences/index.md
  src/engage/images/1525835194991.png
  src/engage/images/1525835663131.png
  src/engage/images/1525836239527.png
  src/engage/images/1525836568474.png
  src/engage/images/1525836818177.png
  src/engage/images/1525837083070.png
  src/engage/images/1525837374378.png
  src/engage/images/audience_builder.png
  src/engage/images/audience_condition_list.png
  src/engage/images/dynamic_property_audiences1.png
  src/engage/images/funnel_audiences1.png
  src/engage/images/new-audience-type.png
  src/guides/how-to-guides/segment-and-attribution.md
  src/partners/destinations/index.md
  src/partners/sources.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/source.md
Labels: release

#4191 Add sentence about MTU calculations for blocked events
  src/protocols/schema.md
Labels: KCS

#4155 Update sql-traits.md
  src/engage/audiences/sql-traits.md
Labels: KCS

#4202 Document multiple instance support
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: KCS

#4196 add appsflyer ios 14 guide
  src/connections/sources/catalog/libraries/mobile/ios/ios14-guide.md
Labels: content-update

#4200 Fix Javascript debug behavior description
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4187 Documentation for VWO Web Destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-vwo-web/index.md
Labels: new-integration

#4180 Fix broken link in Facebook Lead Ads Source
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: fixed-content

#4205 Release 23.6.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-vwo-cloud/index.md
  src/connections/destinations/catalog/actions-vwo-web/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/libraries/mobile/ios/ios14-guide.md
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/engage/audiences/sql-traits.md
  src/guides/usage-and-billing/billing.md
  src/partners/destinations/index.md
  src/partners/sources.md
  src/protocols/schema.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/source.md
Labels: release

#4213 remove beta message
  src/connections/destinations/catalog/journy-io/index.md
Labels: content-update

#4212 Update profile-api.md
  src/profiles/profile-api.md
Labels: fixed-content

#4228 Update Querystring Parameters Table #4148
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
Labels: content-update

#4206 Add Troubleshooting section to custom proxy page
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4203 Add actions event testing information
  src/connections/destinations/actions.md
Labels: KCS

#4223 Launchpad Actions Destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-launchpad/index.md
Labels: new-integration

#4230 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/playerzero-web/index.md
  src/connections/sources/catalog/cloud-apps/pj-test-source/index.md
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
Labels: back-end

#4231 Release 23.7.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-launchpad/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
  src/connections/destinations/catalog/journy-io/index.md
  src/connections/destinations/catalog/playerzero-web/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/pj-test-source/index.md
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
  src/partners/sources.md
  src/profiles/profile-api.md
Labels: release

#4237 Fixed Typo
  src/protocols/faq.md
Labels: KCS

#4238 Hull deprecation note
  src/connections/destinations/catalog/hull/index.md
Labels: content-update

#4210 Copy a Tracking Plan into a Library
  src/protocols/faq.md
Labels: KCS

#4236 Update Profiles Sync table
  src/profiles/profiles-sync/tables.md
Labels: content-update

#4226 Added LiveLike Cloud Documentation
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-livelike-cloud/index.md
Labels: new-integration

#4229 Minor typo fixes
  src/guides/segment-vs-tag-managers.md
Labels: KCS

#4235 Fix path for https://cdn.segment.com/v1/*
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: KCS

#4245 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#4246 Release 23.7.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-livelike-cloud/index.md
  src/connections/destinations/catalog/hull/index.md
  src/connections/destinations/catalog/promoter-io/index.md
  src/connections/destinations/catalog/sailthru-v2/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/guides/segment-vs-tag-managers.md
  src/profiles/profiles-sync/tables.md
  src/protocols/faq.md
  src/protocols/tracking-plan/create.md
Labels: release

#4233 Remove location data
  src/connections/spec/common.md
Labels: KCS

#4241 Adding qualtircs source documentation
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
Labels: new-integration

#4252 Update A.js classic deprecation banner with upgrade timeline to 2.0 [DOC-662]
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#4261 Add FAQ about failure notifications for audience and trait syncs
  src/engage/faqs.md
Labels: KCS

#4159 Add note mentioning need to configure at least one mapping
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: KCS

#4217 add event names that TikTok supports
  src/connections/destinations/catalog/tiktok-conversions/index.md
Labels: KCS

#4234 add docs for formsort
  src/connections/sources/catalog/cloud-apps/formsort/index.md
Labels: new-integration

#4242 add info about warehouse snake_casing
  src/connections/storage/warehouses/schema.md
Labels: KCS

#4268 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/segment-connections/index.md
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
Labels: back-end

#4269 Release 23.08.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/segment-connections/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/sources/catalog/cloud-apps/formsort/index.md
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/connections/spec/common.md
  src/connections/storage/warehouses/schema.md
  src/engage/faqs.md
Labels: release

#4267 Swift Mixpanel Updates
  src/connections/sources/catalog/libraries/mobile/swift/destination-plugins/mixpanel-swift.md
Labels: KCS

#4266 Update Swift Firebase
  src/connections/sources/catalog/libraries/mobile/swift/destination-plugins/firebase-swift.md
Labels: KCS

#4265 Remove unsupported features
  src/connections/sources/catalog/libraries/mobile/swift/destination-plugins/facebook-app-events-swift.md
Labels: KCS

#4264 Swift Amplitude plugin sending mode
  src/connections/sources/catalog/libraries/mobile/swift/destination-plugins/amplitude-swift.md
Labels: KCS

#4259 Add support info
  src/connections/sources/catalog/libraries/mobile/swift/destination-plugins/braze-swift.md
Labels: KCS

#4272 Qualtrics (Actions) to public beta
  src/connections/destinations/catalog/actions-qualtrics/index.md
Labels: new-integration

#4281 Add channel field to Common spec
  src/connections/spec/common.md
Labels: KCS

#4270 Update context.network fields
  src/connections/spec/common.md
Labels: KCS

#4156 Adding FAQ section about connection policy preventing users from adding sources to profiles space
  src/profiles/quickstart.md
Labels: KCS

#4277 Update Product limits
  src/connections/rate-limits.md
  src/connections/spec/index.md
Labels: content-update

#4248 Update documentation on CSP
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update, KCS

#4286 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/qualtrics/index.md
Labels: back-end

#4287 Release 23.8.2
  scripts/catalog_papi.js
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-cordial/index.md
  src/connections/destinations/catalog/actions-qualtrics/index.md
  src/connections/destinations/catalog/qualtrics/index.md
  src/connections/rate-limits.md
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/connections/spec/common.md
  src/connections/spec/index.md
  src/connections/storage/catalog/redshift/index.md
  src/profiles/quickstart.md
Labels: release

#4295 fix typo
  src/connections/destinations/catalog/clevertap/index.md
Labels: KCS

#4251 Add explanation for Privacy Portal
  src/segment-app/iam/roles.md
Labels: KCS

#4313 Add maintenance note to Webhooks classic
  src/connections/destinations/catalog/webhooks/index.md
Labels: content-update

#4300 Kotlin Mixpanel Review
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/mixpanel-kotlin-android.md
Labels: KCS

#4298 Kotlin Firebase Review
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/firebase-kotlin-android.md
Labels: KCS

#4250 Subscription SQL Public Beta
  src/_data/sidenav/main.yml
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
Labels: new-feature

#4117 Update Best Practices for Identifying Users page
  src/connections/spec/best-practices-identify.md
Labels: KCS

#4302 Advanced Transformations (Public Beta)
  src/protocols/transform/index.md
Labels: new-feature

#4306 Add PII access note to SQL Traits doc
  src/engage/audiences/sql-traits.md
Labels: content-update

#4293 Kotlin Appsflyer Review
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/appsflyer-kotlin-android.md
Labels: content-update, KCS

#4013 Suggested note for Regional Segment doc's
  src/guides/regional-segment.md
Labels: content-update, KCS

#4321 Update User Subscription Plan Information [DOC-667]
  src/engage/user-subscriptions/engage-source.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-states.md
Labels: fixed-content

#4315 Add reference to our custom proxy page
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: KCS

#4297 Kotlin Facebook Review
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/facebook-app-events-kotlin-android.md
Labels: KCS

#4296 Kotlin Braze Review
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/braze-kotlin-android.md
Labels: KCS

#4256 Remove beta note from SFMC Actions docs
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
Labels: content-update

#4255 Remove beta note from Webhook (Actions)
  src/connections/destinations/catalog/actions-webhook/index.md
Labels: content-update

#4222 Add reference to support hours and holidays
  src/help/index.md
Labels: KCS

#4312 Anlytics.js Classic EOL update note
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#4289 Information about Huawei devices
  src/connections/sources/catalog/libraries/mobile/android/android-faqs.md
Labels: KCS

#4323 20230228 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/vwo-cloud-mode-actions/index.md
  src/connections/destinations/catalog/vwo-web-mode-actions/index.md
  src/connections/sources/catalog/cloud-apps/livelike/index.md
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
Labels: back-end

#4318 Update profile sync docs to include 3 steps
  src/profiles/profiles-sync/index.md
Labels: content-update

#4324 Release 23.9.1
  .github/styles/Vocab/Docs/accept.txt
  scripts/catalog_papi.js
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-cordial/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/actions-segment/index.md
  src/connections/destinations/catalog/actions-vwo-cloud/index.md
  src/connections/destinations/catalog/actions-vwo-web/index.md
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/clevertap/index.md
  src/connections/destinations/catalog/cordial-actions/index.md
  src/connections/destinations/catalog/vwo-cloud-mode-actions/index.md
  src/connections/destinations/catalog/vwo-web-mode-actions/index.md
  src/connections/destinations/catalog/webhooks/index.md
  src/connections/sources/catalog/cloud-apps/livelike/index.md
  src/connections/sources/catalog/libraries/mobile/android/android-faqs.md
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/connections/spec/best-practices-identify.md
  src/engage/audiences/sql-traits.md
  src/engage/user-subscriptions/engage-source.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-states.md
  src/guides/regional-segment.md
  src/help/index.md
  src/profiles/profiles-sync/index.md
  src/protocols/transform/index.md
  src/segment-app/iam/roles.md
Labels: release
