Repository segmentio/segment-docs, pull requests merged in 2023-11, with the labels that each got.

#5613 remove links to OAuth
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
Labels: back-end

#5624 Master back to develop after hot fix
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
Labels: back-end

#5603 Update destination-betas.md
  src/utils/destination-betas.md
Labels: back-end

#5626 Add note about Google EC Legacy API Deprecation
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update

#5606 Hyperengage (Actions) Destination
  src/connections/destinations/catalog/actions-hyperengage/index.md
Labels: new-integration

#5631 Remove Lantern docs #5629
  src/connections/destinations/catalog/lantern/index.md
  src/protocols/apis-and-extensions/anomaly_detection.md
Labels: fixed-content

#5625 docs(RN): update code blocks to ease copy feature
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#4878 Add to Engage FAQs
  src/engage/faqs.md
Labels: KCS

#5632 11/2 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5633 Release 23.44.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-airship/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-hyperengage/index.md
  src/connections/destinations/catalog/lantern/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/engage/faqs.md
  src/protocols/apis-and-extensions/anomaly_detection.md
  src/utils/destination-betas.md
Labels: release

#5635 Minor fix
  src/connections/destinations/catalog/heap/index.md
Labels: KCS

#5634 Add info about Swift plugin to Consent Management docs
  src/privacy/configure-consent-management.md
Labels: content-update

#5527 Override context value for node library
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: KCS

#5639 correct titles on templates
  templates/partners/destination-new.md
  templates/partners/destination-update.md
Labels: fixed-content

#5641 Fix the provided snippet.md
  src/connections/destinations/catalog/optimizely-web/index.md
Labels: KCS

#5638 remove hidden frontmatter
  src/connections/sources/catalog/cloud-apps/alloyflow/index.md
Labels: back-end

#5587 Add section about conversion tracking with LinkedIn Insight Tag
  src/connections/destinations/catalog/linkedin-insight-tag/index.md
Labels: KCS

#5645 Small typo fix
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5649 Update common.md misspelling
  src/connections/spec/common.md
Labels: fixed-content

#5575 Source transfer impact on connected destination
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#5255 Add information regarding default limit number of functions
  src/connections/functions/usage.md
Labels: KCS

#5653 Fixed table that wasn't rendering properly
  src/_sass/components/_markdown.scss
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: fixed-content

#5650 Add missing spaces between links and next word for clarity
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
  src/getting-started/04-full-install.md
  src/guides/how-to-guides/migrate-from-other-tools.md
Labels: fixed-content

#5648 Fix repo name for kotlin-android-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters.md
Labels: KCS

#5599 Add Survicate Kotlin plugin
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/survicate-kotlin-android.md
Labels: new-feature

#5617 Update computed-traits.md CSV Download Account update
  src/unify/Traits/computed-traits.md
Labels: content-update

#5659 Make Catalog 20231109
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/cdp-resolution/index.md
  src/connections/destinations/catalog/insider-audiences/index.md
  src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
  src/connections/destinations/catalog/launchdarkly-audiences/index.md
  src/connections/destinations/catalog/optimizely-advanced-audience-targeting/index.md
Labels: back-end

#5618 Update index.md CSV Download Accounts update
  src/engage/audiences/index.md
Labels: content-update

#5660 Release 23.45.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_sass/components/_markdown.scss
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
  src/connections/destinations/catalog/autopilothq/index.md
  src/connections/destinations/catalog/cdp-resolution/index.md
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
  src/connections/destinations/catalog/heap/index.md
  src/connections/destinations/catalog/insider-audiences/index.md
  src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
  src/connections/destinations/catalog/launchdarkly-audiences/index.md
  src/connections/destinations/catalog/linkedin-insight-tag/index.md
  src/connections/destinations/catalog/optimizely-advanced-audience-targeting/index.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/functions/usage.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
  src/connections/sources/catalog/cloud-apps/alloyflow/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/survicate-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/connections/spec/common.md
  src/engage/audiences/index.md
  src/getting-started/04-full-install.md
  src/guides/how-to-guides/migrate-from-other-tools.md
  src/guides/usage-and-billing/account-management.md
  src/privacy/configure-consent-management.md
  src/unify/Traits/computed-traits.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
Labels: release

#5616 Update environment.md Testing a function section
  src/connections/functions/environment.md
Labels: content-update

#5276 Add connection string examples
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
Labels: KCS

#5670 Remove page enrichment plugin link
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5675 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5664 Update swift-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-destination-filters.md
Labels: content-update, KCS

#5647 Update swift-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-destination-filters.md
Labels: content-update, KCS

#5508 Update documentation to include archiving events
  src/connections/sources/schema/schema-unique-limits.md
Labels: KCS

#5679 Update Audit Trail docs [DOC-752]
  src/_data/products.yml
  src/segment-app/iam/audit-trail.md
Labels: content-update

#5680 Amazon Kinesis Firehose edits
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
Labels: content-update

#5668 Podscribe Destination (editable)
  src/connections/destinations/catalog/actions-podscribe/index.md
Labels: new-integration

#5677 Fueled/shopify fueled
  src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
Labels: new-integration

#5681 add disable documentation
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5685 Update Predictions FAQ
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update

#5684 Add Journeys SLA to FAQs [DOC-754]
  src/engage/journeys/faq-best-practices.md
Labels: content-update

#5489 Add note on custom traits for deleted audiences
  src/engage/audiences/index.md
Labels: KCS

#5687 Add Twilio Notify Steps to Push Notifications Onboarding
  src/engage/campaigns/mobile-push/index.md
Labels: content-update

#5623 1Flow-web doc
  src/connections/destinations/catalog/1flow-web/index.md
Labels: new-integration

#5690 Revert "add disable documentation"
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: back-end

#5689 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5691 Release 23.46.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/connections/destinations/catalog/1flow-web/index.md
  src/connections/destinations/catalog/actions-podscribe/index.md
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
  src/connections/destinations/catalog/engage-messaging/index.md
  src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-destination-filters.md
  src/connections/sources/schema/schema-unique-limits.md
  src/engage/audiences/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/journeys/faq-best-practices.md
  src/segment-app/iam/audit-trail.md
  src/unify/Traits/predictions/using-predictions.md
Labels: release

#5692 Update index.md
  src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
Labels: fixed-content

#5105 Update index.md Marketo V2 can't have multiple instances
  src/connections/destinations/catalog/marketo-v2/index.md
Labels: content-update

#5091 Add note on payload location for email id
  src/engage/using-engage-data.md
Labels: KCS

#5542 Add note on include anon users flag
  src/engage/audiences/index.md
Labels: KCS

#5693 Update using-engage-data.md
  src/engage/using-engage-data.md
Labels: content-update

#5696 Update index.md
  src/connections/destinations/catalog/hubspot/index.md
Labels: content-update

#5561 Add note on event order in debugger
  src/connections/sources/debugger.md
Labels: KCS

#5694 Add note on using transformations with filters
  src/connections/destinations/destination-filters.md
Labels: KCS

#5666 Add section on locating source by write key
  src/connections/find-writekey.md
  src/connections/images/find-source-using-write-key.png
Labels: KCS

#5703 Attio is going into Public Beta
  src/connections/destinations/catalog/actions-attio/index.md
Labels: back-end

#5699 add overrides to correct metadata
  src/_data/catalog/slugs.yml
Labels: back-end

#5706 Fix breadcrumb issues in Linked Profiles and Trait Activation
  src/_data/sidenav/main.yml
  src/engage/trait-activation/index.md
  src/unify/index.md
  src/unify/linked-profiles/linked-events.md
Labels: back-end

#5704 Replace VAT FAQ PDF
  src/assets/pdf/faq-segment-dissolution-vat.pdf
Labels: content-update

#5711 Remove Outdated Journeys Section
  src/engage/journeys/faq-best-practices.md
Labels: content-update

#5709 Add Unify Plus clarification
  src/unify/index.md
Labels: content-update

#5667 Add link to where to find Conversion Label
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: KCS

#5103 Update source-functions.md Added 2 new errors for source functions
  src/connections/functions/source-functions.md
Labels: content-update

#5161 Update mapping instructions on sending Engage data
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
Labels: content-update, KCS

#5282 Update server side event information
  src/connections/destinations/catalog/appsflyer/index.md
Labels: content-update, KCS

#5586 Add paragraph about when to create custom event
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update, KCS

#5646 clarify hubspot custom properties requirements
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: content-update, KCS

#5712 Make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5713 Release 23.47.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/connections/destinations/catalog/actions-attio/index.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/marketo-v2/index.md
  src/connections/destinations/destination-filters.md
  src/connections/find-writekey.md
  src/connections/functions/source-functions.md
  src/connections/images/find-source-using-write-key.png
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/shopify-fueled/index.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/sources/debugger.md
  src/engage/audiences/index.md
  src/engage/journeys/faq-best-practices.md
  src/engage/trait-activation/index.md
  src/engage/using-engage-data.md
  src/unify/index.md
  src/unify/linked-profiles/linked-events.md
Labels: release

#5715 Grammar fix
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5714 Spec: Alias rewrite
  src/connections/spec/alias.md
Labels: content-update

#5717 Spec style guide fixes
  src/connections/spec/best-practices-event.md
  src/connections/spec/best-practices-identify.md
  src/connections/spec/common.md
  src/connections/spec/ecommerce/index.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/migration-guide.md
  src/connections/spec/mobile.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/semantic.md
  src/connections/spec/track.md
  vale-styles/Vocab/Docs/accept.txt
Labels: content-update

#5725 Fix actions-fields.html typo
  src/_includes/components/actions-fields.html
Labels: fixed-content

#5695 Add note about Audit Trail to consent management docs
  src/privacy/configure-consent-management.md
Labels: content-update

#5719 Update Unify and Engage FAQs
  src/engage/faqs.md
  src/engage/journeys/faq-best-practices.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/trait-enrichment.md
  src/engage/user-subscriptions/subscription-groups.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/faqs.md
  src/unify/identity-resolution/index.md
  src/unify/linked-profiles/linked-events.md
  src/unify/profiles-sync/sample-queries.md
Labels: fixed-content

#5718 Fix typo in Bing Ads doc
  src/connections/destinations/catalog/bing-ads/index.md
Labels: fixed-content

#5720 add docs for new movable ink destination
  src/connections/destinations/catalog/actions-movable-ink/index.md
Labels: new-integration

#5723 Update Kotlin device mode plugin docs to address using classic destination
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
Labels: KCS

#5734 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5735 Release 23.48.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-movable-ink/index.md
  src/connections/destinations/catalog/bing-ads/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/alias.md
  src/connections/spec/best-practices-event.md
  src/connections/spec/best-practices-identify.md
  src/connections/spec/common.md
  src/connections/spec/ecommerce/index.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/migration-guide.md
  src/connections/spec/mobile.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/semantic.md
  src/connections/spec/track.md
  src/engage/faqs.md
  src/engage/journeys/faq-best-practices.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/trait-enrichment.md
  src/engage/user-subscriptions/subscription-groups.md
  src/privacy/configure-consent-management.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/faqs.md
  src/unify/identity-resolution/index.md
  src/unify/linked-profiles/linked-events.md
  src/unify/profiles-sync/sample-queries.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#5697 Feature/upollo sdm 1
  src/connections/destinations/catalog/upollo/index.md
Labels: new-integration

#5729 Update docs to include links to Next.js
  src/connections/sources/catalog/libraries/website/javascript/analytics-js-2.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5740 Update analytics.js snippet to 5.0.1
  src/_includes/content/snippet-helper.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/destinations/catalog/youbora/index.md
Labels: content-update

#5739 Clarify necessary token permissions for Qualtrics source
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
Labels: content-update

#5745 Segment GDPR Compliance Updates
  src/privacy/complying-with-the-gdpr.md
Labels: content-update

#5628 Update custom proxy docs
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: content-update, KCS

#5657 Added information on timestamp format for time comparison operators
  src/engage/audiences/index.md
Labels: content-update, KCS

#5746 Add info on retrieving anonymousId
  src/connections/sources/catalog/libraries/mobile/react-native/implementation.md
Labels: KCS

#5700 Add info about using classic destination with plugins
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/index.md
Labels: KCS
