Repository segmentio/segment-docs, pull requests merged in 2023-04, with the labels that each got.

#4520 Journeys Analytics GA [DOC-661]
  src/engage/journeys/build-journey.md
  src/engage/journeys/images/journeys_analytics_tiles.png
  src/engage/journeys/journeys-analytics.md
  src/engage/journeys/key-terms.md
Labels: content-update, new-feature

#4513 Add instructions on how to get an EU workspace for Source testing
  src/partners/sources.md
Labels: KCS

#4521 Fix addDestinationMiddleware example in docs
  src/connections/sources/catalog/libraries/website/javascript/middleware.md
Labels: fixed-content

#4511 Update Known Limitations section
  src/guides/regional-segment.md
Labels: KCS

#4527 Make Wisepops destination appear in catalog list
  src/connections/destinations/catalog/actions-wisepops/index.md
  src/connections/destinations/catalog/wisepops/index.md
Labels: content-update

#4515 Automate making Private -> Public destinations visible on site
  scripts/private-destination.js
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
Labels: back-end

#4517 Update Intercom Widget
  src/connections/destinations/catalog/intercom/index.md
Labels: KCS

#4498 Add info about GA4 web page views
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#4340 Added information that Iterable perform check on phone number field
  src/connections/destinations/catalog/iterable/index.md
Labels: KCS

#4510 Update two topics to clarify current behavior
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#4193 Add FAQ & Troubleshooting section to Destination Actions docs
  src/connections/destinations/actions.md
Labels: KCS

#4049 Update the section to check for Snowflake account name
  src/connections/storage/catalog/snowflake/index.md
Labels: KCS

#4525 Fix Predictive Traits Typo
  src/engage/audiences/predictive-traits/using-predictive-traits.md
Labels: fixed-content

#4528 Update catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/actions-livelike-cloud/index.md
  src/connections/sources/catalog/cloud-apps/inflection/index.md
  src/connections/sources/catalog/cloud-apps/test_niall/index.md
Labels: back-end

#4529 Release 23.14.1
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/_includes/content/plan-grid.md
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/actions-wisepops/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/iterable/index.md
  src/connections/destinations/catalog/salesforce/index.md
  src/connections/destinations/catalog/tv-squared/index.md
  src/connections/destinations/catalog/wisepops/index.md
  src/connections/sources/catalog/cloud-apps/actions-livelike-cloud/index.md
  src/connections/sources/catalog/cloud-apps/inflection/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/test_niall/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/middleware.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/storage/catalog/azuresqldw/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
  src/getting-started/03-planning-full-install.md
  src/guides/regional-segment.md
  src/partners/sources.md
Labels: release

#4534 Clarify when we strip reserved properties in the Braze destination
  src/connections/destinations/catalog/braze/index.md
Labels: content-update

#4542 Remove ")" from link which breaks on page
  src/connections/destinations/catalog/optimizely-web/index.md
Labels: KCS

#4536 unhide docs as integration is going public beta
  src/connections/destinations/catalog/actions-blend-ai/index.md
Labels: back-end

#4407 Remove Manual Upgrade and Automatic Migration AJS
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: KCS

#4514 Update index.md
  src/connections/destinations/catalog/heap/index.md
Labels: KCS

#4538 GWEN (Actions) deploy PR
  src/connections/destinations/catalog/actions-gwen-cloud/index.md
Labels: new-integration

#4547 Added sample form to Spec pages
  src/_includes/components/codepens/group-spec.html
  src/_includes/components/codepens/identify-spec.html
  src/_includes/components/codepens/page-spec.html
  src/_includes/components/codepens/screen-spec.html
  src/_includes/components/codepens/track-spec.html
  src/_sass/components/_markdown.scss
  src/_sass/components/_sample-form.scss
  src/_sass/elements/_code.scss
  src/_sass/segment.scss
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/track.md
Labels: back-end

#4543 Remove broken anchor link
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4545 Add Predictive Traits FAQs
  src/engage/audiences/predictive-traits/index.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
Labels: content-update

#4550 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/blend-ai/index.md
Labels: back-end

#4495 update folder name to be same as integration slug
  src/connections/destinations/catalog/actions-ripe-web/index.md
Labels: back-end

#4539 Voucherify deploy PR
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/voucherify-actions/index.md
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
Labels: new-integration

#4551 Release 23.14.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/components/codepens/group-spec.html
  src/_includes/components/codepens/identify-spec.html
  src/_includes/components/codepens/page-spec.html
  src/_includes/components/codepens/screen-spec.html
  src/_includes/components/codepens/track-spec.html
  src/_sass/components/_markdown.scss
  src/_sass/components/_sample-form.scss
  src/_sass/elements/_code.scss
  src/_sass/segment.scss
  src/connections/destinations/catalog/actions-blend-ai/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-gwen-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
  src/connections/destinations/catalog/blend-ai/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/heap/index.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/destinations/catalog/voucherify-actions/index.md
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
  src/connections/spec/group.md
  src/connections/spec/identify.md
  src/connections/spec/page.md
  src/connections/spec/screen.md
  src/connections/spec/track.md
  src/engage/audiences/predictive-traits/index.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
Labels: release

#4415 Sentry destination update
  src/connections/destinations/catalog/sentry/images/event-id.png
  src/connections/destinations/catalog/sentry/index.md
Labels: KCS

#4563 Algolia Insights doc update deploy PR
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/algolia-insights/images/algolia_api_keys.png
  src/connections/destinations/catalog/algolia-insights/images/algolia_app_id_dropdown.png
  src/connections/destinations/catalog/algolia-insights/images/algolia_dashboard_settings.png
  src/connections/destinations/catalog/algolia-insights/images/algolia_settings_menu.png
  src/connections/destinations/catalog/algolia-insights/images/mapping_tab.png
  src/connections/destinations/catalog/algolia-insights/images/mapping_tab_edit.png
  src/connections/destinations/catalog/algolia-insights/index.md
Labels: content-update

#4282 Add flag for token collection
  src/connections/destinations/catalog/customer-io-actions/index.md
Labels: KCS

#4561 Remove Iterable from the list of supported destinations
  src/connections/reverse-etl/index.md
Labels: KCS

#4565 Release 23.15.1
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-gwen-cloud/index.md
  src/connections/destinations/catalog/algolia-insights/images/algolia_api_keys.png
  src/connections/destinations/catalog/algolia-insights/images/algolia_app_id_dropdown.png
  src/connections/destinations/catalog/algolia-insights/images/algolia_dashboard_settings.png
  src/connections/destinations/catalog/algolia-insights/images/algolia_settings_menu.png
  src/connections/destinations/catalog/algolia-insights/images/mapping_tab.png
  src/connections/destinations/catalog/algolia-insights/images/mapping_tab_edit.png
  src/connections/destinations/catalog/algolia-insights/index.md
  src/connections/destinations/catalog/customer-io-actions/index.md
  src/connections/destinations/catalog/gwen-actions/index.md
  src/connections/destinations/catalog/repeater/index.md
  src/connections/destinations/catalog/sentry/images/event-id.png
  src/connections/destinations/catalog/sentry/index.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/cloud-apps/gwen/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/guides/what-is-replay.md
Labels: release

#4546 Update identify.md
  src/connections/spec/identify.md
Labels: content-update, KCS

#4567 Fix Engage Quickstart Audience Step #4566
  src/engage/images/pers-qs-config_audience.png
  src/engage/quickstart.md
Labels: fixed-content

#4447 Update faq.md
  src/protocols/faq.md
Labels: KCS

#4577 Outfunnel destination is available
  src/connections/destinations/catalog/actions-outfunnel/index.md
Labels: new-integration

#4562 Website URL field
  src/getting-started/02-simple-install.md
Labels: KCS

#4579 Update Account-Level Audiences
  src/engage/audiences/account-audiences.md
Labels: content-update

#4578 catalog update
  Gemfile.lock
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-outfunnel/index.md
Labels: back-end

#4581 update ajs classic deprecation note
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
Labels: content-update

#4592 add one more redirect and remove beta tag
  src/connections/destinations/catalog/algolia-insights/index.md
Labels: back-end

#4590 Email Template Editor updates
  src/engage/content/email/editor.md
Labels: content-update

#4596 fix: remove beta note from algolia docs
  src/connections/destinations/catalog/algolia-insights/index.md
Labels: content-update

#4553 Add configuration steps for Google Ads gtag
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: KCS

#4593 Update Profiles Sync headers
  src/unify/profiles-sync/tables.md
Labels: content-update

#4509 Update GTM page to mention Firebase for mobile
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#4384 Add information that format shown in pretty view depends on the library used.
  src/connections/sources/debugger.md
Labels: KCS

#4535 Older browser support
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
Labels: KCS

#4600 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/navattic/index.md
Labels: back-end

#4587 Event tester limitation for destination filters
  src/connections/destinations/destination-filters.md
Labels: KCS

#4601 Release 23.16.1
  CODEOWNERS
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/algolia-insights/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/navattic/index.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
  src/connections/sources/debugger.md
  src/engage/content/email/editor.md
  src/unify/profiles-sync/tables.md
Labels: release

#4589 Update External Amplitude Links #4523
  src/connections/destinations/catalog/amplitude/index.md
Labels: fixed-content

#4473 Update user-deletion-and-suppression.md
  src/privacy/user-deletion-and-suppression.md
Labels: KCS

#4609 Note about the Flutter library in pilot
  src/connections/sources/index.md
Labels: content-update

#4608 Add note about nested arrays
  src/connections/destinations/catalog/amplitude/index.md
Labels: KCS

#4607 Update faq.md
  src/connections/storage/warehouses/faq.md
Labels: KCS

#4614 Add Twilio Content Editor Beta Note
  src/engage/content/whatsapp.md
Labels: content-update

#4610 June (Actions) deploy PR
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-june/index.md
Labels: new-integration

#4602 final updates for onetrust before going public
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
Labels: new-integration

#4616 Release 23.16.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-june/index.md
  src/connections/destinations/catalog/actions-toplyne-cloud/index.md
  src/connections/destinations/catalog/amplitude/index.md
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
  src/connections/sources/index.md
  src/connections/storage/warehouses/faq.md
  src/engage/content/whatsapp.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#4620 add redirect, and remove hidden & private front matter
  src/connections/destinations/catalog/june-actions/index.md
Labels: fixed-content

#4617 Add FAQ about Omitted Properties
  src/protocols/faq.md
Labels: KCS

#4622 Unify rebrand updates
  src/connections/reverse-etl/index.md
  src/engage/audiences/index.md
  src/engage/journeys/faq-best-practices.md
  src/engage/journeys/journeys-logic.md
  src/engage/quickstart.md
  src/segment-app/iam/roles.md
  src/unify/identity-resolution/externalids.md
  src/unify/identity-resolution/identity-resolution-onboarding.md
  src/unify/identity-resolution/identity-resolution-settings.md
  src/unify/index.md
  src/unify/profiles-sync/index.md
  src/unify/quickstart.md
Labels: content-update

#4621 RN 2.0 partial
  src/_includes/content/react2-dest.md
  src/connections/destinations/catalog/appsflyer/index.md
Labels: KCS

#4626 Add redirect for Swift SDK
  src/connections/sources/catalog/libraries/mobile/apple/index.md
Labels: KCS

#4532 Small correction for Custom Matcher
  src/privacy/portal.md
Labels: KCS

#4632 Error loading option from Segment Profiles
  src/connections/destinations/catalog/actions-segment-profiles/index.md
Labels: content-update

#4628 add in CORS info
  src/api/public-api/index.md
Labels: KCS

#4636 Revert Identity Admin role
  src/connections/reverse-etl/index.md
  src/engage/audiences/index.md
  src/engage/journeys/faq-best-practices.md
  src/engage/journeys/journeys-logic.md
  src/engage/quickstart.md
  src/segment-app/iam/roles.md
  src/unify/identity-resolution/externalids.md
  src/unify/identity-resolution/identity-resolution-onboarding.md
  src/unify/identity-resolution/identity-resolution-settings.md
  src/unify/index.md
  src/unify/profiles-sync/index.md
  src/unify/quickstart.md
Labels: fixed-content

#4624 make selection hilighting for code more accessible
  src/_sass/elements/_code.scss
Labels: back-end

#4572 4481 ajs single page
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
Labels: content-update

#4637 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-livelike-cloud/index.md
  src/connections/destinations/catalog/june-actions/index.md
Labels: back-end

#4634 Update PAPI availability to Team and BT only
  src/_includes/content/papi-ga.html
Labels: content-update

#4638 Release 23.17.1
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/papi-ga.html
  src/_includes/content/react2-dest.md
  src/_includes/content/regional-integrations-table.md
  src/_sass/elements/_code.scss
  src/api/public-api/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-livelike-cloud/index.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/criteo-audiences/index.md
  src/connections/destinations/catalog/june-actions/index.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
  src/engage/quickstart.md
  src/privacy/portal.md
  src/protocols/faq.md
  src/segment-app/iam/roles.md
Labels: release

#4639 Update index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
Labels: content-update

#4552 add Pixel FAQ
  src/connections/functions/source-functions.md
Labels: KCS

#4640 Update index.md
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
Labels: content-update

#4642 update intercom collection fields
  src/connections/sources/catalog/cloud-apps/intercom/index.md
Labels: content-update

#4641 Add note about availability of Public API SDKs
  src/api/public-api/index.md
Labels: content-update

#4623 Analytics-CSharp Library (Public Beta) [DOC-679]
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/mobile/unity/index.md
  src/connections/sources/catalog/libraries/mobile/xamarin/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/connections/sources/catalog/libraries/server/net/index.md
Labels: new-integration

#4605 Update value mapping on Order Completed event
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: content-update, KCS

#4654 catalog update
  scripts/catalog_papi.js
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-toplyne-cloud/index.md
Labels: back-end

#4655 Release 23.17.2
  scripts/catalog_papi.js
  scripts/private-destination.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/functions/runtime.md
  src/api/public-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
  src/connections/destinations/catalog/actions-toplyne-cloud/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/functions/source-functions.md
  src/connections/sources/catalog/cloud-apps/intercom/index.md
  src/connections/sources/catalog/libraries/mobile/unity/index.md
  src/connections/sources/catalog/libraries/mobile/xamarin/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/engage/quickstart.md
  src/segment-app/iam/roles.md
Labels: release

#4599 Update QueryString Table
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
Labels: KCS
