Repository segmentio/segment-docs, pull requests merged in 2023-09, with the labels that each got.

#5290 Update index.md Customer.io troubleshooting filters
  src/connections/destinations/catalog/customer-io/index.md
Labels: content-update

#5284 Update trait-activation-setup.md
  src/engage/trait-activation/trait-activation-setup.md
Labels: content-update

#5229 Facebook Pixel events in real-time
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#5291 Add Facebook Pixel doc edits
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: content-update

#5299 Catalog - 9/5/23
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/connections/destinations/catalog/canny-actions/index.md
  src/connections/destinations/catalog/data-lakes/index.md
  src/connections/destinations/catalog/google-cloud-storage/index.md
  src/connections/destinations/catalog/inmoment-formerly-wootric/index.md
  src/connections/destinations/catalog/insider-audiences/index.md
  src/connections/destinations/catalog/optimizely-feature-experimentation-actions/index.md
  src/connections/destinations/catalog/revx-cloud-actions/index.md
  src/connections/destinations/catalog/tiktok-pixel/index.md
  src/connections/sources/catalog/cloud-apps/addshoppers-suppression/index.md
  src/connections/sources/catalog/cloud-apps/analytics-js/index.md
  src/connections/sources/catalog/cloud-apps/appy-pie-connect/index.md
  src/connections/sources/catalog/cloud-apps/b222test/index.md
  src/connections/sources/catalog/cloud-apps/freshchat-source/index.md
  src/connections/sources/catalog/cloud-apps/inmoment-formerly-wootric/index.md
  src/connections/sources/catalog/cloud-apps/livelike-source/index.md
  src/connections/sources/catalog/cloud-apps/poc_test/index.md
  src/connections/sources/catalog/cloud-apps/rehook/index.md
  src/connections/sources/catalog/cloud-apps/skyvia/index.md
  src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
  src/connections/sources/catalog/cloud-apps/unlocking-simulation/index.md
  src/connections/sources/catalog/cloud-apps/unstack/index.md
  src/connections/sources/catalog/cloud-apps/upollo/index.md
  src/connections/sources/catalog/libraries/server/amp/index.md
  src/connections/sources/catalog/libraries/server/node-js/index.md
Labels: back-end

#5300 Release 23.36.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/connections/destinations/catalog/canny-actions/index.md
  src/connections/destinations/catalog/customer-io/index.md
  src/connections/destinations/catalog/data-lakes/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/destinations/catalog/google-cloud-storage/index.md
  src/connections/destinations/catalog/inmoment-formerly-wootric/index.md
  src/connections/destinations/catalog/insider-audiences/index.md
  src/connections/destinations/catalog/optimizely-feature-experimentation-actions/index.md
  src/connections/destinations/catalog/revx-cloud-actions/index.md
  src/connections/destinations/catalog/tiktok-pixel/index.md
  src/connections/sources/catalog/cloud-apps/addshoppers-suppression/index.md
  src/connections/sources/catalog/cloud-apps/analytics-js/index.md
  src/connections/sources/catalog/cloud-apps/appy-pie-connect/index.md
  src/connections/sources/catalog/cloud-apps/b222test/index.md
  src/connections/sources/catalog/cloud-apps/freshchat-source/index.md
  src/connections/sources/catalog/cloud-apps/inmoment-formerly-wootric/index.md
  src/connections/sources/catalog/cloud-apps/livelike-source/index.md
  src/connections/sources/catalog/cloud-apps/poc_test/index.md
  src/connections/sources/catalog/cloud-apps/rehook/index.md
  src/connections/sources/catalog/cloud-apps/skyvia/index.md
  src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
  src/connections/sources/catalog/cloud-apps/unlocking-simulation/index.md
  src/connections/sources/catalog/cloud-apps/unstack/index.md
  src/connections/sources/catalog/cloud-apps/upollo/index.md
  src/connections/sources/catalog/libraries/server/amp/index.md
  src/connections/sources/catalog/libraries/server/node-js/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/schema/schema-unique-limits.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
  src/guides/usage-and-billing/billing.md
  src/privacy/configure-consent-management.md
Labels: release

#5275 Add info about keepalive flag in AJS
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#5288 additional functionality note
  src/connections/destinations/catalog/actions-airship/index.md
Labels: content-update

#5302 Unlocking Attribution source
  src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
Labels: new-integration

#5312 Catalog (9-7-23)
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5313 Release 23.36.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-absmartly/index.md
  src/connections/destinations/catalog/actions-airship/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/sources/catalog/cloud-apps/unlocking-attribution/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: release

#4888 Add blurb when source isn't available in catalog
  src/connections/sources/index.md
Labels: KCS

#4772 Adding warning to Warehouse Selective Sync section
  src/connections/storage/warehouses/warehouse-syncs.md
Labels: KCS

#5319 Update custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: content-update

#5197 feat: add ios 17 documentation [netlify-build]
  .tool-versions
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/mobile/apple/ios-17.md
Labels: new-feature

#5320 Remove beta info for RETL Postgres and Databricks sources
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
Labels: content-update

#5324 Added US processing regions note to Customer.io source
  src/connections/sources/catalog/cloud-apps/customer-io/index.md
Labels: fixed-content

#5327 Remove Beta Flags from Marketo and SFMC Sources [DOC-730]
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/salesforce-marketing-cloud/index.md
Labels: content-update

#5329 feat(code): remove public api token requirement for segment profiles destination
  src/connections/destinations/catalog/actions-segment-profiles/index.md
Labels: content-update

#4666 Update Using Engage Data doc
  src/engage/using-engage-data.md
Labels: KCS

#5307 Adding info about reusing sendgrid keys.md
  src/engage/onboarding.md
Labels: KCS

#5323 Update Salesforce doc
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: content-update

#5328 Add New Properties to Stripe Cloud Source
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: content-update

#4665 Added Google Optimize Support Information for GA4 Cloud Mode Destination
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#5321 [STRATCONN-2695]- Update HubSpot doc with information regarding 403 errors
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: content-update

#5331 Make Catalog 20230912
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/wordpress---woocommerce/index.md
Labels: back-end

#5332 Release 23.37.1
  .tool-versions
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
  src/connections/sources/catalog/cloud-apps/customer-io/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/salesforce-marketing-cloud/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/sources/catalog/cloud-apps/wordpress---woocommerce/index.md
  src/connections/sources/catalog/libraries/mobile/apple/ios-17.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/index.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/engage/onboarding.md
  src/engage/using-engage-data.md
Labels: release

#5325 Removed sources with `hidden: true` from source comparison table, Regional Segment guide
  src/_includes/content/regional-integrations-table.md
  src/connections/sources/sources-compare.md
Labels: back-end

#5337 Fix spelling in the migration guide
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
Labels: fixed-content

#5342 cascading changes from one-off
  src/_data/products.yml
  src/_includes/content/connection-modes-intro.md
  src/connections/destinations/add-destination.md
  src/connections/destinations/destination-filters.md
  src/privacy/hipaa-eligible-segment.md
Labels: back-end

#5343 unhide listrak docs
  src/connections/destinations/catalog/actions-listrak/index.md
Labels: content-update

#5339 Add batch concurrency limits.md
  src/engage/product-limits.md
  src/unify/product-limits.md
Labels: KCS

#5345 Connection modes table override
  src/_data/catalog/overrides.yml
Labels: fixed-content

#5277 Clarify HubSpot sync info
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: KCS

#5287 Add FAQ on Google Play warnings
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#5254 Generate a list of event cloud sources supported in EU workspaces
  src/_includes/content/eu-cloud-event-sources.html
  src/connections/sources/catalog/cloud-apps/factual-engine/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
  src/guides/regional-segment.md
Labels: fixed-content

#5348 Updating Databricks Setup Guide with suggestions on connection type
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
Labels: content-update

#5349 Update Catalog 20230912
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/listrak-actions/index.md
Labels: back-end

#5350 Release 23.37.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/eu-cloud-event-sources.html
  src/_includes/content/regional-integrations-table.md
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/listrak-actions/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/sources/catalog/cloud-apps/factual-engine/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/connections/sources/sources-compare.md
  src/engage/product-limits.md
  src/guides/regional-segment.md
  src/unify/product-limits.md
Labels: release

#5330 Update AppsFlyer Device Id Section
  src/connections/destinations/catalog/appsflyer/index.md
Labels: KCS

#5315 add destinations from npm
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: new-feature

#5297 Update Page method paragraph: GTM
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#5354 Fix key type typo (#13)
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
Labels: fixed-content

#5357 Add Source Overview Docs
  src/connections/sources/images/source-overview.jpeg
  src/connections/sources/index.md
Labels: content-update

#5356 Delivery Overview timeframe fix
  src/connections/delivery-overview.md
Labels: fixed-content

#5358 Add Journeys Edits and Versioning Page
  src/engage/journeys/journeys-edits.md
Labels: new-feature

#5366 Remove Iterable Source Regional Callout
  src/connections/sources/catalog/cloud-apps/iterable/index.md
Labels: content-update

#5340 Update user-deletion-and-suppression guide.md
  src/privacy/user-deletion-and-suppression.md
Labels: KCS

#5333 Add AJS Storage Priority Config
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: content-update

#5352 Remove FAQ file and update faqs for React Native
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/react-faqs.md
Labels: content-update, KCS

#5346 Feature/upollo source
  src/connections/sources/catalog/cloud-apps/upollo/index.md
Labels: new-integration

#5367 add koala documentation
  src/connections/destinations/catalog/actions-koala/index.md
  src/connections/destinations/catalog/koala/index.md
Labels: new-integration

#5373 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5375 Release 23.38.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-koala/index.md
  src/connections/destinations/catalog/actions-pinterest-conversions-api/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/koala/index.md
  src/connections/destinations/catalog/test-flow/index.md
  src/connections/sources/catalog/cloud-apps/upollo/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/react-faqs.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#5344 Add note on connecting new mappings to model
  src/connections/reverse-etl/index.md
Labels: KCS

#5383 remove redundant section
  templates/partners/source.md
Labels: content-update

#5267 Add Linked Events docs
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/segment-app/iam/roles.md
  src/unify/linked-profiles/linked-events.md
  src/unify/linked-profiles/setup-guides/BigQuery-setup.md
  src/unify/linked-profiles/setup-guides/redshift-setup.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: new-feature

#5381 Update Engage Onboarding for Event Streams
  src/engage/images/messaging_service.png
  src/engage/onboarding.md
Labels: content-update

#5371 Initial catalog information for Attio Actions Destination
  src/connections/destinations/catalog/actions-attio/index.md
Labels: new-integration

#5359 Renamed iOS and Android repo to make it identical for both platforms
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
Labels: content-update

#5369 adding new swift plugin docs for 1flow
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/1flow-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
Labels: content-update

#5262 Ambee Destination docs
  src/connections/destinations/catalog/actions-ambee/index.md
Labels: new-integration

#5365 fix typo
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#5392 Rupt Actions Destination
  src/connections/destinations/catalog/actions-rupt/index.md
Labels: new-integration

#5389 Add Okta/SAML Integration Guide [DOC-715]
  src/segment-app/iam/images/active_connections.png
  src/segment-app/iam/images/okta_sso.png
  src/segment-app/iam/sso.md
Labels: content-update

#5393 Make Catalog 20230921
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/koala/index.md
Labels: back-end

#5395 Release 23.38.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
  src/connections/destinations/catalog/actions-ambee/index.md
  src/connections/destinations/catalog/actions-attio/index.md
  src/connections/destinations/catalog/actions-braze-cohorts/index.md
  src/connections/destinations/catalog/actions-gainsight-px-cloud/index.md
  src/connections/destinations/catalog/actions-rupt/index.md
  src/connections/destinations/catalog/koala/index.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/1flow-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/segment.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/privacy/hipaa-eligible-segment.md
  src/segment-app/iam/images/active_connections.png
  src/segment-app/iam/images/okta_sso.png
  src/segment-app/iam/sso.md
  templates/partners/source.md
Labels: release

#5388 Fix analytics react native firebase plugin link
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/firebase-react-native.md
Labels: KCS

#5336 Update documentation to reflect Analytics.js limitation
  src/connections/destinations/catalog/appcues/index.md
Labels: automated issue, KCS

#5398 1flow is going live so removing hidden frontmatter
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
Labels: content-update

#5406 Add Broadcasts GA updates
  src/engage/campaigns/broadcasts.md
Labels: content-update

#5399 Make wording more clear in iOS Quickstart Guide
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
Labels: content-update

#5338 Analytics CSharp GA
  src/connections/sources/catalog/libraries/mobile/xamarin/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/connections/sources/catalog/libraries/server/net/index.md
Labels: new-integration

#5408 Master back to develop after one-off deploy for csharp ga
  src/connections/sources/catalog/libraries/mobile/xamarin/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/engage/campaigns/broadcasts.md
Labels: back-end

#5401 Destination Insert Functions GA updates
  src/_includes/content/functions/logs.md
  src/connections/functions/destination-functions.md
  src/connections/functions/index.md
  src/connections/functions/insert-functions.md
Labels: content-update

#5412 unhide docs
  src/connections/destinations/catalog/actions-rupt/index.md
Labels: back-end

#5360 LiveRamp Docs
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/traitEnrichment-EngageSettings.png
  src/connections/destinations/catalog/actions-liveramp-audiences/traitEnrichment-Mappings.png
Labels: new-integration

#5413 Merge master back to develop
  src/_includes/content/functions/logs.md
  src/connections/functions/destination-functions.md
  src/connections/functions/index.md
  src/connections/functions/insert-functions.md
Labels: back-end

#5409 Mobile Push GA [DOC-714]
  src/_data/sidenav/main.yml
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/content/mobile-push.md
Labels: new-feature

#5415 LiveRamp and TTD Public Beta Docs Updates
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: content-update

#5396 Add Swift Package Manager Instructions to the Quickstart Guide
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
Labels: content-update

#5416 Fixed typo
  src/connections/spec/native-mobile-spec.md
Labels: KCS

#5417 Update TTD Docs
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: content-update

#5418 Update Journeys Edits and Versioning for GA
  src/_data/sidenav/main.yml
  src/engage/journeys/journeys-edits.md
Labels: content-update

#5405 Add/Remove traits for RN
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#5306 Updated instructions for adding an integrated parter
  src/connections/destinations/catalog/appsflyer/index.md
Labels: KCS

#5296 explain the dedupe window
  src/guides/duplicate-data.md
Labels: KCS

#5249 Update FAQ: AWS Account ID for EventBridge destination
  src/connections/destinations/catalog/amazon-eventbridge/index.md
Labels: KCS

#5419 Make catalog 20230926
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5420 Release 23.39.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
  src/connections/destinations/catalog/actions-google-campaign-manager/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/traitEnrichment-EngageSettings.png
  src/connections/destinations/catalog/actions-liveramp-audiences/traitEnrichment-Mappings.png
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/actions-pushwoosh/index.md
  src/connections/destinations/catalog/actions-rupt/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
  src/connections/destinations/catalog/amazon-eventbridge/index.md
  src/connections/destinations/catalog/appcues/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/sources/catalog/cloud-apps/elastic-path/index.md
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/firebase-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/spec/native-mobile-spec.md
  src/engage/journeys/journeys-edits.md
  src/guides/duplicate-data.md
Labels: release

#5425 Hide Mobile Push Docs
  src/_data/sidenav/main.yml
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/content/mobile-push.md
Labels: content-update

#5426 Fix Mobile Push Side Navigation
  src/_data/sidenav/main.yml
Labels: content-update

#5376 Trait Activation GA updates
  src/engage/audiences/index.md
  src/engage/journeys/send-data.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/overview.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
Labels: content-update

#5427 Merge master to develop after Trait Activation
  src/_data/sidenav/main.yml
  src/engage/audiences/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/content/mobile-push.md
  src/engage/journeys/send-data.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/overview.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
Labels: back-end

#5430 Put Changelog Script Back
  scripts/changelog.js
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
Labels: back-end

#5433 Unhide Mobile Push Docs
  src/_data/sidenav/main.yml
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/content/mobile-push.md
Labels: content-update

#5435 Merge `master` back into `develop` after Mobile Push
  src/_data/sidenav/main.yml
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/content/mobile-push.md
Labels: back-end

#5400 GA4 Web: Add section about Page Views toggle
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5436 Refactor Segment plugin to use latest 1Flow SDK
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
Labels: content-update

#5438 Add Identifiers Guide
  src/guides/working-with-ids.md
Labels: content-update

#5424 Update information on setconfigfield and pageview
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5439 Make catalog 20230928
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5362 Update privacy-portal.md with synonyms example
  src/privacy/images/privacy-synonym-in-matcher.png
  src/privacy/portal.md
Labels: KCS

#5440 Release 23.39.2
  scripts/changelog.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/storage/warehouses/faq.md
  src/guides/working-with-ids.md
  src/privacy/configure-consent-management.md
  src/privacy/consent-in-segment-connections.md
  src/privacy/consent-in-unify.md
  src/privacy/consent-management.md
  src/privacy/images/privacy-synonym-in-matcher.png
  src/privacy/portal.md
  src/privacy/reconcile-consent.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#5443 Update Identifiers Guide
  src/guides/working-with-ids.md
Labels: content-update

#5447 Small wording change
  src/connections/destinations/catalog/1flow-mobile-plugin/index.md
Labels: fixed-content

#5449 Added information on Journey randomized splits
  src/engage/journeys/step-types.md
Labels: content-update

#5457 Master back to develop
  src/guides/intro-impl.md
  src/guides/working-with-ids.md
Labels: back-end
