Repository segmentio/segment-docs, pull requests merged in 2023-12, with the labels that each got.

#5741 Add sentence about Set Configuration Fields
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5538 Update sample code for Node.js Typewritter
  src/protocols/apis-and-extensions/typewriter.md
Labels: KCS

#5614 Add supported destinations
  src/connections/sources/catalog/libraries/mobile/apple/index.md
Labels: KCS

#5758 Add Libraries Integration Labels
  src/_data/support-types.yml
  src/_includes/content/support-grid.md
  src/_layouts/integration.html
  src/_sass/components/_badge.scss
  src/connections/sources/catalog/libraries/mobile/amp/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/taplytics-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/xamarin/index.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/rust/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: back-end

#5756 Twilio Unified Login [DOC-757]
  src/segment-app/iam/index.md
  src/segment-app/iam/secure-password.md
Labels: new-feature

#5757 Style guide update
  styleguide.md
Labels: back-end

#5759 Update account-audiences redirect
  src/engage/audiences/account-audiences.md
Labels: fixed-content

#5640 Profiles Sync materialized tables
  src/unify/profiles-sync/index.md
  src/unify/profiles-sync/tables.md
Labels: new-feature

#5754 Update snippet to 5.2.0
  src/_includes/content/snippet-helper.md
  src/_layouts/default.html
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/destinations/catalog/youbora/index.md
Labels: content-update

#5764 Release 23.49.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/support-types.yml
  src/_includes/content/snippet-helper.md
  src/_includes/content/support-grid.md
  src/_layouts/default.html
  src/_layouts/integration.html
  src/_sass/components/_badge.scss
  src/connections/destinations/catalog/actions-attio/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/attio-actions/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/movable-ink-actions/index.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/destinations/catalog/youbora/index.md
  src/connections/sources/catalog/libraries/mobile/amp/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/taplytics-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/implementation.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/mobile/xamarin/index.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/rust/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/engage/audiences/account-audiences.md
  src/protocols/apis-and-extensions/typewriter.md
  src/segment-app/iam/index.md
  src/segment-app/iam/secure-password.md
  src/unify/profiles-sync/index.md
  src/unify/profiles-sync/tables.md
  styleguide.md
Labels: release

#5770 Update Public API link
  src/engage/user-subscriptions/set-user-subscriptions.md
Labels: KCS

#4945 Update Event Tester page
  src/_data/sidenav/main.yml
  src/connections/test-connections.md
Labels: KCS

#5636 Destination Actions (Delivery Overview) [DOC-748]
  src/connections/delivery-overview.md
  src/connections/images/delivery-overview-actions-destination.jpeg
Labels: content-update

#5772 Add referrer debug info info
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: content-update, KCS

#5651 Add guidance for authorizing a Facebook account
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: KCS

#5776 Update VAT/Tax FAQs PDF
  src/assets/pdf/faq-segment-dissolution-vat.pdf
Labels: content-update

#5421 Add section on Set Once/Set Always fields
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#5777 Add Push Notifications Advanced Settings
  src/engage/content/mobile-push.md
Labels: content-update

#5778 Make Catalog 20231207
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/podscribe-actions/index.md
Labels: back-end

#5678 Add Import Tracking Plan docs [DOC-687]
  src/protocols/tracking-plan/create.md
Labels: new-feature

#5787 merging master back into develop after one-off release
  src/protocols/tracking-plan/create.md
Labels: back-end

#5295 Add info about Mixpanel's distinct_id
  src/connections/destinations/catalog/mixpanel/index.md
Labels: KCS

#5767 Add Toggle doc updates
  src/engage/content/email/html-editor.md
Labels: content-update

#5786 Add Klaviyo Action Docs
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: new-integration

#5765 Add note on returning event object in handler
  src/connections/functions/insert-functions.md
Labels: KCS

#5790 Updated Tax FAQ pdf
  src/assets/pdf/faq-segment-dissolution-vat.pdf
Labels: content-update

#5496 Update index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: content-update, KCS

#5793 Hubble (Actions) Documentation
  src/connections/destinations/catalog/hubble-web/index.md
Labels: new-integration

#5791 Renamed Analytics.js 2.0 to Analytics.js
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5781 Add direct link to Segment Inspector in Chrome store
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5794 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5796 Release 23.50.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/hubble-web/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/engage/content/email/html-editor.md
Labels: release

#5795 Remove beta tag
  src/connections/destinations/catalog/actions-absmartly/index.md
  src/connections/destinations/catalog/actions-launchdarkly-audiences/index.md
  templates/partners/destination-new.md
Labels: content-update

#5760 Update account-management.md
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#5494 Update Littledata Source Documentation
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/Nd5L0C6.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
Labels: content-update

#5535 GA4 Web: Add section about Recommended Events
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update, KCS

#5803 Unhide Iterate Docs
  src/connections/destinations/catalog/actions-iterate/index.md
Labels: content-update

#5768 Add section about Ignoring duplicate instances of on-page configuration
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5802 Add Bucket Web (Actions) documentation
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/bucket/index.md
Labels: new-integration

#5801 Update GDPR Support Email
  src/privacy/complying-with-the-gdpr.md
Labels: content-update

#5637 Add mentions of Segment Inspector.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#5612 Update Facebook App Events docs to include Swift
  src/connections/destinations/catalog/facebook-app-events/index.md
Labels: content-update, KCS

#5800 Message to upgrade mobile SDKs
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: KCS

#5784 Update documentation for filter data to include warehouses
  src/guides/filtering-data.md
Labels: KCS

#5804 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5805 Release 23.50.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-absmartly/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-iterate/index.md
  src/connections/destinations/catalog/actions-launchdarkly-audiences/index.md
  src/connections/destinations/catalog/actions-outfunnel/index.md
  src/connections/destinations/catalog/actions-screeb-web/index.md
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/bucket/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/images/Nd5L0C6.png
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/guides/filtering-data.md
  src/guides/usage-and-billing/account-management.md
  src/privacy/complying-with-the-gdpr.md
  src/privacy/portal.md
  templates/partners/destination-new.md
Labels: release

#5810 Unhide Bucket docs as integration is now live
  src/connections/destinations/catalog/bucket-web/index.md
Labels: new-integration

#5604 Use account-level SQL traits to associate users to the account
  src/engage/audiences/account-audiences.md
Labels: KCS

#5821 Update insert-functions.md
  src/connections/functions/insert-functions.md
Labels: content-update

#5826 Remove `email` from Profiles Sync example
  src/unify/profiles-sync/tables.md
Labels: fixed-content

#5827 Make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5828 Release 23.52.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/functions/insert-functions.md
  src/engage/audiences/account-audiences.md
  src/unify/profiles-sync/tables.md
Labels: release
