Repository segmentio/segment-docs, pull requests merged in 2023-10, with the labels that each got.

#5456 Update blocked events faq to include api calls
  src/protocols/faq.md
Labels: KCS

#5442 Add note about fuzzy matching support in data encryption
  src/privacy/hipaa-eligible-segment.md
  src/privacy/portal.md
Labels: content-update

#5422 OAuth 2.0 [DOC-735]
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
  src/connections/oauth.md
Labels: new-feature

#5429 Update Custom Event Naming paragraph
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5463 Update index.md Custom traits mutable
  src/engage/audiences/index.md
Labels: content-update

#5458 Update using-engage-data.md Additional info on engage events
  src/engage/using-engage-data.md
Labels: content-update

#5474 adding livelike source docs to correct integration folder
  src/connections/sources/catalog/cloud-apps/livelike-source/index.md
  src/connections/sources/catalog/cloud-apps/livelike/index.md
Labels: new-integration

#5454 Update identity-resolution-settings.md Changing Identity Resolution R…
  src/unify/identity-resolution/identity-resolution-settings.md
Labels: content-update

#5472 fix frontmatter and remove private
  src/connections/destinations/catalog/actions-pushwoosh/index.md
Labels: back-end

#5452 fix ajs storage example
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: fixed-content

#5351 Update settings.md
  src/engage/settings.md
Labels: KCS

#5475 Update Subscription Groups Content
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/template.md
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-states.md
Labels: content-update

#5464 Update index.md Added Troubleshooting section Update Schema Settings …
  src/api/public-api/index.md
Labels: content-update

#5470 Master back to develop after OAuth 2.0 merge
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
  src/connections/oauth.md
Labels: back-end

#5476 Make Catalog 20231003
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/connections/destinations/catalog/gainsight-px-cloud-actions/index.md
  src/connections/destinations/catalog/liveramp-audiences/index.md
  src/connections/destinations/catalog/rehook/index.md
  src/connections/destinations/catalog/rupt/index.md
  src/connections/sources/catalog/cloud-apps/livelike/index.md
  src/connections/sources/catalog/cloud-apps/one-creation-zero-party-data-engagement/index.md
  src/connections/sources/catalog/cloud-apps/this-is-a-test/index.md
Labels: back-end

#5477 Release 23.40.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/connections/destinations/catalog/gainsight-px-cloud-actions/index.md
  src/connections/destinations/catalog/liveramp-audiences/index.md
  src/connections/destinations/catalog/rehook/index.md
  src/connections/destinations/catalog/rupt/index.md
  src/connections/sources/catalog/cloud-apps/livelike/index.md
  src/connections/sources/catalog/cloud-apps/one-creation-zero-party-data-engagement/index.md
  src/connections/sources/catalog/cloud-apps/this-is-a-test/index.md
Labels: release

#5479 Separate content validation content
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/content/sms/template.md
Labels: content-update

#5455 Loops (Actions) Destination
  src/connections/destinations/catalog/actions-loops/index.md
Labels: new-integration

#5446 GA4 Web: Add more details about event naming
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5478 update migration guide
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
Labels: content-update

#5390 Update use case page for Engage Premier
  src/engage/use-cases.md
Labels: KCS

#5483 format and number fix
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: content-update

#5481 LIBWEB-1531 - TikTok Pixel - updating docs to explain 'Use Existing Pixel' setting
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
Labels: content-update

#5118 Clarity in Adobe eVar
  src/connections/destinations/catalog/adobe-analytics/settings.md
Labels: content-update, KCS

#5259 Add information to save the Sandbox enabled settings before authenticate
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: content-update, KCS

#5387 Link to GA4 documentation for required parameters in GA4 Web
  src/_includes/components/actions-fields.html
Labels: KCS

#5484 add beta tag
  src/connections/sources/catalog/cloud-apps/livelike-source/index.md
Labels: back-end

#5485 Fix Broken Callout on The Trade Desk
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: fixed-content

#5486 Add Iterable to Regional Supported Table
  src/_data/catalog/regional-supported.yml
  src/_data/regional-support.yml
Labels: back-end

#5487 Catalog (10/5/23)
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5488 Release 23.40.3
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-loops/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
  src/connections/destinations/catalog/adobe-analytics/settings.md
  src/connections/sources/catalog/cloud-apps/elastic-path/index.md
  src/connections/sources/catalog/cloud-apps/livelike-source/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/engage/use-cases.md
Labels: release

#5491 Mixpanel group ID traits image fix
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/mixpanel-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/mixpanel-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/mixpanel-react-native.md
Labels: back-end

#5490 correct a typo
  src/connections/destinations/destination-filters.md
Labels: KCS

#5497 Update alerts guide
  src/guides/how-to-guides/set-up-notifications-alerts.md
Labels: KCS

#5501 hiding docs as headsup is shutting down
  src/connections/destinations/catalog/headsup-ai/index.md
Labels: back-end

#5471 Add a section to clarify the support for Remarketing
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: KCS

#5377 Add section about using Custom Events: GA4 Web
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5506 add new sources table and remove sources from old regional table
  src/_data/regional-support.yml
  src/_includes/content/regional-integrations-table.md
  src/_includes/content/regional-sources-table.md
  src/guides/regional-segment.md
Labels: back-end

#5503 Add limitation 'Event Type is Page'
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5507 Update Linked Events docs
  src/unify/linked-profiles/linked-events.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: content-update

#5473 Update client side identify
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#5512 Optimizely Audience doc
  src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
Labels: new-integration

#5511 Fix Singular connection modes table
  src/_data/catalog/overrides.yml
Labels: back-end

#5509 RETL for Subscriptions
  src/connections/reverse-etl/index.md
Labels: new-feature

#5513 Miscellaneous how-to doc edits (part 1)
  src/guides/how-to-guides/automated-multichannel-reengagement.md
  src/guides/how-to-guides/collect-on-client-or-server.md
  src/guides/how-to-guides/collect-pageviews-serverside.md
  src/guides/how-to-guides/create-push-notification.md
Labels: content-update

#5514 Make Catalog 20231010
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5516 Release 23.41.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/_includes/content/regional-integrations-table.md
  src/_includes/content/regional-sources-table.md
  src/connections/destinations/catalog/action-optimizely-advanced-audience-targeting/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/headsup-ai/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/destination-filters.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/mixpanel-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/mixpanel-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/mixpanel-react-native.md
  src/guides/how-to-guides/automated-multichannel-reengagement.md
  src/guides/how-to-guides/collect-on-client-or-server.md
  src/guides/how-to-guides/collect-pageviews-serverside.md
  src/guides/how-to-guides/create-push-notification.md
  src/guides/how-to-guides/set-up-notifications-alerts.md
  src/guides/regional-segment.md
  src/unify/linked-profiles/linked-events.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: release

#5518 GA4 Actions mapping note hotfix
  src/_includes/components/actions-fields.html
Labels: back-end

#5525 fix supported methods
  src/connections/destinations/catalog/inflection/index.md
Labels: fixed-content

#5522 Add details on blocking data using JSON Schema
  src/protocols/tracking-plan/create.md
Labels: KCS

#5523 Remove RN partial for old RN 1.x library
  src/_includes/content/react-dest.md
  src/connections/destinations/catalog/adjust/index.md
  src/connections/destinations/catalog/amplitude/index.md
  src/connections/destinations/catalog/branch-metrics/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/bugsnag/index.md
  src/connections/destinations/catalog/clevertap/index.md
  src/connections/destinations/catalog/comscore/index.md
  src/connections/destinations/catalog/countly/index.md
  src/connections/destinations/catalog/crittercism/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/destinations/catalog/flurry/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/localytics/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/quantcast/index.md
  src/connections/destinations/catalog/taplytics/index.md
  src/connections/destinations/catalog/tapstream/index.md
Labels: KCS

#5526 Fix entities role descriptions
  src/segment-app/iam/roles.md
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#5529 Make Catalog 20231012
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/loops-actions/index.md
Labels: back-end

#5528 Fix: GA4 action-fields note only appears on GA4 Web Actions destination page
  src/_includes/components/actions-fields.html
Labels: fixed-site

#5530 Release 23.41.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/_includes/content/react-dest.md
  src/connections/destinations/catalog/actions-launchdarkly-audiences/index.md
  src/connections/destinations/catalog/adjust/index.md
  src/connections/destinations/catalog/amplitude/index.md
  src/connections/destinations/catalog/branch-metrics/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/bugsnag/index.md
  src/connections/destinations/catalog/clevertap/index.md
  src/connections/destinations/catalog/comscore/index.md
  src/connections/destinations/catalog/countly/index.md
  src/connections/destinations/catalog/crittercism/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/destinations/catalog/flurry/index.md
  src/connections/destinations/catalog/inflection/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/localytics/index.md
  src/connections/destinations/catalog/loops-actions/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/quantcast/index.md
  src/connections/destinations/catalog/taplytics/index.md
  src/connections/destinations/catalog/tapstream/index.md
  src/protocols/tracking-plan/create.md
  src/segment-app/iam/roles.md
  src/unify/images/large_trait_csv.png
  src/unify/images/trait_overview.png
  src/unify/linked-profiles/linked-events.md
Labels: release

#5534 The Trade Desk CRM DOCS Update
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: content-update

#5531 removing beta and private
  src/connections/destinations/catalog/actions-loops/index.md
Labels: content-update

#4853 Add info on blocking unplanned identify event
  src/protocols/enforce/schema-configuration.md
Labels: KCS

#5533 GA4: Add Conversion Events section
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5537 Rate limits cleanup [DOC-742]
  src/connections/rate-limits.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#5541 Update kotlin-android-plugin-architecture.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture.md
Labels: content-update

#5540 Add entry condition clarification [DOC-741]
  src/engage/journeys/build-journey.md
Labels: content-update

#4657 Add section to Frequently Asked Questions - Profiles Sync
  src/unify/profiles-sync/sample-queries.md
Labels: KCS

#5521 Segment Intercom Web doesn't support leads
  src/connections/destinations/catalog/actions-intercom-web/index.md
Labels: content-update, KCS

#5519 Add info about CleverTap repo ownership
  src/connections/destinations/catalog/clevertap/index.md
Labels: KCS

#5431 Databricks Delta Lake beta docs [DOC-734]
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-aws.md
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-azure.md
  src/connections/storage/catalog/databricks-delta-lake/index.md
Labels: new-integration, new-feature

#5545 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5549 Databricks updates
  src/_data/catalog/warehouse.yml
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-aws.md
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-azure.md
  src/connections/storage/catalog/databricks-delta-lake/index.md
  src/connections/storage/catalog/index.md
Labels: content-update

#5554 remove mention of partner slack
  src/connections/destinations/catalog/actions-optimizely-advanced-audience-targeting/index.md
  src/partners/destinations/index.md
Labels: content-update

#4771 Adding ANSI Reserved Keyword error to Warehouse Errors Page
  src/connections/storage/warehouses/warehouse-errors.md
Labels: KCS

#5552 Add OneSignal Source Docs
  src/connections/sources/catalog/cloud-apps/onesignal/index.md
Labels: new-integration

#5309 Protocols data type definitions and impact on WH
  src/connections/storage/warehouses/faq.md
  src/protocols/faq.md
Labels: KCS

#5562 GA4 SDK requires page() to initialize.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update, KCS

#5559 Update GA4Web Custom Events Documentation
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update

#5556 Cx studio/source
  src/connections/sources/catalog/cloud-apps/cx-studio/index.md
Labels: new-integration

#5536 Network carrier no longer returned for iOS
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
Labels: KCS

#5557 Clarify how to promote IDFA as an identifier more explicit
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: fixed-content

#5316 Rokt Audiences (Actions) Destination docs
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/action-rokt-audiences/index.md
Labels: new-integration

#5563 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5564 Release 23.42.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/action-rokt-audiences/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-optimizely-advanced-audience-targeting/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
  src/connections/sources/catalog/cloud-apps/alloyflow/index.md
  src/connections/sources/catalog/cloud-apps/cx-studio/index.md
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
  src/connections/spec/video.md
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/warehouse-errors.md
  src/partners/destinations/index.md
  src/protocols/faq.md
Labels: release

#5544 Add "Validate Consent Integration" section
  src/privacy/configure-consent-management.md
Labels: content-update

#5162 Created new section in Anomaly Detection page about Slack (Actions) forwarding
  src/protocols/apis-and-extensions/anomaly_detection.md
  src/protocols/apis-and-extensions/images/slack-actions-forwarding.jpeg
Labels: content-update

#5568 Update custom traits in glossary #5565
  src/_data/glossary.yml
Labels: content-update

#5492 Add faq that PII access is needed to see error messages in SQL trait
  src/unify/Traits/sql-traits.md
Labels: KCS

#5571 Fixing the snippet.md
  src/connections/destinations/catalog/optimizely-web/index.md
Labels: KCS

#5547 Include section on chat widget
  src/connections/destinations/catalog/actions-intercom-web/index.md
Labels: automated issue, KCS

#5574 Fix typo
  src/guides/regional-segment.md
Labels: KCS

#5572 Tracking Plan "create" page cleanup [DOC-724]
  src/protocols/tracking-plan/create.md
Labels: content-update

#5577 Fix Duplicate Table of Contents in `/connections/spec/mobile`
  src/connections/spec/mobile.md
Labels: fixed-content

#5579 10/24 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5580 Release 23.43.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/glossary.yml
  src/_layouts/default.html
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/spec/mobile.md
  src/guides/regional-segment.md
  src/privacy/configure-consent-management.md
  src/privacy/hipaa-eligible-segment.md
  src/protocols/apis-and-extensions/anomaly_detection.md
  src/protocols/apis-and-extensions/images/slack-actions-forwarding.jpeg
  src/protocols/tracking-plan/create.md
  src/segment-app/iam/concepts.md
  src/unify/Traits/sql-traits.md
Labels: release

#5532 update supported destination list
  src/privacy/faq.md
Labels: content-update

#5581 Multiple External IDs
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: KCS

#5584 Remove "ghost" files
  src/connections/destinations/catalog/insider-audiences/index.md
  src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
Labels: back-end

#5589 small fixes
  src/connections/sources/catalog/libraries/mobile/apple/migration.md
  src/connections/spec/video.md
Labels: content-update

#5585 Rate limits clarification
  src/connections/rate-limits.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#5510 update retl extract schedule
  src/connections/reverse-etl/index.md
Labels: KCS

#5573 Add SFMC to Trait Activation
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
Labels: content-update

#5591 More vale edits for the "how to" guides
  src/guides/how-to-guides/cross-channel-tracking.md
  src/guides/how-to-guides/dynamic-coupon-program.md
  src/guides/how-to-guides/forecast-with-sql.md
Labels: fixed-content

#5588 Vero destination revamp
  src/connections/destinations/catalog/vero/index.md
Labels: fixed-content

#5583 move all insider dests out of beta and hide deprecated classic dest docs
  src/connections/destinations/catalog/actions-insider-audiences/index.md
  src/connections/destinations/catalog/insider/index.md
Labels: back-end

#5595 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5596 Release 23.43.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-emarsys/index.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-insider-audiences/index.md
  src/connections/destinations/catalog/insider-audiences/index.md
  src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
  src/connections/destinations/catalog/insider/index.md
  src/connections/destinations/catalog/vero/index.md
  src/connections/rate-limits.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/libraries/mobile/apple/migration.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/spec/video.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
  src/guides/how-to-guides/cross-channel-tracking.md
  src/guides/how-to-guides/dynamic-coupon-program.md
  src/guides/how-to-guides/forecast-with-sql.md
  src/privacy/faq.md
Labels: release

#5543 Include FAQ on unnamed events
  src/connections/sources/index.md
Labels: KCS

#5597 Update alias.md
  src/connections/spec/alias.md
Labels: KCS

#5582 Add information about deleted records id
  src/connections/reverse-etl/index.md
Labels: KCS

#5600 Add information around push onboarding - CSM or AE required
  src/engage/campaigns/mobile-push/index.md
Labels: content-update, KCS

#5609 Minor fix
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
Labels: KCS
