Repository segmentio/segment-docs, pull requests merged in 2023-07, with the labels that each got.

#4961 Update mobile device mode limitations
  src/connections/destinations/destination-filters.md
Labels: KCS

#4963 Add context section to iOS docs
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: KCS

#4964 Update campaign events information
  src/connections/spec/mobile.md
Labels: KCS

#4966 Destination Insert Functions Public Beta
  src/_includes/content/functions/errors-and-error-handling.md
  src/connections/functions/index.md
  src/connections/functions/insert-functions.md
Labels: content-update

#4946 Airship Actions Destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-airship/index.md
Labels: new-integration

#4903 The Intercom source syncs all historic data
  src/connections/sources/catalog/cloud-apps/intercom/index.md
Labels: KCS

#4953 Add troubleshooting section on duplicate events
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#4943 Add additional details to FAQ about pageviews
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#4960 PlayerZero Cloud Docs
  src/connections/destinations/catalog/playerzero-cloud/index.md
Labels: new-integration

#4986 Fix Engage Onboarding Typo
  src/engage/onboarding.md
Labels: fixed-content

#4619 Update filtering-data.md
  src/guides/filtering-data.md
Labels: KCS

#4983 new docs for insider audiences destination
  src/connections/destinations/catalog/actions-insider-audiences/index.md
Labels: new-integration

#4990 Release 23.27.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-airship/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-insider-audiences/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/canny-functions/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/playerzero-cloud/index.md
  src/connections/destinations/destination-filters.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
  src/connections/sources/catalog/cloud-apps/intercom/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/index.md
  src/connections/spec/mobile.md
  src/connections/storage/catalog/data-lakes/index.md
  src/connections/storage/data-lakes/index.md
  src/connections/storage/warehouses/schema.md
  src/engage/audiences/computed-traits.md
  src/engage/onboarding.md
  src/guides/filtering-data.md
  src/unify/profile-api-limits.md
Labels: release

#4988 Add troubleshooting for Intercom regional endpoints
  src/connections/destinations/catalog/actions-intercom-web/index.md
Labels: KCS

#4970 RETL Replays, Objects, Arrays [DOC709]
  src/connections/reverse-etl/index.md
Labels: content-update

#4980 Update Unify FAQ doc
  src/unify/faqs.md
Labels: KCS

#4995 unhide and rename folder to be same as integration slug
  src/connections/destinations/catalog/actions-canny/index.md
Labels: content-update

#4984 add new source docs for Listrak
  src/connections/sources/catalog/cloud-apps/listrak/index.md
Labels: new-integration

#4998 Fix Engage Foundations Unify Reference
  src/engage/quickstart.md
Labels: fixed-content

#5003 Fix OneTrust email bug
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
Labels: fixed-content

#4997 Removed Identify usage bullet point
  src/connections/spec/identify.md
Labels: content-update

#4893 Insider Cloud Mode (Actions)
  src/connections/destinations/catalog/actions-insider-cloud/index.md
  src/connections/destinations/catalog/voucherify-actions/index.md
Labels: new-integration

#5004 Fixed broken link on iOS Quickstart page
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
Labels: fixed-content

#4991 fix bug - wrong tool name
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
Labels: fixed-content

#5007 Update FAQ for resolving duplicate page views.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#4999 Update Braze Getting Started Instructions #4881
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/braze/index.md
Labels: content-update

#5009 Renamed destination from Exponea to Bloomreach Engagement
  src/connections/destinations/catalog/bloomreach-engagement/index.md
  src/connections/destinations/catalog/exponea/index.md
Labels: fixed-content

#5010 Release 23.28.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-airship/index.md
  src/connections/destinations/catalog/actions-canny/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-insider-audiences/index.md
  src/connections/destinations/catalog/actions-insider-cloud/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/airship-actions/index.md
  src/connections/destinations/catalog/bloomreach-engagement/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/exponea/index.md
  src/connections/destinations/catalog/voucherify-actions/index.md
  src/connections/index.md
  src/connections/sources/catalog/cloud-apps/friendbuy/index.md
  src/connections/sources/catalog/cloud-apps/listrak/index.md
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
  src/connections/spec/identify.md
  src/engage/quickstart.md
  src/unify/faqs.md
Labels: release

#5016 Add formatting requirement for Engage email templates
  src/engage/content/email/template.md
Labels: content-update

#5018 Updated Roles for managing Engage destinations
  src/segment-app/iam/roles.md
Labels: content-update

#5011 Unhide Listrak Source and add id
  src/connections/sources/catalog/cloud-apps/listrak/index.md
Labels: new-integration

#5019 Created note include and added to warehouses / faq
  src/_includes/content/warehouse-ip.html
  src/connections/storage/catalog/azuresqldw/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/connections/storage/catalog/db2/index.md
  src/connections/storage/catalog/postgres/index.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/connections/storage/warehouses/faq.md
Labels: content-update

#4968 Add info about supporting sources for Protocols
  src/protocols/index.md
Labels: KCS

#5021 Release 23.28.2
  .github/styles/Vocab/Docs/accept.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/warehouse-ip.html
  src/connections/destinations/catalog/bing-ads/index.md
  src/connections/destinations/catalog/insider-cloud-mode-actions/index.md
  src/connections/sources/catalog/cloud-apps/listrak/index.md
  src/connections/spec/best-practices-identify.md
  src/connections/storage/catalog/azuresqldw/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/connections/storage/catalog/db2/index.md
  src/connections/storage/catalog/postgres/index.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/connections/storage/warehouses/faq.md
  src/engage/content/email/template.md
  src/protocols/index.md
  src/segment-app/iam/roles.md
Labels: release

#5026 fix broken link in docs
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/airship-actions/index.md
Labels: fixed-content

#4989 Adding info about new http client
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: content-update

#5023 Improve Filter Example to Block Anonymous Traffic
  src/connections/destinations/destination-filters.md
Labels: KCS

#5022 Databricks and Postgres Reverse ETL setup guides
  src/_data/sidenav/main.yml
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
Labels: new-integration

#5031 include Function authorization example
  src/unify/profile-api.md
Labels: content-update

#5032 Fix link
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5030 Master back to develop after RETL Databricks and Postgres sources merge
  src/_data/sidenav/main.yml
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
Labels: back-end

#4900 Showing higher audience count in destination than the Segment UI.
  src/engage/faqs.md
Labels: KCS

#5028 Ran sass migrator to replace slashes
  src/_sass/objects/_flex.scss
  src/_sass/objects/_gutter.scss
  src/_sass/objects/_waffle.scss
Labels: back-end

#5035 add context about spaces in trait/property names
  src/connections/destinations/destination-filters.md
Labels: KCS

#5037 Release 23.29.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_sass/objects/_flex.scss
  src/_sass/objects/_gutter.scss
  src/_sass/objects/_waffle.scss
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-vwo-cloud/index.md
  src/connections/destinations/catalog/courier/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/alloy-automation/index.md
  src/connections/sources/catalog/cloud-apps/boda/index.md
  src/connections/sources/catalog/cloud-apps/cdpresolution/index.md
  src/engage/faqs.md
  src/unify/profile-api.md
Labels: release

#5036 Add note on hidden_entry columns
  src/unify/profiles-sync/tables.md
Labels: KCS

#5039 Update Wootric documentation index.md
  src/connections/sources/catalog/cloud-apps/wootric/index.md
Labels: content-update

#5044 [google-analytics] - add warning for google universal analytics deprecation and migration
  src/connections/destinations/catalog/google-analytics/index.md
Labels: content-update

#5034 When to call Page
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4897 Change query parameter to search
  src/guides/how-to-guides/collect-pageviews-serverside.md
Labels: KCS

#5040 Add MD5 hashing info
  src/connections/destinations/catalog/repeater/index.md
Labels: content-update, KCS

#4929 Add note on mapping limitation
  src/connections/destinations/catalog/eloqua/index.md
Labels: KCS

#5042 Script cleanup and documentation
  CONTRIBUTING.md
  Makefile
  branches.txt
  netlify.toml
  scripts/add_id.js
  scripts/atom.sh
  scripts/beta.js
  scripts/catalog_capi.js
  scripts/catalog_papi.js
  scripts/changelog.js
  scripts/engage-compare.js
  scripts/nav.js
  scripts/private-destination.js
  scripts/test.js
  scripts/update.js
  scripts/upload-docs
  scripts/utilities.js
Labels: back-end

#5047 Insert Functions behavior with Actions destinations
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#5043 Update Engage Events Source Docs [DOC-710]
  src/_data/sidenav/main.yml
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/engage/user-subscriptions/engage-source.md
Labels: content-update

#5048 Release 23.29.2
  CONTRIBUTING.md
  Makefile
  branches.txt
  netlify.toml
  scripts/add_id.js
  scripts/atom.sh
  scripts/beta.js
  scripts/catalog_capi.js
  scripts/catalog_papi.js
  scripts/changelog.js
  scripts/engage-compare.js
  scripts/nav.js
  scripts/private-destination.js
  scripts/test.js
  scripts/update.js
  scripts/upload-docs
  scripts/utilities.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/eloqua/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/repeater/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/customer-data-cloud/index.md
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/connections/sources/catalog/cloud-apps/src/index.md
  src/connections/sources/catalog/cloud-apps/wootric/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/engage/faqs.md
  src/engage/user-subscriptions/engage-source.md
  src/guides/how-to-guides/collect-pageviews-serverside.md
  src/unify/profiles-sync/tables.md
Labels: release

#4895 Add HTML Editor
  src/_data/sidenav/main.yml
  src/engage/campaigns/index.md
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/index.md
Labels: new-feature

#5058 Catalog Script Refactor
  Makefile
  netlify.toml
  scripts/catalog/addPrivateDestination.js
  scripts/catalog/catalog_papi.js
  scripts/catalog/index.js
  scripts/catalog/updateDestinations.js
  scripts/catalog/updatePrivateDestinations.js
  scripts/catalog/updateSources.js
  scripts/catalog/updateWarehouses.js
  scripts/catalog/utilities.js
  scripts/catalog/utilities_private_destinations.js
  scripts/catalog_papi.js
Labels: back-end

#5050 Clarify maximum batch size for Salesforce
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: KCS

#5064 DOTORG-872: Update Blackbaud Raiser's Edge NXT Docs
  src/connections/destinations/catalog/blackbaud-raisers-edge-nxt/index.md
Labels: content-update

#5063 Removed A.js classic and the upgrade to Ajs 2.0 doc [DOC-717]
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: content-update

#5067 Release 23.30.1
  Makefile
  scripts/catalog/addPrivateDestination.js
  scripts/catalog/catalog_papi.js
  scripts/catalog/index.js
  scripts/catalog/updateDestinations.js
  scripts/catalog/updatePrivateDestinations.js
  scripts/catalog/updateSources.js
  scripts/catalog/updateWarehouses.js
  scripts/catalog/utilities.js
  scripts/catalog/utilities_private_destinations.js
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/blackbaud-raisers-edge-nxt/index.md
  src/connections/sources/catalog/libraries/website/javascript/ajs-classic.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: release

#5062 Remove unsupported collection from Stripe Cloud app doc
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: content-update

#5060 Listrak Actions Destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-listrak/index.md
Labels: new-integration

#4496 Specify device-mode for UTM parameters feature
  src/connections/destinations/catalog/mixpanel/index.md
Labels: KCS

#5066 Update format for Get Profile Traits endpoint example
  src/unify/profile-api.md
Labels: KCS

#5013 Consent management private beta
  src/connections/delivery-overview.md
  src/privacy/configure-consent-management.md
  src/privacy/consent-management.md
  src/privacy/images/consent-overview.png
  src/privacy/reconcile-consent.md
Labels: new-feature

#5074 Master back into develop after consent management release
  src/connections/delivery-overview.md
  src/privacy/configure-consent-management.md
  src/privacy/consent-management.md
  src/privacy/images/consent-overview.png
  src/privacy/reconcile-consent.md
Labels: release

#5054 update conditions where GA4 silently drops payloads
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#5041 Add Client ID snippet to Gtag code example
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#5020 Add example for host config parameter
  src/connections/sources/catalog/libraries/server/net/index.md
Labels: KCS

#5070 add template for direct destination documentation
  src/partners/direct-destination.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/direct-destination.md
  templates/partners/source.md
Labels: content-update

#5073 Update slugifier for apostrophes, add ID to new source log
  scripts/catalog/utilities.js
Labels: back-end

#5071 Add ID to Blackbaud destination
  .github/styles/Vocab/Docs/accept.txt
  src/connections/destinations/catalog/blackbaud-raisers-edge-nxt/index.md
Labels: new-integration

#5053 Predictive Traits GA Updates
  src/_data/sidenav/main.yml
  src/engage/audiences/predictive-traits/index.md
  src/engage/audiences/predictive-traits/suggested-predictive-audiences.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
  src/engage/images/trait_builder.png
Labels: content-update

#5038 Include dot notation limitation
  src/connections/destinations/actions.md
Labels: content-update

#5069 Strat 2982
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: content-update

#5024 Add note on removing handler
  src/connections/functions/insert-functions.md
Labels: KCS

#4976 Add info about columns for external_id_mapping_updates table
  src/unify/profiles-sync/tables.md
Labels: KCS

#4919 Add blurb to GA4 Web docs
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5079 make catalog 20230727
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
Labels: back-end

#5080 Release 23.30.2
  .github/styles/Vocab/Docs/accept.txt
  scripts/catalog/utilities.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/blackbaud-raisers-edge-nxt/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/engage/audiences/predictive-traits/index.md
  src/engage/audiences/predictive-traits/suggested-predictive-audiences.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
  src/engage/images/trait_builder.png
  src/partners/direct-destination.md
  src/unify/profile-api.md
  src/unify/profiles-sync/tables.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/direct-destination.md
  templates/partners/source.md
Labels: release

#5081 Predictive Audiences Fix
  src/engage/audiences/predictive-traits/suggested-predictive-audiences.md
Labels: fixed-content

#5083 Fix broken "Plugin Architecture" link
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: KCS

#5088 Add public api token workspace permission detail
  src/api/public-api/index.md
Labels: content-update

#5092 Fixing link formatting on analytics-swift-firebase-plugin page
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/firebase-swift.md
Labels: fixed-content

#4941 SQL trait name clarification
  src/engage/audiences/sql-traits.md
Labels: KCS
