Repository segmentio/segment-docs, pull requests merged in 2023-06, with the labels that each got.

#4831 Add page for new direct destination
  Gemfile.lock
  src/_data/sidenav/partners.yml
  src/partners/direct-destination.md
Labels: content-update

#4755 Mapping configuration with Braze cohorts destination
  src/connections/destinations/catalog/actions-braze-cohorts/index.md
Labels: KCS

#4795 Update Engage Analytics Content
  src/engage/analytics/index.md
  src/engage/images/analytics_pickers.png
Labels: content-update

#4840 Update Navattic docs to exclude `anonymousId`
  src/connections/sources/catalog/cloud-apps/navattic/index.md
Labels: content-update

#4773 v2 sample form
  src/_includes/components/codepens/group-spec.html
  src/_includes/components/codepens/identify-spec.html
  src/_sass/components/_sample-form.scss
Labels: back-end

#4817 Add FAQ about 'New Event' button
  src/connections/destination-data-control.md
Labels: KCS

#4844 add id and unhide
  src/connections/sources/catalog/cloud-apps/navattic/index.md
Labels: new-integration

#4846 Release 23.23.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/codepens/group-spec.html
  src/_includes/components/codepens/identify-spec.html
  src/_sass/components/_sample-form.scss
  src/connections/destination-data-control.md
  src/connections/destinations/catalog/actions-upollo/index.md
  src/connections/sources/catalog/cloud-apps/freshchat-source/index.md
  src/connections/sources/catalog/cloud-apps/navattic/index.md
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
Labels: release

#4847 Update install instructions to new braze sdk
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
Labels: KCS

#4854 ios-faqs - AppClip
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
Labels: KCS

#4856 Multiple destination instance update
  src/connections/destinations/add-destination.md
Labels: KCS

#4848 Fix broken link to Braze Destination Plugin
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-middleware-react-native.md
Labels: KCS

#4860 Release 23.23.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/add-destination.md
  src/connections/destinations/catalog/encharge-actions/index.md
  src/connections/sources/catalog/cloud-apps/friendbuy-legacy/index.md
  src/connections/sources/catalog/cloud-apps/friendbuy/index.md
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-middleware-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/common.md
Labels: release

#4813 Broadcasts Public Beta [DOC-682]
  src/_data/sidenav/main.yml
  src/engage/campaigns/broadcasts.md
  src/engage/images/broadcasts.png
  src/guides/audiences-and-journeys.md
Labels: new-feature

#4863 Tiktok/actions tiktok offline conversions
  src/connections/destinations/catalog/actions-tiktok-offline-conversions/index.md
Labels: new-integration

#4864 Add verbiage about regional availablitly for Engage
  src/engage/onboarding.md
  src/engage/quickstart.md
Labels: content-update

#4752 Schema Unique Limits.md
  src/connections/schema-unique-limits.md
Labels: KCS

#4870 Release 23.24.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
  src/connections/destinations/catalog/actions-tiktok-offline-conversions/index.md
  src/connections/schema-unique-limits.md
  src/connections/sources/catalog/cloud-apps/demo-source/index.md
  src/engage/onboarding.md
  src/engage/quickstart.md
Labels: release

#4872 Fixed identify typo
  src/connections/spec/identify.md
Labels: KCS

#4876 Small typo fix
  src/connections/spec/native-mobile-spec.md
Labels: KCS

#4874 Add Edit Concurrency to Engage limits
  src/engage/product-limits.md
Labels: content-update

#4883 Warning about audience edit for anon users
  src/engage/audiences/index.md
Labels: KCS

#4871 Add Send to All content
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/journeys/step-types.md
  src/engage/user-subscriptions/index.md
Labels: new-feature

#4890 Release 23.24.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/voucherify-actions/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
  src/connections/spec/identify.md
  src/connections/spec/native-mobile-spec.md
  src/engage/audiences/index.md
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/journeys/step-types.md
  src/engage/product-limits.md
  src/engage/user-subscriptions/index.md
Labels: release

#4852 Added link to React Native Classic doc
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#4875 Directly mention lowercase schema names
  src/connections/storage/warehouses/faq.md
Labels: KCS

#4765 Add config table field for host option
  src/connections/sources/catalog/libraries/server/php/index.md
Labels: KCS

#4814 Add FAQ for data not reaching destination
  src/connections/destinations/actions.md
Labels: KCS

#4855 Appclip update
  src/connections/sources/catalog/libraries/mobile/apple/index.md
Labels: KCS

#4889 Fixed typo
  src/connections/spec/best-practices-identify.md
Labels: KCS

#4776 Update what-is-replay.md
  src/guides/what-is-replay.md
Labels: KCS

#4896 schema docs reorg
  Gemfile.lock
  src/_data/sidenav/main.yml
  src/connections/sources/schema/destination-data-control.md
  src/connections/sources/schema/images/asset_d3SRmkWy.gif
  src/connections/sources/schema/images/destination-control.png
  src/connections/sources/schema/images/disable-trait.gif
  src/connections/sources/schema/images/event-filters.png
  src/connections/sources/schema/images/schema_config_clear_schema.png
  src/connections/sources/schema/index.md
  src/connections/sources/schema/schema-unique-limits.md
Labels: content-update

#4822 Update Server link to GitHub repo - Totango
  src/connections/destinations/catalog/totango/index.md
Labels: KCS

#4913 Add Engage Analytics Machine Opens Section
  src/engage/analytics/index.md
Labels: content-update

#4908 Note about array of objects in the builder.md
  src/engage/audiences/index.md
Labels: KCS

#4918 Add FAQ on instanceId to Kotlin docs
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
Labels: KCS

#4915 fix folder structure so data loads correctly for source
  src/connections/sources/catalog/cloud-apps/mailmodo-source/index.md
  src/connections/sources/catalog/cloud-apps/mailmodo/index.md
Labels: content-update

#4886 Update account-management.md
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#4922 WhatsApp and MMS GA Updates
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/onboarding.md
Labels: content-update

#4917 Remove cross_domain_id reference
  src/unify/identity-resolution/externalids.md
Labels: content-update

#4909 Update Github repo link for VWO destination (web)
  src/connections/destinations/catalog/visual-website-optimizer/index.md
Labels: KCS

#4926 Release 23.25.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-clevertap/index.md
  src/connections/destinations/catalog/amazon-personalize/index.md
  src/connections/destinations/catalog/tiktok-offline-conversions/index.md
  src/connections/destinations/catalog/visual-website-optimizer/index.md
  src/connections/sources/catalog/cloud-apps/clevertap/index.md
  src/connections/sources/catalog/cloud-apps/hubspot-x/index.md
  src/connections/sources/catalog/cloud-apps/mailmodo-source/index.md
  src/connections/sources/catalog/cloud-apps/mailmodo/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
  src/engage/audiences/index.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/onboarding.md
  src/guides/usage-and-billing/account-management.md
  src/unify/identity-resolution/externalids.md
Labels: release

#4920 added schema doc redirect links
  src/connections/sources/schema/destination-data-control.md
  src/connections/sources/schema/index.md
  src/connections/sources/schema/schema-unique-limits.md
Labels: back-end

#4933 Add upgrade link to the React Native Side Menu
  src/_data/sidenav/strat.yml
Labels: KCS

#4925 Add info on track event for openURL method
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
Labels: KCS

#4937 Removed mobile menu
  src/_includes/sidebar/mobile-menu-side.html
  src/_layouts/integration.html
Labels: back-end

#4907 Correct anchor link for CloudFront
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4696 Analytics Node GA
  src/connections/sources/catalog/libraries/server/node/classic.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
Labels: new-integration

#4944 Master back into develop after one-off for Analytics Node GA
  src/connections/sources/catalog/libraries/server/node/classic.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
Labels: back-end

#4905 Removed trackDeepLinks from table
  src/connections/sources/catalog/libraries/mobile/apple/index.md
Labels: KCS

#4939 Update Schema Controls page
  src/connections/sources/schema/index.md
Labels: KCS

#4932 Punctuation
  src/connections/destinations/catalog/clevertap/index.md
Labels: content-update

#4930 Remove native script: Facebook Pixel
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#4950 Update braze swift docs
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/braze-swift.md
Labels: KCS

#4912 Update index.md
  src/connections/storage/catalog/redshift/index.md
Labels: KCS

#4947 WhatsApp example and callout
  src/engage/user-subscriptions/set-user-subscriptions.md
Labels: content-update

#4849 Add troubleshooting guide for Redshift rETL
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
Labels: KCS

#4951 Release 23.26.1
  Gemfile.lock
  netlify.toml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/_includes/sidebar/mobile-menu-side.html
  src/_layouts/integration.html
  src/connections/destinations/catalog/actions-hubspot-cloud/images/scopeApproval.png
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/castle/index.md
  src/connections/destinations/catalog/clevertap/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/destinations/catalog/google-analytics-4-cloud/index.md
  src/connections/destinations/catalog/iterable-actions/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
  src/connections/sources/catalog/cloud-apps/postgres/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/braze-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/schema/index.md
  src/connections/storage/catalog/redshift/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
Labels: release

#4952 add slug overrides to fix the integrations from being hidden
  src/_data/catalog/slugs.yml
Labels: back-end

#4954 Small spelling fix
  src/connections/destinations/catalog/clevertap/index.md
Labels: KCS

#4861 Added a portion to FAQ to include modifying context object
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#4891 Add section about status page
  src/help/index.md
Labels: KCS

#4877 Add info to Spec: Group page
  src/connections/spec/group.md
Labels: KCS

#4902 Update schema.md
  src/connections/storage/warehouses/schema.md
Labels: KCS

#4935 Update index.md
  src/connections/storage/catalog/data-lakes/index.md
Labels: KCS

#4934 Update index.md
  src/connections/storage/data-lakes/index.md
Labels: KCS

#4733 Update profile-api-limits.md with additional limitations
  src/unify/profile-api-limits.md
Labels: KCS

#4790 Specified that unique traits are in alphabetical order
  src/engage/audiences/computed-traits.md
Labels: KCS
