Repository segmentio/segment-docs, pull requests merged in 2023-08, with the labels that each got.

#5087 Add Missing Reverse ETL Link #4904
  src/connections/sources/index.md
Labels: fixed-content

#5098 update the BQ permission requirement section
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
Labels: content-update

#5107 Subscription Groups GA [DOC-718]
  src/_data/sidenav/main.yml
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/engage/images/subscription_groups.png
  src/engage/user-subscriptions/subscription-groups.md
Labels: new-feature

#5110 Remove Engage Section from Insider Destination
  src/connections/destinations/catalog/insider/index.md
Labels: content-update

#5108 Update timestamp note in spec common doc
  src/connections/spec/common.md
Labels: KCS

#5095 Add link to Kotlin plugin page
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture.md
Labels: KCS

#4927 Add profile_traits_updates table
  src/unify/files/ERD.png
  src/unify/profiles-sync/index.md
  src/unify/profiles-sync/tables.md
Labels: content-update

#4784 Add section covering tracking UTM parameters
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#4975 Specify source type for audit trail forwarding
  src/segment-app/iam/audit-trail.md
Labels: KCS

#5111 Update catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5113 Release 23.31.1
  CODEOWNERS
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/api/public-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/actions-optimizely-feature-experimentation-cloud/index.md
  src/connections/destinations/catalog/clevertap/index.md
  src/connections/destinations/catalog/insider/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/connections/sources/catalog/cloud-apps/listrak/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/firebase-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/index.md
  src/connections/spec/common.md
  src/engage/audiences/sql-traits.md
  src/engage/images/subscription_groups.png
  src/engage/user-subscriptions/subscription-groups.md
  src/segment-app/iam/audit-trail.md
  src/unify/profiles-sync/tables.md
Labels: release

#5115 table format fix
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
Labels: back-end

#5116 Master back to develop
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
Labels: back-end

#5096 Add Google doc link to Account ID section
  src/connections/destinations/catalog/personas-display-video-360/index.md
Labels: content-update

#5119 Update clevertap-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/clevertap-react-native.md
Labels: KCS

#5123 Add Suggested Predictive Audiences Link
  src/engage/audiences/predictive-traits/using-predictive-traits.md
Labels: content-update

#5122 Fixed missing image in A Basic Segment Installation
  src/getting-started/02-simple-install.md
Labels: fixed-content

#5124 Make Catalog 20230803
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5125 AppFit (Actions) Destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/appfit/index.md
Labels: new-integration

#5127 Release 23.31.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/appfit/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/sources/catalog/cloud-apps/zendesk/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/clevertap-react-native.md
  src/engage/audiences/predictive-traits/using-predictive-traits.md
  src/getting-started/02-simple-install.md
Labels: release

#5129 Fix plan note bug
  src/_data/products.yml
  src/segment-app/iam/audit-trail.md
Labels: fixed-site

#5132 Alphabetically reorder swift destination plugins
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
Labels: KCS

#5114 Add profile_traits_updates table
  src/unify/files/ERD.png
  src/unify/profiles-sync/index.md
  src/unify/profiles-sync/tables.md
Labels: content-update

#5135 Master back to Develop after Profiles Sync deploy
  src/unify/files/ERD.png
  src/unify/profiles-sync/index.md
  src/unify/profiles-sync/tables.md
Labels: back-end

#5130 Added plan-grid note to frontmatter
  src/connections/destinations/actions.md
  src/connections/storage/data-lakes/comparison.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/connections/storage/data-lakes/index.md
  src/connections/storage/data-lakes/lake-formation.md
  src/connections/storage/data-lakes/sync-history.md
  src/connections/storage/data-lakes/sync-reports.md
  src/connections/storage/warehouses/index.md
  src/guides/what-is-replay.md
  src/privacy/data-controls.md
  src/privacy/portal.md
  src/protocols/apis-and-extensions/anomaly_detection.md
  src/protocols/apis-and-extensions/index.md
  src/protocols/enforce/forward-blocked-events.md
  src/protocols/enforce/schema-configuration.md
  src/protocols/faq.md
  src/protocols/tracking-plan/libraries.md
  src/protocols/transform/index.md
  src/protocols/validate/connect-sources.md
  src/protocols/validate/forward-violations.md
  src/protocols/validate/review-violations.md
  src/segment-app/iam/concepts.md
  src/segment-app/iam/index.md
  src/segment-app/iam/labels.md
  src/segment-app/iam/membership.md
  src/segment-app/iam/mfa.md
  src/segment-app/iam/scim.md
  src/segment-app/iam/sso.md
Labels: fixed-site

#5136 add note about Event Tester
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#4612 Update Marketo source doc FAQs
  src/connections/sources/catalog/cloud-apps/marketo/index.md
Labels: content-update, KCS

#5146 Add Property to Stripe Source Table
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: content-update

#5142 Add Facebook Insights Breakdown Table
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
Labels: content-update

#5148 Release 23.32.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/listrak/index.md
  src/connections/sources/catalog/cloud-apps/marketo/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/storage/data-lakes/comparison.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/connections/storage/data-lakes/index.md
  src/connections/storage/data-lakes/lake-formation.md
  src/connections/storage/data-lakes/sync-history.md
  src/connections/storage/data-lakes/sync-reports.md
  src/connections/storage/warehouses/index.md
  src/guides/what-is-replay.md
  src/privacy/data-controls.md
  src/privacy/portal.md
  src/protocols/apis-and-extensions/anomaly_detection.md
  src/protocols/apis-and-extensions/index.md
  src/protocols/enforce/forward-blocked-events.md
  src/protocols/enforce/schema-configuration.md
  src/protocols/faq.md
  src/protocols/tracking-plan/libraries.md
  src/protocols/transform/index.md
  src/protocols/validate/connect-sources.md
  src/protocols/validate/forward-violations.md
  src/protocols/validate/review-violations.md
  src/segment-app/iam/audit-trail.md
  src/segment-app/iam/concepts.md
  src/segment-app/iam/index.md
  src/segment-app/iam/labels.md
  src/segment-app/iam/membership.md
  src/segment-app/iam/mfa.md
  src/segment-app/iam/scim.md
  src/segment-app/iam/sso.md
Labels: release

#5137 [STRATCONN-2814]: Fix role policies for AWS destinations
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
  src/connections/destinations/catalog/amazon-kinesis/index.md
  src/connections/destinations/catalog/amazon-lambda/index.md
  src/connections/destinations/catalog/amazon-personalize/index.md
Labels: content-update

#5155 Fix link for Kotlin Optimizely
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
Labels: KCS

#5152 Add region endpoint FAQ.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
Labels: KCS

#4734 Add section for user data field formatting
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: KCS

#5158 Clarify compute credit limit
  src/engage/product-limits.md
Labels: content-update

#5151 Add Regional Data Hosting note
  src/connections/destinations/catalog/actions-intercom-web/index.md
Labels: content-update

#5159 Converted Hubspot source sync collection from`ticket_status` to `deals`
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: fixed-content

#5145 Added Revx Cloud Documentation
  src/connections/destinations/catalog/actions-revx/index.md
Labels: new-integration

#5005 Add Userpilot (Actions) Destination Docs
  src/connections/destinations/catalog/actions-userpilot-cloud/index.md
  src/connections/destinations/catalog/actions-userpilot-web/index.md
Labels: new-integration

#5156 Astrolabe Direct Destination Documentation
  src/connections/destinations/catalog/astrolabe/index.md
Labels: new-integration

#5153 added humanic.ai doc
  src/connections/destinations/catalog/humanic-ai/index.md
Labels: new-integration

#5166 Update Facebook Ads Action Stats
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
Labels: content-update

#5169 Release 23.32.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/actions-revx/index.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/actions-userpilot-cloud/index.md
  src/connections/destinations/catalog/actions-userpilot-web/index.md
  src/connections/destinations/catalog/amazon-kinesis-firehose/index.md
  src/connections/destinations/catalog/amazon-kinesis/index.md
  src/connections/destinations/catalog/amazon-lambda/index.md
  src/connections/destinations/catalog/amazon-personalize/index.md
  src/connections/destinations/catalog/humanic-ai/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/storage/warehouses/faq.md
  src/engage/product-limits.md
Labels: release

#5173 Invalid Token Error Solution
  src/connections/destinations/catalog/actions-snap-conversions/index.md
Labels: KCS

#5178 remove underscores
  src/connections/destinations/catalog/humanic-ai/index.md
Labels: fixed-content

#5072 Update FAQ on sending calls for updates
  src/engage/audiences/sql-traits.md
Labels: KCS

#5109 Add warning for partner audience type
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: KCS

#5172 Add Astrolabe Destination Docs
  src/connections/destinations/catalog/astrolabe/index.md
Labels: new-integration

#5183 Fix Destination template header
  templates/partners/direct-destination.md
Labels: fixed-content

#5185 Rename Userpilot Directories
  src/connections/destinations/catalog/userpilot-cloud-actions/index.md
  src/connections/destinations/catalog/userpilot-web-actions/index.md
Labels: fixed-site

#5174 Amend public docs for Critical Plugin
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update, KCS

#5180 Add info on device.token
  src/connections/destinations/catalog/customer-io/index.md
Labels: content-update, KCS

#5181 Add context to Functions Node.js runtime note
  src/_includes/content/functions/runtime.md
Labels: content-update

#5133 Update test-connections.md
  src/connections/test-connections.md
Labels: KCS

#5186 initial documentation for LiveRamp
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
Labels: new-integration, hidden

#5189 fix algolia docs
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_api_keys.png
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_app_id_dropdown.png
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_dashboard_settings.png
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_settings_menu.png
  src/connections/destinations/catalog/actions-algolia-insights/images/destination_settings.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mapping_tab.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mapping_tab_edit.png
  src/connections/destinations/catalog/actions-algolia-insights/images/rename_events.png
  src/connections/destinations/catalog/actions-algolia-insights/index.md
  src/connections/destinations/catalog/algolia-insights-actions/index.md
Labels: fixed-content

#5193 Remove Extra Header from Facebook Pixel Destination
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: fixed-content

#5188 Add info about CSV Uploader and MTUs count
  src/engage/profiles/csv-upload.md
Labels: content-update

#5163 Add note about autocomplete value in audience builder dropdown
  src/engage/audiences/index.md
Labels: KCS

#5190 add info about Actions destinations
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#5194 Make Catalog 20230815
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
Labels: back-end

#5195 Release 23.33.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_api_keys.png
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_app_id_dropdown.png
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_dashboard_settings.png
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_settings_menu.png
  src/connections/destinations/catalog/actions-algolia-insights/images/destination_settings.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mapping_tab.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mapping_tab_edit.png
  src/connections/destinations/catalog/actions-algolia-insights/images/rename_events.png
  src/connections/destinations/catalog/actions-algolia-insights/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/algolia-insights-actions/index.md
  src/connections/destinations/catalog/customer-io/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/destinations/catalog/humanic-ai/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/test-connections.md
  src/engage/audiences/index.md
  src/engage/audiences/sql-traits.md
  src/engage/profiles/csv-upload.md
  templates/partners/direct-destination.md
Labels: release

#5128 Tiktok Pixel Destination
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-saleswings/index.md
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
Labels: new-integration

#5191 DevRev (Actions) docs
  src/connections/destinations/catalog/devrev/index.md
Labels: new-integration

#5201 Update roles.md to include reverse etl info
  src/segment-app/iam/roles.md
Labels: KCS

#4701 Add information that editing is locked until resume process completes
  src/engage/journeys/build-journey.md
Labels: KCS

#5199 update regional segment intro
  src/guides/regional-segment.md
Labels: content-update

#5198 Fix broken Swift and Kotlin plugin links
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: fixed-content

#5205 Adding missing directory to image link on Testing Connections page
  src/connections/test-connections.md
Labels: fixed-content

#5211 Grammar fix
  src/connections/destinations/catalog/hubspot/index.md
Labels: KCS

#5208 Update index.md - added information about Real-time computations
  src/engage/audiences/index.md
Labels: content-update

#5207 Update warehouses.md - added section about the users table
  src/engage/warehouses.md
Labels: KCS

#5213 hide original canny docs
  src/connections/destinations/catalog/actions-canny/index.md
  src/connections/destinations/catalog/canny/index.md
Labels: content-update

#5202 Update privacy portal page
  src/connections/sources/index.md
  src/privacy/images/privacy-add-new-matcher.gif
  src/privacy/images/privacy-edit-matcher.png
  src/privacy/portal.md
Labels: KCS

#5204 add Insert Function
  src/guides/filtering-data.md
Labels: KCS

#5200 Engage context about filtered events.md
  src/connections/delivery-overview.md
Labels: content-update, KCS

#5214 Make Catalog 20230817
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5215 Release 23.33.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-canny/index.md
  src/connections/destinations/catalog/actions-saleswings/index.md
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
  src/connections/destinations/catalog/canny/index.md
  src/connections/destinations/catalog/devrev/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/sources/index.md
  src/connections/test-connections.md
  src/engage/audiences/index.md
  src/engage/journeys/build-journey.md
  src/engage/warehouses.md
  src/guides/filtering-data.md
  src/guides/regional-segment.md
  src/privacy/images/privacy-add-new-matcher.gif
  src/privacy/images/privacy-edit-matcher.png
  src/privacy/portal.md
  src/segment-app/iam/roles.md
Labels: release

#5210 Updating Clevertap connection modes table
  src/_data/catalog/overrides.yml
Labels: fixed-content

#5015 Source template update
  templates/partners/source.md
Labels: fixed-content

#5217 unhide tiktok docs
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
Labels: content-update

#5222 Change 1 line from template
  templates/partners/source.md
Labels: content-update

#5218 Update HTTP API Rate Limits
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: fixed-content

#5212 add explanation for error notification
  src/guides/usage-and-billing/account-management.md
Labels: content-update, KCS

#4708 Updated typo
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#4660 Add section : Replays & Destination Filters
  src/guides/what-is-replay.md
Labels: content-update, KCS

#4957 Remove native gtag.js script: GA4 Web
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5220 Add info on new libraries
  src/partners/conceptual-model.md
Labels: KCS

#4659 Instructions to download mappings via Public API
  src/connections/destinations/catalog/adobe-analytics/settings.md
Labels: KCS

#5182 Braze React Plugin Cleanup
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
Labels: content-update

#5221 Add array info for CSharp
  src/connections/sources/catalog/libraries/server/csharp/index.md
Labels: KCS

#5230 make catalog 20230822
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5231 Release 23.34.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
  src/connections/destinations/catalog/adobe-analytics/settings.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/sources/catalog/cloud-apps/freshchat-source/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/guides/usage-and-billing/account-management.md
  src/guides/what-is-replay.md
  src/partners/conceptual-model.md
  src/privacy/portal.md
  templates/partners/source.md
Labels: release

#5209 Add info about comparing GA4 vs. UA metrics
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5225 Add paragraph about Delivery Overview only available server-side
  src/connections/delivery-overview.md
Labels: KCS

#5224 Update insert-functions.md
  src/connections/functions/insert-functions.md
Labels: content-update

#4644 Add default mappings caveat (Amplitude Actions)
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#5242 Update Engage Onboarding IP Warmup Instructions
  src/engage/onboarding.md
Labels: content-update

#5243 Add Screeb (Actions) Docs
  src/connections/destinations/catalog/actions-screeb/index.md
Labels: new-integration

#5227 Add difference between GA4 Cloud and GA4 Web
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update, KCS

#5093 Add info block to toggle Destination Filters on
  src/connections/destinations/destination-filters.md
Labels: KCS

#5245 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5246 Release 23.34.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-rehook/index.md
  src/connections/destinations/catalog/actions-screeb/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/freshchat/index.md
  src/engage/onboarding.md
Labels: release

#5240 Add mailchimp marketing dependency
  src/_includes/content/functions/runtime.md
Labels: content-update

#5203 Add faq that insert function can only be connected to one destination
  src/connections/functions/insert-functions.md
Labels: KCS

#5223 Add faq that retries could account for events not filtered by Destination Filter
  src/connections/destinations/destination-filters.md
Labels: content-update, KCS

#5253 Fix sentence in Analytics.js doc
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4779 Warning about Behavior Events (Legacy)
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: KCS

#5149 *updated* RETRY Mixpanel legacy common error
  src/connections/destinations/catalog/mixpanel/index.md
Labels: KCS

#4723 User Token is not taken for validation as Email is not in valid format.
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: KCS

#5247 WebEngage Connection Mode override
  src/_data/catalog/overrides.yml
Labels: fixed-content

#5250 Add tips regrading GTM 404 error
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#5192 feat: add branch metrics to react native dest. plugin catalog
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/branch-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/index.md
Labels: new-integration

#5078 Update doc: iOS does not support destination middleware
  src/connections/sources/catalog/libraries/mobile/ios/middleware.md
Labels: KCS

#5252 Add link to plugin Architecture docs
  src/_data/sidenav/strat.yml
Labels: KCS

#5234 Information about the available actions of SFMC destination.
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
Labels: content-update

#5264 Catalog - 8.29.23
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
Labels: back-end

#5265 Release 23.35.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/overrides.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/functions/runtime.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/libraries/mobile/ios/middleware.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/branch-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: release

#5263 Move note about traits to first sentence of the section
  src/guides/filtering-data.md
Labels: KCS

#5241 Add Trait Activation docs
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/overview.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
Labels: new-feature

#5271 Trait Activation support note
  src/engage/trait-activation/trait-activation-setup.md
Labels: content-update

#5251 Elastic path/source
  src/connections/sources/catalog/cloud-apps/elastic-path/index.md
Labels: new-integration

#5266 Add slug override for Iterable (Actions) Destination
  src/_data/catalog/slugs.yml
Labels: fixed-site

#5269 Remove mention of old mobile libs as they do not support plugin architecture
  src/partners/conceptual-model.md
Labels: KCS

#5273 Adding info about track calls
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
Labels: KCS

#4825 Update cookie-validity-update.md A.js Cookie methods
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: KCS

#5279 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5280 Release 23.35.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/ip-allowlist.md
  src/connections/destinations/index.md
  src/connections/functions/destination-functions.md
  src/connections/sources/catalog/cloud-apps/elastic-path/index.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
  src/guides/filtering-data.md
  src/partners/conceptual-model.md
Labels: release

#5286 Add note to configure UI or code option not both
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#5248 Add sentence about clearing events from Schema
  src/connections/sources/schema/schema-unique-limits.md
Labels: KCS
