Repository segmentio/segment-docs, pull requests merged in 2023-01, with the labels that each got.

#3955 Object API regional endpoint
  src/connections/sources/catalog/libraries/server/object-api/index.md
Labels: content-update

#3984 Fix Ripe Destination External Link [DOC-634]
  src/connections/destinations/catalog/actions-ripe/index.md
Labels: fixed-content

#3968 Add FAQ to HubSpot destination doc
  src/connections/destinations/catalog/hubspot/index.md
Labels: KCS

#3978 Add example to only send events with userId
  src/connections/destinations/destination-filters.md
Labels: KCS

#3976 Update Klaviyo docs
  src/connections/destinations/catalog/klaviyo/index.md
Labels: content-update

#3985 Catalog Update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/ortto/index.md
  src/connections/destinations/catalog/ripe/index.md
  src/connections/sources/catalog/cloud-apps/thomas-test-source/index.md
Labels: back-end

#3987 Release 23.1.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-pipedrive/index.md
  src/connections/destinations/catalog/actions-ripe/index.md
  src/connections/destinations/catalog/autopilotapp/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/ortto/index.md
  src/connections/destinations/catalog/ripe/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/thomas-test-source/index.md
  src/connections/sources/catalog/libraries/server/object-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/partners/streams.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#3979 Site accessibility updates
  src/_layouts/default.html
  src/_sass/components/_markdown.scss
  src/_sass/components/_menu-item.scss
Labels: fixed-site

#3997 fixed RETL icon fill
  src/_includes/icons/reverse-etl.svg
Labels: back-end

#3995 Clarify 24h deduplication window on handling duplicate data page
  src/guides/duplicate-data.md
Labels: fixed-content

#3996 Fix Public API IA
  src/_data/sidenav/main.yml
  src/api/public-api/fql.md
  src/api/public-api/index.md
Labels: back-end

#3994 PROT-4465: remove matchers and add new default matchers
  src/privacy/portal.md
Labels: content-update

#4000 Update Journeys Exit Settings Information
  src/engage/journeys/build-journey.md
  src/engage/journeys/step-types.md
Labels: content-update

#3862 Add Actable Predictive Actions Destinations
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actable-predictive/index.md
Labels: new-integration

#4001 Catalog update - Jan 05
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#4002 Release 23.1.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/icons/reverse-etl.svg
  src/_layouts/default.html
  src/_sass/components/_markdown.scss
  src/_sass/components/_menu-item.scss
  src/api/public-api/fql.md
  src/api/public-api/index.md
  src/connections/destinations/catalog/actable-predictive/index.md
  src/engage/journeys/build-journey.md
  src/engage/journeys/step-types.md
  src/guides/duplicate-data.md
  src/privacy/portal.md
Labels: release

#4006 Update Facebook Conversions API link
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
Labels: content-update

#4011 Update Intercom Classic Destination #3977
  src/connections/destinations/catalog/intercom/index.md
Labels: fixed-content

#4008 Add information about Event Property Limits on Computed Traits
  src/engage/audiences/computed-traits.md
  src/engage/product-limits.md
Labels: content-update

#4014 Add docs for adding a plugin to a destination plugin
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update

#4009 Add clarification about where dc_rdid is used
  src/connections/destinations/catalog/doubleclick-floodlight/index.md
Labels: content-update

#4022 Update Journeys Exit Settings
  src/engage/journeys/build-journey.md
Labels: fixed-content

#4015 Describe why `root` violations may appear in Protocols
  src/protocols/faq.md
Labels: KCS

#4023 catalog update
  Gemfile.lock
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/clevertap-actions/index.md
Labels: back-end

#4029 Transformations clarification
  src/protocols/transform/index.md
Labels: content-update

#4032 Added details for EU workspaces
  src/connections/sources/catalog/libraries/mobile/amp/index.md
Labels: content-update, KCS

#4035 Fix typo
  src/connections/sources/index.md
Labels: content-update

#4039 Add Braze Swift Plugin to our docs
  src/connections/sources/catalog/libraries/mobile/swift-ios/index.md
Labels: KCS

#4041 20230112 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/paytronix/index.md
  src/engage/product-limits.md
Labels: back-end

#4048 Update Amplitude Classic Destination [DOC-629]
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/amplitude/index.md
Labels: content-update

#4025 Add section highlighting User Data parameter mappings to Facebook Conversions API Destination
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: KCS

#4055 Update vale rules
  .github/styles/segment/exclamation.yml
  .github/styles/segment/links copy.yml
  .github/styles/segment/links.yml
  .github/styles/segment/relative-url.yml
Labels: back-end

#4056 added react native quick link
  src/protocols/apis-and-extensions/typewriter.md
Labels: content-update

#4059 Add Audiences and Journeys Guide
  src/_data/sidenav/main.yml
  src/guides/audiences-and-journeys.md
  src/guides/images/digital_marketing_lifecyle.png
Labels: content-update

#4050 Add platform code for setting writekey
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#3921 Add section for api token security [SECFEAT-1021]
  src/api/public-api/index.md
Labels: new-feature

#4033 Update Violation Forwarding Information to include Actions Destinations
  src/protocols/faq.md
Labels: KCS

#4064 catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/thomas-gilbert-test/index.md
  src/connections/sources/catalog/cloud-apps/thomas-source-test-portal/index.md
Labels: back-end

#4045 Updating to exclude authenticating via email/token because it doesn't work
  src/connections/destinations/catalog/zendesk/index.md
Labels: content-update

#4058 Add links to Braze Swift and Kotlin plugin repositories
  src/connections/destinations/catalog/braze/index.md
Labels: KCS

#4036 Update Public API docs to highlight eligibility for PAPI access
  src/_data/products.yml
  src/api/public-api/index.md
Labels: KCS

#4068 Added Proxy Server Side Note
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4018 What to do when credentials have updated/changed
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: KCS

#4066 Add a note that some Actions-based destinations do not support IE11
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
Labels: KCS

#4047 Add link to GitHub repository
  src/connections/destinations/catalog/matomo/index.md
Labels: KCS

#4027 Add clarity to source URL vs Source ID
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#4034 Add information about deleting/changing ExternalID's
  src/profiles/faqs.md
Labels: KCS

#4082 Add device id config option for RN.
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#4077 Update language
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: back-end

#4072 Mention that the A.js snippet has version history available on GitHub
  src/getting-started/02-simple-install.md
Labels: KCS

#4067 Mention that an A.js snippet must be added to each subdomain
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#4053 Add guidance around the number of sources a user should create
  src/connections/sources/index.md
Labels: KCS

#4044 Update FAQ section with solution for data not sending to Google
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#4019 Update on choosing the Intercom workspace
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
Labels: KCS

#4031 add details about data type mismatch
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/schema.md
Labels: KCS

#4080 Add Amplitude Session ID Info #3972
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: content-update

#4078 Add info note specifying supported data types for mapping operators
  src/connections/destinations/actions.md
Labels: KCS

#4085 Release 23.3.3
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/_data/sidenav/strat.yml
  src/api/public-api/index.md
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-commandbar/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/commandbar/index.md
  src/connections/destinations/catalog/matomo/index.md
  src/connections/destinations/catalog/youbora/index.md
  src/connections/destinations/catalog/zendesk/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/cloud-apps/test-jina/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/server/node/classic.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
  src/connections/sources/catalog/libraries/server/node/quickstart.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
  src/connections/sources/index.md
  src/connections/storage/warehouses/faq.md
  src/connections/storage/warehouses/schema.md
  src/getting-started/02-simple-install.md
  src/profiles/faqs.md
Labels: release

#4094 Fix Broken Merge Protection Image
  src/engage/faqs.md
  src/engage/images/merge_protection.png
Labels: fixed-content

#4090 Simple update to anonymousId retrieval
  src/connections/sources/catalog/libraries/website/javascript/identity.md
Labels: KCS

#4097 update api links
  src/partners/enable-with-segment.md
Labels: content-update

#4095 Add info about clearing schema properties
  src/connections/schema-unique-limits.md
Labels: KCS

#4109 repo sync
  templates/sources.example.yml
Labels: autoupdate, automated-reposync-pr

#4112 Fixed typo
  src/getting-started/implementation-guide.md
Labels: KCS

#4116 Fix link to Reset section
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: fixed-content

#3986 Ironclad Documentation
  .yarn/cache/loader-utils-npm-1.4.2-b4537b2f88-eb6fb622ef.zip
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-ironclad/index.md
Labels: new-integration

#4101 Update Source function FAQs Retry Policy
  src/connections/functions/source-functions.md
Labels: KCS

#4087 Add info section about client-side Klaviyo events
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#4118 Ripe Cloud Mode deploy
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
Labels: new-feature

#4102 Update AJS FAQs to include adding new context fields
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#4093 Typo fix
  src/connections/destinations/catalog/google-analytics/index.md
Labels: KCS

#4086 Describe latency with data appearing in Google Analytics
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#4114 Trustpilot moving out of beta
  src/connections/destinations/catalog/trustpilot/index.md
Labels: new-integration

#4119 Catalog update
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/attacker/index.md
  src/connections/sources/catalog/cloud-apps/test/index.md
  src/connections/sources/catalog/cloud-apps/test_source_1/index.md
  src/connections/sources/catalog/cloud-apps/xyz1/index.md
  src/connections/sources/catalog/cloud-apps/zaza/index.md
Labels: back-end

#4120 Release 23.4.1
  .yarn/cache/loader-utils-npm-1.4.2-b4537b2f88-eb6fb622ef.zip
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-ironclad/index.md
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/trustpilot/index.md
  src/connections/functions/source-functions.md
  src/connections/schema-unique-limits.md
  src/connections/sources/catalog/cloud-apps/attacker/index.md
  src/connections/sources/catalog/cloud-apps/test/index.md
  src/connections/sources/catalog/cloud-apps/test_source_1/index.md
  src/connections/sources/catalog/cloud-apps/xyz1/index.md
  src/connections/sources/catalog/cloud-apps/zaza/index.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/storage/catalog/postgres/index.md
  src/connections/storage/catalog/redshift/images/redshift05.png
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/connections/storage/warehouses/faq.md
  src/engage/faqs.md
  src/engage/images/merge_protection.png
  src/getting-started/02-simple-install.md
  src/getting-started/implementation-guide.md
  src/partners/enable-with-segment.md
  templates/sources.example.yml
Labels: release

#4122 YouTube Plugin updates
  src/connections/sources/catalog/libraries/website/plugins/youtube/index.md
Labels: content-update

#4098 sanitize integration metadata
  scripts/catalog_papi.js
  src/_data/catalog/destinations.yml
Labels: back-end

#4129 repo sync
  src/_data/catalog/destinations_capi.yml
  src/_data/catalog/sources_capi.yml
Labels: autoupdate, automated-reposync-pr

#4125 Adding 404 error info
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
Labels: KCS

#4110 Add links to Full Segment Implementation
  src/getting-started/04-full-install.md
Labels: KCS

#4061 Update FAQ for custom objects clarification over associations
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: KCS

#4132 Catalog update Jan 26
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/cloud-apps/moengage-source/index.md
  src/connections/sources/catalog/cloud-apps/test_c2/index.md
Labels: back-end

#4133 Release 23.4.2
  scripts/catalog_papi.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_capi.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/sources_capi.yml
  src/connections/destinations/catalog/actions-fullstory-cloud/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/sources/catalog/cloud-apps/moengage-source/index.md
  src/connections/sources/catalog/cloud-apps/test_c2/index.md
  src/connections/sources/catalog/libraries/website/plugins/youtube/index.md
  src/connections/sources/index.md
  src/getting-started/04-full-install.md
Labels: release

#4143 Add new paytronix docs
  src/connections/sources/catalog/cloud-apps/paytronix/index.md
Labels: new-integration

#4142 Fix broken link
  src/connections/sources/catalog/cloud-apps/moengage-source/index.md
Labels: fixed-site

#4147 Update broken link to Kissmetrics
  src/connections/destinations/catalog/kissmetrics/index.md
Labels: content-update

#4140 Add files for custom proxy with AJS 2.0
  src/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2.md
Labels: KCS

#4149 Clarify Source URL vs Source ID [#4027]
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: content-update

#4151 Fix Broken Data Lakes Comments #4146
  src/connections/storage/data-lakes/lake-formation.md
  src/connections/storage/data-lakes/sync-reports.md
Labels: fixed-content

#4089 DOC 641 stripe update
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: content-update

#4154 Format kilobyte abbreviation and other edits (DOC-642)
  src/_includes/content/tracking-api-limit.md
  src/connections/destinations/catalog/preact/index.md
  src/connections/sources/catalog/libraries/mobile/android/android-faqs.md
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
  src/connections/sources/catalog/libraries/mobile/react-native/react-faqs.md
  src/connections/sources/catalog/libraries/server/object-api/index.md
  src/connections/sources/catalog/libraries/server/object-bulk-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/audiences/sql-traits.md
  src/guides/filtering-data.md
Labels: content-update

#4150 Rename pilgrim to movement
  src/connections/sources/catalog/cloud-apps/foursquare-pilgrim/index.md
Labels: content-update

#4145 Add partner docs templates to non-build folder
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/source.md
Labels: back-end

#4144 Update Application Crashed event information
  src/connections/spec/mobile.md
Labels: KCS

#4139 Fix incomplete definition in the Glossary
  src/_data/glossary.yml
Labels: content-update

#4134 Add note highlighting at least one mapping must be configured and enabled in Actions destination
  src/connections/destinations/actions.md
Labels: KCS

#4153 SalesWings Actions docs deploy
  .yarn/cache/loader-utils-npm-1.4.2-b4537b2f88-eb6fb622ef.zip
  src/_data/catalog/destinations_private.yml
  src/connections/destinations/catalog/actions-saleswings/index.md
Labels: new-integration

#4161 Catalog update 01-31-2023
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/wisepops/index.md
  src/connections/sources/catalog/cloud-apps/foursquare-movement/index.md
  src/connections/sources/catalog/cloud-apps/pinwheel/index.md
  src/connections/sources/catalog/cloud-apps/stitch/index.md
Labels: back-end

#4099 Update information that Engage generated source cannot be deleted
  src/profiles/debugger.md
Labels: KCS

#4160 Analytics.js only sets first-party cookies
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/persistence.md
Labels: content-update
