Repository segmentio/segment-docs, pull requests merged in 2024-10, with the labels that each got.

#7042 Add Web Setup Guide to Auto-Instrumentation Docs
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
Labels: content-update

#7099 Update troubleshooting.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#6476 Update to reflect support of email as identifier
  src/connections/destinations/catalog/actions-braze-cloud/index.md
Labels: KCS

#7098 Update Contentstack link
  src/connections/destinations/catalog/actions-contentstack/index.md
  src/connections/destinations/catalog/contentstack-web/index.md
Labels: content-update

#7100 PrivateLink P&P
  src/connections/aws-privatelink.md
Labels: content-update

#7096 Update linked-audiences for list actions destinations
  src/engage/audiences/linked-audiences.md
Labels: KCS

#7103 Release 24.40.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
  src/connections/aws-privatelink.md
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-contentstack/index.md
  src/connections/destinations/catalog/actions-customerio/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/contentstack-web/index.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/images/mapping-alerting.jpeg
  src/connections/reverse-etl/manage-retl.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/audiences/linked-audiences.md
  src/protocols/faq.md
Labels: release

#7093 Add note to restore API host
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#7107 Add OneTrust EU workspace info and JSON
  src/connections/sources/catalog/cloud-apps/onetrust/OneTrust-Segment-Track-API-Integration-EU.json
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
Labels: content-update

#7106 Adding Information on Segment Snippet Version Updates
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: KCS

#7108 Tweak EU endpoint for partner sources
  src/partners/sources.md
Labels: content-update

#6965 Add Guidance on Editing Journey Settings
  src/engage/journeys/journeys-edits.md
Labels: content-update, KCS

#7110 Add Note about GA4 User-Provided Data Collection
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update, KCS

#7111 Catalog Update 3 October 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7059 Add note about Identify events generated by the CSV uploader
  src/engage/profiles/csv-upload.md
Labels: content-update, KCS

#7095 Update Braze Actions Destination to reflect handling of JWT
  src/connections/destinations/catalog/actions-braze-web/index.md
Labels: KCS

#7112 Release 24.40.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/accoil-analytics/index.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
  src/connections/sources/catalog/cloud-apps/onetrust/OneTrust-Segment-Track-API-Integration-EU.json
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/engage/audiences/linked-audiences-limits.md
  src/engage/journeys/journeys-edits.md
  src/engage/profiles/csv-upload.md
  src/partners/sources.md
Labels: release

#7117 LA limits fix
  src/engage/audiences/linked-audiences-limits.md
Labels: fixed-content

#7116 Unhide One Creation Docs
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
Labels: back-end

#7118 Master back to develop after hot fix
  src/engage/audiences/linked-audiences-limits.md
Labels: back-end

#7115 Update account-management.md
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#7125 Update Ninetailed Name
  src/connections/destinations/catalog/ninetailed/index.md
Labels: content-update

#7127 Unhide Use Cases Docs
  src/_data/sidenav/main.yml
  src/getting-started/use-cases/guide.md
  src/getting-started/use-cases/index.md
  src/getting-started/use-cases/reference.md
  src/getting-started/use-cases/setup.md
Labels: back-end, content-update

#7123 Add Custom Domain FAQ
  src/connections/sources/custom-domain.md
Labels: content-update, KCS

#7124 Added FAQ and troubleshooting section
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#7129 Release 24.41.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/actions-accoil-analytics/index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/ninetailed/index.md
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
  src/connections/sources/custom-domain.md
  src/getting-started/use-cases/guide.md
  src/getting-started/use-cases/index.md
  src/getting-started/use-cases/reference.md
  src/getting-started/use-cases/setup.md
  src/guides/usage-and-billing/account-management.md
Labels: release

#7114 Best Practices for Custom Domains
  src/connections/sources/custom-domain.md
Labels: KCS

#7122 Accoil updates
  src/connections/destinations/catalog/actions-accoil-analytics/index.md
Labels: content-update

#7133 Update the support team that Unified Profiles customers should contact
  src/unified-profiles/unified-profiles-workspace.md
Labels: content-update

#7131 Fixes
  src/_includes/content/warehouse-ip.html
Labels: fixed-content

#7135 Updated Linked Audiences Dynamic Reference/Entity Conditions
  src/engage/audiences/linked-audiences.md
Labels: content-update

#7101 Braze Cloud Mode (Actions) v2
  src/connections/destinations/catalog/actions-braze-cloud/index.md
Labels: content-update

#7104 Google Ads Conversions Destination Actions v2
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update

#7137 Release 24.41.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/warehouse-ip.html
  src/connections/auto-instrumentation/web-setup.md
  src/connections/destinations/catalog/actions-accoil-analytics/index.md
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/sources/custom-domain.md
  src/engage/audiences/linked-audiences.md
  src/unified-profiles/unified-profiles-workspace.md
Labels: release

#7139 Klaviyo 403 error section + Vale cleanup [DOC-1000]
  src/connections/destinations/catalog/actions-klaviyo/index.md
  vale-styles/Vocab/Docs/accept.txt
Labels: content-update

#7141 Update Migration Guides for Swift and Kotlin
  src/connections/sources/catalog/libraries/mobile/apple/migration.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
Labels: content-update

#7120 Linked Events Limits + GA [DOC-997]
  src/_data/sidenav/main.yml
  src/unify/data-graph/linked-events-limits.md
  src/unify/data-graph/linked-events.md
Labels: content-update

#7145 Master back to develop after Linked Events GA deploy
  src/_data/sidenav/main.yml
  src/unify/data-graph/linked-events-limits.md
  src/unify/data-graph/linked-events.md
Labels: back-end

#7147 Update ID Resolution Custom Identifier Screenshot
  src/unify/identity-resolution/identity-resolution-onboarding.md
  src/unify/identity-resolution/images/custom_identifiers.png
Labels: content-update

#7146 10.15.24 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7149 Added a clarification around content policy
  src/connections/sources/custom-domain.md
Labels: KCS

#7150 Refactor the "supported CMPs" section of Configure Consent Management
  src/privacy/consent-management/configure-consent-management.md
Labels: content-update

#7138 Add FAQ on 200 Rules Limit for Tracking Plan Updates via Public API
  src/protocols/faq.md
Labels: KCS

#7132 Clarify Debounce Middleware behavior in public docs
  src/connections/destinations/catalog/actions-braze-web/index.md
Labels: KCS

#7144 array info for Triggers
  src/connections/destinations/actions.md
Labels: KCS

#7153 Update Destination Filters page
  src/connections/destinations/destination-filters.md
Labels: content-update

#7066 Update setup.md
  src/connections/reverse-etl/setup.md
Labels: KCS

#7154 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7155 Release 24.42.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/destination-filters.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
  src/connections/reverse-etl/setup.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/custom-domain.md
  src/privacy/consent-management/configure-consent-management.md
  src/protocols/faq.md
Labels: release

#7156 Fixed broken Braze links
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/catalog/braze/index.md
Labels: fixed-site

#7159 Fix dbt Extension Info Callout
  src/segment-app/extensions/dbt.md
Labels: fixed-site

#7160 Add Source Function Custom Response FAQ
  src/connections/functions/source-functions.md
Labels: content-update

#7161 Fix broken BigQuery Reverse ETL link
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
Labels: fixed-site

#7162 Catalog Update 22 October 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7163 Release 24.43.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/functions/source-functions.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
  src/connections/sources/about-cloud-sources.md
  src/segment-app/extensions/dbt.md
Labels: release

#7165 Update Databricks Setup
  src/unify/data-graph/setup-guides/databricks-setup.md
Labels: content-update

#6818 Update Profile API sample URL
  src/unify/profile-api.md
Labels: content-update

#6962 Add Predictions FAQ on Calculating Averages
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update, KCS

#6951 Add FAQ on 5 most common Traits calculation
  src/engage/faqs.md
Labels: content-update, KCS

#6747 Add Insert Functions FAQ on Storage Destinations
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#7168 Catalog Update 24 October 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7170 Update VAT/GST FAQ Doc
  src/assets/pdf/Segment_VAT_GST_FAQ.pdf
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/guides/usage-and-billing/billing.md
Labels: content-update

#7169 Update CODEOWNERS
  CODEOWNERS
Labels: back-end

#7171 Release 24.43.2
  CODEOWNERS
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/assets/pdf/Segment_VAT_GST_FAQ.pdf
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/connections/functions/insert-functions.md
  src/engage/faqs.md
  src/guides/usage-and-billing/billing.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/profile-api.md
Labels: release

#6641 Add ID Sync info to Google Ads Remarketing Lists Destination
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: content-update, KCS

#6846 Add Info about GA4 User-Provided Data Collection
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#7176 Adding a note about FB <> Ip addresses
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
Labels: KCS

#7178 make catalog 20241029
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7179 Release 24.44.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/facebook-pixel-server-side/index.md
  src/connections/storage/catalog/azuresqldw/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/connections/storage/catalog/databricks/index.md
  src/connections/storage/catalog/db2/index.md
  src/connections/storage/catalog/postgres/index.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/connections/storage/warehouses/faq.md
Labels: release

#7172 update common fields page for IPv6
  src/connections/spec/common.md
Labels: KCS

#7180 Event-Triggered Journeys Private Beta
  src/engage/journeys/event-triggered-journeys.md
Labels: new-feature

#7175 Recommended Items GA [DOC-1007]
  src/_data/sidenav/main.yml
  src/unify/Traits/computed-traits.md
  src/unify/Traits/recommended-items.md
  src/unify/images/recommendation_items.png
Labels: new-feature

#7185 Unify Plus AI Limits/Packaging Update [DOC-1005]
  src/unify/product-limits.md
Labels: content-update

#7186 make catalog 20241031
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7183 Add new supported integrations to PrivateLink
  src/connections/aws-privatelink.md
Labels: content-update, KCS

#6815 Update sync frequency of real-time audience-to-batch destination
  src/engage/product-limits.md
Labels: content-update, KCS

#7187 First Party DV 360 Actions Destination (Take 2)
  src/_data/catalog/destinations_private.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-first-party-dv360/index.md
Labels: new-integration

#7182 First Party DV 360 Actions Destination
  src/_data/catalog/destinations_private.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-first-party-dv360/index.md
Labels: new-integration

#7189 Release 24.44.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/connections/aws-privatelink.md
  src/connections/destinations/catalog/actions-first-party-dv360/index.md
  src/connections/spec/common.md
  src/engage/journeys/event-triggered-journeys.md
  src/engage/product-limits.md
  src/unify/Traits/computed-traits.md
  src/unify/Traits/recommended-items.md
  src/unify/images/recommendation_items.png
  src/unify/product-limits.md
Labels: release
