Repository segmentio/segment-docs, pull requests merged in 2024-04, with the labels that each got.

#6320 Updated FAQ section.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: KCS

#6321 Clearbit Enrichment Destination Not Compatible with EU Segment Worksp…
  src/connections/destinations/catalog/clearbit-enrichment/index.md
Labels: KCS

#6328 Add SQL Traits EoS Callout
  src/unify/Traits/sql-traits.md
Labels: content-update

#6329 `master` back to `develop`
  src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/unify/Traits/sql-traits.md
Labels: back-end

#6327 Fix URL for Use Cases
  src/engage/audiences/linked-audiences.md
Labels: fixed-content

#6271 Add 'external id' to user subscription status
  src/engage/user-subscriptions/index.md
Labels: KCS

#6331 Update proxy info
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
Labels: KCS

#6304 LinkedIn Conversions API [DOC-858]
  src/connections/destinations/catalog/actions-linkedin-conversions/index.md
Labels: new-integration

#6324 Add info on typewriter tiering and support
  src/protocols/apis-and-extensions/typewriter-v7.md
  src/protocols/apis-and-extensions/typewriter.md
Labels: KCS

#6333 running make catalog for 04/02/2024 deploy
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6335 Re-run catalog for kafka and linkedin conversions api destinations
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/actions-kafka/index.md
Labels: back-end

#6339 Master to develop after hotfix
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/actions-kafka/index.md
Labels: back-end

#6319 Update index.md
  src/connections/storage/catalog/aws-s3/index.md
Labels: KCS

#6330 Fixing documentation for batch filtering case
  src/connections/functions/insert-functions.md
Labels: content-update

#6283 Add clarity around Predictive Audiences limit
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update, KCS

#6342 update databricks source setup page
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
Labels: content-update

#6312 Add note about timestamp changes in Kotlin
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: KCS

#5841 Updated the Troubleshooting section with details on using Synchronous mode and Celery
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: KCS

#5851 Added space ID section
  src/unify/unify-settings.md
Labels: content-update, KCS

#6350 AI Copilot Spec Update
  src/connections/spec/copilot.md
Labels: content-update

#6352 updating catalog for 04/04/24 deploy
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6353 Release 24.14.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-kafka/index.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/spec/copilot.md
  src/connections/storage/catalog/aws-s3/index.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/Traits/sql-traits.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
  src/unify/unify-settings.md
Labels: release

#6326 Niall/partner partial
  scripts/catalog/updateDestinations.js
  src/_includes/content/destination-dossier.html
Labels: KCS

#6314 Optimizely Data Platform - New docs
  src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
Labels: new-integration

#6355 merge `master` into `develop`
  src/connections/functions/insert-functions.md
Labels: back-end

#6356 Optimizely Data Platform docs + catalog release
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/optimizely-data-platform/index.md
Labels: back-end

#6357 Master to develop after one-off
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/optimizely-data-platform/index.md
Labels: back-end

#6361 Hide digioh destination docs
  src/connections/destinations/catalog/digioh/index.md
Labels: back-end

#6307 Update facebook-app-events-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/facebook-app-events-react-native.md
Labels: KCS

#5652 Update index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#6102 Upgrade Broken Link
  src/connections/sources/catalog/libraries/server/node/migration.md
Labels: KCS

#6354 Add FAQ around changing SQL traits
  src/unify/Traits/sql-traits.md
Labels: content-update, KCS

#5663 Update insert-functions.md
  src/connections/functions/insert-functions.md
Labels: KCS

#6008 Add Timestamp Requirement for Mixpanel (Actions)
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: KCS

#6096 Added required information for using Gtag via server
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#6010 Updating Information on GCLID
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update, KCS

#6192 Update SendGrid collections
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: content-update, KCS

#6150 FAQ validation error for google ads
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: KCS

#6159 Difference between destination instance id and destination meta id
  src/api/public-api/index.md
Labels: KCS

#6179 Add the full list of required fields for FB CAPI
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: automated issue, KCS

#6305 Update URL referencing required frameworks for IDFA
  src/connections/destinations/catalog/facebook-app-events/index.md
Labels: KCS

#6344 Troubleshoot addition to the FB Customer Audience Destination
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: KCS

#6349 Add FAQ to Linked Events
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#6348 Adding replace function to consent mode docs [DOC-857]
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update

#6363 Make Catalog 2024_04_09
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6303 Fix Destinations URL
  src/_includes/content/whats-a-destination.md
Labels: content-update, KCS

#6198 Connections Alerting GA [DOC-809]
  src/_data/sidenav/main.yml
  src/connections/alerting.md
  src/connections/delivery-overview.md
  src/connections/images/alerting-source-alert.png
  src/guides/how-to-guides/set-up-notifications-alerts.md
Labels: new-feature

#6366 Observability GAs: Delivery Overview and Alerting
  src/_data/sidenav/main.yml
  src/connections/alerting.md
  src/connections/delivery-overview.md
  src/connections/images/alerting-source-alert.png
  src/guides/how-to-guides/set-up-notifications-alerts.md
Labels: release

#6368 hotfix for delivery overview GA
  src/connections/delivery-overview.md
Labels: release

#6308 Remove broken link
  src/connections/destinations/catalog/gainsight-px/index.md
Labels: KCS

#5665 Troubleshooting Inquiry index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: KCS

#6370 Fix Quantcast plugin title bug, Vale fixes
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/optimizely-full-stack-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/quantcast-swift.md
Labels: content-update

#6360 Fixing broken Engage Audiences link
  src/engage/audiences/index.md
Labels: fixed-content, KCS

#6374 Fix link
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5899 Prediction failure
  src/unify/Traits/predictions/index.md
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update, KCS

#6375 Add a note with info on how to ungroup users to Group spec
  src/connections/spec/group.md
Labels: content-update

#6376 Fix alerting sync freq
  src/_data/sidenav/main.yml
  src/connections/alerting.md
  src/connections/delivery-overview.md
  src/connections/images/alerting-source-alert.png
  src/guides/how-to-guides/set-up-notifications-alerts.md
Labels: content-update

#6099 Double Hashing for FB
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: content-update, KCS

#4955 Additional details added to Pretty View section
  src/connections/sources/debugger.md
Labels: content-update, KCS

#6275 Add FAQ around updating Predictive Traits and Audiences
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update, KCS

#6378 Release 24.15.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/alerting.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-marketo-static-lists/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/gainsight-px/index.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/optimizely-full-stack-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/quantcast-swift.md
  src/connections/sources/debugger.md
  src/connections/spec/group.md
  src/engage/audiences/index.md
  src/guides/intro-impl.md
  src/privacy/consent-management/consent-in-unify.md
  src/unify/Traits/predictions/index.md
  src/unify/Traits/predictions/using-predictions.md
Labels: release

#6380 Update query-language docs to match changes being made with actual query language
  src/api/public-api/query-language.md
Labels: content-update

#5982 Update track.md - Track Spec added context.traits and actions destina…
  src/connections/spec/track.md
Labels: KCS

#6298 additional linked fixes
  src/engage/audiences/linked-audiences.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: content-update

#6385 Add information about sending to a Segment source
  src/connections/functions/destination-functions.md
Labels: KCS

#6387 Hide Connection Modes table for GA Remarketing Lists destination
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: back-end

#6383 Add note to the Connections page about consent sharing workaround
  src/privacy/consent-management/consent-in-segment-connections.md
Labels: content-update

#6386 Fix spelling error in slug override file
  src/_data/catalog/slugs.yml
Labels: back-end

#6381 Update Custom Traits limit info
  src/unify/Traits/custom-traits.md
Labels: content-update, KCS

#6389 Specifying Source Volume alert
  src/connections/alerting.md
Labels: fixed-content

#6391 Update SQL Traits Unify Limits
  src/unify/product-limits.md
Labels: content-update

#6337 Update DV360 Docs
  src/connections/destinations/catalog/actions-display-video-360/index.md
Labels: fixed-content

#6359 Unified Profiles Public Beta+ release [DOC-860]
  src/unified-profiles/segment-for-flex.md
Labels: content-update

#6316 SQL Trait edit/resync applied changes
  src/unify/Traits/sql-traits.md
Labels: content-update

#6392 Add Audiences identifier breakdown clarification
  src/engage/audiences/index.md
Labels: KCS

#6395 adding vale instructions to gh
  styleguide.md
Labels: content-update

#6394 passive voice to active fix
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: content-update

#6397 Catalog plus deleted double ripe actions folders
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/ripe/index.md
Labels: back-end

#6398 Release 24.16.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/api/public-api/query-language.md
  src/connections/alerting.md
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/ripe/index.md
  src/connections/functions/destination-functions.md
  src/connections/spec/track.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/unified-profiles/segment-for-flex.md
  src/unify/Traits/custom-traits.md
  src/unify/Traits/sql-traits.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
  src/unify/product-limits.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
  styleguide.md
Labels: release

#6403 update FAQ on associating company with user
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
Labels: KCS

#6382 Azure RETL Source GA
  src/connections/reverse-etl/reverse-etl-source-setup-guides/azure-setup.md
Labels: content-update

#6278 Add info on how to search for alias in Braze to avoid confusion
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
Labels: KCS

#6407 quick fix of mw pr
  src/connections/sources/catalog/libraries/website/javascript/middleware.md
Labels: fixed-content

#6372 Clarify Marketo audience updating info
  src/connections/destinations/catalog/marketo-static-lists/index.md
Labels: content-update, KCS

#6409 Add information on deduplication
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: content-update, KCS

#6411 Change class for better styling
  src/_includes/content/destination-dossier.html
Labels: KCS

#6412 Add AI Copilot Link
  src/connections/spec/index.md
Labels: content-update

#6414 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6415 Release 24.16.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/retently/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/middleware.md
  src/connections/spec/index.md
Labels: release

#6373 Remove line about config
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#6401 Wisepops - Documentation for the new goal tracking
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-custom-event.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-id.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-id.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-plan.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-setup-code.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-website-hash.png
  src/connections/destinations/catalog/actions-wisepops/index.md
Labels: content-update

#6426 Ajs collects timezone by default
  src/connections/spec/common.md
Labels: KCS

#6420 Update out of date analytics.js docs
  src/connections/sources/catalog/libraries/website/javascript/analytics-js-2.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: fixed-content

#6423 Fix broken email editor link
  src/engage/content/email/editor.md
Labels: fixed-site

#6429 Predictions Updates
  src/unify/Traits/predictions/index.md
Labels: content-update

#6421 Add Unify Insights FAQ
  src/unify/insights.md
Labels: content-update

#6430 running catalog for today's deploy
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6427 Update Identify spec to include note about uuidv4 format [DOC-883]
  src/connections/spec/identify.md
Labels: content-update

#6431 Release 24.17.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-custom-event.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-goal-id.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-id.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-group-plan.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-setup-code.png
  src/connections/destinations/catalog/actions-wisepops/images/wisepops-website-hash.png
  src/connections/destinations/catalog/actions-wisepops/index.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/libraries/website/javascript/analytics-js-2.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/common.md
  src/connections/spec/identify.md
  src/engage/content/email/editor.md
  src/guides/regional-segment.md
  src/unify/Traits/predictions/index.md
  src/unify/insights.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: release

#6399 Add Moloco MCM destination beta doc
  src/connections/destinations/catalog/actions-moloco-rmp/index.md
Labels: new-integration

#6443 running today's catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6444 Release 24.17.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-moloco-rmp/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/privacy/data-controls.md
Labels: release

#6446 feat(content): add `DropEvent` error handler
  src/connections/functions/insert-functions.md
Labels: content-update

#6447 Update faq-segment-dissolution-vat.pdf
  src/assets/pdf/faq-segment-dissolution-vat.pdf
Labels: content-update

#6448 Add note about consent in Linked Events docs
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#6452 Add klaviyo FAQ about 429 response
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: content-update

#6458 remove outdated info
  src/connections/functions/insert-functions.md
Labels: KCS

#6461 Update index.md Creating A Public API Token
  src/api/public-api/index.md
Labels: KCS

#6469 Update faq.md
  src/connections/storage/warehouses/faq.md
Labels: KCS

#6428 Add docs for new Inleads destination
  src/connections/destinations/catalog/inleads-ai/index.md
Labels: new-integration

#6470 Catalog Update 04292024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6471 Release 24.18.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/api/public-api/index.md
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/connections/destinations/catalog/actions-gameball/index.md
  src/connections/destinations/catalog/actions-kameleoon/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/gameball/index.md
  src/connections/destinations/catalog/inleads-ai/index.md
  src/connections/destinations/catalog/kameleoon/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/storage/warehouses/faq.md
  src/unified-profiles/create-sql-traits.md
  src/unified-profiles/segment-for-flex.md
  src/unify/linked-profiles/linked-events.md
Labels: release

#6473 Update flush policies to include overriding standard policies
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS
