Repository segmentio/segment-docs, pull requests merged in 2024-03, with the labels that each got.

#6154 Update functions runtime section
  src/_includes/content/functions/runtime.md
Labels: content-update

#6162 Fix broken links under error types section
  src/connections/functions/source-functions.md
Labels: KCS

#6129 Typewriter7 API token update
  src/protocols/apis-and-extensions/typewriter-v7.md
Labels: KCS

#6163 `master` back to `develop` after one-off
  src/_includes/content/functions/runtime.md
Labels: back-end

#6059 Unified Profiles in Flex [DOC-806]
  src/_includes/icons/flex.svg
  src/_includes/icons/unified-profiles.svg
  src/_sass/components/_breadcrumbs.scss
  src/unified-profiles/connect-a-workspace.md
  src/unified-profiles/index.md
  src/unified-profiles/segment-for-flex.md
Labels: new-feature

#6165 Update FullStory's Action destination documentation
  src/connections/destinations/catalog/actions-fullstory/index.md
Labels: content-update

#6173 Update Subscription Groups CSV page
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/subscription-groups.md
Labels: content-update

#6122 Trait activation updates
  src/_data/sidenav/main.yml
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/index.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
Labels: content-update

#6160 Add section to address named page events in source ingestion.md
  src/connections/sources/index.md
Labels: KCS

#6172 Add slug override and cleanup folders
  src/_data/catalog/slugs.yml
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/images/connect.png
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/images/export.png
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
Labels: back-end, content-update

#6168 Master back to develop after one-off release
  src/_data/sidenav/main.yml
  src/_includes/icons/flex.svg
  src/_includes/icons/unified-profiles.svg
  src/_sass/components/_breadcrumbs.scss
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/index.md
  src/engage/trait-activation/trait-activation-setup.md
  src/engage/trait-activation/trait-enrichment.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/subscription-groups.md
  src/unified-profiles/connect-a-workspace.md
  src/unified-profiles/index.md
  src/unified-profiles/segment-for-flex.md
Labels: back-end

#6166 Add "RETL Scripts For Importing Salesforce Objects Into Unified Profiles" documentation
  src/unified-profiles/create-sql-traits.md
  src/unified-profiles/segment-for-flex.md
Labels: new-feature

#6164 Google Consent Mode [DOC-839]
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
Labels: new-feature

#6174 Fix DV360 docs link
  src/connections/destinations/catalog/actions-display-video-360/index.md
Labels: broken links, content-update

#6091 Included info about transformations with the event tester
  src/protocols/faq.md
Labels: KCS

#6171 Convert Generative Audiences label to HTML
  src/_includes/content/generative-audiences-nutrition-facts.html
  src/engage/audiences/generative-audiences-nutrition-facts.md
Labels: content-update

#6182 Update CODEOWNERS
  CODEOWNERS
Labels: back-end

#6180 Add info about null values to Protocols docs
  src/protocols/faq.md
  src/protocols/tracking-plan/create.md
Labels: content-update

#6184 Catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/intercom/index.md
Labels: back-end

#6183 Release 24.10.1
  CODEOWNERS
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/generative-audiences-nutrition-facts.html
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-fullstory/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/functions/source-functions.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/images/connect.png
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/images/export.png
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/sources/index.md
  src/engage/audiences/generative-audiences-nutrition-facts.md
  src/protocols/apis-and-extensions/typewriter-v7.md
  src/protocols/faq.md
  src/protocols/tracking-plan/create.md
Labels: release

#6142 Add FAQ about loading multiple writeKeys for iOS
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
Labels: KCS

#6194 Update script to account for Screen method
  scripts/catalog/updateDestinations.js
Labels: content-update

#6189 Fix Salesforce Marketing Cloud typo
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
Labels: KCS

#6201 Update Google Analytics Consent Mode callout
  src/connections/destinations/catalog/google-analytics/index.md
Labels: content-update, KCS

#6001 update documentation on grabbing specific traits
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: KCS

#6087 Add to delivery overview alerts section
  src/connections/delivery-overview.md
Labels: KCS

#6149 Salesforce version upgrade [DOC-835]
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: content-update

#6141 rETL - Add FAQ for Syntax errors
  src/connections/reverse-etl/index.md
Labels: KCS

#6170 Add info on how to manually pass UTMs to subsequent calls
  src/guides/how-to-guides/cross-channel-tracking.md
Labels: KCS

#5857 Update index.md
  src/connections/reverse-etl/index.md
Labels: KCS

#6202 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6203 Release 24.10.2
  scripts/catalog/updateDestinations.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/cloud-apps/moengage-source/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/libraries/mobile/ios/ios-faqs.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/guides/how-to-guides/cross-channel-tracking.md
Labels: release

#6158 Update Protocols FAQ
  src/protocols/faq.md
Labels: KCS

#6175 Custom Proxy: does not apply to device-mode destinations
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#6207 Fix typo
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#6205 Remove links to non-specific pages
  src/guides/how-to-guides/collect-on-client-or-server.md
Labels: KCS

#6212 updated wording for salesforce version upgrade
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/guides/how-to-guides/collect-on-client-or-server.md
  src/protocols/faq.md
Labels: fixed-content

#6213 Master back to develop after one-off
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: back-end

#6210 Added back in a redirect from the original Mixpanel source link
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
Labels: back-end

#6209 Google consent mode wording update
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
Labels: content-update

#4744 IPv6 not supported callout
  src/connections/sources/catalog/libraries/website/javascript/identity.md
Labels: content-update, KCS

#6218 Make Catalog 20240312
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6219 Release 24.11.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/firebase/index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
Labels: release

#6220 Add CSV Upload Page to Unify
  src/_data/sidenav/main.yml
  src/unify/csv-upload.md
Labels: content-update

#6199 Azure RETL Public Beta and RETL Partial Syncs [DOC-782]
  src/_data/sidenav/main.yml
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/azure-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
Labels: new-integration, new-feature

#6151 Update destination-functions.md
  src/connections/functions/destination-functions.md
Labels: KCS

#6230 Update index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
Labels: KCS

#6215 Update delivery-overview.md
  src/connections/delivery-overview.md
Labels: KCS

#6225 Add information about traits and adding to context for new mobile lib…
  src/connections/spec/common.md
Labels: content-update, KCS

#6144 Update Destination Filters device-mode support
  src/connections/destinations/destination-filters.md
Labels: KCS

#6232 Make Catalog 20240314
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6233 Release 24.11.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-gameball/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/google-ads-classic/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/destination-functions.md
  src/connections/spec/common.md
Labels: release

#6235 Clarify ipv6 docs
  src/connections/sources/catalog/libraries/website/javascript/identity.md
Labels: fixed-content

#6241 Typo Housekeeping
  src/_data/actions/braze-cloud.yml
  src/_data/actions/braze-web.yml
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/split/index.md
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/connections/sources/catalog/cloud-apps/freshchat/index.md
  src/connections/spec/best-practices-identify.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/engage/quickstart.md
  src/guides/how-to-guides/forecast-with-sql.md
Labels: fixed-content

#6200 Add info about Insert ID
  src/connections/destinations/catalog/mixpanel/index.md
Labels: KCS

#6231 Add Proxy info for mobile libraries
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: KCS

#6239 add oauth callout
  src/connections/destinations/catalog/autopilotapp/index.md
Labels: content-update

#6237 Delivery Overview discard table improvements
  src/_includes/content/delivery-overview-discards.html
  src/_includes/content/retl-discards.md
  src/connections/delivery-overview.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#6240 PROT-5203: Add section clarifying the .$ operator
  src/connections/sources/schema/index.md
  src/protocols/tracking-plan/create.md
Labels: content-update

#6229 adds destination docs for MetricStory
  src/connections/destinations/catalog/metricstory/index.md
Labels: new-integration

#6249 master back into develop after one-off
  src/_includes/content/delivery-overview-discards.html
  src/_includes/content/retl-discards.md
  src/connections/delivery-overview.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: back-end

#6251 Release 24.12.1
  src/_data/actions/braze-cloud.yml
  src/_data/actions/braze-web.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-sheets/index.md
  src/connections/destinations/catalog/autopilotapp/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/metricstory/index.md
  src/connections/destinations/catalog/mixpanel/index.md
  src/connections/destinations/catalog/split/index.md
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/connections/sources/catalog/cloud-apps/freshchat/index.md
  src/connections/sources/catalog/cloud-apps/synap/index.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/sources/schema/index.md
  src/connections/spec/best-practices-identify.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/engage/quickstart.md
  src/guides/how-to-guides/forecast-with-sql.md
  src/privacy/user-deletion-and-suppression.md
  src/protocols/tracking-plan/create.md
Labels: release

#6139 Add note about Adobe timestamp options
  src/connections/destinations/catalog/adobe-analytics/index.md
Labels: KCS

#6247 Fixed minor change from 100,000 to 110,000 update user-deletion-and-suppression.md
  src/privacy/user-deletion-and-suppression.md
Labels: content-update, KCS

#6256 Update MetricStory URL
  src/connections/destinations/catalog/metricstory/index.md
Labels: content-update

#6211 RETL Reset Syncs [DOC-847]
  src/connections/reverse-etl/index.md
Labels: content-update

#6257 master back to develop after one-off
  src/connections/reverse-etl/index.md
Labels: back-end

#5411 Engage content updates [DOC-733]
  src/engage/campaigns/email-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/template.md
  src/engage/content/sms/template.md
Labels: content-update

#6130 Correcting the misspelled "recieved_at" in the documentation
  src/connections/storage/warehouses/warehouse-syncs.md
Labels: KCS

#4805 Update ab-testing.md Sending A / B Testing Data To Different Destinat…
  src/connections/spec/ab-testing.md
Labels: KCS

#6085 Update the Node version that is supported
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: KCS

#6228 Add documentation on using trait information in event rules
  src/connections/destinations/catalog/actions-stackadapt/images/email-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt/index.md
Labels: content-update

#5459 Update Send Data Journey payload details
  src/engage/journeys/send-data.md
Labels: content-update, KCS

#6242 Populating lists with CSV or TSV.md
  src/engage/audiences/index.md
Labels: content-update, KCS

#6236 Update GTM docs
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: content-update, KCS

#6234 Add info about mobile device mode destination filters
  src/connections/destinations/destination-filters.md
Labels: fixed-content, content-update, KCS

#6267 Release 24.12.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-stackadapt/images/email-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt/index.md
  src/connections/destinations/catalog/adobe-analytics/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/metricstory/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/spec/ab-testing.md
  src/connections/storage/warehouses/warehouse-syncs.md
  src/engage/audiences/index.md
  src/engage/campaigns/email-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/template.md
  src/engage/content/sms/template.md
  src/engage/journeys/send-data.md
  src/privacy/user-deletion-and-suppression.md
  src/segment-app/iam/sso.md
  src/unify/linked-profiles/linked-events.md
Labels: release

#6273 Fix raw tag
  src/engage/content/email/template.md
Labels: back-end

#6274 master to develop after one-off
  src/engage/content/email/template.md
Labels: back-end

#6272 Fixed broken external links [DOC-768]
  ignore-links.txt
  src/connections/destinations/catalog/actions-absmartly/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/adobe-analytics/best-practices.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/cdpresolution/index.md
  src/connections/destinations/catalog/correlated/index.md
  src/connections/destinations/catalog/courier/index.md
  src/connections/destinations/catalog/everflow/index.md
  src/connections/destinations/catalog/experiments-by-growthhackers/index.md
  src/connections/destinations/catalog/graphjson/index.md
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/mammoth/index.md
  src/connections/destinations/catalog/olark/index.md
  src/connections/destinations/catalog/orb/index.md
  src/connections/destinations/catalog/qualaroo/index.md
  src/connections/destinations/catalog/retentive/index.md
  src/connections/destinations/catalog/retently/index.md
  src/connections/destinations/catalog/tune/index.md
  src/connections/destinations/catalog/vespucci/index.md
  src/connections/destinations/catalog/willow/index.md
  src/connections/sources/catalog/cloud-apps/launchdarkly/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/braze-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/braze-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/intercom-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/warehouses/choose-warehouse.md
  src/protocols/tracking-plan/create.md
Labels: fixed-content

#6264 clear up common Actions misconception
  src/connections/destinations/actions.md
Labels: KCS

#6269 Update kotlin-android-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters.md
Labels: content-update

#6204 updated wording for salesforce version upgrade on March 25, 2024
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
Labels: content-update

#6288 Fix Emarsys (Actions) "additional version" link
  src/connections/destinations/catalog/actions-emarsys/index.md
Labels: back-end

#6290 AI Copilot Spec [DOC-852]
  src/_data/sidenav/main.yml
  src/connections/spec/copilot.md
Labels: new-feature

#6037 Profiles sync setup updates
  src/unify/index.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
  src/unify/profiles-sync/tables.md
Labels: new-feature

#6292 Remove extra bracket
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: fixed-site, KCS

#6281 Update Mixpanel link
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/mixpanel-kotlin-android.md
Labels: content-update, KCS

#6262 adding changes to GA4 topics
  src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: content-update

#6294 3/26/24 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6270 Update insert-functions.md
  src/connections/functions/insert-functions.md
Labels: KCS

#6285 Add section for sending consent data in Appsflyer
  src/connections/destinations/catalog/appsflyer/index.md
Labels: content-update

#6252 Add note about change in sentat in new mobile libraries
  src/connections/spec/common.md
Labels: KCS

#6254 Rebrand from cdp resolution to delivrai
  src/connections/destinations/catalog/cdpresolution/index.md
  src/connections/destinations/catalog/delivrai-resolve/index.md
  src/connections/sources/catalog/cloud-apps/cdp-resolution-enrichment/index.md
Labels: content-update

#6295 Release 24.13.1
  ignore-links.txt
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-absmartly/index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-emarsys/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/adobe-analytics/best-practices.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/branch-metrics/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/cdpresolution/index.md
  src/connections/destinations/catalog/correlated/index.md
  src/connections/destinations/catalog/courier/index.md
  src/connections/destinations/catalog/delivrai-resolve/index.md
  src/connections/destinations/catalog/everflow/index.md
  src/connections/destinations/catalog/experiments-by-growthhackers/index.md
  src/connections/destinations/catalog/graphjson/index.md
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/mammoth/index.md
  src/connections/destinations/catalog/olark/index.md
  src/connections/destinations/catalog/orb/index.md
  src/connections/destinations/catalog/qualaroo/index.md
  src/connections/destinations/catalog/retentive/index.md
  src/connections/destinations/catalog/retently/index.md
  src/connections/destinations/catalog/tune/index.md
  src/connections/destinations/catalog/vespucci/index.md
  src/connections/destinations/catalog/willow/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/cdp-resolution-enrichment/index.md
  src/connections/sources/catalog/cloud-apps/launchdarkly/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/braze-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/braze-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/intercom-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/mixpanel-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/connections/spec/common.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/warehouses/choose-warehouse.md
  src/protocols/tracking-plan/create.md
  src/unify/index.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
  src/unify/profiles-sync/tables.md
Labels: release

#6296 post GA update to table
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: content-update

#6227 Linked audiences public beta
  src/engage/audiences/linked-audiences-use-cases.md
  src/engage/audiences/linked-audiences.md
Labels: content-update

#6284 Data Graph Changes 3_25_24
  src/_data/sidenav/main.yml
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/linked-events.md
  src/unify/linked-profiles/setup-guides/BigQuery-setup.md
  src/unify/linked-profiles/setup-guides/redshift-setup.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: content-update

#6301 Remove beta tag from ABsmartly actions
  src/connections/destinations/catalog/actions-absmartly/index.md
Labels: fixed-content

#6302 Add GA4 FAQ back to index page
  src/connections/destinations/catalog/actions-google-analytics-4-web/ga4-faq-and-troubleshooting
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: fixed-content

#5780 Update index.md
  src/connections/destinations/catalog/singular/index.md
Labels: KCS

#6255 Klaviyo Endpoint
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#6300 Add FAQ to Kotlin Sidenav
  src/_data/sidenav/strat.yml
Labels: KCS
