Repository segmentio/segment-docs, pull requests merged in 2024-02, with the labels that each got.

#5927 Update index.md
  src/connections/storage/catalog/aws-s3/index.md
Labels: KCS

#5978 Remove event schema section from Shopify Littledata source
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
Labels: fixed-content

#5974 Add EU-specific warehouses IP note
  src/_includes/content/warehouse-ip.html
Labels: fixed-content

#5966 Fix typo
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5958 Analytics.js: Move "Getting started" section to top of page
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#5953 Consent in Segment Connections (Public Beta) [DOC-772]
  src/connections/delivery-overview.md
  src/privacy/configure-consent-management.md
  src/privacy/consent-in-segment-connections.md
  src/privacy/consent-in-unify.md
  src/privacy/consent-management.md
Labels: content-update

#5972 Add Analytics-C# note to Regional Segment
  src/guides/regional-segment.md
Labels: content-update

#5967 Custom proxy update
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#5962 Update Marketo device mode to reflect required fields
  src/connections/destinations/catalog/marketo-v2/index.md
Labels: KCS

#5983 Updates to Data Graph and Linked Events
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#4026 Be more explicit about where to find Source URL and Source ID for Support ticket requests
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS, Outdated

#5976 Update index.md - Slack (Classic) Link broken
  src/connections/destinations/catalog/actions-slack/index.md
Labels: KCS

#4770 Add alternatives to SSH Tunneling FAQ
  src/connections/storage/catalog/redshift/index.md
Labels: KCS

#5949 Add docs for installing Analytics under custom global key
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5984 Make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5985 Release 24.5.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/warehouse-ip.html
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-slack/index.md
  src/connections/destinations/catalog/marketo-v2/index.md
  src/connections/sources/catalog/libraries/server/csharp/migration-guide.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/shopify-littledata/index.md
  src/connections/storage/catalog/aws-s3/index.md
  src/connections/storage/catalog/redshift/index.md
  src/guides/regional-segment.md
  src/privacy/configure-consent-management.md
  src/privacy/consent-in-segment-connections.md
  src/privacy/consent-in-unify.md
  src/privacy/consent-management.md
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/linked-events.md
Labels: release

#5986 Live Plugins Pilot [DOC-791]
  src/connections/sources/catalog/libraries/mobile/apple/live-plugins.md
Labels: new-feature

#5824 Add note that new config api tokens cannot be created
  src/api/config-api/index.md
Labels: KCS

#5987 Fix Side Navigation
  src/_data/sidenav/strat.yml
Labels: back-end

#5988 Merge `master` into `develop`
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/mobile/apple/live-plugins.md
Labels: back-end

#5973 GA4: Update paragraph on "Data is not sent to Google"
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5989 Update insert-functions.md
  src/connections/functions/insert-functions.md
Labels: KCS

#5960 GTM: Add info block
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#5825 Add info on Common JSON schema blocking
  src/protocols/enforce/schema-configuration.md
  src/protocols/images/advanced-blocking-controls.png
  src/protocols/images/standard-schema-controls.png
Labels: KCS

#5922 Added userguiding documentation
  src/_data/catalog/beta_sources.yml
  src/connections/sources/catalog/cloud-apps/userguiding/index.md
Labels: new-integration

#5896 Clarify self-hosted ajs and add more links.
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: content-update

#5977 Update index.md - Missing details on generating Incoming Webhook URL
  src/connections/destinations/catalog/actions-slack/index.md
Labels: KCS

#5965 Add information about cross-domain tracking
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#5961 Add info on schema integration filters with existing integration object
  src/guides/filtering-data.md
Labels: KCS

#5441 Add note on sending null values
  src/connections/destinations/catalog/salesforce-marketing-cloud/index.md
Labels: KCS

#5937 Update account-management.md
  src/guides/usage-and-billing/account-management.md
Labels: KCS

#5910 Feat: Add Missing Documentation for Mobile Destination Plugins [Netlify Build]
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/adobe-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/localytics-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dtvr-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/images/eventsV2.png
  src/connections/sources/catalog/libraries/mobile/apple/images/map-event-adobe.png
  src/connections/sources/catalog/libraries/mobile/apple/images/map-property-adobe.png
  src/connections/sources/catalog/libraries/mobile/apple/images/map-property-segment.png
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/adobe-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/intercom-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/localytics-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dcr-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dtvr-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/eventsV2.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/import.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/map-event-adobe.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/map-property-adobe.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/map-property-segment.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture.md
Labels: new-integration

#5957 Analytics.js: Add FAQ about CSPs
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: content-update, KCS

#4254 excessive notifications for aud/trait failures
  src/engage/faqs.md
Labels: content-update, KCS

#4971 Add note on Facebook Custom Audiences destination
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: content-update, KCS

#5998 Catalog 2.6.2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5999 Update link in Journeys #5990
  src/engage/journeys/key-terms.md
Labels: fixed-content

#6000 Release 24.6.1
  src/_data/catalog/beta_sources.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/api/config-api/index.md
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-slack/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/connections/destinations/catalog/salesforce-marketing-cloud/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/userguiding/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/adobe-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/localytics-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dtvr-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/images/eventsV2.png
  src/connections/sources/catalog/libraries/mobile/apple/images/map-event-adobe.png
  src/connections/sources/catalog/libraries/mobile/apple/images/map-property-adobe.png
  src/connections/sources/catalog/libraries/mobile/apple/images/map-property-segment.png
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/adobe-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/intercom-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/localytics-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dcr-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/nielsen-dtvr-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/eventsV2.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/import.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/map-event-adobe.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/map-property-adobe.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/images/map-property-segment.png
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/faqs.md
  src/engage/journeys/key-terms.md
  src/guides/filtering-data.md
  src/guides/usage-and-billing/account-management.md
  src/protocols/enforce/schema-configuration.md
  src/protocols/images/advanced-blocking-controls.png
  src/protocols/images/standard-schema-controls.png
Labels: release

#6004 Updated userguiding source documentation details
  src/connections/sources/catalog/cloud-apps/userguiding/index.md
Labels: content-update

#6012 Fix links in the Google App Engine section
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: broken links

#6014 Fix id duplication bug leading to missing RETL destinations
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/fullstory-cloud-mode-actions/index.md
  src/connections/destinations/catalog/google-analytics-4-cloud/index.md
  src/connections/destinations/catalog/klaviyo-actions/index.md
  src/connections/reverse-etl/reverse-etl-catalog.md
Labels: back-end

#5921 Add custom traits content
  src/_data/sidenav/main.yml
  src/_includes/content/trait-types.md
  src/connections/spec/identify.md
  src/engage/audiences/index.md
  src/engage/profiles/csv-upload.md
  src/unify/Traits/computed-traits.md
  src/unify/Traits/custom-traits.md
  src/unify/Traits/sql-traits.md
Labels: content-update

#6006 Add info on multi-instance support
  src/connections/sources/catalog/libraries/mobile/apple/index.md
Labels: KCS

#6025 Fix broken link
  src/engage/audiences/index.md
Labels: back-end

#6018 Add links to github and remove cloud mode text
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/adobe-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dtvr-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/adobe-kotlin-android.md
Labels: KCS

#6022 Add support note to Linked Profiles
  src/unify/linked-profiles/index.md
Labels: content-update

#6011 Update Snowflake setup doc
  src/unify/images/snowflake-setup.png
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: content-update

#6020 UserGuiding going live, removing hidden frontmatter
  src/connections/sources/catalog/cloud-apps/userguiding/index.md
Labels: new-integration

#6026 Add error message to Generative Audiences
  src/engage/audiences/generative-audiences.md
Labels: content-update

#6017 CSV Upload Updates [DOC-815]
  src/engage/profiles/csv-upload.md
Labels: content-update

#6028 Catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6021 Fixed custom proxy formatting error
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: fixed-content, KCS

#6023 RETL email alerts [DOC-819]
  src/connections/reverse-etl/index.md
Labels: content-update

#6029 Release 24.6.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/content/trait-types.md
  src/connections/destinations/catalog/fullstory-cloud-mode-actions/index.md
  src/connections/destinations/catalog/google-analytics-4-cloud/index.md
  src/connections/destinations/catalog/klaviyo-actions/index.md
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/reverse-etl-catalog.md
  src/connections/sources/catalog/cloud-apps/userguiding/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/adobe-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dtvr-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/adobe-kotlin-android.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/spec/identify.md
  src/engage/audiences/generative-audiences.md
  src/engage/audiences/index.md
  src/engage/profiles/csv-upload.md
  src/unify/Traits/computed-traits.md
  src/unify/Traits/custom-traits.md
  src/unify/Traits/sql-traits.md
  src/unify/images/snowflake-setup.png
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: release

#6031 Profiles CSV Upload Fixes
  src/_data/sidenav/main.yml
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/csv-upload.md
Labels: content-update

#6032 Merge `master` into `develop`
  src/_data/sidenav/main.yml
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/csv-upload.md
Labels: back-end

#6036 Add anonymous identify method info
  src/connections/sources/catalog/libraries/mobile/react-native/implementation.md
Labels: KCS

#6005 Rename file and add placeholders for Intercom destination
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr-swift.md
Labels: KCS

#5847 Segment <> Shopify source
  src/connections/sources/catalog/libraries/website/shopify/images/manage_events.png
  src/connections/sources/catalog/libraries/website/shopify/images/manage_user_profile_details.png
  src/connections/sources/catalog/libraries/website/shopify/images/settings.png
  src/connections/sources/catalog/libraries/website/shopify/index.md
Labels: new-integration

#5621 Add FAQ about the `$` operator
  src/engage/audiences/index.md
Labels: content-update, KCS

#5873 Update index.md
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
Labels: KCS

#5872 Add webhook clarification
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: KCS

#6038 Remove beta tag for encharge
  src/connections/destinations/catalog/encharge-cloud-actions/index.md
Labels: back-end

#6039 Library Tier Updates
  src/_data/support-types.yml
  src/connections/sources/catalog/libraries/ott/roku/index.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
Labels: content-update

#6016 Documentation for StackAdapt destination
  src/connections/destinations/catalog/actions-stackadapt/images/copy-pixel-id.png
  src/connections/destinations/catalog/actions-stackadapt/images/install-pixel-link.png
  src/connections/destinations/catalog/actions-stackadapt/images/order-completed-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt/images/user-registered-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt/index.md
Labels: new-integration

#6046 Update Roku Source Support Label
  src/connections/sources/catalog/libraries/ott/roku/index.md
Labels: fixed-content

#6003 Avo destination docs
  src/connections/destinations/catalog/avo/images/api-key.png
  src/connections/destinations/catalog/avo/images/avo-destination.png
  src/connections/destinations/catalog/avo/images/issue-sidebar.png
  src/connections/destinations/catalog/avo/images/select-source.png
  src/connections/destinations/catalog/avo/index.md
Labels: new-integration

#6047 Update CSV Upload Guidelines
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/csv-upload.md
Labels: content-update

#6040 obtain OAuth access token [DOC-821]
  src/connections/oauth.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#6048 Make Catalog 20240213
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/equals/index.md
Labels: back-end

#6049 Fixed 2 more slugs
  src/_data/catalog/slugs.yml
Labels: back-end

#6050 Release 24.7.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/support-types.yml
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/actions-segment/index.md
  src/connections/destinations/catalog/actions-stackadapt/images/copy-pixel-id.png
  src/connections/destinations/catalog/actions-stackadapt/images/install-pixel-link.png
  src/connections/destinations/catalog/actions-stackadapt/images/order-completed-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt/images/user-registered-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt/index.md
  src/connections/destinations/catalog/avo/images/api-key.png
  src/connections/destinations/catalog/avo/images/avo-destination.png
  src/connections/destinations/catalog/avo/images/issue-sidebar.png
  src/connections/destinations/catalog/avo/images/select-source.png
  src/connections/destinations/catalog/avo/index.md
  src/connections/destinations/catalog/encharge-cloud-actions/index.md
  src/connections/destinations/catalog/equals/index.md
  src/connections/oauth.md
  src/connections/sources/catalog/cloud-apps/google-ads/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/nielsen-dcr-swift.md
  src/connections/sources/catalog/libraries/mobile/react-native/implementation.md
  src/connections/sources/catalog/libraries/ott/roku/index.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
  src/connections/sources/catalog/libraries/website/shopify/images/manage_events.png
  src/connections/sources/catalog/libraries/website/shopify/images/manage_user_profile_details.png
  src/connections/sources/catalog/libraries/website/shopify/images/settings.png
  src/connections/sources/catalog/libraries/website/shopify/index.md
  src/connections/storage/data-lakes/index.md
  src/engage/audiences/index.md
  src/engage/profiles/csv-upload.md
  src/engage/user-subscriptions/csv-upload.md
Labels: release

#6043 Add Troubleshooting for invalid list ID.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: KCS

#6033 Add details for support on this destination
  src/connections/destinations/catalog/actions-pendo-web/index.md
Labels: automated issue, KCS

#6055 Fix support type param for library tiers
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: fixed-content, KCS

#6051 creating a nutrition label for predictions feature
  src/_data/sidenav/main.yml
  src/images/label-customer-ai-predictions .png
  src/unify/Traits/predictions/index.md
  src/unify/Traits/predictions/predictions-nutrition-facts.md
Labels: content-update

#6057 fixed OAuth link
  src/connections/destinations/catalog/actions-pendo-web/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/oauth.md
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
Labels: broken links

#6058 Master back to develop after one-off
  src/_data/sidenav/main.yml
  src/connections/oauth.md
  src/images/label-customer-ai-predictions .png
  src/unify/Traits/predictions/index.md
  src/unify/Traits/predictions/predictions-nutrition-facts.md
Labels: back-end

#5905 Profiles Sync and Databricks Destination GA
  src/_data/catalog/warehouse.yml
  src/_data/sidenav/main.yml
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-aws.md
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-azure.md
  src/connections/storage/catalog/databricks-delta-lake/index.md
  src/connections/storage/catalog/databricks/index.md
  src/unify/profiles-sync/profiles-sync-setup/databricks-profiles-sync.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: new-integration, new-feature

#5993 update-warehouse-faq-datatype
  src/connections/storage/warehouses/faq.md
Labels: KCS

#6062 Master back to Develop after one-off
  src/_data/catalog/warehouse.yml
  src/_data/sidenav/main.yml
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-aws.md
  src/connections/storage/catalog/databricks-delta-lake/databricks-delta-lake-azure.md
  src/connections/storage/catalog/databricks-delta-lake/index.md
  src/connections/storage/catalog/databricks/index.md
  src/unify/profiles-sync/profiles-sync-setup/databricks-profiles-sync.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: back-end

#6061 Snowflake setup updates
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: content-update

#6064 Fix Boomtrain Destination Title
  src/connections/destinations/catalog/boomtrain/index.md
Labels: fixed-site

#6065 Make Catalog 20240215
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/appfit/index.md
Labels: back-end

#6056 adding build preview instructions to contribution guide
  CONTRIBUTING.md
Labels: back-end

#6066 Release 24.7.2
  CONTRIBUTING.md
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-app-fit/index.md
  src/connections/destinations/catalog/appfit/index.md
  src/connections/destinations/catalog/avo/index.md
  src/connections/destinations/catalog/boomtrain/index.md
  src/connections/storage/warehouses/faq.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: release

#6067 Catalog Update
  src/_data/catalog/destinations.yml
Labels: back-end

#6069 Remove Zopim Destination (temporarily)
  src/_data/catalog/destinations.yml
Labels: back-end

#6070 Add Personas and Zopim Destinatinos back
  src/_data/catalog/destinations.yml
Labels: back-end

#6072 Merge `master` into `develop`
  src/_data/catalog/destinations.yml
Labels: back-end

#6068 Add ID to the Shopify source docs
  src/connections/sources/catalog/libraries/website/shopify/index.md
Labels: content-update

#6073 Update C# Support Label
  src/connections/sources/catalog/libraries/server/csharp/index.md
Labels: content-update

#5878 adding prereqs to readme
  README.md
Labels: back-end

#5656 add oauth faq for actions destination
  src/connections/destinations/actions.md
Labels: KCS

#6034 Segment Query Language Private Beta [DOC-763]
  src/_data/sidenav/main.yml
  src/api/public-api/query-language.md
Labels: new-feature

#6077 Merge `master` into `develop`
  src/_data/sidenav/main.yml
  src/api/public-api/query-language.md
Labels: back-end

#6076 Generative Audiences Nutrition Facts
  src/_data/sidenav/main.yml
  src/engage/audiences/generative-audiences-nutrition-facts.md
  src/engage/audiences/generative-audiences.md
  src/engage/images/generative-audiences-nutrition-facts.png
Labels: content-update

#5753 Update audience docs to ensure users don't edit audiences until initial backfill is complete
  src/engage/audiences/index.md
Labels: KCS

#6086 Add Support Label to Analytics for Kotlin (Server)
  src/connections/sources/catalog/libraries/server/kotlin/index.md
Labels: content-update

#6082 Update guide to add a note about Consent Mode.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: KCS

#6081 Update guide to add a note about Consent Mode.md
  src/connections/destinations/catalog/google-ads-gtag/index.md
Labels: KCS

#6080 Update guide to add a note about Consent Mode.md
  src/connections/destinations/catalog/google-ads-classic/index.md
Labels: KCS

#6078 Update guide to add a note about Consent Mode.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#6090 Make Catalog 20240220
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5963 Amplitude Actions: Update "tracking sessions" for clarity
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#6084 Update guide to include a note about Consent Mode.md
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#6092 Avo docs updates
  src/connections/destinations/catalog/avo/images/avo-destination.png
  src/connections/destinations/catalog/avo/index.md
Labels: content-update

#5997 Consent in Segment Connections GA [DOC-807]
  src/_data/sidenav/main.yml
  src/connections/delivery-overview.md
  src/privacy/consent-in-unify.md
  src/privacy/consent-management.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/images/consent-overview.png
  src/privacy/consent-management/index.md
  src/segment-app/iam/audit-trail.md
Labels: content-update

#6095 Consent GA hotfix
  src/_data/sidenav/main.yml
  src/privacy/consent-management/consent-in-unify.md
Labels: content-update

#6097 master back into develop after one-off
  src/_data/sidenav/main.yml
  src/connections/delivery-overview.md
  src/privacy/consent-in-unify.md
  src/privacy/consent-management.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/images/consent-overview.png
  src/privacy/consent-management/index.md
  src/segment-app/iam/audit-trail.md
Labels: back-end

#6083 Update guide to add a note about Consent Mode.md
  src/connections/destinations/catalog/google-analytics/index.md
Labels: KCS

#4005 Create section : Frequently asked questions
  src/segment-app/iam/audit-trail.md
Labels: KCS

#4108 Add details on Replay when connecting Engage Sources
  src/engage/quickstart.md
Labels: KCS

#4130 Update actual steps to Add Source to Engage Space
  src/engage/quickstart.md
Labels: KCS

#6105 Remove hidden and private add beta
  src/connections/destinations/catalog/actions-app-fit/index.md
Labels: new-integration

#6015 Add BQ dataset's partition expiry
  src/connections/storage/catalog/bigquery/index.md
Labels: KCS

#6110 Add BCC limitation.md
  src/engage/campaigns/broadcasts.md
Labels: KCS

#6108 Fix wording
  src/connections/index.md
Labels: KCS

#6098 Fixed bug on Segment App index page
  src/segment-app/index.md
Labels: fixed-content

#6115 Make Catalog 20240222
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6116 Add clarification to Linked Events/Audiences
  src/engage/audiences/linked-audiences.md
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#6104 Updates to The Trade Desk CRM Destination docs [DOC-828]
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: content-update

#6118 fixed broken npm link
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: broken links

#5721 Facebook requirements update
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: KCS

#6106 Post-GA Consent Mgmt items
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/index.md
  src/protocols/faq.md
  src/protocols/tracking-plan/create.md
Labels: content-update

#6112 Add Peaka Destination Documentation
  src/connections/destinations/catalog/peaka/index.md
Labels: new-integration

#6120 Remove beta tag from Avo destination docs
  src/connections/destinations/catalog/avo/index.md
Labels: new-integration

#5627 prototype.js issue
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#6132 Convert Predictions nutrition facts PNG to HTML
  src/_includes/content/predictions-nutrition-facts.html
  src/unify/Traits/predictions/predictions-nutrition-facts.md
Labels: content-update

#6131 Update best-practices-identify.md
  src/connections/spec/best-practices-identify.md
Labels: KCS

#6113 Add plan slug to Consent Management docs
  src/_data/products.yml
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/index.md
Labels: KCS

#6128 Update step 1 in Data Graph doc
  src/unify/images/snowflake-setup.png
  src/unify/linked-profiles/data-graph.md
Labels: content-update

#6138 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6137 Release 24.9.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/_includes/content/predictions-nutrition-facts.html
  src/connections/destinations/catalog/avo/index.md
  src/connections/destinations/catalog/peaka/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/spec/best-practices-identify.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/index.md
  src/segment-app/iam/index.md
  src/unify/Traits/predictions/predictions-nutrition-facts.md
  src/unify/images/snowflake-setup.png
  src/unify/linked-profiles/data-graph.md
Labels: release

#6133 Filter options for the Violations page
  src/protocols/validate/review-violations.md
Labels: KCS

#5743 in-app messages customer.io
  src/connections/destinations/catalog/customer-io-actions/index.md
Labels: KCS

#6053 update pendo destination url
  src/connections/destinations/catalog/pendo/index.md
Labels: content-update

#6126 Segment's data flow to destination.
  src/connections/destinations/index.md
Labels: KCS

#6089 Update Profile insights.md
  src/unify/images/external_id.png
  src/unify/insights.md
Labels: KCS

#6134 Update AJS snippet version information
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
Labels: KCS

#6136 Re-list Intercom for mobile destination plugins
  src/connections/destinations/catalog/intercom/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
Labels: KCS

#6013 Add Predictions HIPAA FAQ
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update

#5384 Importing Tracking plan
  src/protocols/faq.md
Labels: KCS

#6145 removing reference to kanye
  src/protocols/tracking-plan/best-practices.md
Labels: content-update

#6143 Add guide to connect Facebook Lead Ad wit Segment
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: KCS

#6153 Subscription Group CSV Upload updates
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/subscription-groups.md
Labels: content-update

#6155 Add another HIPAA disclaimer [DOC-837]
  src/unify/Traits/predictions/index.md
Labels: content-update

#6088 Flutter SDK [DOC-811]
  src/connections/sources/catalog/libraries/mobile/flutter/index.md
Labels: new-integration

#6156 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6157 Release 24.9.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/customer-io-actions/index.md
  src/connections/destinations/catalog/intercom/index.md
  src/connections/destinations/catalog/pendo/index.md
  src/connections/destinations/catalog/startdeliver-v2/index.md
  src/connections/destinations/index.md
  src/connections/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
  src/connections/sources/catalog/libraries/mobile/flutter/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/index.md
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/subscription-groups.md
  src/protocols/faq.md
  src/protocols/tracking-plan/best-practices.md
  src/protocols/validate/review-violations.md
  src/unify/Traits/predictions/index.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/Traits/sql-traits.md
  src/unify/images/external_id.png
  src/unify/insights.md
Labels: release
