Repository segmentio/segment-docs, pull requests merged in 2024-01, with the labels that each got.

#5773 Update user-deletion-and-suppression.md
  src/privacy/user-deletion-and-suppression.md
Labels: content-update, KCS

#5807 Add disable documentation to anaytics.js
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#5783 Update Regional Segment sources, destinations, and warehouses tables
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/warehouse.yml
  src/_data/regional-support.yml
  src/_includes/content/regional-integrations-table.md
  src/guides/regional-segment.md
Labels: fixed-site

#5750 Refactor sources catalog [DOC-744]
  src/_data/catalog/beta_sources.yml
  src/_data/catalog/test_sources.yml
  src/_includes/menu/menu-source.html
  src/_includes/sidebar/source-menu.html
  src/connections/sources/catalog/index.md
  src/connections/sources/index.md
Labels: fixed-site

#5823 Add sessionId timeout info
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#5837 Add docs for new yahoo destination
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-1.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-2.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-3.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-4.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-5.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-6.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-7.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-8.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-9.png
  src/connections/destinations/catalog/actions-yahoo-audiences/index.md
Labels: new-integration

#5839 Release 24.1.1
  src/_data/catalog/beta_sources.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/test_sources.yml
  src/_data/catalog/warehouse.yml
  src/_data/regional-support.yml
  src/_includes/content/regional-integrations-table.md
  src/_includes/menu/menu-source.html
  src/_includes/sidebar/source-menu.html
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-1.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-2.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-3.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-4.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-5.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-6.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-7.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-8.png
  src/connections/destinations/catalog/actions-yahoo-audiences/images/yahoo-9.png
  src/connections/destinations/catalog/actions-yahoo-audiences/index.md
  src/connections/destinations/catalog/logrocket/index.md
  src/connections/sources/catalog/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/index.md
  src/engage/trait-activation/trait-activation-setup.md
  src/guides/regional-segment.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#5842 Add SCIM guide to Segment app section of sidenav
  src/_data/sidenav/main.yml
  src/segment-app/iam/scim.md
  vale-styles/Vocab/Docs/accept.txt
Labels: back-end

#5844 Bucket Web (Actions) slug override [DOC-769]
  src/_data/catalog/slugs.yml
Labels: back-end

#5818 Added White Label Loyalty source documentation
  src/connections/sources/catalog/cloud-apps/white-label-loyalty/index.md
Labels: new-integration

#5819 Updating OneSignal Partner Source Documentation
  src/connections/sources/catalog/cloud-apps/onesignal/index.md
Labels: content-update

#5813 Removing messaging services
  src/engage/campaigns/mobile-push/index.md
Labels: content-update

#5811 multiple audience entered events for the same user
  src/engage/faqs.md
Labels: KCS

#5845 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5846 Release 24.1.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/sources/catalog/cloud-apps/onesignal/index.md
  src/connections/sources/catalog/cloud-apps/white-label-loyalty/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/faqs.md
  src/segment-app/iam/scim.md
  vale-styles/Vocab/Docs/accept.txt
Labels: release

#5836 update azure ad name
  src/segment-app/iam/scim.md
  src/segment-app/iam/sso.md
Labels: KCS

#5853 Update information on Journey destination steps
  src/engage/journeys/journeys-logic.md
Labels: content-update, KCS

#5737 adding info about runtime & dependencies npm to insert functions
  src/connections/functions/insert-functions.md
Labels: KCS

#5661 add section for server side
  src/connections/destinations/catalog/batch/index.md
Labels: content-update

#5856 Engage IP Pools
  src/engage/campaigns/email-campaigns.md
Labels: new-feature

#5858 Add workaround for using liquid statements with images
  src/engage/content/email/template.md
Labels: content-update

#5860 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5809 Template folders
  src/_includes/content/engage-folders.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
Labels: new-feature

#5863 Master back to develop
  src/_includes/content/engage-folders.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
Labels: back-end

#5808 change maxEventsInBatch -> flushAt
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
Labels: content-update

#5869 Braze: add section on batching
  src/connections/destinations/catalog/actions-braze-cloud/index.md
Labels: content-update

#5865 updating Pipedrive docs
  src/connections/destinations/catalog/actions-pipedrive/images/deal_match_fields.png
  src/connections/destinations/catalog/actions-pipedrive/images/email_match_field.png
  src/connections/destinations/catalog/actions-pipedrive/images/match_field.png
  src/connections/destinations/catalog/actions-pipedrive/index.md
Labels: content-update

#5854 Add npm steps to A.js setup [DOC-771]
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
Labels: content-update

#5870 Edits to Yahoo Audiences destination doc
  src/connections/destinations/catalog/actions-yahoo-audiences/index.md
Labels: content-update

#5871 Update folders content
  src/_data/sidenav/main.yml
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
Labels: content-update

#5874 Update Engage IP Pools wording
  src/engage/campaigns/email-campaigns.md
Labels: content-update

#5875 Updated Build a Prediction section
  src/unify/Traits/predictions/index.md
Labels: content-update

#5876 Make Catalog 20240111
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/1flow-web-actions/index.md
  src/connections/destinations/catalog/hubble-actions/index.md
  src/connections/destinations/catalog/klaviyo-actions/index.md
  src/connections/destinations/catalog/screeb-web-actions/index.md
Labels: back-end

#5877 Release 24.2.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/1flow-web-actions/index.md
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-pipedrive/images/deal_match_fields.png
  src/connections/destinations/catalog/actions-pipedrive/images/email_match_field.png
  src/connections/destinations/catalog/actions-pipedrive/images/match_field.png
  src/connections/destinations/catalog/actions-pipedrive/index.md
  src/connections/destinations/catalog/actions-yahoo-audiences/index.md
  src/connections/destinations/catalog/hubble-actions/index.md
  src/connections/destinations/catalog/klaviyo-actions/index.md
  src/connections/destinations/catalog/screeb-web-actions/index.md
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
  src/engage/campaigns/email-campaigns.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/unify/Traits/predictions/index.md
Labels: release

#5888 Make Catalog 20240116
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5722 Update Swift device mode plugin docs with destination details
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
Labels: content-update, KCS

#5889 Release 24.3.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-1flow/index.md
  src/connections/destinations/catalog/actions-pipedrive/images/email_match_field.png
  src/connections/destinations/catalog/actions-pipedrive/images/match_field.png
  src/connections/destinations/catalog/actions-pipedrive/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/index.md
Labels: release

#5848 Add event formatting info to style guide
  styleguide.md
Labels: back-end

#5881 Add White Label Loyalty to beta sources list
  src/_data/catalog/beta_sources.yml
Labels: back-end

#5882 Added docs for the Gleap (Actions) destination
  src/connections/destinations/catalog/gleap-cloud-actions/index.md
Labels: new-integration

#5733 Update insert-functions.md
  src/connections/functions/insert-functions.md
Labels: KCS

#5895 Unhide Klaviyo (Actions) Destination
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: content-update

#5897 Update SMS Broadcast steps
  src/engage/campaigns/broadcasts.md
Labels: content-update

#5866 APP-94627 pendo web (actions) doc
  src/connections/destinations/catalog/actions-pendo-web/index.md
Labels: new-integration

#5883 Privacy Portal docs improvements
  src/privacy/images/privacy-synonym-in-matcher.png
  src/privacy/images/synonym-in-matcher.png
  src/privacy/portal.md
Labels: content-update

#5893 New PR to replace existing for Aggregations.io
  src/connections/destinations/catalog/actions-aggregations-io/index.md
Labels: new-integration

#5731 Update section on Ad blockers.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#5902 Release 24.3.2
  src/_data/catalog/beta_sources.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-aggregations-io/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/actions-pendo-web/index.md
  src/connections/destinations/catalog/aggregations-io-actions/index.md
  src/connections/destinations/catalog/gleap-cloud-actions/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/cdp-resolution-enrichment/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/engage/campaigns/broadcasts.md
  src/privacy/images/privacy-synonym-in-matcher.png
  src/privacy/images/synonym-in-matcher.png
  src/privacy/portal.md
  src/segment-app/iam/scim.md
  styleguide.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/direct-destination.md
  templates/partners/source.md
Labels: release

#5894 Update LiveRamp Integration doc to remove Public Beta instructions
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
Labels: KCS

#5879 Update docs to include Activity Notifications Details
  src/segment-app/index.md
Labels: documentation, content-update, KCS

#5907 make snippet come first
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
Labels: content-update

#5904 Add slug override for aggregations integration
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/aggregations-io-actions/index.md
Labels: back-end

#5908 Fixed sidebar buffer [DOC-764]
  src/_sass/components/_sidebar.scss
Labels: back-end

#5912 Add cdn setting for Kotlin
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: KCS

#5898 Add MTU calculation during profile merge content
  src/unify/faqs.md
Labels: KCS

#5903 Add reset info for new libraries
  src/_includes/content/reset-mobile.md
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/implementation.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
Labels: content-update, KCS

#5900 Adding Kameleoon (Actions) Destination documentation
  src/connections/destinations/catalog/actions-kameleoon/index.md
Labels: new-integration

#5913 Remove Twilio Notify link
  src/engage/campaigns/mobile-push/index.md
Labels: content-update

#5915 Release 24.4.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/reset-mobile.md
  src/_includes/content/snippet-helper.md
  src/_layouts/default.html
  src/_sass/components/_sidebar.scss
  src/connections/destinations/catalog/actions-kameleoon/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/aggregations-io-actions/index.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/destinations/catalog/youbora/index.md
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/implementation.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/campaigns/mobile-push/index.md
  src/segment-app/index.md
  src/unify/faqs.md
Labels: release

#5806 Update audiences/index.md to add specificity that time comparison operators apply only to custom traits
  src/engage/audiences/index.md
Labels: KCS

#5919 Update Google Enhanced Conversions Docs - Legacy API Sunset
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update

#5885 Update index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
Labels: KCS

#5766 Add information on Alias and Unify
  src/connections/spec/alias.md
Labels: content-update

#5686 device mode cookie-validity-update.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: content-update, KCS

#5592 Update duplicate-data.md
  src/guides/duplicate-data.md
Labels: content-update, KCS

#5886 Add a note about Chrome third-party cookie restrictions.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#4824 Update index.md Zendesk clarification on sending name
  src/connections/destinations/catalog/zendesk/index.md
Labels: KCS

#5789 Update computed-traits.md - corrected spelling mistake "appropriate"
  src/unify/Traits/computed-traits.md
Labels: KCS

#5817 Update insert-functions.md spelling correction
  src/connections/functions/insert-functions.md
Labels: KCS

#5928 Update max length naming for destination-filters.md
  src/connections/destinations/destination-filters.md
Labels: KCS

#5926 Update filtering-data.md
  src/guides/filtering-data.md
Labels: KCS

#5920 Add back EU endpoint column
  src/_data/catalog/warehouse.yml
  src/_includes/content/regional-integrations-table.md
  src/guides/regional-segment.md
Labels: back-end

#5929 HLS Data Encryption to GA
  src/_includes/content/connection-modes-intro.md
  src/connections/destinations/add-destination.md
  src/connections/destinations/destination-filters.md
  src/privacy/hipaa-eligible-segment.md
Labels: content-update

#5374 Added the Failed and Archived statuses
  src/engage/journeys/key-terms.md
Labels: KCS

#5548 Update cloud action to include limitation of chat widget
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
Labels: KCS

#5460 Update destination-filters.md Added Filter Conditional Operators
  src/connections/destinations/destination-filters.md
Labels: KCS

#5462 Update index.md Klaviyo segments
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#5620 Add note about changing SQL Trait data type
  src/unify/Traits/sql-traits.md
Labels: KCS

#4806 Update Actions Guidance
  src/connections/destinations/actions.md
Labels: KCS

#5930 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#4843 Update send-data.md Updated page with List Destination info
  src/engage/journeys/send-data.md
Labels: KCS

#5931 Release 24.4.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/catalog/warehouse.yml
  src/_includes/content/connection-modes-intro.md
  src/_includes/content/regional-integrations-table.md
  src/connections/destinations/actions.md
  src/connections/destinations/add-destination.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/actions-pendo-web/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/zendesk/index.md
  src/connections/destinations/destination-filters.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/index.md
  src/connections/sources/catalog/cloud-apps/facebook-ads/index.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/spec/alias.md
  src/engage/audiences/index.md
  src/engage/journeys/key-terms.md
  src/engage/journeys/send-data.md
  src/guides/duplicate-data.md
  src/guides/filtering-data.md
  src/guides/regional-segment.md
  src/privacy/hipaa-eligible-segment.md
  src/unify/Traits/computed-traits.md
  src/unify/Traits/sql-traits.md
  src/unify/product-limits.md
Labels: release

#5453 Update sql-traits.md Add Troubleshooting step
  src/unify/Traits/sql-traits.md
Labels: KCS

#5932 Update HTTP API rate limits
  src/connections/rate-limits.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#4802 Update index.md Added section on Limitations (fixed typo)
  src/connections/destinations/catalog/actions-qualtrics/index.md
Labels: KCS

#4576 Update Regional Endpoint doc to provide examples
  src/guides/regional-segment.md
Labels: KCS

#5935 Add sources/destinations section to style guide
  styleguide.md
Labels: back-end

#5835 update import historical data with retl
  src/guides/how-to-guides/import-historical-data.md
Labels: KCS

#4801 Update index.md repeater to include details on replay
  src/connections/destinations/catalog/repeater/index.md
Labels: KCS

#5940 Update about-cloud-sources.md
  src/connections/sources/about-cloud-sources.md
Labels: content-update, KCS

#5566 Update Engage Section.md
  src/connections/destinations/catalog/kustomer/index.md
Labels: KCS

#5788 Add warning on realtime computations connected to List destinations
  src/engage/audiences/index.md
Labels: KCS

#5941 Engage Events updates
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/engage/settings.md
  src/engage/warehouses.md
Labels: content-update

#5833 DV360 (Actions) Docs
  src/connections/destinations/catalog/actions-display-video-360/index.md
Labels: new-integration

#4842 Update using-engage-data.md Adding Journeys info
  src/engage/using-engage-data.md
Labels: KCS

#5944 Add beta and id to equals destination docs
  src/connections/destinations/catalog/actions-equals/index.md
Labels: content-update

#5945 Make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#5947 Make Catalog 20240130_2
  src/_data/catalog/destinations.yml
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/connections/destinations/catalog/display-and-video-360-actions/index.md
  src/connections/destinations/catalog/gleap-action/index.md
  src/connections/destinations/catalog/pendo-web-actions/index.md
Labels: back-end

#5948 Catalog and Changelog update
  src/_data/catalog/destinations.yml
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/connections/destinations/catalog/display-and-video-360-actions/index.md
  src/connections/destinations/catalog/gleap-action/index.md
  src/connections/destinations/catalog/pendo-web-actions/index.md
Labels: back-end

#5951 Remove contact support link
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#4377 Update Outdated Doc's
  src/connections/destinations/catalog/bing-ads/index.md
Labels: KCS

#4803 Update destination-filters.md added limitation for array types
  src/connections/destinations/destination-filters.md
Labels: KCS

#5843 Generative Audiences
  src/_data/sidenav/main.yml
  src/engage/audiences/generative-audiences.md
  src/engage/images/No-purchases.png
  src/engage/images/phone-doesn't-exist.png
Labels: new-feature

#5106 Update Insider Audiences (Actions) prerequisites
  src/connections/destinations/catalog/actions-insider-audiences/index.md
Labels: content-update, KCS

#4807 Update actions.md Added comprehensive migration strategy
  src/connections/destinations/actions.md
Labels: KCS

#5955 Master back to develop
  src/_data/sidenav/main.yml
  src/engage/audiences/generative-audiences.md
  src/engage/images/No-purchases.png
  src/engage/images/phone-doesn't-exist.png
Labels: back-end

#5956 Remove outdated connection modes include in Bing Ads destination doc
  src/connections/destinations/catalog/bing-ads/index.md
Labels: back-end

#5959 Fix minor typo
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#5569 OAuth 2.0 new SDK feature documentation
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: new-feature

#5952 OAuth 2.0 to Private Beta [DOC-780]
  src/_data/sidenav/main.yml
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
  src/connections/oauth.md
Labels: new-feature

#5890 Linked Audiences and Data Graph content
  src/_data/sidenav/main.yml
  src/engage/audiences/linked-audiences.md
  src/engage/images/conditions.png
  src/unify/images/data-graph-example.png
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/linked-events.md
  src/unify/linked-profiles/setup-guides/BigQuery-setup.md
  src/unify/linked-profiles/setup-guides/redshift-setup.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: new-feature

#5964 master back to develop after OAuth merge
  src/_data/sidenav/main.yml
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
  src/connections/oauth.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/engage/audiences/linked-audiences.md
  src/engage/images/conditions.png
  src/unify/images/data-graph-example.png
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/linked-events.md
  src/unify/linked-profiles/setup-guides/BigQuery-setup.md
  src/unify/linked-profiles/setup-guides/redshift-setup.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: back-end

#5969 Hide LA and Data Graph for private beta
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-insider-audiences/index.md
  src/connections/destinations/catalog/bing-ads/index.md
  src/connections/destinations/destination-filters.md
  src/engage/audiences/linked-audiences.md
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/linked-events.md
Labels: back-end

#5970 Master back to develop
  src/_data/sidenav/main.yml
  src/engage/audiences/linked-audiences.md
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/linked-events.md
Labels: back-end
