Repository segmentio/segment-docs, pull requests merged in 2024-12, with the labels that each got.

#7277 Update FAQ for Identify Calls Not Updating Intercom Profiles
  src/connections/destinations/catalog/actions-intercom-web/index.md
Labels: KCS

#7271 Segment integrations with a proxy
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#7252 Add table of expected behavior to the OneTrust Consent wrapper page
  src/privacy/consent-management/onetrust-wrapper.md
Labels: content-update

#7001 Update custom domain downtime info.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#7279 Add hidden flag deprecated Criteo Offline Conversions integration
  src/connections/destinations/catalog/criteo-offline-conversions/index.md
Labels: KCS

#7280 Change Release Notes to Product Updates
  src/_includes/menu/menu.html
Labels: back-end

#7281 `master` into `develop` after one-off
  src/_includes/menu/menu.html
Labels: back-end

#7284 Improve formatting
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#7257 Unify space removal info on A&DD page [DOC-1014]
  src/privacy/account-deletion.md
Labels: content-update

#7286 Hide Upload Enhanced Conversion (Legacy) Action (again)
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: back-end

#7241 Create Drip (Actions) Destination documentation
  src/connections/destinations/catalog/actions-drip/index.md
Labels: new-integration

#7236 Update Journey Re-entry Logic info
  src/engage/journeys/build-journey.md
Labels: content-update, KCS

#7287 Updated destination dossier to note that some dests aren't supported in EU workspaces
  src/_includes/content/destination-dossier.html
Labels: back-end

#7290 Update Destination Filter Query Language API Links
  src/api/public-api/fql.md
Labels: fixed-content

#7285 Update BigQuery Data Graph Setup Guide
  src/unify/data-graph/setup-guides/BigQuery-setup.md
Labels: content-update

#7294 Update CODEOWNER file
  CODEOWNERS
Labels: back-end

#7278 Add Clarity around Source Migration Storage Destinations
  src/guides/usage-and-billing/account-management.md
Labels: content-update, KCS

#7283 [STRATCONN-5303] Mapping tester not supported for actions-the-trade-desk-crm & actions-liveramp-audiences
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: content-update

#7296 Update Data Graph Supported Warehouses
  src/unify/data-graph/index.md
Labels: content-update

#7292 Journey Context Private Beta
  src/engage/journeys/journey-context.md
Labels: new-feature

#7242 Initial Commit
  src/connections/destinations/catalog/actions-s3/index.md
  src/connections/destinations/catalog/aws-s3/images/aws-s3-catalog.png
Labels: new-integration

#7298 Release 24.49.1
  CODEOWNERS
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/api/public-api/fql.md
  src/connections/destinations/catalog/actions-drip/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-s3/index.md
  src/connections/destinations/catalog/actions-stackadapt-audiences/images/map-fields-example.png
  src/connections/destinations/catalog/actions-stackadapt-audiences/index.md
  src/connections/destinations/catalog/actions-stackadapt-cloud/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
  src/connections/destinations/catalog/aws-s3/images/aws-s3-catalog.png
  src/connections/destinations/catalog/criteo-offline-conversions/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/engage/journeys/build-journey.md
  src/engage/journeys/journey-context.md
  src/guides/usage-and-billing/account-management.md
  src/privacy/account-deletion.md
  src/privacy/consent-management/onetrust-wrapper.md
  src/unify/data-graph/index.md
  src/unify/data-graph/setup-guides/BigQuery-setup.md
Labels: release

#7230 Add Postscript Destination doc
  src/connections/destinations/catalog/actions-postscript/index.md
Labels: new-integration

#7303 `master` into `develop`
  src/connections/destinations/catalog/actions-postscript/index.md
Labels: back-end

#7305 Fix Auto-Instrumentation Typo
  src/connections/auto-instrumentation/index.md
Labels: fixed-content, KCS

#7273 [RETL] add content for RETL cancel syncs
  src/connections/reverse-etl/manage-retl.md
Labels: content-update

#7308 Redshift Data Graph Public Beta Setup Docs [DOC-1016]
  src/_data/sidenav/main.yml
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/redshift-setup.md
Labels: new-feature

#7311 clarify ownership
  src/connections/destinations/catalog/tiktok-conversions/index.md
Labels: KCS

#7304 Update Journey Context for Public Beta
  src/connections/destinations/index.md
  src/connections/functions/index.md
  src/engage/journeys/event-triggered-journeys.md
  src/engage/journeys/journey-context.md
Labels: content-update

#7214 Rokt Audience Set to Publicly Available
  src/connections/destinations/catalog/actions-rokt-audiences/index.md
Labels: new-integration

#7313 Update dbt Extension
  src/segment-app/extensions/dbt.md
Labels: content-update

#7315 Update data-lakes-manual-setup.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
Labels: fixed-content

#7317 Fix link in pushwoosh docs
  src/connections/sources/catalog/cloud-apps/pushwoosh-source/index.md
Labels: fixed-site

#7314 Automatic retry docs
  src/connections/reverse-etl/manage-retl.md
Labels: new-feature

#7299 Update Spaces on Data Graph Supported Warehouses
  src/unify/data-graph/index.md
Labels: fixed-content

#7302 Update Materialized Views Section with Backfill and Selective Sync Info
  src/unify/profiles-sync/tables.md
Labels: content-update

#7300 Responsys Action Destination docs.
  src/connections/destinations/catalog/actions-responsys/index.md
Labels: new-integration

#7295 Reddit Conversions API Destination Documentation
  src/connections/destinations/catalog/actions-reddit-conversions-api/index.md
Labels: new-integration

#7309 Rabble AI Destination Documentation
  src/connections/destinations/catalog/rabble-ai/index.md
Labels: new-integration

#7319 Release 24.50.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/auto-instrumentation/index.md
  src/connections/destinations/catalog/actions-attentive/index.md
  src/connections/destinations/catalog/actions-reddit-conversions-api/index.md
  src/connections/destinations/catalog/actions-responsys/index.md
  src/connections/destinations/catalog/actions-rokt-audiences/index.md
  src/connections/destinations/catalog/actions-singlestore/index.md
  src/connections/destinations/catalog/rabble-ai/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/sources/catalog/cloud-apps/pushwoosh-source/index.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/segment-app/extensions/dbt.md
  src/unify/data-graph/index.md
  src/unify/profiles-sync/tables.md
Labels: release

#7322 Master to develop after hotfix
  src/connections/destinations/catalog/actions-drip/index.md
Labels: back-end

#7259 Payload order info
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: KCS

#6244 Add FAQ for Common Error in HubSpot Cloud Mode
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: KCS

#7301 [SendGrid Lists Destination] - doc for new SendGrid Lists Destination
  src/connections/destinations/catalog/actions-sendgrid-audiences/index.md
Labels: new-integration

#7329 one-off
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/actions-sendgrid-audiences/index.md
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: back-end

#7331 Catalog Update 16 December 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7190 Add FAQ on omitted properties
  src/protocols/faq.md
Labels: KCS

#7307 [Sendgrid] - Doc update for new Sendgrid send email Action
  src/connections/destinations/catalog/actions-sendgrid/index.md
Labels: content-update

#7337 Master back to develop after one-off
  src/connections/destinations/catalog/actions-sendgrid/index.md
Labels: back-end

#7336 Custom Activity behavior
  src/connections/destinations/catalog/marketo-v2/index.md
Labels: KCS

#7320 Add info for objects sending to Google Sheets
  src/connections/destinations/catalog/actions-google-sheets/index.md
Labels: KCS

#7316 Adding a note on UTM parameters validation
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#7251 Update insert-functions.md - faq (can i connect multiple functions to…
  src/connections/functions/insert-functions.md
Labels: KCS

#7340 Fix the wrong version of its/it's
  src/connections/storage/warehouses/schema.md
Labels: fixed-content

#7235 Reverse ETL: dbt Cloud schedule limitation
  src/connections/reverse-etl/setup.md
Labels: KCS

#7341 Clarify regional instructions for go server
  src/connections/sources/catalog/libraries/server/go/index.md
Labels: content-update

#7226 csharp singleton update
  src/connections/sources/catalog/libraries/server/csharp/index.md
Labels: KCS

#7143 Add Unify FAQ on Removing Traits from User Profiles
  src/unify/faqs.md
Labels: content-update, KCS

#7094 Add note about 'value' property in Facebook PIxel
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#7051 Add cookie implementation details for the NPM package
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
Labels: KCS

#7090 Click conversion v2
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: KCS

#7276 Antavo Destination documentation
  src/connections/destinations/catalog/antavo/index.md
Labels: new-integration

#7344 Unhide Send Email With Dynamic Template action
  src/connections/destinations/catalog/actions-sendgrid/index.md
Labels: back-end

#7343 Add explanation for session_id not automatically added to web events
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: KCS

#7022 Update destination-functions.md - add details on how to gracefully ha…
  src/connections/functions/destination-functions.md
Labels: KCS

#7342 Event-Triggered Journeys Public Beta
  src/_data/sidenav/main.yml
  src/engage/journeys/event-triggered-journeys.md
  src/engage/journeys/journey-context.md
Labels: back-end, content-update

#7345 Catalog Update 19 December 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7346 Changelogs Update 19 December 2024
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
Labels: back-end

#7339 Update Linked Audiences Limits
  src/engage/audiences/linked-audiences-limits.md
Labels: content-update

#7293 Clarify Event-Triggered Journeys Destination Activation steps
  src/engage/journeys/event-triggered-journeys.md
Labels: content-update

#7347 Add Segment Startup Program Application Deadline
  src/guides/usage-and-billing/startup-program.md
Labels: content-update

#7348 Release 24.51.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-google-sheets/index.md
  src/connections/destinations/catalog/actions-s3/index.md
  src/connections/destinations/catalog/actions-sendgrid/index.md
  src/connections/destinations/catalog/antavo/index.md
  src/connections/destinations/catalog/bucket/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/destinations/catalog/marketo-v2/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/setup.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/storage/warehouses/schema.md
  src/engage/audiences/linked-audiences-limits.md
  src/engage/journeys/event-triggered-journeys.md
  src/engage/journeys/journey-context.md
  src/guides/usage-and-billing/startup-program.md
  src/protocols/faq.md
  src/unify/faqs.md
Labels: release
