Repository segmentio/segment-docs, pull requests merged in 2024-11, with the labels that each got.

#7075 Update index.md - mrkto static list (actions) real-time to batch dest…
  src/connections/destinations/catalog/actions-marketo-static-lists/index.md
Labels: KCS

#7076 Update snowflake-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
Labels: KCS

#7195 Master back to develop after BigQuery one-off
  src/_data/sidenav/main.yml
  src/unify/data-graph/setup-guides/BigQuery-setup.md
  src/unify/data-graph/setup-guides/redshift-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: back-end

#7196 Hide DevRev docs and correct folder name
  src/connections/destinations/catalog/actions-devrev/index.md
Labels: back-end

#7198 Unify Plus Packaging Update
  src/unify/product-limits.md
Labels: content-update

#7200 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7201 Release 24.45.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-devrev/index.md
  src/connections/destinations/catalog/actions-marketo-static-lists/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/unify/product-limits.md
Labels: release

#7202 [Facebook Custom Audiences (Actions)] Updates auth prerequisites
  src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
Labels: content-update

#7194 Update Linked Audiences Limits
  src/engage/audiences/linked-audiences-limits.md
Labels: content-update

#7207 Git Sync/dbt Extension Updates
  src/segment-app/extensions/dbt.md
  src/segment-app/extensions/git.md
Labels: content-update

#7206 Data Graph breaking changes alerting docs
  src/unify/data-graph/index.md
Labels: new-feature

#7208 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7209 Release 24.45.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
  src/engage/audiences/linked-audiences-limits.md
  src/segment-app/extensions/dbt.md
  src/segment-app/extensions/git.md
  src/unify/data-graph/index.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: release

#7203 Removing group_id from promoted identifiers | IDRES-20
  src/unify/identity-resolution/externalids.md
  src/unify/identity-resolution/identity-resolution-settings.md
Labels: fixed-content

#7199 Add FAQ for IPv6 Collection in Analytics.js
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: KCS

#7193 Update index.md - remove reference to limitation of mapping tester
  src/connections/destinations/catalog/actions-segment-profiles/index.md
Labels: KCS

#7223 Update roles.md - updated Engage destination role reqs
  src/segment-app/iam/roles.md
Labels: KCS

#7210 Add upgrade notes for Swift
  src/connections/sources/catalog/libraries/mobile/apple/migration.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
Labels: KCS

#7219 Add information on ID Sync to Using Engage Data
  src/engage/using-engage-data.md
Labels: content-update, KCS

#6313 Add info about timestamp changes in C#
  src/connections/sources/catalog/libraries/server/csharp/index.md
Labels: content-update, KCS

#6544 Clarify 5-min lookback window for Delivery Overview
  src/connections/delivery-overview.md
Labels: content-update, KCS

#7225 Update VAT/GST FAQ Doc November 2024
  src/assets/pdf/Segment_VAT_GST_FAQ.pdf
Labels: content-update

#7224 Catalog Update 14 November 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7184 Adding Telemetry info for Analytics-Swift and Analytics-Kotlin SDKs
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
Labels: content-update

#7181 Analytics.js sources are required for Custom Domain
  src/connections/sources/custom-domain.md
Labels: content-update, KCS

#6837 Updated Planhat Supported Spec Calls
  src/connections/destinations/catalog/planhat/index.md
Labels: content-update, KCS

#7228 Release 24.46.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/assets/pdf/Segment_VAT_GST_FAQ.pdf
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/planhat/index.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/apple/migration.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/connections/sources/catalog/libraries/server/csharp/index.md
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/connections/sources/custom-domain.md
  src/engage/using-engage-data.md
  src/segment-app/iam/roles.md
  src/unify/identity-resolution/externalids.md
  src/unify/identity-resolution/identity-resolution-settings.md
Labels: release

#6948 Add Trait Activation Limits FAQ to Google Ads Remarketing Lists Destination
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: content-update, KCS

#7229 Add React Native link to Braze docs
  src/connections/destinations/catalog/braze/index.md
Labels: content-update

#7088 Add Note about Custom Domain Setup Downtime
  src/connections/sources/custom-domain.md
Labels: content-update, KCS

#7197 Add Clarity around Entity Condition Types to Linked Audiences Doc
  src/engage/audiences/linked-audiences.md
Labels: content-update

#6917 Update Library Tiers Description
  src/connections/sources/index.md
Labels: content-update, KCS

#7233 Remove hidden attribute that shouldn't be there
  src/connections/sources/custom-domain.md
Labels: fixed-content

#7192 Add info about Customer Disclaimer Responses
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/images/customer-disclaimer-settings.png
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
Labels: KCS

#7220 Update LinkedIn Audiences
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
Labels: content-update

#7234 Add note about order of ops to Braze Cohorts docs
  src/connections/destinations/catalog/actions-braze-cohorts/index.md
Labels: content-update

#7239 Remove SendGrid Marketing Campaigns Destination's hidden action
  src/connections/destinations/catalog/actions-sendgrid/index.md
Labels: back-end

#7238 Master back to develop after one-off for LA Runs Log
  src/connections/destinations/catalog/actions-sendgrid/index.md
  src/engage/audiences/linked-audiences.md
Labels: back-end

#7240 Add Audience Compute Info to Product Based Audiences
  src/engage/audiences/product-based-audiences.md
Labels: content-update

#6345 Conversion Upload Error Troubleshoot
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: KCS

#7248 20241121 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7243 Braze Liquid Syntax Copy for Linked Audience Public Beta
  src/engage/audiences/linked-audiences.md
Labels: new-feature

#7249 Release 24.47.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-braze-cohorts/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/images/customer-disclaimer-settings.png
  src/connections/sources/catalog/cloud-apps/facebook-lead-ads/index.md
  src/connections/sources/custom-domain.md
  src/engage/audiences/linked-audiences.md
  src/engage/audiences/product-based-audiences.md
Labels: release

#7253 Add missing period to Profile Source Debugger page
  src/unify/debugger.md
Labels: back-end

#7255 Add Source Function FAQ on Infinite Looping Error
  src/connections/functions/source-functions.md
Labels: content-update, KCS

#6877 Add Profile Suppression and Batching Details to Klaviyo(Actions) Destination
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: content-update, KCS

#7263 Update custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#6346 HTTP API Troubleshooting Topic: Retries to Iterable
  src/connections/destinations/catalog/iterable/index.md
Labels: KCS

#7265 Privacy Portal FAQ Updates
  src/privacy/faq.md
Labels: content-update

#7268 Predictions Model Monitoring GA
  src/unify/Traits/predictions/using-predictions.md
  src/unify/images/model_monitoring.png
Labels: new-feature

#7269 Catalog Update 26 November 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6640 Add FAQ on Changing Email Templates and Journeys Impact
  src/engage/content/email/template.md
Labels: content-update, KCS

#6474 Add warning that Impact/Segment OAuth must be done by workspace owner
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
Labels: content-update, KCS

#7270 Release 24.48.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/destinations/catalog/impact-partnership-cloud/index.md
  src/connections/destinations/catalog/iterable/index.md
  src/connections/functions/source-functions.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/engage/content/email/template.md
  src/engage/journeys/event-triggered-journeys.md
  src/privacy/faq.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/debugger.md
  src/unify/images/model_monitoring.png
Labels: release
