Repository segmentio/segment-docs, pull requests merged in 2024-07, with the labels that each got.

#6719 Create actions-jimo
  src/connections/destinations/catalog/actions-jimo/index.md
Labels: new-integration

#6769 linked audiences Iterable
  src/engage/audiences/linked-audiences-braze.md
  src/engage/audiences/linked-audiences-iterable.md
  src/engage/images/braze_advanced_email.png
  src/engage/images/braze_basic_email.png
  src/engage/images/linked-cart-advanced.png
  src/engage/images/linked-cart-simple.png
Labels: new-feature

#6775 LA schedule update
  src/engage/audiences/linked-audiences.md
  src/engage/images/linked_audience_payload.png
Labels: content-update

#6783 Catalog Update 2 July 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6785 Hide deprecated Jimo Destination docs
  src/connections/destinations/catalog/jimo/index.md
Labels: content-update

#6788 Add info about Ketch support + add FQL quirk note
  src/privacy/consent-management/configure-consent-management.md
Labels: content-update

#6764 Update Data Lakes user deletion note
  src/connections/storage/data-lakes/index.md
Labels: content-update

#6765 Update index.md - update segment profiles destination FAQ
  src/connections/destinations/catalog/actions-segment-profiles/index.md
Labels: KCS

#6794 Update braze-middleware-react-native.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-middleware-react-native.md
Labels: fixed-content

#6796 Add launchdarkly actions note
  src/_includes/components/actions-fields.html
Labels: content-update

#6772 Update index.md - add profile to list engage, listID restraints
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: KCS

#6797 catalog 7/9/24
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6798 Release 24.28.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/jimo/index.md
  src/connections/destinations/catalog/user_guiding/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-middleware-react-native.md
  src/connections/storage/data-lakes/index.md
  src/privacy/consent-management/configure-consent-management.md
Labels: release

#6801 adding links to braze and iterable
  src/engage/audiences/linked-audiences.md
Labels: content-update

#6790 Add Profiles Sync Sample Query
  src/unify/profiles-sync/sample-queries.md
Labels: KCS

#6805 Sync Overview docs release [DOC-899]
  src/connections/reverse-etl/images/sync-overview.png
  src/connections/reverse-etl/index.md
Labels: new-feature

#6766 Add Warning to Unify/Engage Source Debugger
  src/unify/debugger.md
Labels: content-update, KCS

#6755 Remove Support Reference from Using Predictions
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update, KCS

#6810 july 11 '24 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6812 Master to develop after one-off
  src/connections/reverse-etl/images/sync-overview.png
  src/connections/reverse-etl/index.md
Labels: back-end

#6811 Release 24.28.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/convertly/index.md
  src/connections/destinations/catalog/metricstory/index.md
  src/connections/sources/catalog/cloud-apps/onetrust/OneTrust-Segment-Track-API-Integration.json
  src/connections/sources/catalog/cloud-apps/onetrust/index.md
  src/engage/audiences/linked-audiences.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/debugger.md
  src/unify/profiles-sync/sample-queries.md
Labels: release

#6814 Update Kotlin migration guide
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
Labels: content-update

#6816 Master to develop after one-off
  src/_data/sidenav/main.yml
  src/engage/audiences/recommendation-audiences.md
Labels: back-end

#6694 Update Engage Premier EOS banner for Readability
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/onboarding.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
Labels: content-update, KCS

#6817 Acoustic is out of beta, remove hidden and beta
  src/connections/destinations/catalog/actions-acoustic/index.md
Labels: content-update

#6823 updating catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6824 Release 24.29.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-acoustic/index.md
  src/connections/destinations/catalog/fl0/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/onboarding.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
Labels: release

#6821 Fixed Consent Management Typo
  src/privacy/consent-management/consent-in-segment-connections.md
Labels: fixed-content, KCS

#6828 Merge `master` into `develop` after one-off
  src/getting-started/use-cases/guide.md
  src/getting-started/use-cases/index.md
  src/getting-started/use-cases/reference.md
  src/getting-started/use-cases/setup.md
Labels: back-end

#6825 Add EU endpoint callout to HTTP API doc
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#6802 Create faq.md
  src/_data/sidenav/strat.yml
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: KCS

#6831 Add note for monitoring Bulk API uploads & warning for External Id
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: KCS

#6829 Multiple instances
  src/protocols/transform/index.md
Labels: KCS

#6803 Update Analytics.js Troubleshooting Info
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#6736 Update Engage Quickstart to Improve Formatting
  src/engage/quickstart.md
Labels: KCS

#6832 making catalog for deploy
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6833 Release 24.29.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/quickstart.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/protocols/transform/index.md
Labels: release

#6835 remove OpenAI mentions at request of Chris Lyon
  src/connections/functions/copilot.md
  src/engage/audiences/generative-audiences.md
Labels: back-end

#6836 Master to develop after one-off
  src/connections/functions/copilot.md
  src/engage/audiences/generative-audiences.md
Labels: back-end

#6822 Update category name restriction, fix grammar error
  src/privacy/consent-management/configure-consent-management.md
Labels: content-update

#6839 Fix spelling error in "Consent in RETL" docs
  src/privacy/consent-management/consent-in-retl.md
Labels: content-update

#6850 Catalog Update 23 July 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6851 Release 24.30.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/spec/group.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-retl.md
Labels: release

#6853 Update braze-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/braze-kotlin-android.md
Labels: KCS

#6838 Update faq.md
  src/privacy/faq.md
Labels: KCS

#6842 Adding a note about Scope of Transformations
  src/protocols/transform/index.md
Labels: KCS

#6819 Specify AMD64 in Docker Compose File
  docker-compose.yml
Labels: back-end

#6826 Taboola Action Destination docs
  src/connections/destinations/catalog/actions-taboola-actions/images/add_mapping.png
  src/connections/destinations/catalog/actions-taboola-actions/images/add_mapping_popup.png
  src/connections/destinations/catalog/actions-taboola-actions/images/audience_settings.png
  src/connections/destinations/catalog/actions-taboola-actions/images/device_id_identifier_config.png
  src/connections/destinations/catalog/actions-taboola-actions/images/enabled_mapping.png
  src/connections/destinations/catalog/actions-taboola-actions/images/engage_id_resolution_settings.png
  src/connections/destinations/catalog/actions-taboola-actions/index.md
Labels: new-integration

#6844 Scrub linked profiles
  src/unify/data-graph/data-graph.md
  src/unify/data-graph/index.md
  src/unify/data-graph/linked-events.md
  src/unify/data-graph/setup-guides/BigQuery-setup.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/redshift-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
  src/unify/linked-profiles/index.md
Labels: content-update

#6847 Update index.md - user-provided data collection (GA4 Web)
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#5576 Add info to return event in handler to sent through destination
  src/connections/functions/insert-functions.md
Labels: KCS

#6848 Update Mutiny Destination to Remove support for page events
  src/connections/destinations/catalog/mutiny/index.md
Labels: content-update

#6854 Add note w context on Consent Management's RETL limit implications
  src/privacy/consent-management/consent-in-retl.md
Labels: content-update

#6857 Catalog Update 25 July 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6855 Add docs for amazon ads destination
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-amazon-amc/index.md
Labels: new-integration

#6834 Custom Domains GA docs [DOC-980]
  src/_data/products.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/domain-delegation-solutions.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/custom-domain.md
  src/connections/sources/images/custom-domain.png
Labels: new-feature

#6856 Update Deprecated and Beta Destinations
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-linkedin-conversions/index.md
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-create-new-role.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-leads.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-newfolder.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-newservice.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-perms.png
  src/connections/destinations/catalog/marketo-static-lists/images/personas-add-emailtrait.png
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/personas-display-video-360/images/dv360-1-select-destination.png
  src/connections/destinations/catalog/personas-display-video-360/index.md
Labels: content-update

#6858 Release 24.30.2
  docker-compose.yml
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/domain-delegation-solutions.md
  src/connections/aws-privatelink.md
  src/connections/destinations/catalog/actions-amazon-amc/index.md
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-linkedin-conversions/index.md
  src/connections/destinations/catalog/actions-taboola-actions/images/add_mapping.png
  src/connections/destinations/catalog/actions-taboola-actions/images/add_mapping_popup.png
  src/connections/destinations/catalog/actions-taboola-actions/images/audience_settings.png
  src/connections/destinations/catalog/actions-taboola-actions/images/device_id_identifier_config.png
  src/connections/destinations/catalog/actions-taboola-actions/images/enabled_mapping.png
  src/connections/destinations/catalog/actions-taboola-actions/images/engage_id_resolution_settings.png
  src/connections/destinations/catalog/actions-taboola-actions/index.md
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-create-new-role.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-leads.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-newfolder.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-newservice.png
  src/connections/destinations/catalog/marketo-static-lists/images/marketosl-perms.png
  src/connections/destinations/catalog/marketo-static-lists/images/personas-add-emailtrait.png
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/mutiny/index.md
  src/connections/destinations/catalog/personas-display-video-360/images/dv360-1-select-destination.png
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/braze-kotlin-android.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/custom-domain.md
  src/connections/sources/images/custom-domain.png
  src/privacy/consent-management/consent-in-retl.md
  src/privacy/faq.md
  src/protocols/transform/index.md
  src/unify/data-graph/data-graph.md
  src/unify/data-graph/index.md
  src/unify/data-graph/linked-events.md
  src/unify/data-graph/setup-guides/BigQuery-setup.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/redshift-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
  src/unify/linked-profiles/index.md
Labels: release

#6861 Batching with Shared Secret Clarification
  src/connections/destinations/catalog/actions-webhook/index.md
Labels: content-update, KCS

#6762 Update source-functions.md - Source function logging limits
  src/connections/functions/source-functions.md
Labels: KCS

#6863 Remove mentions of deprecated destination
  src/_data/catalog/slugs.yml
  src/_data/regional-support.yml
  src/_data/sidenav/strat.yml
  src/engage/using-engage-data.md
  src/folders.txt
Labels: content-update

#6827 LA advanced conditions
  src/engage/audiences/linked-audiences.md
  src/engage/images/entity_explorer.png
  src/engage/images/operator_selection.png
Labels: content-update

#6760 Update destination-functions.md - console.log UI limit
  src/connections/functions/destination-functions.md
Labels: KCS

#6867 Deleted Tracking Plan
  src/protocols/faq.md
Labels: KCS

#6869 Add Google Universal Analytics Redirects
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/google-analytics/ga4-plans.md
  src/connections/destinations/catalog/google-analytics/images/ab-mapping.png
  src/connections/destinations/catalog/google-analytics/images/checkout-funnel.png
  src/connections/destinations/catalog/google-analytics/images/dimension-mapping-google-analytics.png
  src/connections/destinations/catalog/google-analytics/images/dimension-mapping.png
  src/connections/destinations/catalog/google-analytics/images/dimensions-metrics.png
  src/connections/destinations/catalog/google-analytics/images/site-search.png
  src/connections/destinations/catalog/google-analytics/images/tracking-method.png
  src/connections/destinations/catalog/google-analytics/index.md
  src/connections/destinations/catalog/google-analytics/migrating.md
Labels: back-end, fixed-site

#6871 Updated stratnav and added redirect for new DV360 destination
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-display-video-360/index.md
Labels: back-end

#6860 Update GA4 Actions to fix Typo
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: fixed-content

#6859 Update Audiences CSV Download Guidance
  src/engage/audiences/index.md
Labels: content-update, KCS

#6872 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6882 Update usermaven docs for public beta
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-usermaven/index.md
Labels: content-update
