Repository segmentio/segment-docs, pull requests merged in 2024-05, with the labels that each got.

#6465 Added a note about destination filters
  src/protocols/transform/index.md
Labels: KCS

#6478 updating image path to correct place
  src/privacy/images/privacy-edit-matcher.png
  src/privacy/portal.md
Labels: fixed-content

#6439 Add documentation for Magellan AI (Actions) Destination
  src/connections/destinations/catalog/actions-magellan-ai/index.md
Labels: new-integration

#6480 Remove internal-only error code in the Delivery Overview discards table
  src/_includes/content/delivery-overview-discards.html
Labels: back-end

#6455 OneTrust wrapper doc [DOC-895]
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/onetrust-wrapper.md
Labels: content-update

#6450 Arrays/objects are not supported in Broadcasts
  src/engage/content/email/template.md
Labels: content-update, KCS

#6491 Catalog Update 05022024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6123 Added hyperlink for sending data to destinations via journey's
  src/engage/journeys/faq-best-practices.md
Labels: KCS

#6152 Add FAQ for Connections Spec
  src/connections/index.md
Labels: KCS

#6176 Add Email Alert Steps for Failed Events/Syncs
  src/connections/event-delivery.md
Labels: KCS

#6490 Misc consent mgmt items [DOC-906]
  src/_data/sidenav/main.yml
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-faq.md
Labels: content-update

#6499 Generative Audiences GA
  src/engage/audiences/generative-audiences.md
Labels: content-update

#6501 Merge `master` into `develop`
  src/engage/audiences/generative-audiences.md
Labels: back-end

#6456 Klaviyo - Add note about 'Enforce email as primary identifier' setting
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#6504 remove beta callout
  src/connections/destinations/catalog/actions-listrak/index.md
Labels: content-update

#6503 Remove callout for old destination
  src/connections/destinations/catalog/actions-kameleoon/index.md
Labels: content-update

#6466 Update destination-filters.md
  src/connections/destinations/destination-filters.md
Labels: KCS

#6509 Update index.md
  src/connections/reverse-etl/index.md
Labels: KCS

#6485 Add events.win destination docs
  src/connections/destinations/catalog/events-win/index.md
Labels: new-integration

#6460 Update Profile API Guidance on Escape Characters
  src/unify/profile-api.md
Labels: content-update

#6258 Update Action Mapping Directions
  src/connections/destinations/actions.md
Labels: automated issue, content-update, KCS

#6486 TikTok Pixel - remove the Use Existing Pixel setting from our docs
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
Labels: content-update, KCS

#6511 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6512 Release 24.19.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-chartmogul/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-kameleoon/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/actions-stackadapt/images/snowflake-mappings.png
  src/connections/destinations/catalog/actions-stackadapt/index.md
  src/connections/destinations/catalog/actions-tiktok-pixel/index.md
  src/connections/destinations/catalog/events-win/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/destination-filters.md
  src/connections/event-delivery.md
  src/connections/functions/source-functions.md
  src/connections/index.md
  src/connections/reverse-etl/index.md
  src/engage/journeys/faq-best-practices.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-faq.md
  src/unify/profile-api.md
Labels: release

#6513 Fix typo in image filename
  src/connections/destinations/catalog/actions-stackadapt/index.md
Labels: fixed-content

#5658 Update faq.md
  src/privacy/faq.md
Labels: KCS

#6516 Add Actions fields to DV360 (Actions) docs
  src/connections/destinations/catalog/actions-display-video-360/index.md
Labels: fixed-content

#6522 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6514 Source overview updates [DOC-911]
  src/connections/sources/images/source-overview.jpeg
  src/connections/sources/images/source-overview.png
  src/connections/sources/index.md
Labels: content-update

#6523 Release 24.19.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-stackadapt/index.md
  src/connections/sources/catalog/cloud-apps/azure/index.md
  src/connections/sources/images/source-overview.jpeg
  src/connections/sources/images/source-overview.png
  src/connections/sources/index.md
  src/privacy/faq.md
Labels: release

#6525 schematic documentation
  src/connections/destinations/catalog/actions-schematic/index.md
Labels: new-integration

#6528 Add Xtremepush (Actions) Destination docs.
  src/connections/destinations/catalog/actions-xtremepush/index.md
Labels: new-integration

#6531 Revamp Snowflake dest docs [DOC-910]
  src/connections/storage/catalog/snowflake/index.md
Labels: content-update

#6535 Info around open-source projects not officially supported by Segment
  src/guides/how-to-guides/import-historical-data.md
Labels: KCS

#6520 Engage Audience Destination Update [DOC-892]
  src/_data/sidenav/main.yml
  src/engage/audiences/index.md
  src/engage/audiences/send-audience-data.md
  src/engage/images/destinations_table.png
Labels: content-update

#6533 Fix analytics.js plugin section
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#6527 Update Segment Query Language docs
  src/api/public-api/query-language.md
Labels: content-update

#6540 catalog 05/14/24
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6541 Release 24.20.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/api/public-api/query-language.md
  src/connections/destinations/catalog/actions-schematic/index.md
  src/connections/destinations/catalog/actions-xtremepush/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/engage/audiences/index.md
  src/engage/audiences/send-audience-data.md
  src/engage/faqs.md
  src/engage/images/destinations_table.png
  src/guides/how-to-guides/import-historical-data.md
Labels: release

#6542 Update index.md - fixed typo
  src/connections/reverse-etl/index.md
Labels: KCS

#6539 Add more info on send_to for GA4
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#6547 Remove Automatic Event Collection References from Native Mobile Spec
  src/connections/spec/mobile.md
Labels: content-update

#6425 Acoustic Catalog initial submit
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_152537_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_152921_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_153616_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_155823_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_155857_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_160007_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_161221_image.png
  src/connections/destinations/catalog/actions-acoustic/index.md
Labels: new-integration

#6546 Rename Bucket Tracking Key to Publishable Key
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/bucket/index.md
Labels: content-update

#6552 Update create.md
  src/protocols/tracking-plan/create.md
Labels: KCS

#6548 Update paragraph about Google sunsetting Google Enhanced Conversion L…
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: KCS

#6529 linked audiences p0.1
  src/engage/audiences/linked-audiences.md
  src/engage/images/conditions.png
Labels: new-feature

#6554 Release 24.20.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_152537_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_152921_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_153616_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_155823_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_155857_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_160007_image.png
  src/connections/destinations/catalog/actions-acoustic/assets/20240422_161221_image.png
  src/connections/destinations/catalog/actions-acoustic/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/bucket/index.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/index.md
  src/connections/spec/mobile.md
  src/engage/audiences/linked-audiences.md
  src/engage/images/conditions.png
  src/protocols/tracking-plan/create.md
Labels: release

#6561 fix typo
  src/connections/destinations/catalog/actions-schematic/index.md
Labels: fixed-content

#6564 Remove private as destination is now live
  src/connections/destinations/catalog/actions-moloco-rmp/index.md
Labels: content-update

#6563 Add note to Xtremepush Classic destination mentioning Actions destination
  src/connections/destinations/catalog/actions-xtremepush/index.md
  src/connections/destinations/catalog/xtremepush/index.md
Labels: content-update

#6562 fixing broken link
  src/engage/audiences/linked-audiences.md
Labels: fixed-content

#6566 Release 24.20.3
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-moloco-rmp/index.md
  src/connections/destinations/catalog/actions-schematic/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/actions-xtremepush/index.md
  src/connections/destinations/catalog/xtremepush/index.md
  src/engage/audiences/linked-audiences.md
Labels: release

#6568 fix typo
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
Labels: KCS

#6567 Refactor destination dossier to include Engage-only option [DOC-882] 🦆
  scripts/catalog/utilities.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: fixed-site

#6572 Add legacy feature explanation
  src/partners/enable-with-segment.md
Labels: content-update

#6449 Add FAQ about Audience Historical Data
  src/engage/audiences/index.md
Labels: content-update, KCS

#6576 Remove hidden and private for new integration
  src/connections/destinations/catalog/actions-chartmogul/index.md
Labels: content-update

#6575 Update strat.yml with new Marketo Lists destination
  src/_data/sidenav/strat.yml
Labels: back-end

#6570 Add info about engage frontmatter to CONTRIBUTING.md guide
  CONTRIBUTING.md
Labels: back-end

#6573 dbt and Git Extensions Public Beta [DOC-862]
  src/_data/sidenav/main.yml
  src/segment-app/extensions/dbt.md
  src/segment-app/extensions/git.md
  src/segment-app/extensions/index.md
Labels: new-feature

#6577 Catalog Update 05212024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6578 Release 24.21.1
  CONTRIBUTING.md
  scripts/catalog/utilities.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/destination-dossier.html
  src/api/public-api/query-language.md
  src/connections/destinations/catalog/actions-chartmogul/index.md
  src/connections/destinations/catalog/actions-display-video-360/index.md
  src/connections/destinations/catalog/actions-linkedin-audiences/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/fl0/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/connections/sources/catalog/cloud-apps/blip/index.md
  src/connections/sources/catalog/cloud-apps/engage-events/index.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences-use-cases.md
  src/partners/enable-with-segment.md
  src/segment-app/extensions/dbt.md
  src/segment-app/extensions/git.md
  src/segment-app/extensions/index.md
Labels: release

#6224 Update index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
Labels: KCS

#6590 Add info about /debug endpoint
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#6583 Update data-lakes-manual-setup.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
Labels: KCS

#6433 Update Identity Resolution External IDs
  src/unify/identity-resolution/externalids.md
Labels: content-update, KCS

#6598 Catalog Update 052324
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6599 Release 24.21.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/sources/catalog/cloud-apps/stripe/index.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/unify/identity-resolution/externalids.md
Labels: release

#6603 Remove duplicate LinkedIn Audiences folder
  src/connections/destinations/catalog/linkedin-audiences/index.md
Labels: back-end

#6602 Update identity.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
Labels: KCS

#6605 Fix SFMC (Actions) destination slug
  src/connections/destinations/catalog/salesforce-marketing-cloud-actions/index.md
Labels: back-end

#6588 Add q about data freshness to Delivery Overview docs
  src/connections/delivery-overview.md
Labels: content-update

#6500 Unified Profiles edits [DOC-908]
  src/unified-profiles/segment-for-flex.md
Labels: fixed-content

#6593 Add context about batching to destination overview page [DOC-904]
  src/connections/destinations/index.md
Labels: content-update

#6610 today's catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6611 Release 24.22.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/delivery-overview.md
  src/connections/destinations/catalog/actions-kafka/index.md
  src/connections/destinations/catalog/linkedin-audiences/index.md
  src/connections/destinations/catalog/salesforce-marketing-cloud-actions/index.md
  src/connections/destinations/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/unified-profiles/segment-for-flex.md
Labels: release

#6435 Adding warning about device mode sources and multi-instances of destinationsUpdate add-destination.md
  src/connections/destinations/add-destination.md
Labels: KCS

#6608 Update sentence for clarity
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
Labels: KCS

#6259 Add considerations for multi instance of destinations
  src/connections/destinations/add-destination.md
Labels: automated issue, KCS

#5059 Tracking Plan Ids
  src/protocols/faq.md
Labels: content-update

#6613 Fix typos on query-language.md
  src/api/public-api/query-language.md
Labels: content-update

#6589 adding definitions to linked audiences
  src/engage/audiences/linked-audiences.md
Labels: content-update

#6607 Update Source Overview tab information
  src/connections/sources/index.md
Labels: KCS

#6580 Pushwoosh Source doc
  src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
Labels: new-integration

#6617 Fix link to Kotlin Firebase plugin
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/firebase-kotlin-android.md
Labels: back-end

#6418 Update Snowflake Setup
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: content-update

#6419 Adding FAQs
  src/connections/destinations/catalog/actions-webhook/index.md
Labels: KCS

#6587 linked audiences use cases mini edit
  src/engage/audiences/linked-audiences-use-cases.md
Labels: content-update

#6623 Remove connections alerting beta note
  src/guides/how-to-guides/set-up-notifications-alerts.md
Labels: fixed-content

#6475 Add section on anonymousId config option
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
Labels: KCS

#6625 Server-side libraries troubleshooting information + Vale pass
  src/_includes/content/server-side-troubleshooting.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/go/v2/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/node/classic.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
  src/connections/sources/catalog/libraries/server/rust/index.md
Labels: content-update

#6626 Catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6627 Release 24.22.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/server-side-troubleshooting.md
  src/api/public-api/query-language.md
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/images/autoinstrumentation_signals.png
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/setup.md
  src/connections/destinations/add-destination.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-pendo-web/index.md
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/churned/index.md
  src/connections/destinations/catalog/pendo/index.md
  src/connections/destinations/index.md
  src/connections/sources/catalog/cloud-apps/pendo/index.md
  src/connections/sources/catalog/cloud-apps/pushwoosh/index.md
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/firebase-kotlin-android.md
  src/connections/sources/catalog/libraries/server/clojure/index.md
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/go/v2/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/connections/sources/catalog/libraries/server/net/index.md
  src/connections/sources/catalog/libraries/server/node/classic.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/php/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/server/ruby/index.md
  src/connections/sources/catalog/libraries/server/rust/index.md
  src/connections/sources/index.md
  src/engage/audiences/linked-audiences-use-cases.md
  src/engage/audiences/linked-audiences.md
  src/guides/how-to-guides/set-up-notifications-alerts.md
  src/protocols/faq.md
  src/segment-app/iam/images/asset_MSaDZk2f.png
  src/segment-app/iam/images/asset_generate_scim_token.png
  src/segment-app/iam/images/asset_s19XDgWX.png
  src/segment-app/iam/images/generate_sso_token.jpg
  src/segment-app/iam/images/okta_sso.png
  src/segment-app/iam/images/okta_sso_step1.jpg
  src/segment-app/iam/images/okta_sso_step2.jpg
  src/segment-app/iam/images/scim_edit_group.jpg
  src/segment-app/iam/images/scim_edit_groups.png
  src/segment-app/iam/images/sso_certificate.jpg
  src/segment-app/iam/images/sso_domain.jpg
  src/segment-app/iam/scim.md
  src/segment-app/iam/sso.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
  templates/destinations.example.yml
Labels: release

#6629 Correct folder name to match slug
  src/connections/sources/catalog/cloud-apps/pushwoosh-source/index.md
Labels: back-end

#6624 Add section on native Amplitude events
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/amplitude-swift.md
Labels: KCS

#6632 Remove beta tag for Podscribe
  src/connections/destinations/catalog/actions-podscribe/index.md
Labels: fixed-content

#6631 Remove Predictions HIPAA Callout
  src/unify/Traits/predictions/index.md
Labels: content-update

#6633 Update mobile spec to reflect new libraries
  src/connections/spec/mobile.md
Labels: KCS
