Repository segmentio/segment-docs, pull requests merged in 2024-09, with the labels that each got.

#6396 Update Context Spec Code for GroupId
  src/connections/spec/common.md
Labels: KCS

#6999 Update roles.md
  src/segment-app/iam/roles.md
Labels: KCS

#6981 Added IP Address to Geolocation Conversion FAQ
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: content-update, KCS

#7002 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7003 Release 24.36.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/connections/spec/common.md
  src/segment-app/iam/roles.md
Labels: release

#6998 add route information for oauth
  src/connections/oauth.md
Labels: KCS

#6939 Google Customer Match List [DOC-979]
  src/connections/destinations/catalog/actions-1flow/index.md
  src/connections/destinations/catalog/actions-adobe-target-cloud/index.md
  src/connections/destinations/catalog/actions-adobe-target-web/index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-blackbaud-raisers-edge-nxt/index.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-hubspot-web/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/amplitude-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/amplitude-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/amplitude-react-native.md
Labels: content-update

#7004 Hide bucket actions
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/bucket/index.md
Labels: back-end

#7012 [netlify-build] Adding additional empty line to apply styling
  src/privacy/faq.md
  src/privacy/user-deletion-and-suppression.md
Labels: fixed-site

#7011 Adding new topic to FAQ about ChunkLoadError
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: KCS

#6978 Update setup.md
  src/connections/reverse-etl/setup.md
Labels: content-update

#7014 update .flush info
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: content-update

#7017 [Dynamic Yield] adding instructions for ip allowlisting
  src/connections/destinations/catalog/actions-dynamic-yield-audiences/index.md
Labels: content-update

#7015 Reverse ETL 2.0 feedback
  src/connections/destinations/catalog/actions-sprig-web/index.md
  src/connections/destinations/catalog/actions-stackadapt-cloud/index.md
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/reverse-etl/reverse-etl-catalog.md
  src/connections/reverse-etl/setup.md
  src/connections/reverse-etl/system.md
Labels: content-update

#7006 Mappings 2.0 [DOC-990]
  src/connections/destinations/actions.md
  src/connections/destinations/index.md
  src/connections/reverse-etl/setup.md
Labels: new-feature

#7019 Release 24.37.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-1flow/index.md
  src/connections/destinations/catalog/actions-adobe-target-cloud/index.md
  src/connections/destinations/catalog/actions-adobe-target-web/index.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-blackbaud-raisers-edge-nxt/index.md
  src/connections/destinations/catalog/actions-dynamic-yield-audiences/index.md
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-google-analytics-4-web/index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-hubspot-web/index.md
  src/connections/destinations/catalog/actions-intercom-web/index.md
  src/connections/destinations/catalog/actions-pardot/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/actions-snap-conversions/index.md
  src/connections/destinations/catalog/actions-sprig-web/index.md
  src/connections/destinations/catalog/actions-stackadapt-cloud/index.md
  src/connections/destinations/catalog/bucket-web/index.md
  src/connections/destinations/catalog/bucket/index.md
  src/connections/destinations/catalog/jimo/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/destinations/index.md
  src/connections/oauth.md
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/reverse-etl/reverse-etl-catalog.md
  src/connections/reverse-etl/setup.md
  src/connections/reverse-etl/system.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/amplitude-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/destination-plugins/amplitude-kotlin-android.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/amplitude-react-native.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/storage/data-lakes/data-lakes-manual-setup.md
  src/privacy/faq.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#7024 Adding a note about "initialized" event and track() callback
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#7020 updated doc based on feedback
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
Labels: content-update

#7025 Fix section order in Setup Reverse ETL docs
  src/connections/reverse-etl/setup.md
Labels: fixed-content

#7026 Fix info/notes box sections that have wrong spacing
  src/connections/destinations/catalog/actions-moloco-rmp/index.md
  src/connections/destinations/catalog/inkit/index.md
  src/connections/destinations/catalog/retina/index.md
  src/connections/destinations/catalog/userlist/index.md
Labels: back-end

#6761 Update insert-functions.md - insert funk FAQ logging limit
  src/connections/functions/insert-functions.md
Labels: KCS

#7027 Duplicate Mappings
  src/connections/destinations/actions.md
  src/connections/reverse-etl/setup.md
  src/engage/audiences/send-audience-data.md
  src/engage/journeys/send-data.md
Labels: new-feature

#7021 Trait Activation for classic destinations
  src/engage/trait-activation/index.md
Labels: content-update

#7028 Update Salesforce Unify Direct Integration
  src/unify/salesforce-unify.md
Labels: content-update

#7030 20240912 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7031 Release 24.37.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-moloco-rmp/index.md
  src/connections/destinations/catalog/inkit/index.md
  src/connections/destinations/catalog/retina/index.md
  src/connections/destinations/catalog/userlist/index.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/setup.md
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/engage/audiences/send-audience-data.md
  src/engage/journeys/send-data.md
  src/engage/trait-activation/index.md
  src/segment-app/extensions/dbt.md
  src/unify/salesforce-unify.md
Labels: release

#7029 Add common questions about custom proxy setup
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#7035 Automatic retry handling docs [DOC-898]
  src/connections/reverse-etl/manage-retl.md
Labels: new-feature

#7032 Update PrivateLink supported regions and Redshift step link
  src/connections/aws-privatelink.md
Labels: content-update

#7036 Clarify window.analytics.initialized behavior in documentation
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#7038 Hubspot Mappings 2.0 docs
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: content-update

#7037 Master 2 develop after one-off
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: back-end

#6983 Create documentation for Quin AI source integration
  src/connections/sources/catalog/cloud-apps/quin-ai/index.md
Labels: new-integration

#6977 Add model number info
  src/connections/spec/common.md
Labels: KCS

#6905 Update user-deletion-and-suppression.md
  src/privacy/user-deletion-and-suppression.md
Labels: KCS

#7043 Catalog Update 17 September 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7044 Release 24.38.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/aws-privatelink.md
  src/connections/sources/catalog/cloud-apps/quin-ai/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/common.md
  src/privacy/user-deletion-and-suppression.md
Labels: release

#7039 Rename Recommendation Audiences to Product Based Audiences
  src/_data/sidenav/main.yml
  src/engage/audiences/product-based-audiences.md
Labels: content-update

#7046 Correct Snowflake Setup Typo
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: fixed-content

#7008 suggested mappings [DOC-993]
  src/_includes/content/suggested-mappings-nutrition-facts.html
  src/connections/destinations/actions.md
  src/connections/reverse-etl/setup.md
  src/connections/reverse-etl/suggested-mappings-nutrition-facts.md
Labels: new-feature

#7045 Fix Data Graph Snowflake Setup Formatting
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: fixed-content

#7048 Update IP Allowlisting note
  src/_includes/content/warehouse-ip.html
Labels: content-update

#7055 Update the format section of the style guide to include HTTP response code section
  styleguide.md
Labels: back-end

#7050 Add Docs for New Contentstack Destinations
  src/connections/destinations/catalog/actions-contentstack/index.md
  src/connections/destinations/catalog/contentstack-web/index.md
Labels: new-integration

#7052 Update Product Based Audiences AI Label
  src/_data/sidenav/main.yml
  src/_includes/content/product-based-audiences-nutrition-facts.html
  src/engage/audiences/product-based-audiences-nutrition-label.md
  src/engage/audiences/recommendation-audiences-nutrition-label.md
Labels: content-update

#7056 Update Journeys Step Limits
  src/engage/product-limits.md
Labels: content-update

#7057 Catalog Update 19 September 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7058 Release 24.38.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/_includes/content/product-based-audiences-nutrition-facts.html
  src/_includes/content/suggested-mappings-nutrition-facts.html
  src/_includes/content/warehouse-ip.html
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-contentstack/index.md
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/contentstack-web/index.md
  src/connections/reverse-etl/setup.md
  src/connections/reverse-etl/suggested-mappings-nutrition-facts.md
  src/connections/sources/catalog/cloud-apps/salesforce-unify/index.md
  src/engage/audiences/product-based-audiences-nutrition-label.md
  src/engage/audiences/product-based-audiences.md
  src/engage/audiences/recommendation-audiences-nutrition-label.md
  src/engage/product-limits.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
  styleguide.md
Labels: release

#7065 Add updated context re deleted records to RETL system page
  src/connections/reverse-etl/system.md
Labels: content-update

#7067 Update Engage Audiences Overview
  src/engage/audiences/index.md
Labels: content-update

#7064 Add V2 Actions Callout to Braze Cloud Actions Docs
  src/connections/destinations/catalog/actions-braze-cloud/index.md
Labels: content-update

#7068 Move Salesforce Unify Direct Screenshot
  src/connections/sources/catalog/cloud-apps/salesforce-unify/index.md
  src/connections/sources/images/select_mappings.png
Labels: fixed-site

#7069 catalog 9/24/2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7070 Release 24.39.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/reverse-etl/system.md
  src/connections/sources/catalog/cloud-apps/salesforce-unify/index.md
  src/connections/sources/images/select_mappings.png
  src/engage/audiences/index.md
Labels: release

#7041 Linked Audience Limits [DOC-933]
  src/_data/sidenav/main.yml
  src/engage/audiences/linked-audiences-limits.md
Labels: content-update

#7077 Update RETL Query Length Limit
  src/connections/reverse-etl/system.md
Labels: fixed-content

#7060 Google Sheets - Mappings 2.0 [DOC-978]
  src/connections/destinations/catalog/actions-google-sheets/index.md
Labels: content-update

#7079 Rollback automatic retry handling docs
  src/connections/reverse-etl/manage-retl.md
Labels: back-end

#7080 Add TrustArc link to the consent mgmt docs
  src/privacy/consent-management/configure-consent-management.md
Labels: content-update

#7074 Fix links in the Analytics for Node.js docs
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: fixed-content

#7061 Facebook Conversions API Mappings 2.0 [DOC-975]
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
Labels: content-update

#7073 Add note about iOS IDFA settings conflict to ID sync page
  src/engage/trait-activation/id-sync.md
Labels: content-update

#7083 Release 24.39.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/actions-facebook-conversions-api/index.md
  src/connections/destinations/catalog/actions-google-sheets/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/reverse-etl/system.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/engage/audiences/linked-audiences-limits.md
  src/engage/trait-activation/id-sync.md
  src/privacy/consent-management/configure-consent-management.md
Labels: release

#7085 [Hubspot Actioons] - spelling correction
  src/_includes/components/actions-fields.html
Labels: fixed-content

#7071 Functions Copilot GA
  src/connections/functions/copilot.md
Labels: content-update

#7086 Move destination settings up one heading level
  src/_includes/components/actions-fields.html
  src/connections/destinations/catalog/actions-customerio/index.md
Labels: fixed-site

#7089 master to develop after one-off
  src/connections/functions/copilot.md
Labels: back-end

#7081 Salesforce (Actions) Mappings 2.0
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: content-update
