Repository segmentio/segment-docs, pull requests merged in 2024-06, with the labels that each got.

#6286 Provide information on sending email data to Iterable destination
  src/connections/destinations/catalog/iterable/index.md
Labels: KCS

#6306 Update facebook-app-events-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/facebook-app-events-swift.md
Labels: KCS

#6393 Update v2.md
  src/connections/spec/ecommerce/v2.md
Labels: KCS

#6347 Add Troubleshooting Note Regarding Webhook Limit for Free Plans
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: automated issue, KCS

#6400 Indicate time on audience builder’s UI is based on local timezone
  src/engage/audiences/index.md
Labels: KCS

#6462 Add note about “Search for user” in Journeys
  src/engage/journeys/journeys-analytics.md
Labels: KCS

#6545 Audience cycle error
  src/engage/audiences/index.md
Labels: KCS

#5466 Added FAQ Entry.md
  src/engage/faqs.md
Labels: KCS

#6559 Snowflake key-pair authentication GA [DOC-865]
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/connections/storage/catalog/snowflake/index.md
Labels: new-feature

#6616 Add faq for App Name
  src/connections/destinations/catalog/actions-pinterest-conversions-api/index.md
Labels: KCS

#6643 Add more granual permissions information to Klaviyo (Actions) destination
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: fixed-content

#6644 Master to develop after one-off
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/connections/storage/catalog/snowflake/index.md
Labels: back-end

#6645 Add Signals SwiftUI info
  src/connections/auto-instrumentation/setup.md
  src/connections/sources/catalog/libraries/mobile/apple/live-plugins.md
Labels: content-update

#6636 Remove section referencing iAD
  src/connections/destinations/catalog/singular/index.md
Labels: KCS

#6652 running catalog 2024/06/94
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6646 Fix Profiles Sync Typo
  src/unify/profiles-sync/profiles-sync-setup/databricks-profiles-sync.md
Labels: fixed-content

#6653 Release 24.23.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/api/public-api/query-language.md
  src/connections/auto-instrumentation/setup.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-pinterest-conversions-api/index.md
  src/connections/destinations/catalog/actions-podscribe/index.md
  src/connections/destinations/catalog/iterable/index.md
  src/connections/destinations/catalog/singular/index.md
  src/connections/sources/catalog/cloud-apps/pushwoosh-source/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/amplitude-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/facebook-app-events-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/live-plugins.md
  src/connections/spec/ecommerce/v2.md
  src/connections/spec/mobile.md
  src/engage/audiences/index.md
  src/engage/faqs.md
  src/engage/journeys/journeys-analytics.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/unify/Traits/predictions/index.md
  src/unify/profiles-sync/profiles-sync-setup/databricks-profiles-sync.md
Labels: release

#6642 Update faq-segment-dissolution-vat.pdf
  src/assets/pdf/faq-segment-dissolution-vat.pdf
Labels: content-update

#6526 Update index.md - tiktok audiences minimum size requirement
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: KCS

#6620 Attio: document support for new batching mode
  src/connections/destinations/catalog/actions-attio/index.md
Labels: new-integration

#6585 resizing image to reduce blur [netlify-build]
  src/engage/images/conditions.png
  src/unify/images/data-graph-example.png
  src/unify/images/snowflake-setup.png
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
Labels: fixed-content

#6672 Move StackAdapt docs to folder matching slug
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/copy-pixel-id.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/email-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/install-pixel-link.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/order-completed-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/snowflake-mappings.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/user-registered-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/index.md
Labels: fixed-content

#6671 Removed the phrase "Braze is complex"
  src/connections/destinations/catalog/braze/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/braze-swift.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
Labels: fixed-content

#6664 Added link to Reverse ETL catalog
  src/connections/destinations/index.md
Labels: fixed-content

#6662 Update another Reverse ETL Catalog link
  src/connections/reverse-etl/index.md
Labels: fixed-content

#6675 Unhide Reverse ETL Catalog
  src/connections/reverse-etl/reverse-etl-catalog.md
Labels: back-end

#6670 Add Anonymous Predictive Traits limitation
  src/unify/Traits/predictions/index.md
Labels: content-update

#6668 Klaviyo classic destination migration info
  src/connections/destinations/catalog/klaviyo/images/migrated-dest.png
  src/connections/destinations/catalog/klaviyo/images/migrated-settings.png
  src/connections/destinations/catalog/klaviyo/index.md
Labels: content-update

#6666 Add section about auto-migration for legacy Google Ads Conversions mappings [DOC-934]
  src/connections/destinations/catalog/actions-google-enhanced-conversions/images/google-enhanced-conversions-migration.png
  src/connections/destinations/catalog/actions-google-enhanced-conversions/images/mapping-fields.png
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: content-update

#6532 Add Survicate (Actions) Destination README
  src/connections/destinations/catalog/actions-survicate/index.md
Labels: new-integration

#6628 Add updates from prev pull request for Ripe
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
Labels: content-update

#6676 running catalog for June 6, 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6677 Release 24.23.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/assets/pdf/faq-segment-dissolution-vat.pdf
  src/connections/destinations/catalog/actions-attio/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/images/google-enhanced-conversions-migration.png
  src/connections/destinations/catalog/actions-google-enhanced-conversions/images/mapping-fields.png
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-ripe-cloud/index.md
  src/connections/destinations/catalog/actions-ripe-web/index.md
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/copy-pixel-id.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/email-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/install-pixel-link.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/order-completed-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/snowflake-mappings.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/images/user-registered-event-rule.png
  src/connections/destinations/catalog/actions-stackadapt-cloud/index.md
  src/connections/destinations/catalog/actions-survicate/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/braze/index.md
  src/connections/destinations/catalog/churned/index.md
  src/connections/destinations/catalog/klaviyo/images/migrated-dest.png
  src/connections/destinations/catalog/klaviyo/images/migrated-settings.png
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/index.md
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/reverse-etl-catalog.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/braze-swift.md
  src/connections/sources/catalog/libraries/mobile/react-native/destination-plugins/braze-react-native.md
  src/engage/images/conditions.png
  src/guides/what-is-replay.md
  src/unify/Traits/predictions/index.md
  src/unify/images/data-graph-example.png
  src/unify/images/snowflake-setup.png
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/setup-guides/snowflake-setup.md
  templates/partners/source.md
Labels: release

#6682 Remove beta tag for Workramp source
  src/connections/sources/catalog/cloud-apps/workramp/index.md
Labels: content-update

#6686 Hide docs for deprecated destination
  src/connections/destinations/catalog/userlike/index.md
Labels: back-end

#6679 RETL alerting
  src/connections/reverse-etl/index.md
Labels: new-feature

#6684 Hide docs for Bento as this destination is now deprecated
  src/connections/destinations/catalog/bento/index.md
Labels: content-update

#6654 Unified Profiles - CSV upload and UI updates [DOC-932]
  src/unified-profiles/connect-a-workspace.md
  src/unified-profiles/index.md
  src/unified-profiles/unified-profiles-workspace.md
Labels: content-update

#6687 update klaviyo source doc
  src/connections/sources/catalog/cloud-apps/klaviyo/index.md
Labels: KCS

#6689 Klaviyo migration docs - additional context about mappings
  src/connections/destinations/catalog/klaviyo/index.md
Labels: content-update

#6648 linked audiences test event draft
  src/engage/audiences/linked-audiences.md
  src/engage/images/linked_audience_payload.png
Labels: content-update

#6688 data graph updates for demo
  src/unify/linked-profiles/data-graph.md
Labels: content-update

#6690 Catalog Update 06112024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6691 Update Engage Premier documentation with EOS banner
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/onboarding.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
Labels: content-update

#6693 Release 24.24.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/bento/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/userlike/index.md
  src/connections/sources/catalog/cloud-apps/klaviyo/index.md
  src/connections/sources/catalog/cloud-apps/workramp/index.md
  src/engage/audiences/linked-audiences.md
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/images/linked_audience_payload.png
  src/engage/onboarding.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
  src/unify/linked-profiles/data-graph.md
  templates/partners/destination-new.md
  templates/partners/destination-update.md
  templates/partners/direct-destination.md
Labels: release

#6685 Update Marketo Static Lists and DV360 deprecation notices.
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
Labels: content-update

#6459 Consent in Reverse ETL "soft" GA
  src/_data/sidenav/main.yml
  src/connections/reverse-etl/index.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-retl.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/index.md
Labels: new-feature

#6681 Freshsales Suite - traits is mandatory for Identify
  src/connections/destinations/catalog/freshsales-suite-crm/index.md
Labels: KCS

#6596 Adding ConfigCat source documentation
  src/connections/sources/catalog/cloud-apps/configcat/index.md
Labels: new-integration

#6701 Master to develop after consent in RETL one off
  src/_data/sidenav/main.yml
  src/connections/reverse-etl/index.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-retl.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/index.md
Labels: back-end

#6692 Update Consent Object section in Consent Mgmt docs
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
Labels: content-update

#6637 Kochava - Removed sections referencing iAD
  src/connections/destinations/catalog/kochava/index.md
Labels: content-update, KCS

#6704 Catalog Update 13 June 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6658 Update insert-functions.md Insert Functions only return one event
  src/connections/functions/insert-functions.md
Labels: KCS

#6592 Link Show an Ad step for advertising destinations
  src/engage/journeys/send-data.md
Labels: content-update, KCS

#6634 Add FAQ about destination filters
  src/connections/test-connections.md
Labels: KCS

#6699 Using Predictions HIPAA Updates
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update

#6700 Predictions Updates
  src/unify/Traits/predictions/index.md
Labels: content-update

#6706 Add info about users enabling a.js dest filters for onetrust wrapper users (consent management)
  src/privacy/consent-management/configure-consent-management.md
Labels: fixed-content

#6707 Release 24.24.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/fl0/index.md
  src/connections/destinations/catalog/freshsales-suite-crm/index.md
  src/connections/destinations/catalog/kochava/index.md
  src/connections/destinations/catalog/marketo-static-lists/index.md
  src/connections/destinations/catalog/personas-display-video-360/index.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/connections/sources/catalog/cloud-apps/configcat/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/connections/test-connections.md
  src/engage/journeys/send-data.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/unify/Traits/predictions/index.md
  src/unify/Traits/predictions/using-predictions.md
Labels: release

#6665 add yotpo as a source docs
  src/connections/sources/catalog/cloud-apps/yotpo/index.md
Labels: new-integration

#6678 Add SendGrid Marketing Campaigns Source docs
  src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
Labels: new-integration

#6710 feat(content): clarify no dependency on profiles sync for linked events
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/linked-events.md
Labels: content-update

#6709 Update CSV Upload plan type
  src/engage/profiles/csv-upload.md
Labels: content-update

#6711 Update index.md
  src/connections/destinations/catalog/optimizely-web/index.md
Labels: fixed-content

#6712 Change warehouse to workspace
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: fixed-content

#6714 Update index.md Source Disabled After 14 days Without Enabled Destina…
  src/connections/sources/index.md
Labels: KCS

#6717 Enhance clarity in connection settings instructions to toggle identify/track events
  src/connections/destinations/catalog/actions-listrak/index.md
Labels: KCS

#6708 AWS PrivateLink Private Beta [DOC-876]
  src/connections/aws-privatelink.md
Labels: new-feature

#6718 Update Klaviyo classic migration timeline
  src/connections/destinations/catalog/klaviyo/index.md
Labels: fixed-content

#6720 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6721 Release 24.25.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/connections/aws-privatelink.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/destinations/catalog/optimizely-web/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid-marketing-campaigns/index.md
  src/connections/sources/catalog/cloud-apps/yotpo/index.md
  src/connections/sources/index.md
  src/engage/profiles/csv-upload.md
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/linked-events.md
Labels: release

#6723 AWS PrivateLink hotfix at request of PM
  src/_data/sidenav/main.yml
  src/connections/aws-privatelink.md
Labels: back-end

#6724 rerun catalog
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6726 Update scim.md
  src/segment-app/iam/scim.md
Labels: KCS

#6728 Klaviyo Migration - no action is required for Ajs
  src/connections/destinations/catalog/klaviyo/index.md
Labels: KCS

#6725 Databricks Data Graph setup
  src/unify/linked-profiles/setup-guides/databricks-setup.md
Labels: content-update

#6730 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6731 Release 24.25.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/klaviyo/index.md
  src/segment-app/iam/scim.md
  src/unify/linked-profiles/setup-guides/databricks-setup.md
Labels: release

#6732 Update index.md - update the add/remove user frequency google ads rem…
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: KCS

#6735 Update index.md - fix typo
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: KCS

#6739 Move inleads out of beta
  src/connections/destinations/catalog/inleads-ai/index.md
Labels: content-update

#6408 Clarify Segment timestamps are in UTC
  src/connections/spec/common.md
Labels: content-update, KCS

#6310 Add note about config options for downstream sdks
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update, KCS

#6615 Update Regional Segment Limitations
  src/guides/regional-segment.md
Labels: fixed-content, KCS

#6729 UserMotion docs
  src/connections/destinations/catalog/actions-usermotion/index.md
Labels: new-integration

#6737 Add notes indicating Databricks support to other Linked Profiles pages
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/linked-events.md
Labels: fixed-content

#6745 OAuth 2.0 GA
  src/_data/products.yml
  src/_data/sidenav/main.yml
  src/api/public-api/index.md
  src/connections/functions/source-functions.md
  src/connections/oauth.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
Labels: new-feature

#6742 Remove Google Ads Hourly Sync Info
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: content-update, KCS

#6741 Update index.md - remove 'every hour' verbiage
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
Labels: KCS

#6743 Update index.md - FAQ section is above the Mapping Actions section
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: KCS

#6740 Update Generative Audiences with CustomerAI T&C
  src/engage/audiences/generative-audiences.md
Labels: content-update, KCS

#6750 fix a typo
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: fixed-content

#6751 creating catalog for deploy
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6752 Release 24.26.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/_data/sidenav/main.yml
  src/api/public-api/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/actions-usermotion/index.md
  src/connections/destinations/catalog/adwords-remarketing-lists/index.md
  src/connections/destinations/catalog/inleads-ai/index.md
  src/connections/destinations/catalog/klaviyo/index.md
  src/connections/functions/source-functions.md
  src/connections/oauth.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/python/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/common.md
  src/engage/audiences/generative-audiences.md
  src/guides/regional-segment.md
  src/unify/Traits/predictions/index.md
  src/unify/linked-profiles/data-graph.md
  src/unify/linked-profiles/index.md
  src/unify/linked-profiles/linked-events.md
Labels: release

#6753 DM-3198: Add an additional option about SUPPRESS_WITH_ DELETE _INTERNAL
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#6759 fix code snippet
  src/connections/sources/catalog/libraries/mobile/kotlin-android/implementation.md
Labels: fixed-content

#6519 Update intercom-swift.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
Labels: KCS

#6749 [actions] Adds a info box describing invalid property or trait values
  src/connections/destinations/actions.md
Labels: content-update

#6763 fix(docs): update link to profiles sync setup doc
  src/unify/index.md
Labels: fixed-site

#6758 Update Klaviyo API scope to include Events
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: content-update, KCS

#6635 Add note about empty campaign objects in Analytics.js
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: content-update, KCS

#6767 Auto-Instrumentation Updates
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/setup.md
Labels: content-update

#6748 Braze Linked Audiences Docs
  src/engage/audiences/linked-audiences-braze.md
  src/engage/images/braze-cart-advanced.png
  src/engage/images/braze-cart-simple.png
  src/engage/images/braze_advanced_email.png
  src/engage/images/braze_basic_email.png
  src/engage/images/send-test-event.png
Labels: new-feature

#6746 Update Predictions Events Limit
  src/unify/Traits/predictions/using-predictions.md
Labels: content-update, KCS

#6771 Release 24.26.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/setup.md
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/sources/catalog/libraries/mobile/apple/destination-plugins/intercom-swift.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/implementation.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/engage/audiences/linked-audiences-braze.md
  src/engage/images/braze-cart-advanced.png
  src/engage/images/braze-cart-simple.png
  src/engage/images/braze_advanced_email.png
  src/engage/images/braze_basic_email.png
  src/engage/images/send-test-event.png
  src/privacy/portal.md
  src/privacy/user-deletion-and-suppression.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/index.md
Labels: release

#6773 Functions Copilot Public Beta [DOC-953]
  src/_data/sidenav/main.yml
  src/_includes/content/functions-copilot-nutrition-facts.html
  src/connections/functions/copilot.md
  src/connections/functions/functions-copilot-nutrition-facts.md
  src/connections/functions/index.md
Labels: new-feature

#6774 add actions fields to Marketo dest
  src/connections/destinations/catalog/actions-marketo-static-lists/index.md
Labels: back-end

#6776 `master` into `develop` after release
  src/_data/sidenav/main.yml
  src/_includes/content/functions-copilot-nutrition-facts.html
  src/connections/functions/copilot.md
  src/connections/functions/functions-copilot-nutrition-facts.md
  src/connections/functions/index.md
Labels: back-end
