Repository segmentio/segment-docs, pull requests merged in 2024-08, with the labels that each got.

#6874 Update Snowflake Setup Guide
  src/unify/data-graph/setup-guides/snowflake-setup.md
  src/unify/images/snowflake-setup.png
Labels: content-update

#6886 Update Listrak Destination Docs for New Functionality
  src/connections/destinations/catalog/actions-listrak/images/mappings1.png
  src/connections/destinations/catalog/actions-listrak/images/mappings2.png
  src/connections/destinations/catalog/actions-listrak/images/subscription1.png
  src/connections/destinations/catalog/actions-listrak/images/subscription2.png
  src/connections/destinations/catalog/actions-listrak/index.md
Labels: content-update

#6883 Update Survicate Actions for Public Beta Launch
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-survicate/index.md
Labels: back-end

#6876 Remove Linked Events and Linked Audiences warnings from Snowflake Setup
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: content-update

#6887 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6875 Destination functions & trait activation
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/index.md
  src/engage/trait-activation/trait-enrichment.md
Labels: content-update

#6888 Release 24.31.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-listrak/images/mappings1.png
  src/connections/destinations/catalog/actions-listrak/images/mappings2.png
  src/connections/destinations/catalog/actions-listrak/images/subscription1.png
  src/connections/destinations/catalog/actions-listrak/images/subscription2.png
  src/connections/destinations/catalog/actions-listrak/index.md
  src/connections/destinations/catalog/actions-survicate/index.md
  src/connections/destinations/catalog/actions-usermaven/index.md
  src/engage/audiences/linked-audiences.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/index.md
  src/engage/trait-activation/trait-enrichment.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
  src/unify/images/snowflake-setup.png
Labels: release

#6898 Add Data Lakes limited access note
  src/connections/storage/data-lakes/index.md
Labels: content-update

#6896 Fix typo on Consent in Segment Connections page
  src/privacy/consent-management/consent-in-segment-connections.md
Labels: fixed-content

#6892 IP Allowlisting GA [DOC-986]
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
  src/connections/destinations/catalog/amazon-kinesis/index.md
  src/connections/destinations/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/insert-functions.md
Labels: new-feature

#6893 Add note that messageId is limited to 100 chars
  src/_includes/content/spec-field-message-id.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/guides/duplicate-data.md
Labels: content-update

#6879 Documentation for Plotline Direct Destination
  src/connections/destinations/catalog/plotline/index.md
Labels: new-integration

#6900 Update Insert Functions Guidance
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#6852 Update Salesforce Actions Batch Size Limit
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: content-update, KCS

#6895 Adding note about Audit Trail timeframe
  src/segment-app/iam/audit-trail.md
Labels: KCS

#6901 Fix event tables for Voucherify
  src/connections/sources/catalog/cloud-apps/voucherify/index.md
Labels: fixed-site

#6885 Add warning about dom
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#6899 Clean up for action destinations
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/1flow-web-actions/index.md
  src/connections/destinations/catalog/actions-actable-predictive/index.md
  src/connections/destinations/catalog/actions-avo/images/api-key.png
  src/connections/destinations/catalog/actions-avo/images/avo-destination.png
  src/connections/destinations/catalog/actions-avo/images/issue-sidebar.png
  src/connections/destinations/catalog/actions-avo/images/select-source.png
  src/connections/destinations/catalog/actions-avo/index.md
  src/connections/destinations/catalog/actions-blackbaud-raisers-edge-nxt/index.md
  src/connections/destinations/catalog/actions-braze-cloud/index.md
  src/connections/destinations/catalog/actions-braze-web/index.md
  src/connections/destinations/catalog/actions-criteo-audiences/index.md
  src/connections/destinations/catalog/actions-customer-io/index.md
  src/connections/destinations/catalog/actions-customerio/index.md
  src/connections/destinations/catalog/actions-gwen-cloud/index.md
  src/connections/destinations/catalog/actions-optimizely-data-platform/index.md
  src/connections/destinations/catalog/actions-ripe/index.md
  src/connections/destinations/catalog/actions-talon-one/index.md
  src/connections/destinations/catalog/actions-userpilot-cloud/index.md
  src/connections/destinations/catalog/actions-userpilot-web/index.md
  src/connections/destinations/catalog/blend-ai/index.md
  src/connections/destinations/catalog/braze-cloud-mode-actions/index.md
  src/connections/destinations/catalog/braze-web-device-mode-actions/index.md
  src/connections/destinations/catalog/criteo-audiences/index.md
  src/connections/destinations/catalog/equals/index.md
  src/connections/destinations/catalog/gleap-action/index.md
  src/connections/destinations/catalog/google-analytics-4-web/index.md
  src/connections/destinations/catalog/gwen-actions/index.md
  src/connections/destinations/catalog/hubble-actions/index.md
  src/connections/destinations/catalog/linkedin-conversion-tag/index.md
  src/connections/destinations/catalog/pendo-web-actions/index.md
  src/connections/destinations/catalog/ripe-cloud-mode-actions/index.md
  src/connections/destinations/catalog/screeb-web-actions/index.md
  src/connections/destinations/catalog/stackadapt/index.md
  src/connections/destinations/catalog/talon-one-actions/index.md
  src/connections/destinations/catalog/tiktok-offline-conversions/index.md
  src/connections/destinations/catalog/tiktok-pixel/index.md
Labels: fixed-site

#6890 Added doc for Angler AI (Actions)
  src/connections/destinations/catalog/actions-angler-ai/index.md
Labels: new-integration

#6889 Fix `user_id` in Data Graph
  src/unify/data-graph/data-graph.md
Labels: content-update

#6906 Catalog Update 6 August 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6880 Data Graph Updates
  src/unify/data-graph/data-graph.md
Labels: content-update

#6910 Update Data Graph HIPAA warning
  src/unify/data-graph/data-graph.md
Labels: content-update

#6911 Google Enhanced Conversions - Hide Some Actions
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: back-end

#6884 Add note about nested properties
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#6908 Adding RETL source Q
  src/connections/reverse-etl/index.md
Labels: content-update

#6841 [STRAT-3624] | Remove hidden action fields from showing in public segment docs.
  scripts/catalog/updateDestinations.js
Labels: back-end

#6918 Catalog Update 8 August 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6914 Add React Native Consent plugin link
  src/privacy/consent-management/configure-consent-management.md
Labels: content-update

#6912 Update CONTRIBUTING.md to include hide_action
  CONTRIBUTING.md
Labels: back-end

#6920 Release 24.32.2
  CONTRIBUTING.md
  scripts/catalog/updateDestinations.js
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/reverse-etl/index.md
  src/privacy/consent-management/configure-consent-management.md
  src/unify/data-graph/data-graph.md
Labels: release

#6913 Facebook Custom Audiences (Actions) documentation
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
Labels: new-integration

#6924 Slug hotfix for Facebook Custom Audiences doc
  src/_data/catalog/slugs.yml
  src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
Labels: back-end

#6926 Add clarification for permissions/account structure on Facebook Custom Audiences
  src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
Labels: content-update

#6925 Master to develop after one-off + hotfix
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-facebook-custom-audiences/index.md
  src/unify/data-graph/data-graph.md
Labels: back-end

#6897 Added Authvia source for Review
  src/connections/sources/catalog/cloud-apps/authvia/index.md
Labels: new-integration

#6902 Update Predictions Access Requirements
  src/unify/Traits/predictions/index.md
Labels: content-update

#6927 Facebook Custom Audiences (Actions) hotfix II
  src/_includes/components/actions-fields.html
  src/_includes/content/destination-dossier.html
Labels: back-end

#6928 Master to develop after one-off
  src/_includes/content/storage-do-include.md
  src/connections/delivery-overview.md
  src/connections/images/delivery-overview-storage-destinations.png
  src/connections/storage/catalog/aws-s3/index.md
  src/connections/storage/catalog/azuresqldw/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/connections/storage/catalog/databricks/index.md
  src/connections/storage/catalog/db2/index.md
  src/connections/storage/catalog/google-cloud-storage/index.md
  src/connections/storage/catalog/postgres/index.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/catalog/snowflake/index.md
Labels: back-end

#6923 Update custom-domain.md
  src/connections/sources/custom-domain.md
Labels: KCS

#6931 Remove references to Upload Enhanced Conversion (Legacy) action
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: fixed-site

#6862 Update custom-domain.md
  src/connections/sources/custom-domain.md
Labels: KCS

#6782 Update index.md Salesforce Auth limitation
  src/connections/destinations/catalog/actions-salesforce/index.md
Labels: KCS

#6808 Update Algolia Insights Destination
  src/connections/destinations/catalog/actions-algolia-insights/images/algolia_app_id_dropdown.png
  src/connections/destinations/catalog/actions-algolia-insights/images/destination_settings.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mapping_tab.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mapping_tab_edit.png
  src/connections/destinations/catalog/actions-algolia-insights/images/mappings_tab.png
  src/connections/destinations/catalog/actions-algolia-insights/images/rename_events.png
  src/connections/destinations/catalog/actions-algolia-insights/index.md
Labels: content-update

#6936 Update Analytics Libraries Titles [LIBRARIES-1506]
  src/connections/sources/catalog/libraries/mobile/android/index.md
  src/connections/sources/catalog/libraries/mobile/android/quickstart.md
  src/connections/sources/catalog/libraries/mobile/android/wear.md
  src/connections/sources/catalog/libraries/mobile/apple/implementation.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-plugin-architecture.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-samples.md
  src/connections/sources/catalog/libraries/mobile/apple/swift-typewriter.md
  src/connections/sources/catalog/libraries/mobile/ios/index.md
  src/connections/sources/catalog/libraries/mobile/ios/quickstart.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/implementation.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/index.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-faq.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-plugin-architecture.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-samples.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-typewriter.md
  src/connections/sources/catalog/libraries/mobile/kotlin-android/migration.md
  src/connections/sources/catalog/libraries/server/kotlin/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/engage/campaigns/mobile-push/index.md
  src/getting-started/02-simple-install.md
Labels: content-update

#6571 Reverse ETL 2.0 docs
  src/_data/sidenav/main.yml
  src/connections/reverse-etl/faq.md
  src/connections/reverse-etl/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/reverse-etl/reverse-etl-catalog.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/azure-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/bigquery-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/connections/reverse-etl/setup.md
  src/connections/reverse-etl/system.md
Labels: content-update

#6916 Add SQL Traits Nullify Behavior
  src/unify/Traits/sql-traits.md
Labels: content-update, KCS

#6937 catalog 8-13-24
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6904 add UI nuance to troubleshooting section
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
Labels: KCS

#6843 Adding a new topic about duplicate events
  src/connections/destinations/catalog/google-tag-manager/index.md
Labels: KCS

#6941 Redirect funkiness
  src/connections/destinations/catalog/action-rokt-audiences/index.md
  src/connections/destinations/catalog/actions-criteo-audiences/index.md
  src/connections/sources/catalog/libraries/website/shopify/index.md
  src/connections/storage/catalog/data-lakes/index.md
Labels: back-end

#6942 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6943 Release 24.33.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/action-rokt-audiences/index.md
  src/connections/destinations/catalog/google-tag-manager/index.md
  src/connections/sources/catalog/cloud-apps/sendgrid/index.md
  src/connections/sources/catalog/libraries/website/shopify/index.md
  src/connections/storage/catalog/data-lakes/index.md
Labels: release

#6945 Extensions dbt and Git Sync GA [DOC-983]
  src/segment-app/extensions/dbt.md
  src/segment-app/extensions/git.md
  src/segment-app/extensions/index.md
Labels: content-update

#6946 `master` to `develop` after one-off
  src/segment-app/extensions/dbt.md
  src/segment-app/extensions/git.md
  src/segment-app/extensions/index.md
Labels: back-end

#6947 Update link for Profiles historical backfill
  src/unify/profiles-sync/tables.md
Labels: fixed-content

#6792 Update index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: KCS

#6454 Update index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: fixed-site, KCS

#6909 More Data Graph Updates [DOC-920]
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/unify/data-graph/data-graph.md
  src/unify/profiles-sync/tables.md
Labels: content-update

#6864 Add note that at least one of Email Id or Advertising ID must be provided
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: KCS

#6932 add One Creation Source documentation
  src/connections/sources/catalog/cloud-apps/one-creation-zero-party-data-engagement/index.md
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
Labels: new-integration

#6929 Snowflake Setup Updates
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: content-update

#6930 Databricks Setup Updates
  src/unify/data-graph/setup-guides/databricks-setup.md
Labels: content-update

#6955 `master` to `develop`
  src/unify/data-graph/data-graph.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: back-end

#6367 Update destination-filters.md | Correct execution order of Dest Filters
  src/connections/destinations/destination-filters.md
Labels: KCS

#6957 Catalog Update 20 August 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6958 Release 24.34.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/one-creation-zero-party-data-engagement/index.md
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
Labels: release

#6949 Fix Use Cases Typos
  src/getting-started/use-cases/reference.md
Labels: fixed-content

#6967 Update Engage FAQs Typo
  src/engage/faqs.md
Labels: fixed-content, KCS

#6964 Add details about content_id mapping
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#6963 Filter conditions are case sensitive.md
  src/connections/destinations/destination-filters.md
Labels: KCS

#6935 add first documentation page for destination dynamic yield by mastercard
  src/connections/destinations/catalog/actions-dynamic-yield-audiences/index.md
Labels: new-integration

#6969 Catalog Update 22 August 2024
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6971 Configure Consent Management hotfix
  src/privacy/consent-management/configure-consent-management.md
Labels: fixed-content

#6956 Data Graph GA Updates
  src/unify/data-graph/index.md
Labels: content-update

#6973 Update Side Navigation for Linked Audiences GA
  src/_data/sidenav/main.yml
Labels: back-end

#6968 Update Linked Audiences Activation Content
  src/engage/audiences/linked-audiences.md
Labels: content-update

#6975 Release 24.34.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/catalog/actions-dynamic-yield-audiences/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/destinations/catalog/inkit/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/engage/audiences/linked-audiences.md
  src/engage/faqs.md
  src/getting-started/use-cases/reference.md
  src/privacy/consent-management/configure-consent-management.md
  src/unify/data-graph/index.md
Labels: release

#6979 Fix Functions Copilot Link
  src/connections/functions/copilot.md
  src/connections/functions/index.md
Labels: fixed-content

#6536 Update index.md - add FAQ Google Sheets & fix error
  src/connections/destinations/catalog/actions-google-sheets/index.md
Labels: KCS

#6417 Add Troubleshooting note in MailChimp
  src/connections/destinations/catalog/mailchimp/index.md
Labels: KCS

#6934 Add Profile Explorer Lookback Period Guidance
  src/unify/faqs.md
Labels: content-update, KCS

#6982 Salesforce Unify Direct Integration GA [DOC-960]
  src/unify/images/select_mappings.png
  src/unify/salesforce-unify.md
Labels: new-feature

#6980 Added FAQ Section Including Common Question/Answer Regarding Timestamp Discrepancies
  src/connections/spec/common.md
Labels: KCS

#6518 Update index.md
  src/connections/destinations/catalog/webhooks/index.md
Labels: KCS

#6984 Update Data Graph SQL Code Blocks
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: fixed-content

#6985 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6986 Release 24.35.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-sheets/index.md
  src/connections/destinations/catalog/mailchimp/index.md
  src/connections/destinations/catalog/posthog/index.md
  src/connections/destinations/catalog/webhooks/index.md
  src/connections/functions/copilot.md
  src/connections/functions/index.md
  src/connections/spec/common.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
  src/unify/faqs.md
  src/unify/images/select_mappings.png
  src/unify/salesforce-unify.md
Labels: release

#6952 [TOPSORT] added topsort events destination docs
  src/connections/destinations/catalog/actions-topsort/index.md
Labels: new-integration

#6987 Note on additional charges for deletions
  src/privacy/faq.md
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#6988 Funtions FAQ
  src/connections/reverse-etl/faq.md
Labels: KCS

#6990 make catalog 20240829
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6989 hide advance retries note
  src/connections/reverse-etl/manage-retl.md
Labels: content-update

#6991 Release 24.35.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-topsort/index.md
  src/connections/reverse-etl/faq.md
  src/connections/reverse-etl/manage-retl.md
  src/privacy/faq.md
  src/privacy/user-deletion-and-suppression.md
Labels: release
