Repository segmentio/segment-docs, pull requests merged in 2025-06, with the labels that each got.

#7658 Clarify how date range filter applies to V1 journey analytics
  src/engage/journeys/journeys-analytics.md
Labels: content-update

#7625 Ortto (Actions) docs
  src/connections/destinations/catalog/actions-ortto/index.md
Labels: new-integration

#7653 Analytics.js cleanup (part 1)
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
Labels: fixed-content

#7662 Catalog update 5 June 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7659 Contact support for Profile Sync backfill
  src/unify/profiles-sync/tables.md
Labels: content-update

#7663 Release 25.23.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-ortto/index.md
  src/connections/reverse-etl/system.md
  src/connections/sources/catalog/libraries/website/javascript/cookie-validity-update.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/catalog/libraries/website/javascript/quickstart.md
  src/connections/sources/catalog/libraries/website/javascript/supported-browsers.md
  src/engage/audiences/index.md
  src/engage/audiences/product-based-audiences.md
  src/engage/journeys/journeys-analytics.md
  src/unify/Traits/computed-traits.md
  src/unify/profiles-sync/tables.md
Labels: release

#7644 Remind folks not to hardcode IP addresses w HTTP API
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: content-update

#7667 Added other supported warehouses to LA prerequisites
  src/engage/audiences/linked-audiences.md
Labels: content-update

#7670 first pass of the new alert types
  src/monitor/alerts/default-alerts.md
Labels: content-update

#7673 Dot Notation Support in Mappings Destination Fields
  src/connections/destinations/actions.md
Labels: content-update

#7675 Master back to develop after one-off
  src/_data/catalog/warehouse.yml
Labels: back-end

#7652 Note added on Timestamp column being null during backfill
  src/unify/profiles-sync/tables.md
Labels: content-update

#7648 Data Graph Visual Builder
  src/unify/data-graph/index.md
  src/unify/images/data-graph-entities-tab.png
  src/unify/images/relationships-tab-data-graph.png
Labels: new-feature

#7680 Master back to develop after one-off for Data Graph Visual Builder
  src/unify/data-graph/index.md
  src/unify/images/data-graph-entities-tab.png
  src/unify/images/relationships-tab-data-graph.png
Labels: back-end

#7657 Draft for public facing documentation for Amazon Conversions API
  src/connections/destinations/catalog/actions-amazon-conversions-api/index.md
Labels: new-integration

#7682 More Analytics.js cleanup
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/sources/catalog/libraries/website/javascript/middleware.md
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
Labels: fixed-content

#7692 Cherry picked audience size alert PR
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
  src/monitor/alerts/default-alerts.md
Labels: back-end

#7693 Master to develop after one-off
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
  src/monitor/alerts/default-alerts.md
Labels: back-end

#7696 Delete Event-Triggered Journeys beta alerts [DOC-1138]
  src/engage/journeys/event-triggered-journeys-steps.md
  src/engage/journeys/event-triggered-journeys.md
  src/engage/journeys/exit-rules.md
  src/engage/journeys/journey-context.md
Labels: content-update

#7697 Catalog update 20 June 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7699 Add Randomized Splits step to V2 Journeys Step page [DOC-1077]
  src/engage/journeys/event-triggered-journeys-steps.md
Labels: content-update

#7698 Add section on observability in V2 Journeys [DOC-1080]
  src/engage/journeys/event-triggered-journeys.md
Labels: content-update

#7688 Insert functions now supported in event and mapping tester [DOC-1135]
  src/connections/functions/insert-functions.md
Labels: content-update

#7700 Release 25.25.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-amazon-conversions-api/index.md
  src/connections/destinations/catalog/actions-intercom-cloud/index.md
  src/connections/destinations/catalog/actions-reddit-audiences/index.md
  src/connections/destinations/catalog/actions-reddit-conversions-api/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/connections/sources/catalog/libraries/website/javascript/middleware.md
  src/connections/sources/catalog/libraries/website/javascript/querystring.md
  src/connections/sources/catalog/libraries/website/javascript/single-page-apps.md
  src/connections/sources/catalog/libraries/website/javascript/troubleshooting.md
  src/connections/spec/track.md
  src/engage/journeys/event-triggered-journeys-steps.md
  src/engage/journeys/event-triggered-journeys.md
  src/engage/journeys/exit-rules.md
  src/engage/journeys/journey-context.md
  src/engage/journeys/v2/limits.md
  src/unify/profiles-sync/tables.md
Labels: release

#7590 webhooks information corrected [DOC-1110]
  src/_includes/content/destination-dossier.html
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: fixed-content

#7706 EVT Journeys hotfixes
  src/engage/journeys/v2/event-triggered-journeys-steps.md
  src/engage/journeys/v2/exit-rules.md
  src/engage/journeys/v2/journey-context.md
  src/engage/journeys/v2/limits.md
Labels: fixed-content

#7707 Removed public beta alert
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: content-update

#7708 Hotfix for DotDigital destination
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/dotdigital/index.md
Labels: back-end

#7694 Added Source Insert Functions page
  src/_data/sidenav/main.yml
Labels: content-update

#7709 `master` into `develop` again
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/dotdigital/index.md
  src/engage/journeys/v2/event-triggered-journeys-steps.md
  src/engage/journeys/v2/exit-rules.md
  src/engage/journeys/v2/journey-context.md
  src/engage/journeys/v2/limits.md
Labels: back-end

#7703 Db2 source setup updates
  src/connections/reverse-etl/reverse-etl-source-setup-guides/db2-setup.md
Labels: content-update

#7690 entity counts
  src/engage/audiences/linked-audiences.md
Labels: new-feature

#7684 Hide Attentive Actions documentation
  src/connections/destinations/catalog/actions-attentive/index.md
Labels: content-update

#7687 Added recipe pages for destination integrations with Extensible Webhooks [DOC-1108]
  src/connections/destinations/catalog/actions-webhook-extensible/amazon-ads-integration-recipe.md
  src/connections/destinations/catalog/actions-webhook-extensible/google-search-ads-integration-recipe.md
  src/connections/destinations/catalog/actions-webhook-extensible/microsoft-integration-recipe.md
  src/connections/destinations/catalog/actions-webhook-extensible/reddit-ads-audience-integration-recipe.md
  src/connections/destinations/catalog/actions-webhook-extensible/reddit-ads-conversion-api-integration-recipe.md
Labels: new-feature

#7702 Add guidance on including/excluding Traits from Predictions
  src/unify/Traits/predictions/index.md
Labels: content-update

#7712 Catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7713 Move Journeys Logic page
  src/_data/sidenav/main.yml
  src/engage/journeys/v1/journeys-logic.md
Labels: back-end

#7683 Added steps on sending in-app events to Segment [DOC-1131]
  src/connections/destinations/catalog/adjust/index.md
Labels: content-update

#7718 Fixed bullet point
  src/connections/destinations/catalog/actions-webhook-extensible/microsoft-integration-recipe.md
Labels: content-update

#7719 add info about custom traits/audience interaction
  src/privacy/consent-management/consent-in-unify.md
Labels: content-update

#7715 Doc updates for mapping editor changes + misc updates
  src/connections/destinations/actions.md
Labels: content-update

#7720 Extensible Webhooks hotfix
  src/_data/catalog/destinations.yml
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: fixed-content

#7726 Ortto (Actions): Add Audience Name field docs
  src/connections/destinations/catalog/actions-ortto/index.md
Labels: content-update

#7728 Decrease `font-weight` for bold text
  src/_sass/components/_accordion.scss
  src/_sass/components/_button.scss
  src/_sass/components/_code-example.scss
  src/_sass/components/_destination-menu.scss
  src/_sass/components/_list-steps.scss
  src/_sass/components/_markdown.scss
  src/_sass/components/_mobile-menu-side.scss
  src/_sass/components/_quickinfo.scss
  src/_sass/components/_thumbnail-integration.scss
  src/_sass/components/_widget.scss
  src/_sass/generics/_typography.scss
  src/_sass/vendors/_premonition.scss
  src/privacy/consent-management/consent-in-retl.md
Labels: back-end
