Repository segmentio/segment-docs, pull requests merged in 2025-01, with the labels that each got.

#7362 Remove beta tag script from Podscribe
  src/connections/destinations/catalog/actions-podscribe/index.md
Labels: content-update

#7023 update http api guide with batch limit
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: KCS

#7358 Add flatten function info
  src/connections/destinations/actions.md
Labels: content-update

#7366 Add note linking to role in attribution
  src/connections/destinations/catalog/appsflyer/index.md
Labels: content-update, KCS

#7352 removed inaccurate information
  src/connections/destinations/destination-filters.md
Labels: fixed-content

#7367 Add FAQ on blocking forwarded blocked events
  src/protocols/faq.md
Labels: content-update, KCS

#7351 Fix Audiences Typo
  src/engage/audiences/index.md
Labels: fixed-content, KCS

#7121 Google Campaign Manager 360 destination docs.
  src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
Labels: new-integration

#7371 Update sso.md
  src/segment-app/iam/sso.md
Labels: KCS

#7368 Update node docs
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
Labels: content-update

#7373 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7374 Release 25.02.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-google-campaign-manager-360/index.md
  src/connections/destinations/catalog/actions-marketo-static-lists/index.md
  src/connections/destinations/catalog/actions-podscribe/index.md
  src/connections/destinations/catalog/actions-sendgrid-audiences/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/destination-filters.md
  src/connections/sources/catalog/cloud-apps/antavo/images/1-antavo-enable_segment_extension.png
  src/connections/sources/catalog/cloud-apps/antavo/images/2-antavo-configure_segment_extension.png
  src/connections/sources/catalog/cloud-apps/antavo/images/3-antavo-configure_event_sync.png
  src/connections/sources/catalog/cloud-apps/antavo/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/catalog/libraries/server/node/migration.md
  src/engage/audiences/index.md
  src/protocols/faq.md
  src/segment-app/iam/sso.md
Labels: release

#7376 Typo fix
  src/connections/destinations/catalog/actions-amplitude/index.md
Labels: fixed-site, KCS

#7353 Update default Traits return count
  src/unify/profile-api.md
Labels: content-update

#7354 Clarify Page and Screen calls in Audience Builder
  src/engage/audiences/index.md
Labels: content-update, KCS

#7380 StackAdapt Audiences destination hotfix
  src/connections/destinations/catalog/actions-stackadapt-audiences/index.md
Labels: back-end

#7375 SF-1275: Add us-east-2 as supported privatelink region
  src/connections/aws-privatelink.md
Labels: content-update

#7381 Master back to develop
  src/connections/destinations/catalog/actions-stackadapt-audiences/index.md
Labels: back-end

#7049 Add documentation for Recombee destination
  src/connections/destinations/catalog/actions-recombee/index.md
  src/connections/destinations/catalog/recombee-ai/index.md
Labels: new-integration

#7385 Update Auto-Instrumentation Production Environment Guidance [DOC-1018]
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
Labels: content-update

#7231 Remove CustomerAI References
  src/_includes/content/functions-copilot-nutrition-facts.html
  src/_includes/content/predictions-nutrition-facts.html
  src/_includes/content/product-based-audiences-nutrition-facts.html
  src/connections/functions/copilot.md
  src/engage/audiences/generative-audiences.md
  src/engage/audiences/product-based-audiences.md
  src/unified-profiles/connect-a-workspace.md
  src/unified-profiles/index.md
  src/unified-profiles/unified-profiles-workspace.md
Labels: content-update

#7372 Revoke workspace deletion request feature
  src/guides/usage-and-billing/account-management.md
  src/privacy/account-deletion.md
Labels: content-update

#7389 Add note to Protocols FAQ about mobile device mode destinations
  src/protocols/faq.md
Labels: content-update

#7390 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7391 Release 25.03.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/_includes/content/functions-copilot-nutrition-facts.html
  src/_includes/content/predictions-nutrition-facts.html
  src/_includes/content/product-based-audiences-nutrition-facts.html
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
  src/connections/aws-privatelink.md
  src/connections/destinations/catalog/actions-amplitude/index.md
  src/connections/destinations/catalog/actions-recombee/index.md
  src/connections/destinations/catalog/recombee-ai/index.md
  src/connections/functions/copilot.md
  src/engage/audiences/generative-audiences.md
  src/engage/audiences/index.md
  src/engage/audiences/product-based-audiences.md
  src/guides/usage-and-billing/account-management.md
  src/guides/usage-and-billing/startup-program.md
  src/privacy/account-deletion.md
  src/protocols/faq.md
  src/unified-profiles/connect-a-workspace.md
  src/unified-profiles/index.md
  src/unified-profiles/unified-profiles-workspace.md
  src/unify/profile-api.md
Labels: release

#7382 Update the screenshot
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/images/ConnectV2.png
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
Labels: KCS

#7379 Add Dub source
  src/connections/sources/catalog/cloud-apps/dub/index.md
Labels: new-integration

#7394 Extensible Webhooks Private Beta [DOC-1022]
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: new-integration

#7357 Mapping Tester doesn't support Insert Functions
  src/connections/functions/insert-functions.md
Labels: content-update, KCS

#7398 Catalog Update 23 January 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7369 Add customer header and `keepalive` info to Analytics.js documentation
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: content-update

#7360 Add info on blocked events in the debugger
  src/connections/sources/schema/index.md
Labels: content-update, KCS

#7326 Entity property values in Linked audience builder are case-sensitive
  src/engage/audiences/linked-audiences.md
Labels: content-update, KCS

#6287 Add AppsFlyer attribution data FAQ
  src/connections/destinations/catalog/appsflyer/index.md
Labels: content-update, KCS

#7218 Add info about custom sessions IDs for the PostHog destination
  src/connections/destinations/catalog/posthog/index.md
Labels: content-update

#7400 Release 25.04.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
  src/connections/destinations/catalog/appsflyer/index.md
  src/connections/destinations/catalog/posthog/index.md
  src/connections/functions/insert-functions.md
  src/connections/sources/catalog/cloud-apps/dub/index.md
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/images/ConnectV2.png
  src/connections/sources/catalog/cloud-apps/mixpanel-cohorts-source/index.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/sources/schema/index.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
Labels: release

#7396 Event-Triggered Journeys Steps [DOC-1024]
  src/_data/sidenav/main.yml
  src/engage/journeys/event-triggered-journeys-steps.md
  src/engage/journeys/images/hold_until.png
Labels: new-feature

#7401 `master` back into `develop`
  src/_data/sidenav/main.yml
  src/engage/journeys/event-triggered-journeys-steps.md
  src/engage/journeys/images/hold_until.png
Labels: back-end

#7387 Update faq.md
  src/privacy/faq.md
Labels: KCS

#4858 Update custom-proxy.md SDK initialization
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
Labels: KCS

#7402 Update Label-Based Access Control guide: navigation, permissions, and FAQs
  src/segment-app/iam/labels.md
Labels: fixed-content

#7062 Add some clarifications to the Clear Schema History setting
  src/connections/sources/schema/schema-unique-limits.md
Labels: KCS

#7410 Deleted workspace migration section [DOC-1026]
  src/guides/regional-segment.md
Labels: content-update

#7386 Update portal.md
  src/privacy/portal.md
Labels: KCS

#7406 Explain raw tables and materialized views in Profiles Sync docs
  src/unify/profiles-sync/tables.md
Labels: content-update

#6845 Add nested properties FAQ to Predictions docs
  src/unify/Traits/predictions/using-predictions.md
Labels: KCS

#6868 Add import type guidance to Google Ads Conversion destination doc
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
Labels: KCS

#7177 Add note about Facebook's mismatched IP address warning
  src/connections/destinations/catalog/facebook-pixel/index.md
Labels: KCS

#7412 Add details on how Page/Screen name property surface in Audience builder
  src/engage/audiences/index.md
Labels: content-update

#7405 Klaviyo (Actions) | Added FAQ regarding Event Name Configuration
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: content-update

#7166 Iterable List (Actions) Destinations docs
  src/connections/destinations/catalog/actions-iterable-lists/index.md
  src/connections/destinations/catalog/actions-iterable/index.md
Labels: new-integration

#6621 Add info that Mailchimp might reject misspelled email domains
  src/connections/destinations/catalog/mailchimp/index.md
Labels: KCS

#7413 Pinterest Conversions API Destination Improvements
  src/connections/destinations/catalog/actions-pinterest-conversions-api/index.md
Labels: content-update

#6655 Add FAQ on handling historical data in Journey entry conditions
  src/engage/journeys/faq-best-practices.md
Labels: KCS

#7416 20250130 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#6597 Update index.md
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#7417 Release 25.05.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/connections/destinations/catalog/actions-google-enhanced-conversions/index.md
  src/connections/destinations/catalog/actions-iterable-lists/index.md
  src/connections/destinations/catalog/actions-iterable/index.md
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-pinterest-conversions-api/index.md
  src/connections/destinations/catalog/actions-salesforce/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/destinations/catalog/mailchimp/index.md
  src/connections/sources/catalog/libraries/website/javascript/custom-proxy.md
  src/connections/sources/schema/schema-unique-limits.md
  src/engage/audiences/index.md
  src/engage/journeys/faq-best-practices.md
  src/guides/regional-segment.md
  src/privacy/faq.md
  src/privacy/portal.md
  src/protocols/faq.md
  src/protocols/images/protocols-faq-blocked-events.png
  src/segment-app/iam/labels.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/profiles-sync/tables.md
Labels: release

#7393 Create index.md for Userlens By Wudpecker
  src/connections/destinations/catalog/userlens/index.md
Labels: new-integration

#7419 Added a clarification on Additional Domains
  src/connections/sources/custom-domain.md
Labels: KCS

#7415 Schema UI and CSV Export expected difference
  src/connections/sources/schema/destination-data-control.md
Labels: KCS
