Repository segmentio/segment-docs, pull requests merged in 2025-07, with the labels that each got.

#7730 Fixed bullet/ bold formatting
  src/connections/destinations/catalog/actions-reddit-audiences/index.md
Labels: fixed-content

#7732 Add context about what CM was designed for
  src/privacy/consent-management/consent-faq.md
  src/privacy/consent-management/index.md
Labels: content-update

#7737 `master` into `develop` after one-off
  src/connections/destinations/catalog/actions-twilio-messaging/index.md
Labels: back-end

#7723 Update to audience trait operators
  src/engage/audiences/index.md
Labels: content-update

#7739 Update list of list destinations/computed traits callout
  src/engage/using-engage-data.md
  src/unify/Traits/computed-traits.md
Labels: content-update

#7735 Link section about recipes to extensible webhooks and updated sidenav to incl recipes
  src/_data/sidenav/_auto/main.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: content-update

#7742 Fix: update link for the ADBMobileConfig.json instructions
  src/connections/destinations/catalog/adobe-analytics/mobile.md
Labels: fixed-content

#7745 `master` back into `develop` after one-off
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/_auto/main.yml
  src/_data/sidenav/main.yml
  src/_data/sidenav/strat.yml
  src/connections/destinations/catalog/actions-dub/index.md
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: back-end

#7717 [Amazon Conversions API] Updating documentation based on questions asked in client calls
  src/connections/destinations/catalog/actions-amazon-conversions-api/index.md
Labels: content-update

#7751 Master to develop after one-off release
  src/_data/catalog/slugs.yml
Labels: back-end

#7754 remove mentions of Azure Data Lakes as Azure is going EOL
  src/connections/storage/catalog/data-lakes/index.md
  src/connections/storage/data-lakes/index.md
Labels: content-update

#7753 Added integrations and consent behaviors [DOC-1144]
  src/guides/what-is-replay.md
Labels: content-update

#7761 Update partner local build instructions with info from action-destinations repo
  src/partners/destinations/build.md
Labels: content-update

#7685 Refresh the deletions and suppressions page to match new UI
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#7764 Master to develop after one-off release
  src/_data/privacy.yml
  src/_data/sidenav/main.yml
  src/privacy/user-deletion-and-suppression.md
Labels: back-end

#7762 Add Aampe (Actions) destination documentation
  src/connections/destinations/catalog/actions-aampe/index.md
Labels: new-integration

#7769 Moving the pages for the direct Segment Profiles integrations
  src/connections/destinations/catalog/actions-segment-profiles/hubspot-source.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/actions-segment-profiles/salesforce-source.md
  src/connections/sources/catalog/cloud-apps/b222test/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/src/index.md
  src/connections/sources/catalog/cloud-apps/this-is-a-test/index.md
Labels: fixed-content

#7766 Update Predictions Destination information
  src/unify/Traits/predictions/index.md
Labels: content-update

#7765 Add note about Latin characters in audiences/computed traits
  src/engage/audiences/index.md
Labels: content-update

#7774 Release 25.29.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-aampe/index.md
  src/connections/destinations/catalog/actions-nudge/index.md
  src/connections/destinations/catalog/actions-segment-profiles/hubspot-source.md
  src/connections/destinations/catalog/actions-segment-profiles/index.md
  src/connections/destinations/catalog/actions-segment-profiles/salesforce-source.md
  src/connections/destinations/catalog/amazon-kinesis/index.md
  src/connections/sources/catalog/cloud-apps/b222test/index.md
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
  src/connections/sources/catalog/cloud-apps/salesforce/index.md
  src/connections/sources/catalog/cloud-apps/src/index.md
  src/connections/sources/catalog/cloud-apps/this-is-a-test/index.md
  src/connections/storage/catalog/data-lakes/index.md
  src/engage/audiences/index.md
  src/partners/destinations/build.md
  src/privacy/data-retention-policy.md
  src/unify/Traits/predictions/index.md
  src/unify/data-graph/index.md
  src/unify/images/data-graph-add-relationship.png
  src/unify/images/data-graph-profile-to-entity.png
Labels: release

#7778 Correcting slug for Aampe Actions Destination
  src/_data/catalog/destinations.yml
  src/_data/catalog/slugs.yml
Labels: fixed-content

#7734 Update docs to include new liquid syntax function feature
  src/connections/destinations/actions.md
Labels: new-feature

#7783 Add link to Twilio account deletion docs
  src/segment-app/iam/index.md
Labels: content-update

#7776 Add warning that hashing detection applies only to action-destinations
  src/connections/destinations/index.md
Labels: content-update

#7784 Fix dbt extension troubleshooting + Git sync instructions
  src/segment-app/extensions/dbt.md
Labels: bug

#7789 Release 25.30.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/index.md
  src/segment-app/extensions/dbt.md
  src/segment-app/iam/index.md
  src/unify/profile-api.md
Labels: release

#7796 Master back to develop after one-off
  src/connections/destinations/actions.md
Labels: back-end

#7794 Fixed the Back-to-top button
  src/_sass/components/_back-scrolling.scss
Labels: fixed-site

#7793 Fix code snippet in Anomaly Detection docs
  src/protocols/apis-and-extensions/anomaly_detection.md
Labels: fixed-content

#7797 fix: Duplicate partner owned notes
  src/_includes/content/cloud-app-note.md
  src/_includes/content/destination-dossier.html
Labels: fixed-site

#7802 Outdated prereq removed [DOC-1155]
  src/connections/destinations/catalog/actions-segment-profiles/salesforce-source.md
Labels: fixed-content

#7805 Clarify daily event requirement for Predictions model training
  src/unify/Traits/predictions/index.md
Labels: content-update

#7806 Update Generative Audiences nutrition facts label
  src/_includes/content/generative-audiences-nutrition-facts.html
Labels: content-update

#7746 Dotdigital/destination
  src/connections/destinations/catalog/dotdigital/index.md
Labels: content-update
