Repository segmentio/segment-docs, pull requests merged in 2025-02, with the labels that each got.

#7421 Added "analytics.js" to the list of sources
  src/connections/sources/catalog/libraries/server/http-api/index.md
Labels: KCS

#7422 Ajs: events exceeding 32 KB limit gets 400 error response
  src/connections/sources/catalog/libraries/website/javascript/faq.md
Labels: KCS

#7408 Destination Info Added
  src/connections/destinations/catalog/tiktok-conversions/index.md
Labels: KCS

#7420 Update Common Fields Spec to reflect timezone support
  src/connections/spec/common.md
Labels: KCS

#7403 Clarify Audience Real-Time Computation Rules
  src/engage/audiences/index.md
Labels: content-update

#7262 Explain how to find users by external ID to Profile API doc
  src/unify/profile-api.md
Labels: KCS

#7397 Update Unify space deletion docs
  src/privacy/account-deletion.md
Labels: content-update

#7426 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7424 LE Sync Schedule [netlify-build]
  src/unify/data-graph/linked-events.md
Labels: new-feature

#7429 Release 25.6.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/regional-support.yml
  src/connections/destinations/catalog/actions-mixpanel/index.md
  src/connections/destinations/catalog/tiktok-conversions/index.md
  src/connections/destinations/catalog/userlens/index.md
  src/connections/sources/catalog/libraries/server/http-api/index.md
  src/connections/sources/catalog/libraries/website/javascript/faq.md
  src/connections/sources/custom-domain.md
  src/connections/sources/schema/destination-data-control.md
  src/connections/spec/common.md
  src/connections/storage/warehouses/faq.md
  src/engage/audiences/index.md
  src/guides/usage-and-billing/mtus-and-throughput.md
  src/privacy/account-deletion.md
  src/privacy/user-deletion-and-suppression.md
  src/unify/Traits/predictions/using-predictions.md
  src/unify/data-graph/linked-events.md
  src/unify/profile-api.md
Labels: release

#7432 Master to develop after one-off
  src/privacy/user-deletion-and-suppression.md
Labels: back-end

#7434 Add Exclusion Rules to Recommended Items doc
  src/unify/Traits/recommended-items.md
Labels: content-update

#7439 Updated email template limits - attachments not supported [DOC-1042]
  src/engage/campaigns/broadcasts.md
Labels: content-update

#7438 Catalog Update 13 February 2025
  .bundle/config
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7435 Add space after "Segment specs"
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
Labels: KCS

#6246 deleted computed traits become custom traits
  src/unify/Traits/computed-traits.md
Labels: KCS

#7441 Release 25.07.01
  .bundle/config
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-google-analytics-4/index.md
  src/engage/campaigns/broadcasts.md
  src/protocols/enforce/schema-configuration.md
  src/unify/Traits/computed-traits.md
  src/unify/Traits/recommended-items.md
Labels: release

#7445 Fix broken maintenance mode popup
  src/connections/destinations/catalog/customer-io/index.md
Labels: fixed-content

#7448 Voucherify asked we remove their old destination from our docs
  src/connections/destinations/catalog/voucherify/index.md
Labels: back-end

#7452 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7453 Release 25.08.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/customer-io/index.md
  src/connections/destinations/catalog/jimo/index.md
  src/connections/destinations/catalog/voucherify/index.md
Labels: release

#7463 Fix broken link in Consent docs
  src/privacy/consent-management/consent-in-unify.md
Labels: fixed-content

#6780 Add Info Alert about Identify Events to Unify Quickstart
  src/unify/quickstart.md
Labels: KCS

#7460 Add recommendation to ID Syncs page about Segment prop > destination prop mappings
  src/engage/trait-activation/id-sync.md
Labels: content-update

#6463 Add info on how Segment handles Klaviyo rate limiting
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: KCS

#7464 Data Graph docs fix traits to trait
  src/unify/data-graph/index.md
Labels: fixed-content

#7465 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7467 Master to develop after one-off
  src/privacy/faq.md
  src/privacy/user-deletion-and-suppression.md
Labels: back-end
