Repository segmentio/segment-docs, pull requests merged in 2025-05, with the labels that each got.

#7586 Update to faq re: changes to tracking plan may be delayed [DOC-1100]
  src/protocols/faq.md
Labels: content-update

#7589 [Bing Ads] Add consent mode instructions
  src/connections/destinations/catalog/bing-ads/index.md
Labels: content-update

#7593 Add Audience Compute Run default alert
  src/monitor/alerts/default-alerts.md
Labels: content-update

#7592 Add analytics.instance.user().id(xxx) [DOC-1101]
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/best-practices-identify.md
  src/guides/usage-and-billing/mtus-and-throughput.md
Labels: content-update

#7595 Release 25.18.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/bing-ads/index.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/connections/sources/catalog/libraries/website/javascript/index.md
  src/connections/spec/best-practices-identify.md
  src/connections/storage/catalog/snowflake/index.md
  src/guides/regional-segment.md
  src/guides/usage-and-billing/mtus-and-throughput.md
  src/monitor/alerts/default-alerts.md
  src/protocols/faq.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: release

#7597 Update catalog for bing ads settings
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7596 Add a question to Consent Mgmt FAQ about a common error
  src/privacy/consent-management/consent-faq.md
Labels: content-update

#7600 [DG-573] Add description field to entities/relationships
  src/unify/data-graph/index.md
Labels: content-update

#7603 unhide linked audiences docs for braze and iterable
  src/_data/sidenav/main.yml
  src/engage/audiences/linked-audiences-braze.md
  src/engage/audiences/linked-audiences-iterable.md
Labels: back-end

#7605 Added missing period
  src/getting-started/whats-next.md
Labels: fixed-content

#7606 Install page fixes
  src/getting-started/01-what-is-segment.md
  src/getting-started/03-planning-full-install.md
Labels: fixed-content

#7519 Add Reddit (Actions) Audiences documentation
  src/connections/destinations/catalog/actions-reddit-audiences/index.md
  src/connections/destinations/catalog/actions-reddit-conversions-api/index.md
Labels: new-integration

#7607 Add User alerts to the default alerts tab
  src/monitor/alerts/default-alerts.md
Labels: content-update

#7608 Add Trubrics (Actions) destination docs
  src/connections/destinations/catalog/trubrics/index.md
Labels: new-integration

#7602 Unify Event Filtering Public Beta [DOC-1107]
  src/unify/event-filtering.md
Labels: new-feature

#7599 Add Slack workflow + schedule info [DOC-1106]
  src/connections/alerting.md
  src/connections/reverse-etl/manage-retl.md
  src/engage/audiences/index.md
  src/monitor/alerts/default-alerts.md
Labels: content-update

#7609 Catalog update 8 May 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7610 Release 25.19.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/sidenav/main.yml
  src/connections/alerting.md
  src/connections/destinations/catalog/actions-chartmogul/index.md
  src/connections/destinations/catalog/actions-reddit-audiences/index.md
  src/connections/destinations/catalog/actions-reddit-conversions-api/index.md
  src/connections/destinations/catalog/trubrics/index.md
  src/connections/reverse-etl/manage-retl.md
  src/connections/sources/catalog/cloud-apps/qualtrics/index.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences-braze.md
  src/engage/audiences/linked-audiences-iterable.md
  src/getting-started/01-what-is-segment.md
  src/getting-started/03-planning-full-install.md
  src/getting-started/whats-next.md
  src/monitor/alerts/default-alerts.md
  src/privacy/consent-management/consent-faq.md
  src/unify/data-graph/index.md
  src/unify/event-filtering.md
Labels: release

#7612 Add redirect to the SendGrid docs
  src/connections/destinations/catalog/actions-sendgrid/index.md
Labels: fixed-content

#7616 OAuth docs improvements [DOC-1104]
  src/connections/oauth.md
Labels: content-update

#7613 [Reddit Audiences] - minor update to the reddit audience doc
  src/connections/destinations/catalog/actions-reddit-audiences/index.md
Labels: content-update

#7211 Consent on Profile
  src/_data/sidenav/main.yml
  src/engage/profiles/csv-upload.md
  src/privacy/consent-management/consent-in-retl.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/images/device-level-consent-conflict.png
  src/privacy/consent-management/images/profile-level-consent-conflict.png
  src/unify/csv-upload.md
  src/unify/profile-api.md
Labels: new-feature

#7618 Add more context about PII/hashed emails to TTD CRM docs
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
Labels: content-update

#7619 Update Predictions historical data requirement to 3x target window
  src/unify/Traits/predictions/index.md
Labels: content-update

#7620 Master to develop after Consent on the Profile release
  src/_data/sidenav/main.yml
  src/engage/profiles/csv-upload.md
  src/privacy/consent-management/consent-in-retl.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/consent-management/consent-in-unify.md
  src/privacy/consent-management/images/device-level-consent-conflict.png
  src/privacy/consent-management/images/profile-level-consent-conflict.png
  src/unify/csv-upload.md
  src/unify/profile-api.md
Labels: back-end

#7563 fix(docs): use `pnpm add` instead of `pnpm install`
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: fixed-content

#7615 Update docs about sibling entity conditions behavior
  src/engage/audiences/linked-audiences.md
Labels: content-update

#7621 Add link to LA with Braze and Iterable docs
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
  src/unify/data-graph/index.md
  src/unify/data-graph/linked-events.md
Labels: content-update

#7622 20250315-makecatalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7611 Add Data Split to Event-Triggered Journeys Steps [DOC-1072]
  src/engage/journeys/event-triggered-journeys-steps.md
Labels: new-feature

#7623 Release 25.20.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-reddit-audiences/index.md
  src/connections/destinations/catalog/actions-sendgrid/index.md
  src/connections/destinations/catalog/actions-the-trade-desk-crm/index.md
  src/connections/oauth.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
  src/engage/journeys/event-triggered-journeys-steps.md
  src/unify/Traits/predictions/index.md
  src/unify/data-graph/index.md
  src/unify/data-graph/linked-events.md
Labels: release

#7629 Update Kotlin Auto-Instrumentation setup guide for Signals SDK `0.5.0`
  src/connections/auto-instrumentation/kotlin-setup.md
Labels: content-update

#7627 Dub (Actions) Destination docs
  src/connections/destinations/catalog/actions-dub/index.md
Labels: new-integration

#7632 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7630 Event-Triggered Journeys Exit Rules [DOC-1074]
  src/engage/journeys/exit-rules.md
Labels: new-feature

#7631 Clarify that Data Split branch order can be changed
  src/engage/journeys/event-triggered-journeys-steps.md
Labels: content-update

#7628 Update supported Actions trigger operators
  src/connections/destinations/actions.md
Labels: content-update

#7634 Release 25.21.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-dub/index.md
  src/connections/destinations/catalog/actions-liveramp-audiences/index.md
  src/engage/journeys/event-triggered-journeys-steps.md
  src/engage/journeys/exit-rules.md
Labels: release

#7640 Add set-up retl
  src/connections/reverse-etl/setup.md
Labels: content-update

#7636 Redirect broken Extensible Webhooks link
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: broken links

#7645 Add note about adjusted `sent_at` timestamps [DOC-1128]
  src/connections/spec/common.md
  src/connections/storage/warehouses/schema.md
Labels: content-update

#7642 Update Extensible Webhooks beta alert
  src/connections/destinations/catalog/actions-webhook-extensible/index.md
Labels: content-update

#7650 Hide Engage (Premier) Use Cases page
  src/_data/sidenav/main.yml
  src/engage/use-cases.md
Labels: content-update

#7639 Add note about `segment_id` behavior in Track event tables where ID res fails
  src/unify/profiles-sync/tables.md
Labels: content-update
