Repository segmentio/segment-docs, pull requests merged in 2025-03, with the labels that each got.

#7454 Event Tester [DOC-1030]
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/images/event-tester-2025.png
  src/connections/images/event-tester-filter.png
  src/connections/test-connections.md
  src/unify/data-graph/linked-events.md
Labels: new-feature

#7472 Add Delay Step to Event-Triggered Journeys Steps [DOC-1041]
  src/engage/journeys/event-triggered-journeys-steps.md
Labels: new-feature

#7471 Update data retention time period from 7 days to 14 days
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#7473 `master` into `develop` after one-offs
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/images/event-tester-2025.png
  src/connections/images/event-tester-filter.png
  src/connections/test-connections.md
  src/engage/journeys/event-triggered-journeys-steps.md
  src/unify/data-graph/linked-events.md
Labels: back-end

#7333 Update process for requesting account-level Audiences
  src/engage/audiences/account-audiences.md
Labels: KCS

#7476 Added note about needing Linked Audiences to define entity relationships
  src/unify/data-graph/index.md
Labels: KCS

#7478 Catalog Update 6 March 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7479 Update Changelogs March 2025
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
Labels: back-end

#6660 Add Saving Traits to Context Object info to Analytics.js Identity management
  src/connections/sources/catalog/libraries/website/javascript/identity.md
Labels: KCS

#7480 Release 25.10.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/changelogs/analytics-android.yml
  src/_data/changelogs/analytics-go.yml
  src/_data/changelogs/analytics-ios.yml
  src/_data/changelogs/analytics-java.yml
  src/_data/changelogs/analytics-node.yml
  src/_data/changelogs/analytics-php.yml
  src/_data/changelogs/analytics-python.yml
  src/_data/changelogs/analytics-react-native.yml
  src/_data/changelogs/analytics.NET.yml
  src/connections/sources/catalog/libraries/website/javascript/identity.md
  src/engage/audiences/account-audiences.md
  src/engage/product-limits.md
  src/engage/using-engage-data.md
  src/privacy/user-deletion-and-suppression.md
  src/unify/data-graph/index.md
  src/unify/product-limits.md
Labels: release

#7377 Data Retention Policy
  src/privacy/data-retention-policy.md
  src/privacy/images/data-retention-policy-flowchart.png
Labels: new-feature

#7483 Master to develop after one-off
  src/privacy/data-retention-policy.md
  src/privacy/images/data-retention-policy-flowchart.png
Labels: back-end

#7484 Add data retention policy to side navigation
  src/_data/sidenav/main.yml
Labels: back-end

#7486 Master to develop after one-off
  src/_data/sidenav/main.yml
Labels: back-end

#7490 Move "data retention" section from account and data deletion to data retention policy
  src/privacy/data-retention-policy.md
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#7493 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7495 Release 25.11.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/storage/catalog/bigquery/index.md
  src/privacy/data-retention-policy.md
  src/privacy/user-deletion-and-suppression.md
  src/unify/Traits/predictions/index.md
Labels: release

#7312 Audience observability and monitoring features
  src/connections/delivery-overview.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
Labels: new-feature

#7499 HubSpot/Segment Profiles Integration doc
  src/connections/sources/catalog/cloud-apps/hubspot-profiles/index.md
Labels: new-feature

#7502 Update selective sync settings [DOC-1038]
  src/connections/sources/catalog/cloud-apps/hubspot-profiles/index.md
Labels: content-update

#7494 removed banner
  src/unify/data-graph/linked-events.md
Labels: content-update

#7496 Hubspot (Classic) destination fixes
  src/_includes/content/destination-maintenance.md
  src/connections/destinations/catalog/hubspot/index.md
Labels: fixed-content

#7507 HubSpot now public beta [DOC-1038]
  src/connections/sources/catalog/cloud-apps/hubspot-profiles/index.md
Labels: content-update

#7501 `master` into `develop` after one-off
  src/connections/delivery-overview.md
  src/connections/sources/catalog/cloud-apps/hubspot-profiles/index.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences.md
Labels: back-end

#7508 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7509 Release 25.12.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-maintenance.md
  src/connections/destinations/catalog/hubspot/index.md
  src/connections/sources/catalog/libraries/server/pixel-tracking-api/index.md
  src/engage/journeys/event-triggered-journeys-steps.md
  src/engage/journeys/event-triggered-journeys.md
  src/engage/journeys/journey-context.md
  src/privacy/data-retention-policy.md
  src/unify/data-graph/linked-events.md
Labels: release

#7510 hotfix for Rokt Audiences (Actions) dest
  src/connections/destinations/catalog/actions-rokt-audiences/index.md
Labels: back-end

#7411 Update version for Kotlin filters
  src/connections/sources/catalog/libraries/mobile/kotlin-android/kotlin-android-destination-filters.md
Labels: KCS

#7482 Updates to Collections + Sync [DOC-1038]
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: content-update

#7518 Add support for Pixel API to Custom Domain docs
  src/connections/sources/custom-domain.md
Labels: content-update

#7504 Monitor tab/Alerting hub [DOC-1059]
  src/_data/sidenav/main.yml
  src/_includes/icons/monitor.svg
  src/connections/alerting.md
  src/monitor/alerts/default-alerts.md
  src/monitor/alerts/index.md
  src/monitor/index.md
Labels: new-feature

#7516 hotfix data retention policy
  src/privacy/data-retention-policy.md
Labels: content-update

#7520 Master to develop after today's two one-off's (two-off's?)
  src/_data/sidenav/main.yml
  src/_includes/icons/monitor.svg
  src/connections/alerting.md
  src/connections/destinations/catalog/actions-rokt-audiences/index.md
  src/monitor/alerts/default-alerts.md
  src/monitor/alerts/index.md
  src/monitor/index.md
  src/privacy/data-retention-policy.md
Labels: back-end

#7522 Updated incorrect installation URL in Analytics-Go documentation
  src/connections/sources/catalog/libraries/server/go/index.md
Labels: fixed-content

#7523 HubSpot Source Collections/Syncs one off
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: content-update

#7525 Remove Reference to Engage Channels in Engage Intro [DOC-1082]
  src/engage/index.md
Labels: content-update

#7526 `master` into `develop` after one-off
  src/connections/sources/catalog/cloud-apps/hubspot/index.md
Labels: back-end

#7500 Fix typos in StackAdapt Audiences destination and add specification
  src/connections/destinations/catalog/actions-stackadapt-audiences/index.md
Labels: content-update

#7515 Bidirectional Sync docs
  src/segment-app/extensions/git.md
Labels: new-feature

#7531 Catalog update 27 March 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7264 Improve Retries section in Analytics.js docs
  src/connections/sources/catalog/libraries/website/javascript/index.md
Labels: KCS

#7151 Explain how to concatenate values in Actions mappings
  src/connections/destinations/actions.md
  src/connections/destinations/images/mapping-concatenation.png
Labels: KCS

#6483 Clarify expected behavior when connecting a new destination to an existing audience
  src/engage/audiences/index.md
Labels: KCS

#7527 Update Engage EOS alerts and hide Premier Onboarding page [DOC-1082]
  src/_data/sidenav/main.yml
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/html-editor.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/onboarding.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
Labels: content-update
