Repository segmentio/segment-docs, pull requests merged in 2025-09, with the labels that each got.

#7536 Add custom alerts to the monitor tab
  src/_data/sidenav/main.yml
  src/connections/alerting.md
  src/monitor/alerts/custom-alerts.md
  src/monitor/alerts/index.md
  src/monitor/images/custom-alerting.png
Labels: new-feature

#7864 Public API edits [DOC-1232]
  src/api/public-api/index.md
Labels: content-update

#7867 Basic installation page audit [DOC-1200]
  src/getting-started/02-simple-install.md
Labels: content-update

#7861 Unify overview audit [DOC-1198]
  src/unify/index.md
Labels: content-update

#7865 Customer.io classic destination: update images, rate limits
  src/connections/destinations/catalog/customer-io/images/cio-track-api-keys.png
  src/connections/destinations/catalog/customer-io/images/segment-source-cio.png
  src/connections/destinations/catalog/customer-io/index.md
Labels: content-update

#7866 Identify best practices audit [DOC-1199]
  src/connections/spec/best-practices-identify.md
Labels: content-update

#7870 Connections overview edits [DOC-1235]
  src/connections/index.md
Labels: content-update

#7878 nine branches update and add info on context split
  src/engage/journeys/v2/event-triggered-journeys-steps.md
Labels: content-update

#7884 Catalog update 4 September 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7879 Profiles Syncs review [DOC-1204]
  src/unify/profiles-sync/tables.md
Labels: content-update

#7874 Rewrite "what is Segment?" page for content audit
  src/getting-started/index.md
Labels: content-update

#7882 Master to develop after hotfix
  src/monitor/alerts/custom-alerts.md
  src/monitor/alerts/default-alerts.md
  src/monitor/alerts/index.md
Labels: back-end

#7883 Source functions overview audit [DOC-1205]
  src/connections/functions/source-functions.md
Labels: content-update

#7885 Release 25.36.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/components/actions-fields.html
  src/api/public-api/index.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/connections/destinations/catalog/customer-io/images/cio-track-api-keys.png
  src/connections/destinations/catalog/customer-io/images/segment-source-cio.png
  src/connections/destinations/catalog/customer-io/index.md
  src/connections/destinations/catalog/strikedeck/index.md
  src/connections/destinations/index.md
  src/connections/functions/source-functions.md
  src/connections/index.md
  src/connections/spec/best-practices-identify.md
  src/connections/spec/page.md
  src/engage/audiences/index.md
  src/engage/images/audience-array.png
  src/engage/journeys/v2/event-triggered-journeys-steps.md
  src/getting-started/02-simple-install.md
  src/getting-started/index.md
  src/unify/Traits/computed-traits.md
  src/unify/index.md
  src/unify/profiles-sync/tables.md
Labels: release

#7891 Edits to getting started guide
  src/getting-started/01-what-is-segment.md
Labels: content-update

#7894 Edits to Analytics for Node.js
  src/connections/sources/catalog/libraries/server/node/index.md
Labels: content-update

#7900 Batch of edits for Data Retention, Apple, and Screen
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/spec/screen.md
  src/privacy/data-retention-policy.md
Labels: content-update

#7909 monitor tab is GA now
  src/monitor/alerts/custom-alerts.md
  src/monitor/alerts/default-alerts.md
  src/monitor/alerts/index.md
Labels: content-update

#7911 Using Engage Data rewrite
  src/engage/using-engage-data.md
Labels: content-update

#7919 Master 2 develop after one off
  src/monitor/alerts/custom-alerts.md
  src/monitor/alerts/default-alerts.md
  src/monitor/alerts/index.md
Labels: back-end

#7913 Batch edits (Profiles Sync, Semantic, and Test Connections)
  src/connections/spec/semantic.md
  src/connections/test-connections.md
  src/unify/profiles-sync/overview.md
Labels: content-update

#7890 Edits to destination functions
  src/connections/functions/destination-functions.md
Labels: content-update

#7921 Testing and debugging edits
  src/getting-started/06-testing-debugging.md
Labels: content-update

#7904 Custom Traits edit [DOC-1209]
  src/unify/Traits/custom-traits.md
Labels: content-update

#7852 Profiles Sync setup content audit edits [DOC-1231]
  src/unify/profiles-sync/profiles-sync-setup/index.md
Labels: content-update

#7897 Predictions and Mobile batch edits [DOC-1250][DOC-1251]
  src/connections/spec/mobile.md
  src/unify/Traits/predictions/index.md
Labels: content-update

#7893 Journeys overview review [DOC-1207]
  src/engage/journeys/faq-best-practices.md
  src/engage/journeys/index.md
Labels: content-update

#7871 Alt text of images updated
  src/connections/destinations/catalog/actions-batch/index.md
Labels: content-update

#7923 Release 25.37.1
  src/api/config-api/index.md
  src/connections/destinations/catalog/actions-batch/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/index.md
  src/connections/reverse-etl/system.md
  src/connections/sources/catalog/cloud-apps/zigpoll/index.md
  src/connections/sources/catalog/libraries/mobile/apple/index.md
  src/connections/sources/catalog/libraries/server/node/index.md
  src/connections/sources/custom-domain.md
  src/connections/sources/index.md
  src/connections/spec/ecommerce/v2.md
  src/connections/spec/mobile.md
  src/connections/spec/screen.md
  src/connections/spec/semantic.md
  src/connections/storage/warehouses/index.md
  src/connections/test-connections.md
  src/engage/analytics/index.md
  src/engage/audiences/linked-audiences.md
  src/engage/campaigns/broadcasts.md
  src/engage/campaigns/email-campaigns.md
  src/engage/campaigns/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/campaigns/mobile-push/push-campaigns.md
  src/engage/campaigns/sms-campaigns.md
  src/engage/campaigns/whatsapp-campaigns.md
  src/engage/content/email/editor.md
  src/engage/content/email/template.md
  src/engage/content/mobile-push.md
  src/engage/content/organization.md
  src/engage/content/sms/template.md
  src/engage/content/whatsapp.md
  src/engage/journeys/faq-best-practices.md
  src/engage/journeys/index.md
  src/engage/use-cases.md
  src/engage/user-subscriptions/csv-upload.md
  src/engage/user-subscriptions/index.md
  src/engage/user-subscriptions/set-user-subscriptions.md
  src/engage/user-subscriptions/subscription-groups.md
  src/engage/user-subscriptions/subscription-sql.md
  src/engage/user-subscriptions/subscription-states.md
  src/engage/using-engage-data.md
  src/getting-started/01-what-is-segment.md
  src/getting-started/06-testing-debugging.md
  src/getting-started/implementation-guide.md
  src/guides/filtering-data.md
  src/guides/usage-and-billing/mtus-and-throughput.md
  src/monitor/alerts/custom-alerts.md
  src/monitor/alerts/default-alerts.md
  src/privacy/consent-management/configure-consent-management.md
  src/privacy/consent-management/consent-in-segment-connections.md
  src/privacy/data-retention-policy.md
  src/protocols/apis-and-extensions/typewriter.md
  src/unify/Traits/custom-traits.md
  src/unify/Traits/predictions/index.md
  src/unify/data-graph/linked-events.md
  src/unify/identity-resolution/index.md
  src/unify/profiles-sync/overview.md
  src/unify/profiles-sync/profiles-sync-setup/index.md
  src/unify/quickstart.md
Labels: release

#7941 A Full Segment Implementation review
  src/getting-started/04-full-install.md
Labels: content-update

#7940 typo fix
  src/engage/audiences/index.md
Labels: fixed-content

#7949 hotfix for failing develop builds
  src/connections/destinations/actions.md
Labels: back-end

#7938 Warehouse Schema and Protocols Overview review
  src/_data/protocols.yml
  src/connections/storage/warehouses/schema.md
  src/protocols/index.md
Labels: content-update

#7955 Release 25.38.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_data/products.yml
  src/_data/protocols.yml
  src/_data/sidenav/main.yml
  src/connections/destinations/actions.md
  src/connections/destinations/catalog/actions-stackadapt-audiences/index.md
  src/connections/destinations/catalog/actions-stackadapt-cloud/index.md
  src/connections/destinations/catalog/actions-vibe-audience/index.md
  src/connections/sources/catalog/libraries/mobile/react-native/index.md
  src/connections/storage/warehouses/schema.md
  src/engage/audiences/index.md
  src/getting-started/04-full-install.md
  src/monitor/granular-observability.md
  src/monitor/index.md
  src/protocols/index.md
Labels: release

#7957 fix extra `/`
  src/connections/spec/ecommerce/v2.md
Labels: content-update

#7959 Update beta language callout w pricing implications
  src/monitor/granular-observability.md
Labels: content-update

#7960 Revise background on traditional tracking setups
  src/connections/auto-instrumentation/index.md
Labels: content-update

#7958 Master back to develop after one-off
  src/connections/storage/catalog/azuresqldw/index.md
  src/connections/storage/catalog/bigquery/index.md
  src/connections/storage/catalog/databricks/index.md
  src/connections/storage/catalog/db2/index.md
  src/connections/storage/catalog/postgres/index.md
  src/connections/storage/catalog/redshift/index.md
  src/connections/storage/catalog/snowflake/index.md
  src/monitor/granular-observability.md
Labels: back-end

#7963 Segment now retains 90 days of deletions
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#7964 Added screenshot of mapping in Segment UI to Mixpanel docs [DOC-1275]
  src/connections/destinations/catalog/actions-mixpanel/images/traits-mapping-screenshot.png
  src/connections/destinations/catalog/actions-mixpanel/index.md
Labels: content-update

#7901 Updates to audience run behavior
  src/engage/audiences/linked-audiences.md
Labels: content-update

#7961 Add callout about ID sync edge case
  src/engage/audiences/index.md
  src/engage/trait-activation/id-sync.md
Labels: content-update

#7976 Documents performance limits on liquid functions
  src/connections/destinations/actions.md
Labels: content-update

#7977 Remove Upollo integrations
  src/connections/destinations/catalog/actions-upollo/index.md
  src/connections/destinations/catalog/upollo/index.md
  src/connections/sources/catalog/cloud-apps/upollo/index.md
Labels: content-update

#7888 warehouse faqs docs edits
  src/connections/storage/warehouses/faq.md
Labels: content-update

#7966 [EventBridge Actions] - new Destination
  src/connections/destinations/catalog/actions-amazon-eventbridge/index.md
  src/connections/destinations/catalog/amazon-eventbridge/index.md
Labels: new-integration

#7962 Audience size change alerts are GA now
  src/engage/audiences/index.md
  src/monitor/alerts/custom-alerts.md
Labels: content-update

#7984 chore: manual fixes for migration of batch 1.4
  src/engage/journeys/v2/event-triggered-journeys-steps.md
  src/engage/quickstart.md
  src/engage/user-subscriptions/subscription-groups.md
  src/unify/csv-upload.md
Labels: content-update

#7987 Master to develop after audience size change alerts
  src/engage/audiences/index.md
  src/engage/journeys/v2/event-triggered-journeys-steps.md
  src/monitor/alerts/custom-alerts.md
Labels: back-end

#7990 Remove Legacy Auto-Instrumentation Information
  src/connections/auto-instrumentation/index.md
Labels: content-update
