Repository segmentio/segment-docs, pull requests merged in 2025-10, with the labels that each got.

#7994 [DOCSPLAT-2879] Pt2. Small fixes - Fix bad defined links
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/functions/source-functions.md
  src/connections/spec/ab-testing.md
  src/engage/quickstart.md
  src/guides/what-is-replay.md
Labels: fixed-content, content-update

#7992 chore: formatting fixes for batch 1.4 of segment migration
  src/engage/audiences/generative-audiences.md
  src/engage/audiences/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/content/organization.md
  src/engage/journeys/v2/index.md
  src/engage/onboarding.md
  src/engage/profiles/csv-upload.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/trait-enrichment.md
  src/engage/use-cases.md
  src/engage/user-subscriptions/subscription-groups.md
Labels: fixed-content

#8003 Release 25.40.2
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
  src/connections/destinations/catalog/actions-batch/index.md
  src/connections/destinations/catalog/actions-webhook/index.md
  src/connections/destinations/catalog/batch/index.md
  src/connections/destinations/catalog/facebook-app-events/index.md
  src/connections/functions/source-functions.md
  src/connections/spec/ab-testing.md
  src/engage/audiences/generative-audiences.md
  src/engage/audiences/index.md
  src/engage/campaigns/mobile-push/index.md
  src/engage/content/organization.md
  src/engage/journeys/index.md
  src/engage/journeys/v2/index.md
  src/engage/onboarding.md
  src/engage/profiles/csv-upload.md
  src/engage/quickstart.md
  src/engage/trait-activation/id-sync.md
  src/engage/trait-activation/trait-enrichment.md
  src/engage/use-cases.md
  src/engage/user-subscriptions/subscription-groups.md
  src/guides/how-to-guides/measure-marketing-roi.md
  src/guides/how-to-guides/segment-and-attribution.md
  src/guides/segment-vs-tag-managers.md
  src/guides/what-is-replay.md
  src/partners/destinations/index.md
  src/protocols/validate/forward-violations.md
  src/segment-app/iam/restrict-access.md
Labels: release

#8005 Add permissions, preview section, and tracking plan integration information for auto-instrumentation
  src/connections/auto-instrumentation/configuration.md
Labels: content-update

#8015 DOCSPLAT 2981 Changes to simplify migration
  src/connections/destinations/catalog/actions-commandbar/index.md
  src/connections/destinations/catalog/plotline/index.md
  src/connections/destinations/catalog/retently/index.md
  src/connections/sources/catalog/cloud-apps/gwen-webhooks/index.md
  src/connections/sources/catalog/cloud-apps/one-creation/index.md
Labels: fixed-content
