Repository segmentio/segment-docs, pull requests merged in 2025-08, with the labels that each got.

#7808 STRATCONN-6101/wrong-description
  src/_includes/content/destination-footer.md
Labels: fixed-content

#7814 Add additional context to deletions page to coincide with new UI updates
  src/privacy/user-deletion-and-suppression.md
Labels: content-update

#7817 Master to develop after one-off release
  src/privacy/user-deletion-and-suppression.md
Labels: back-end

#7812 [Nextdoor] - New Destination - docs
  src/connections/destinations/catalog/actions-nextdoor-capi/index.md
Labels: new-integration

#7821 Auto-Instrumentation configuration updates
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/images/signals_identify_event.png
  src/connections/auto-instrumentation/images/signals_track_event.png
Labels: content-update

#7819 Clarifying how Page events are sent to Optimizely [DOC-1161]
  src/connections/destinations/catalog/optimizely-web/index.md
Labels: fixed-content

#7800 Userpilot mobile destination
  src/connections/destinations/catalog/userpilot-mobile/index.md
Labels: new-integration

#7829 `master` into `develop`
  src/connections/auto-instrumentation/web-setup.md
Labels: back-end

#7822 Amazon S3 not supported by Segment
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
Labels: fixed-content

#7832 Add Linked Audience Overview video
  src/engage/audiences/linked-audiences.md
Labels: content-update

#7835 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7827 Backfill consent preferences on the Profile docs
  src/privacy/consent-management/consent-in-unify.md
Labels: content-update

#7836 Release 25.33.1
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/_includes/content/destination-dossier.html
  src/connections/sources/catalog/cloud-apps/amazon-s3/index.md
  src/engage/audiences/linked-audiences.md
  src/privacy/consent-management/consent-in-unify.md
Labels: release

#7842 catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/slugs.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/nudge-actions/index.md
Labels: back-end

#7846 BQ data graph permissions [DOC-1173]
  src/unify/data-graph/setup-guides/BigQuery-setup.md
Labels: content-update

#7847 Master back to develop after one-off
  src/unify/data-graph/setup-guides/BigQuery-setup.md
Labels: back-end

#7791 [algolia-insights] auth user token and product list viewed support
  src/connections/destinations/catalog/actions-algolia-insights/index.md
Labels: content-update

#7850 Identify page audit edits [DOC-1211]
  src/_includes/content/spec-field-identify-traits.md
  src/connections/spec/identify.md
Labels: fixed-content

#7854 Hide Engage section from Inflection destination docs
  src/connections/destinations/catalog/inflection/index.md
Labels: content-update

#7858 Catalog update 28 August 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7863 Update page.md to match style guide
  src/connections/spec/page.md
Labels: content-update

#7862 Style guide/formatting edits to destination overview page
  src/connections/destinations/index.md
Labels: content-update
