Repository segmentio/segment-docs, pull requests merged in 2025-04, with the labels that each got.

#7538 smart hashing
  src/connections/destinations/index.md
Labels: new-feature

#7542 Master back to develop after hashing one-off
  src/connections/destinations/index.md
Labels: back-end

#7547 Catalog Update 3 April 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7546 Fixed syntax error in the code under What's new in v3 heading
  src/connections/sources/catalog/libraries/server/go/index.md
Labels: fixed-content

#7541 Add example for blocking flush to Analytics-Java doc
  src/connections/sources/catalog/libraries/server/java/index.md
Labels: content-update

#7545 Clarify regional endpoint requirements for SDKs and custom sources [DOC-1067]
  src/guides/regional-segment.md
Labels: content-update

#7537 Update docs to reflect new audience consumers feature
  src/engage/audiences/index.md
Labels: new-feature

#7548 Release 25.14.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/regional-supported.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/sources/catalog/libraries/server/go/index.md
  src/connections/sources/catalog/libraries/server/java/index.md
  src/engage/audiences/index.md
  src/guides/regional-segment.md
Labels: release

#7550 Clarify lack of LTV based audience support
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
Labels: content-update

#7551 Doc updates for lookback config feature
  src/engage/audiences/index.md
Labels: new-feature

#7552 Add required permissions to dbt sync doc
  src/segment-app/extensions/dbt.md
Labels: KCS

#7503 Data extension creation for SFMC [DOC-1055]
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
Labels: new-feature

#7555 Fix Auto-Instrumentation GitHub link [DOC-1062]
  src/connections/auto-instrumentation/swift-setup.md
Labels: fixed-content

#7549 Corrected Predictions user limit value [DOC-1086]
  src/unify/Traits/predictions/index.md
Labels: fixed-content

#7558 Add performance and warehouse guidance to Linked Audiences limits
  src/engage/audiences/linked-audiences-limits.md
Labels: content-update

#7554 Redshift/BigQuery Linked Audiences GA + Materialized view requirements [DOC-1094]
  src/unify/data-graph/index.md
  src/unify/data-graph/setup-guides/BigQuery-setup.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/redshift-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: content-update

#7559 Release 25.15.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/destinations/catalog/actions-kafka/index.md
  src/connections/destinations/catalog/actions-salesforce-marketing-cloud/index.md
  src/connections/destinations/catalog/personas-facebook-custom-audiences/index.md
  src/connections/functions/source-functions.md
  src/engage/audiences/index.md
  src/engage/audiences/linked-audiences-limits.md
  src/segment-app/extensions/dbt.md
  src/unify/Traits/predictions/index.md
  src/unify/data-graph/index.md
  src/unify/data-graph/setup-guides/BigQuery-setup.md
  src/unify/data-graph/setup-guides/databricks-setup.md
  src/unify/data-graph/setup-guides/redshift-setup.md
  src/unify/data-graph/setup-guides/snowflake-setup.md
Labels: release

#7512 Update destination functions - including variable scoping [DOC-1065]
  src/connections/functions/destination-functions.md
Labels: content-update

#7570 Remove Engage Premier section from Engage homepage
  src/engage/index.md
Labels: content-update

#7564 Add private beta tag to bidirectional sync docs
  src/segment-app/extensions/git.md
Labels: content-update

#7565 Remove Source-Level Archive Retention Periods section from the data retention policy
  src/privacy/data-retention-policy.md
Labels: content-update

#7566 improve RETL setup instructions
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
Labels: content-update

#7560 Add Deprecation Banner to Facebook Offline Conversions
  src/connections/destinations/catalog/facebook-offline-conversions/index.md
Labels: content-update

#7562 Added permissions prerequisite info [DOC-1096]
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
Labels: content-update

#7575 removed faq from actions-klaviyo [DOC-1098]
  src/connections/destinations/catalog/actions-klaviyo/index.md
Labels: fixed-content

#7574 Linked Events syncs clarification [DOC-1097]
  src/unify/data-graph/linked-events.md
Labels: content-update

#7573 Fix Broken Insert Functions anchor link
  src/connections/functions/insert-functions.md
Labels: fixed-content

#7576 20250416 make catalog
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7577 Release 25.16.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/destinations/catalog/actions-klaviyo/index.md
  src/connections/destinations/catalog/actions-tiktok-audiences/index.md
  src/connections/destinations/catalog/facebook-offline-conversions/index.md
  src/connections/destinations/catalog/facebook-pixel/index.md
  src/connections/functions/destination-functions.md
  src/connections/functions/insert-functions.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/postgres-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/redshift-setup.md
  src/connections/reverse-etl/reverse-etl-source-setup-guides/snowflake-setup.md
  src/engage/index.md
  src/privacy/data-retention-policy.md
  src/segment-app/extensions/git.md
  src/unify/data-graph/index.md
  src/unify/data-graph/linked-events.md
Labels: release

#7583 Update Engage product limits to reflect new concurrency limit
  src/engage/product-limits.md
  src/unify/product-limits.md
Labels: content-update

#7578 [STRAT-5744]| Added Warning for breaking changes in Hubspot for referring custom object Types by base names.
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
Labels: content-update

#7580 Auto-Instrumentation Private Beta [DOC-1063]
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/event-builder.md
  src/connections/auto-instrumentation/images/detecting_activity.png
  src/connections/auto-instrumentation/images/event_builder_tab.png
  src/connections/auto-instrumentation/images/event_rules.png
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
Labels: content-update

#7581 More data retention policy edits
  src/privacy/data-retention-policy.md
Labels: fixed-content

#7584 Catalog update 24 April 2025
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
Labels: back-end

#7585 Release 25.17.01
  src/_data/catalog/destination_categories.yml
  src/_data/catalog/destinations.yml
  src/_data/catalog/destinations_private.yml
  src/_data/catalog/source_categories.yml
  src/_data/catalog/sources.yml
  src/connections/auto-instrumentation/configuration.md
  src/connections/auto-instrumentation/event-builder.md
  src/connections/auto-instrumentation/images/detecting_activity.png
  src/connections/auto-instrumentation/images/event_builder_tab.png
  src/connections/auto-instrumentation/images/event_rules.png
  src/connections/auto-instrumentation/index.md
  src/connections/auto-instrumentation/kotlin-setup.md
  src/connections/auto-instrumentation/swift-setup.md
  src/connections/auto-instrumentation/web-setup.md
  src/connections/destinations/catalog/actions-hubspot-cloud/index.md
  src/engage/audiences/index.md
  src/engage/product-limits.md
  src/privacy/data-retention-policy.md
  src/unify/product-limits.md
Labels: release
